### ISSUE TITLE
Detail control

### ISSUE THREAD

**Issue by JimBabcock59** [DevExpress/DevExtreme#10040]
I need a file manager where I have control as described below:

1 - When a file is loaded, I need to replace the name of the file with a UUID to ensure it is unique.
2 - I will be creating a versioning system for the files.
3 - When files are loaded I will be creating a digital signature and manifest for every file that can be used to prove files have not been tampered with.
4 - When files are loaded a table in MySQL will be updated with the new file name and the original.
5 - The file grid needs to be customizable so other information from the database can be included.

Can file manager be used for this?

**Comment by hakimio** [comment]
Points 1-4 have to be done on the backend, DevExtreme file manager doesn't need to be involved in any of those.
5. You should be able to customize columns using [customizeDetailColumns](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/Configuration/#customizeDetailColumns) config.

**Comment by CodeKarno** [comment]
@JimBabcock59
Thank you for contacting us! @hakimio gave correct directions on how to accomplish your tasks. If you have any troubles with implementation, feel free to submit a ticket to our Support Center in this regard: [Support Center](https://supportcenter.devexpress.com/ticket/list). We will do our best to help you!
