### ISSUE TITLE
DataGrid component cells cannot span rows or cannot merge rows and columns

### ISSUE THREAD

**Issue by wcldyx** [DevExpress/DevExtreme#10066]
DataGrid  component does not have cell merge function, or I did not find

**Comment by AlisherAmonulloev** [comment]
Yes, you are right. DataGrid does not support the cell merging functionality.

**Comment by wcldyx** [comment]
> Yes, you are right. DataGrid does not support the cell merging functionality.

Will consider support in the future？

**Comment by AlisherAmonulloev** [comment]
We will consider implementing this functionality, however, I cannot provide you with any estimates on when it will be done. Please watch for our announcements.
