### ISSUE TITLE
Change export to excel icon in the current beta (19.2.2)

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#10121]
Hi,

I'm testing the new beta version and export to excel icon is looking very strange like it was cropped. Icon in the current stable version is much better.

**Comment by artem-kurchenko** [comment]
Hi @Bykiev ,

We replaced our previous icons with modern ones starting with v19.2.
This change will be announced in Version History with the official release as well.

**Comment by Bykiev** [comment]
@artem-kurchenko, well, but I think excel icon should be redesigned as it's not looking like excel icon, more like a cross inside rectangle.

**Comment by artem-kurchenko** [comment]
@Bykiev 

The new design originates from the current MS Excel icon where the same abbreviation is used.
![](https://user-images.githubusercontent.com/22076961/66664500-53928f80-ec55-11e9-83dd-3ecaced5dad4.png)

As an alternative, consider using either icons that display a file extension type or custom icons.
![](https://user-images.githubusercontent.com/22076961/66664555-6e650400-ec55-11e9-9342-d6e82429ffe5.png)
