### ISSUE TITLE
Pager doesn't shown if `dataSource` length equals or more than `pageSize`

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#10154]
### Steps to Reproduce:

1. Open [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RecordPaging/jQuery/Light/)
2. Change `pageSize` to 20 in `paging` option.
3. Press `Apply`

### Results You Received:
Pager doesn't shown

### Results You Expected:
Pager is shown

**Comment by hakimio** [comment]
Looks more like a feature than a bug. Why would you need a pager when there is only one page?

**Comment by Bykiev** [comment]
@Semigradsky, as already said, it's a feature, not a bug. If you still want to display pager, you can specify [visible](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/pager/#visible) option of a pager

**Comment by Semigradsky** [comment]
@Bykiev thank you, I missed this property. It will help me :+1:

**Comment by Bykiev** [comment]
@Semigradsky, you're welcome!
