### ISSUE TITLE
Depreciation error in _showRecurrenceChangeConfirm

### ISSUE THREAD

**Issue by iknowmac** [DevExpress/DevExtreme#10228]
https://github.com/DevExpress/DevExtreme/blob/db398b03a2cac0a9c7114c9845d6f9c966feb372/js/ui/scheduler/ui.scheduler.js#L2444

Should be `messageHtml: message`

**Comment by andrewmakarov** [comment]
Hi @towen ,
Thanks for letting us know.
We fixed this problem and attached our PR requests for review
[https://github.com/DevExpress/DevExtreme/pull/10289](url)
[https://github.com/DevExpress/DevExtreme/pull/10290](url)
