### ISSUE TITLE
DataGrid - The Master-Detail view - Load the detail data by using Ajax on first time expanding row

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#10255]
### Steps to Reproduce:

1. Fill the data using Data Grid with master-details. There is 3 rows in the grid. Detail data should be loaded on ajax request.
2. Load the detail data using direct ajax call while expanding the selected row on first time expanding
3. After the collapse the selected row, again expanding the same row. again it's going on ajax request actually. But I don't want ajax request while expanding selected row on the second time onwards, but need to load detail data (first time expanded ajax requested data) whenever I expand. 

### Results You Received:
1. I expand the selected row every time direct ajax request happened for detail data load.

### Results You Expected:
1. I expand the selected row second time onwards direct ajax request should not happen. But need  detail data ( need to load first time ajax request data here)

Please find the attached text file for my req.

[Master_Det_Ajax.txt](https://github.com/DevExpress/DevExtreme/files/3743003/Master_Det_Ajax.txt)
)

**Comment by igormalzew** [comment]
You can cache the data that comes through an ajax request by a unique identifier. And each time you expand a row check for data in the cache. If there is no data in the cache, then the row is expanded for the first time and you need to perform an ajax request and write the result to the cache.

If you have other technical questions, please submit a new ticket to our Support Center (https://www.devexpress.com/Support/Center/Question/Create). In the ticket, describe the issue and your final goal in detail.
