### ISSUE TITLE
[REGRESSION][19.1.7] No longer possible to expand rows in virtual scroll datagrid on ContentReady

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#10310]
### Steps to Reproduce:

1.  Define a DevExtreme datagrid
2. Set scroll mode to "virtual"
3. Try to expand a row in "onContentReady" event handler

### Results You Received:
The datagrid freezes in loading state.

### Results You Expected:
The row would expand like it did in version **19.1.5** and everything else would work as expected.

### Demo
https://codesandbox.io/s/record-grouping-devextreme-data-grid-rf6f4

If you switch to version **19.1.5**, it will work as expected.

### Environment Details:
DevExtreme: 19.1.7
devextreme-angular: 19.1.7
browser: Chrome 77

**Comment by AlisherAmonulloev** [comment]
I reproduced the issue and created a public ticket in our Support Center: https://supportcenter.devexpress.com/ticket/details/T826930
We will update the ticket once we have any results. Thank you for your patience.
In the meantime, to resolve the issue, call the expandRow method in the setTimeout method:

```js
  gridContentReady(e) {
    if (!this.expanded) {
      const grid: DxDataGrid = e.component;
    setTimeout(() => {
      grid.expandRow(["California"]);
      this.expanded = true;
    })  
    }
  }
```

**Comment by hakimio** [comment]
@AlisherAmonulloev or another simple workaround is to run `grid.refresh()` after `grid.expandRow()`.
Anyway, thanks for creating the ticket.
