### ISSUE TITLE
Object does not support 'include' property or method(IE10)

### ISSUE THREAD

**Issue by JingGeGe77** [DevExpress/DevExtreme#10320]
### Steps to Reproduce:

1. vue project open in IE 10
2.
 /**
 * DevExtreme (ui/radio_group/radio_group.js)
 * Version: 19.1.7
 * Build date: Fri Oct 11 2019
3.  RadioGroup.include(_ui2.default);

### Environment Details:
IE 10 , DevExtreme and DevExtreme version: 19.1.7

**Comment by AlisherAmonulloev** [comment]
IE10 is not supported. We support Internet Explorer 11. Check https://js.devexpress.com/Documentation/Guide/Common/Supported_Browsers/ for more information.
