### ISSUE TITLE
FilterBuilder - allowHierarchicalFields is ignored

### ISSUE THREAD

**Issue by MaximeTroiano** [DevExpress/DevExtreme#10380]
### Steps to Reproduce:

1. Create a datagrid
2. Add the filterbuilder
3. Set fields (example below)
`
[
        {
            dataField: "Category.Name",
            lookup: {
                dataSource: ["Televisions", "Monitors", "Projectors"]
            }
        },
        {
            dataField: "Category.Description"
        },
        {
            dataField: "UnitPrice",
            dataType: "number"
        },
        {
            dataField: "Shipped",
            dataType: "date"
        }
]
`
4. Set the parameter `allowHierarchicalFields` to true

### Results You Received:

The fields are not shown as in the example / docs: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFilterBuilder/

![image](https://user-images.githubusercontent.com/13046607/67743905-5a285180-fa20-11e9-9f9a-241cea9d2ef5.png)

### Results You Expected:

I would like them to show as announced

![image](https://user-images.githubusercontent.com/13046607/67743946-71ffd580-fa20-11e9-8dd8-457707b9de17.png)

### Environment Details:

React
        "react": "^16.8.6",
        "devextreme": "^19.2.3",
        "devextreme-react": "^19.2.3",

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. In this case, FilterBuilder behaves in the same manner as the grid, which displays columns as "Category Name" and "Category Description". You can set up the [column.caption](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#caption) option to change this behavior: [https://codesandbox.io/s/simple-array-devextreme-data-grid-8mgwv](https://codesandbox.io/s/simple-array-devextreme-data-grid-8mgwv)
