### ISSUE TITLE
gantt chart error

### ISSUE THREAD

**Issue by gwaksuyeon** [DevExpress/DevExtreme#10425]
![image](https://user-images.githubusercontent.com/51697335/68178705-5d977c00-ffd0-11e9-89a3-6c3f82af00f6.png)

If you run the gantt chart, the task header will fail.
what went wrong?

**Comment by natashaash** [comment]
Hello,
It seems that you did not add the dx-gantt.min.css file to your page. Please review the [Getting Started with Gantt](https://js.devexpress.com/Documentation/Guide/Widgets/Gantt/Getting_Started_with_Gantt/) article that describes how to do this. Let me know if this helps.
