### ISSUE TITLE
DxTextBox input event is not triggered if the component has a mask attribute ( vue )

### ISSUE THREAD

**Issue by aspirin37** [DevExpress/DevExtreme#10544]
I have a text input with a mask in my Vue app and it's value is not reactive, though other inputs without a mask work properly. 

` 
<dx-text-box
  v-model="myValue"
  value-change-event="input"
  mask="0000000000/0000000000000/0000000"
/>
`

If i remove the mask attribute, everything is fine and I get the updated value.

**Comment by sometimesElen** [comment]
Hi,

I was not able to reproduce the issue using the latest DevExtreme version (19.2.4). You can check the [following sample](https://codesandbox.io/s/overview-devextreme-text-box-0pb17) - it works fine. For further investigation, please specify the DevExtreme version and in which browser you faced this issue.

I also wish to add that we process inquiries related to use cases in the [Support Center](https://devexpress.com/ask). Feel free to describe the problem there and add a simple working project illustrating the issue in action. Our support engineers are always ready to help.
