### ISSUE TITLE
DataGrid - Master-Detail export to excel

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#10553]
### Steps to Reproduce:

1.  Dx datagrid master detail data - Export to excel using Excel JS
2. 
3. 

### Results You Received:
1. Only master row exported. No details rows

### Results You Expected:
1.  Master & detail row should be exported

**Comment by AlisherAmonulloev** [comment]
DataGrid does not provide the functionality to export its detail rows.
