### ISSUE TITLE
chart print & export is white

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#10813]
hello, I click print or export chart, export done but chart show white. your demo has same problem.
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ExportAndPrintingAPI/React/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ExportAndPrintingAPI/React/Light/)

**Comment by alexanderPolosatov** [comment]
Hi,

I created a [ticket](https://supportcenter.devexpress.com/internal/ticket/details/t835729) about this issue in our Support Center and suggest you track it to be notified of our progress.
