### ISSUE TITLE
Drop Down Button Color & Material-Theme

### ISSUE THREAD

**Issue by Faey2222** [DevExpress/DevExtreme#10825]
I really like the new Drop Down Button component but I have noticed there isn't any possibility to change it's colors such as for the regular button. Is this planned or achievable in some way?

Also I have noticed that the Drop Down Button component does not have the typcial Material wave?

**Comment by hakimio** [comment]
You can use [stylingMode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDropDownButton/Configuration/#stylingMode) to change the button style and [elementAttr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDropDownButton/Configuration/#elementAttr) for further customization.
