### ISSUE TITLE
Scheduler, avoid showing popup form

### ISSUE THREAD

**Issue by ArtemAlekhin** [DevExpress/DevExtreme#1084]
Hello, DevEx
I'm using the Scheduler in Angular2 app and I need instead of a popup editing form, **redirect user to another route** with my own editing form (not popup).
I did not find a way to cancel the popup appointment editing form. 
How can I cancel popup form?

**Comment by lukyanovas** [comment]
Hi, 
Please try the approach from the following thread:
[T341083: dxScheduler - How to replace the appointment popup with a custom popup](https://www.devexpress.com/Support/Center/Question/Details/T341083/dxscheduler-how-to-replace-the-appointment-popup-with-a-custom-popup)
