### ISSUE TITLE
dxbuttonwithtemplate is undefined in dx.all.js in devextreme latest version release.please check

### ISSUE THREAD

**Issue by nighotatul** [DevExpress/DevExtreme#10931]
after beautify js please check line number 87423 of dx.all.js. t.subclass of js is undefined for dxbuttonwithtemplate

**Comment by DokaRus** [comment]
Hi,

I cannot reproduce it with v.19.2.5 or v.19.2.4. This code is related to the Knockout integration. I checked the demos - they run correctly. Could you please specify the DevExtreme version and add an example that demonstrates the issue?
