### ISSUE TITLE
Losing selected value on datasource change

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/DevExtreme#1105]
If I select a value from a `select-box` and than I refresh the items/datasource, I lost the current value on the UI because of the reference value change.

Is it possible to override the compare behaviour?

### Steps to Reproduce:

[This Plunker ](http://plnkr.co/edit/S1I2RVZyT2g16n1O5tHv?p=preview) reproduce the problem.

### Results You Expected:

Changing the items/datasource I would like to not lose the current selected value

### Environment Details:
OS: MacOs 10.12.6
angular/cli: 1.2.3
node: 6.11.0

**Comment by AlekseyMartynov** [comment]
Your code sample can be easily fixed by specifying the [`valueExpr`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Configuration/#valueExpr) option:

```html
<dx-select-box valueExpr="id"></dx-select-box>
```

P.S. For Angular-related topics, please use the dedicated repo:
https://github.com/DevExpress/devextreme-angular
