### ISSUE TITLE
DX-Data Grid- Master -Detail - Value Update

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#11127]
### Steps to Reproduce:

1.  dx-Data-Grid with load data with master-detail using HTML JS 
2.  Details rows are dx form data. 
3. When values are updated or changed in detail row, that values should be updated in master row colums. In master row that columns are hidden

### Results You Received:
1. Can't updated  or changed  detail row values to master row

### Results You Expected:
1. Updated  or changed detail row values to master row
![Master_Det_Upd](https://user-images.githubusercontent.com/47413890/70880389-c706a380-1fee-11ea-9d67-bc48ad863843.png)

**Comment by igormalzew** [comment]
In general, masterDetail has a template in which you can implement any functionality. On the other hand, you need to update the master row data yourself.

If you work with local data, you can solve your task by assigning "options.data" to "dxForm.formData" as in the following [example](https://codepen.io/vconst/pen/yLyXqWL?&editable=true).

If you have other technical questions, please submit a new ticket to our Support Center ([https://www.devexpress.com/Support/Center/Question/Create](https://www.devexpress.com/Support/Center/Question/Create)). In the ticket, describe the issue and your final goal in detail.
