### ISSUE TITLE
Fix for the index error on scheduler

### ISSUE THREAD

**Issue by bilicio** [DevExpress/DevExtreme#11228]
I found that if i let the startDate and endDate hours on 0 ( zero ) it gives me the error :
```
ncaught TypeError: Cannot read property 'index' of undefined
    at HorizontalMonthRenderingStrategy.value 
```
if i change the hour to 1 ( one) the error disappears. 

i was using the devextreme-react 19.1.5 and now i updated to 19.2.4. Changing the hour fixes the error.

maybe this helps.

thank you!

maybe this helps support ticket T698406

**Comment by andrewmakarov** [comment]
@bilicio 
Hi,
could you please attach a simple project to helps us reproduce the problem on our side faster.

**Comment by andrewmakarov** [comment]
Thank you for bringing our attention to this issue.
We created a report in our Support Center. [Here](https://supportcenter.devexpress.com/internal/ticket/details/t873734) is a link where you can track its status.

Our Support Center is the main channel of communication and we recommend you contact us there in the future.
