### ISSUE TITLE
Devexpress JS dxGrid Lookup not working after I change the datasource

### ISSUE THREAD

**Issue by Shon1N** [DevExpress/DevExtreme#11279]
Good day, when I execute the following code It logs the old data and then the new data but the actual lookup column doesn't expand any longer, why might that be?

 console.log("Gender Updating:", $("#EntitlementRules").dxDataGrid("instance").columnOption("GenderID", "lookup"));
                    $("#EntitlementRules").dxDataGrid("instance").columnOption("GenderID", "lookup.dataSource", distinctGenders);
                    console.log("Gender Updated:", $("#EntitlementRules").dxDataGrid("instance").columnOption("GenderID", "lookup"));

**Comment by Shon1N** [comment]
This pretty much solved the issue:

                    setTimeout(
                        function () {
                            $("#EntitlementRules").dxDataGrid("instance").columnOption("GenderID", "lookup.dataSource", distinctGenders);
                            $("#EntitlementRules").dxDataGrid("instance").columnOption("SizeID", "lookup.dataSource", distinctSizes);
                            $("#EntitlementRules").dxDataGrid("instance").columnOption("StyleID", "lookup.dataSource", distinctStyles);
                            $("#EntitlementRules").dxDataGrid("instance").columnOption("ColourID", "lookup.dataSource", distinctColours);
                        }, 2500);

**Comment by AntonSermyazhko** [comment]
Hello @Shon1N,

Can you provide us with a simple example showing the issue, so that we can reproduce it and find a solution for you?
