### ISSUE TITLE
DX Tree List Level based Font Size

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#11285]
### Steps to Reproduce:

1.  Need level based font size/ font bold required
2. Need Child value summary to its parent
3. 

### Results You Received:
1. Same font size for all levels
2. Unable to find property

### Results You Expected:
1. First Level font size 16 & bold, Second Level font size 14 etc...
2. Child value (Last level for its parent) summary to its parent (recursive method)

### Environment Details:
Sample for First Req:
**- First Level**
       _-- Second Level_

Sample for Send Req:

S. No | Description | Debit | Credit | Remarks
-- | -- | -- | -- | --
  | A  (Level 1) |   | 7.00 | (A2+A3-A1)
  |  A1 (Level 2) | 15.00 |   |  
  |  A2  (Level 2) |   | 20.00 |  
  |    A3  (Level 2) |   | 2.00 | (A3b-A3a)
  |      A3a  (Level 3) | 8.00 |   |  
  |      A3b  (Level 3) |   | 10.00 |  
  | B  (Level 1) | 20.00 |   | (B1+B2)
  |   B1  (Level 2) | 12.00 |   |  
  |   B2  (Level 2) | 8.00 |   |

**Comment by vconst** [comment]
@sunbala,

Thank you for contacting us.

To customize styles for specific rows, you can use the [onRowPrepared](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/#onRowPrepared) event handler. See the following example: [https://codepen.io/vconst/pen/wvBqKmX](https://codepen.io/vconst/pen/wvBqKmX).

For summary calculations, you can use the [onNodesInitialized](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/#onNodesInitialized) event handler. See the following example that demonstrates how to calculate the total count of children for parent nodes: [https://codepen.io/vconst/pen/jOELbKd](https://codepen.io/vconst/pen/jOELbKd)

If you have other technical questions, please submit a new ticket to our Support Center ([https://www.devexpress.com/Support/Center/Question/Create](https://www.devexpress.com/Support/Center/Question/Create)).
