### ISSUE TITLE
DataGrid: headerFilter How to obtain filtered data?

### ISSUE THREAD

**Issue by windows99** [DevExpress/DevExtreme#11355]
I want to get all the filtered data,but I can't find a way!
getDataSrouce  There are paging restrictions.
What should I do?
我想获取 DataGrid 控件 headerFilter 筛选后的数据，做下一步计算，但是找不到可以使用的方法，我该怎么做

**Comment by Alyar666** [comment]
Hello @windows99,

You can use the store to load all filtered data:
```
const store = dataGridInstance.getDataSource().store();
const filter = dataGridInstance.getCombinedFilter(true);

store.load({ filter: filter }).done((filteredData) => { 
     .....
});
```

**See also:**
[DataSource.store()](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/Methods/#store)
[DataGrid.getCombinedFilter(returnDataField)](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#getCombinedFilterreturnDataField)
