### ISSUE TITLE
File Manager Events

### ISSUE THREAD

**Issue by deranjer** [DevExpress/DevExtreme#11352]
Hello,

I am trying out the File Manager that is currently in CTP to see if it will fit my needs. 

I'm just using the JSON backend for my data source, but that JSON is generated by the backend when it scans the folder structure.

 I have a hopefully quick question about events: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/Events/

I was hoping for a lot more events, I need to communicate all the changes through an API to the backend, so moving files/folders or creating a new folder, or uploading a file (which I would like to replace the basic uploader with a more full featured one but that also doesn't seem easy to do) would need to send API events to the backend.  Am I missing something on how to implement that? Or is that something that will be added?

**Comment by hakimio** [comment]
Have you checked [File Providers](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/File_Providers/Custom/) ([fileProvider](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/Configuration/#fileProvider) config)?

**Comment by deranjer** [comment]
Okay yes, that is it, I was searching for everything in the "Array" implementation, but I need to use a "Custom" file provider.  Thank you.
