### ISSUE TITLE
DX Data Grid Summary for Selected rows

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#11393]
### Steps to Reproduce:

1.  Need  Data Grid Summary column for selected rows only (selection mode: multiple)
2. 
3. 

### Results You Received:
1. unable to calculate summary using custom summary while selecting multiple rows

### Results You Expected:
1. Need to calculate summary while selecting rows in run time. Please find attachment

### Environment Details:
![Summary](https://user-images.githubusercontent.com/47413890/71876763-8dd4d580-314d-11ea-8d9a-5e6cd017e2d7.png)

**Comment by vconst** [comment]
Hi, @sunbala,

You can find the solution in the Custom Summaries demo: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CustomSummaries](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CustomSummaries).

If you have other technical questions, please submit a new ticket to our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
