### ISSUE TITLE
ignoreEmptyPoints in chart not work

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#11576]
I set ignoreEmptyPoints true but show null value in argumentaxis.
for example USA point is null:
[https://codepen.io/hassandl/pen/eYmPRwq](https://codepen.io/hassandl/pen/eYmPRwq)

**Comment by AlisherAmonulloev** [comment]
Please submit your question to our Support Center: https://www.devexpress.com/ask

**Comment by HASSANDL** [comment]
This issue is no question, is a bug report.
