### ISSUE TITLE
DxDataGird-column: data  lost and validates fail when set both calculateDisplayValue& validationRules(required) property to a column

### ISSUE THREAD

**Issue by steelcg** [DevExpress/DevExtreme#11601]
# Bug Report

**Package versions:**

    devexteme version: 19.1.6
    devextreme-vue version: 19.1.6

**Steps to reproduce:**

```javascrip
{
        dataField: "datetime",
        dataType: "datetime",
        allowEditing: true,
        caption: "Date time", 
        type: "datetime",
        editorOptions: {
          showClearButton: true,
          calendarOptions: { showTodayButton: true },
          acceptCustomValue: false
        },
       
        format: "yyyy-MM-dd HH:mm:ss",
        calculateDisplayValue: rowData => rowData.datetime ? moment(rowData.datetime.$date).format("YYYY-MM-DD HH:mm:ss"):"",
        validationRules: [{
          type: "required"
        }],
        calculateCellValue: rowData => rowData.datetime ? new Date(rowData.datetime.$date):null
        
        // if remove validationRules or calculateCellValue property, this works
        // but I need validation and auto header filter features.
      }
```
set calculateDisplayValue& validationRules(required) property to a column(column a), edit another column will lead data of column a lost and validates fail.

If remove validationRules or calculateCellValue property, this works
But I need validation and auto header filter feature.

note: this issue happens both devextreme and devextreme-vue. for some network problems, i just give the devextreme example. sorry for this.

refer to [Code pen page](https://codepen.io/steelcg/pen/BaazXay?editors=1010)

1. edit name column, such as n1-> n1111, then click save button.
2. you will see the data lost and validate fail

**Current behavior:**

data lost and validate fail

**Expected behavior:**

no data lost and validate successfully

**Screenshots:**

![issue](https://user-images.githubusercontent.com/38218864/66987705-d737fa80-f0f3-11e9-8990-30b53e8390c9.png)

**Comment by Alyar666** [comment]
Hello @steelcg,

From what I gather, you implemented calculateCellValue because you have complex data in a cell. You can set dataField in the following manner: dataField: "datetime.$date"

In this case, it will not be necessary to implement calculateCellValue. Is this a suitable solution for you?
