### ISSUE TITLE
Error in PieChart's label

### ISSUE THREAD

**Issue by Lehakos** [DevExpress/DevExtreme#11666]
### Steps to Reproduce:
1. Add PieChart
2. Add Legend
3. Add Title to legend 
4. Add verticalAlign="bottom" to Title
5. Set small size to chart (The legend should be hidden due to the container size)

### Results You Received:
Chart is broken. TypeError: "that._markersGroup is null"

### Environment Details:
I prepared a sandbox: https://codesandbox.io/s/determined-mcnulty-xhi4i

**Comment by alexanderPolosatov** [comment]
Hi,

I created a [ticket](https://supportcenter.devexpress.com/ticket/details/T854736) about this issue in our Support Center and suggest you track it to be notified of our progress.
