### ISSUE TITLE
Chart tooltip & label problem with rtl language

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#11699]
chart tooltip & label problem with rtl language.
https://codepen.io/hassandl/pen/NWPJYyq

![image](https://user-images.githubusercontent.com/22093903/73133481-56679380-403e-11ea-9ee5-fae719602b06.png)

**Comment by AlisherAmonulloev** [comment]
Please submit your question to our Support Center: https://www.devexpress.com/ask

**Comment by HASSANDL** [comment]
this is a report bug not a question.
Are you problem with me?
