### ISSUE TITLE
DxDataTable doesn't get focus when is selected by table selector on JAWS screen reader

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#11797]
### Steps to Reproduce:

 

1. Add two dxDataGrid on a page

2. Open JAWS screen reader

3. press Tab to go to first table and continue to some rows and columns

4. press ctrl + Ins + T, JAWS will open a table selector

5. Select second table

6. press Tab

 

### Results You Received:

Focus stays on first table

 

 

### Results You Expected:

Focus should go to the tabled selected (in this case second table)

 

 

### Environment Details:

DevExtreme 19.1.6

**Comment by jtoming830** [comment]
Hello,

I reproduced the behavior you described. I created a bug report in the Support Center and forwarded it to our team for further research.
[https://supportcenter.devexpress.com/ticket/details/t862713/dxdatagrid-doesn-t-get-focus-when-is-selected-by-table-selector-on-jaws-screen-reader](https://supportcenter.devexpress.com/ticket/details/t862713/dxdatagrid-doesn-t-get-focus-when-is-selected-by-table-selector-on-jaws-screen-reader)

We will let you know once we have any news.

**Comment by RezaRahmati** [comment]
Answer from support center:

The issue occurs because of a conflict between the dxDataGrid and JAWS keyboard navigation. There are two ways to resolve the issue:

Use the onKeyDown event and handle the key combination to clear the focus from the dxDataGrid element (codepen sample):
```
{
    . . .
    onKeyDown: e => onDataGridKeyDown(e),
    . . . 
}

function onDataGridKeyDown(e) {  
    const event = e.event;  
    if(event.key === 'o' && event.ctrlKey && event.altKey) {  
        $(':focus')  
            .trigger('dxpointerdown')  
            .trigger('blur');  
        e.handled = true;  
    }  
}

```
Disable the dxDataGrid keyboard navigation by using the keyboardNavigation.enabled option.
