### ISSUE TITLE
Tabpanel, Tabs - Show the close button on a tab

### ISSUE THREAD

**Issue by pssrecom** [DevExpress/DevExtreme#11824]
Why TabPanel and Tabs widget. Show close button on item is not supported. This is an important feature, such as easyUI: www.jeasyui.com

**Comment by EugeniyKiyashko** [comment]
Hello,

We researched how to add the Close Button to Tabs and TabPanel widgets and found that it will take us some time to implement a possible approach.

We plan to introduce a similar solution for TabPanel with close button functionality in the near future (though I cannot promise any strict time frame). At the moment, we're working on the features listed in our [Road Map](https://js.devexpress.com/Roadmap/) and this functionality is not in our immediate plans. We appreciate your understanding.

In the meantime, as a workaround for this scenario, you can place a custom button into the Tab of dxTabPanel widget using [itemTitleTemplate](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTabPanel/Configuration/#itemTitleTemplate). Use the [splice](http://www.w3schools.com/jsref/jsref_splice.asp) method to delete items from an items array on a 'close' button click. Here's an CodePen example demonstrating how to do this: [https://codepen.io/EugeniyKiyashko/pen/eYNWrrX](https://codepen.io/EugeniyKiyashko/pen/eYNWrrX)

**Comment by pssrecom** [comment]
Very much looking forward to it. Thank you for the example.
