### ISSUE TITLE
Why do not trigger scroll event ?

### ISSUE THREAD

**Issue by lain9293** [DevExpress/DevExtreme#11859]
# Support Question

https://codesandbox.io/s/event-handling-devextreme-lookup-5ty7v?fontsize=14&hidenavigation=1&theme=dark

**Comment by AlisherAmonulloev** [comment]
I reproduced the issue and created a public ticket in our Support Center: https://supportcenter.devexpress.com/ticket/details/t873450
We will update the ticket once we make any progress.
In the meantime, you can handle the **scroll** event by setting the onScroll option in the widget's onInitialized event handler:
```js
onInitialized(e) {
    e.component.option("onScroll", function(args) {
        console.log("test");
    });
}
```
