### ISSUE TITLE
No need to load values when getting fields for PivotGrid

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#11959]
Currently `getFieldValues` function in `devextreme/ui/pivot_grid/data_source.js` assign `skipValues: true` to `loadOptions`.
(https://github.com/DevExpress/DevExtreme/blob/4703178bce8d27009b6e14bd2428ba5390f1538f/js/ui/pivot_grid/data_source.js#L769
But this value not used in `createLoadOptions`.
https://github.com/DevExpress/DevExtreme/blob/4703178bce8d27009b6e14bd2428ba5390f1538f/js/ui/pivot_grid/remote_store.js#L151-L190

Requests for getting fields almost the same as requests for getting data. I want to have `skipValues` field in `loadOptions` when I getting fields or something like this for knowing than I not need to get values (it takes long time for me).

**Comment by Semigradsky** [comment]
I would be happy if you will pass `skipValues` to `loadOptions`. Smth like:
```
  if (options.skipValues) {
    loadOptions.skipValues = options.skipValues;
  }
```

**Comment by igormalzew** [comment]
Would you please clarify what task you need to solve by adding this parameter.
Maybe you are trying to optimize a request for calculating aggregated values when opening a header filter, or do you have a different scenario?
Could you please describe your real scenario in greater detail and how this parameter will help you solve the problem?

**Comment by Semigradsky** [comment]
@igormalzew I have two goals.

At the first, optimize a request for getting possible header values when opening a header filter. I see that values which I need to generate is not used.

At the second, I want to load more header values for filtering that there are on grid. For example: load grid data for one month but load filter values for two years. Currently requests for getting filter values and for getting grid data almost the same, I can't distinguish them.

**Comment by igormalzew** [comment]
Regarding your query, please refer to [this ticket](https://supportcenter.devexpress.com/internal/ticket/details/T863867) wherein a similar issue was discussed.

If you have any questions, please submit a new ticket on [this page](https://www.devexpress.com/Support/Center/Question/Create)
