### ISSUE TITLE
Feature request: SSML editor

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#12044]
In the component there is a Html Editor that supports both markdown and html, in my project I need SSML editor and Html editor. there is a free ssml editor [https://www.npmjs.com/package/quill-rich-voice-editor](https://www.npmjs.com/package/quill-rich-voice-editor), but since it's not compatible with all my themes (in devextreme) I was wondring if it's possible to Support SSML in Html Editor as a new feature

**Comment by DokaRus** [comment]
Thank you for your suggestion! This feature is not included in our short-term plan, but we will take it into account during further development.
We will also check the existing problems with the integration of third-party Quill extensions.
