### ISSUE TITLE
[Question] Change locale on the fly

### ISSUE THREAD

**Issue by felpel** [DevExpress/DevExtreme#12074]
Hi,

I'm trying to change the locale of my application at runtime with a language picker like this one:

![image](https://user-images.githubusercontent.com/5000004/38840522-23cc2e58-41ae-11e8-8684-cb4c18beb80d.png)

In the current screenshot, "French" would be the selected language, but I could pick also "English".

It works fine when I call the locale method in my custom localization module after loading my french and english translations as:

```ts
// DevExtreme localization
import { loadMessages, locale } from "devextreme/localization";
import * as enMessages from "devextreme/localization/messages/en.json";
import * as frMessages from "devextreme/localization/messages/fr.json";

loadMessages(frMessages);
loadMessages(enMessages);

locale(navigator.language);
```

If I hardcode `fr` or `en` as the argument for the locale method, I see your translations showing up. Although, after I've selected another language from my combo box, it's seems that recalling `locale(selectedLanguage)` does nothing. **Do I need to refresh the webpage?** It seems that it's the case with your Angular [example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Localization/UsingIntl/Angular/Light/)...

**Comment by Azbesciak** [comment]
I am fully agree with the above comments.
Maybe at least you should expose method to manually update translations? For now I have the same problem, and stumble with your components for some (quite long) time. And the best is - you are not totally correct; lazy initialized components like calendar, or other if those exist with `ngIf` will have the i18n correct with the one at the moment of initialization. So you can have dx components with different locales at the same time.

**Comment by LexDX** [comment]
Hi @All,

We understand that the current solution is not perfect and we hope to come up with a better derision in one of our future updates. As you know, such improvements require lots of changes in the core code base. We may also need to redesign the architecture of our current controls, which is not fast and simple. So, at the moment we are unable to give you exact time frames.
