### ISSUE TITLE
Virtual scrolling, virtual row rendering, and page size

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#12085]
### Steps to Reproduce:

1.  Open the local virtual scrolling demo at https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/VirtualScrolling/Angular/Light/
2. Set the grid's height to 900 and set rowRenderingMode (dxo-scrolling) to 'virtual'
3. Scroll quickly. Eventually the bottom few displayed rows will not be rendered (gray bars).
4. Now set pageSize (dxo-paging) to 30 (up from the default value of 20).
5. Scroll quickly again.  No more persistent gray bars.

### Results You Received:
With virtual scrolling and virtual row rendering, roughly the top pageSize rows are guaranteed to render, but below that rows sometimes will not render depending on scrolling pattern.  The number of rows that fit in the grid viewport depends on zoom and screen resolution, so setting pageSize to 30 as above will only work for standard zoom and resolution.

### Results You Expected:
- pageSize should have no effect when scrolling is virtual.  All rows in the viewport should render regardless of the pageSize, zoom, or screen resolution.  If pageSize is going to affect virtual scrolling this should be documented.
- The documentation for virtual row rendering should be improved.  It's not clear what it does in the case of local virtual scrolling.

**Comment by AntonSermyazhko** [comment]
Hello,

We have a [similar issue](https://supportcenter.devexpress.com/internal/ticket/details/T750279) in our Support Center.
You can subscribe to it to receive notifications of our progress.
