### ISSUE TITLE
autocomplete list bug

### ISSUE THREAD

**Issue by rsznajder** [DevExpress/DevExtreme#12120]
Here is my code
<dx-autocomplete
                  placeholder="Wstaw nazwę towaru..."
                  [dataSource]="towarDataSource"
                  [maxItemCount]=1000
                  [minSearchLength]=0 
                  [openOnFieldClick]=true
                  [showDropDownButton]=true
                  [(value)]="nazwaTowar"
                  (onItemClick)="onItemClickNazwaTowar($event)">
              </dx-autocomplete>

An array towarDataSource has 100 elements. When I click on an empty control it shows only 20 elements. When I type any letter it shows filtered items properly. The bug is when the control is empty -  [maxItemCount] doesn't work as expected then.

**Comment by artem-kurchenko** [comment]
Hi @rsznajder ,

Thank you for the report. We'll research this behavior in the context of the [t869431](https://supportcenter.devexpress.com/ticket/details/t869431/autocomplete-doesn-t-display-items-according-to-maxitemcount-if-openonfieldclick-is-true)  Support Center thread. As an immediate workaround, you can define [DataSource.pageSize ](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/Configuration/#pageSize)
