### ISSUE TITLE
TreeList - enhance recursive parent nodes intermediate state

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#12169]
Use case: 
When `selection: {mode: 'multiple', showCheckBoxesMode: 'always', recursive: true}` and if a parent node has multiple children I want to be able to select all the children without the parent node automatically selected in which case I want the parent to show an intermediate icon state. In which case if I also after selecting the all children then select the parent too, then the parent should show a normal checkbox icon as well. 

If I don't have anything selected, and I select a parent directly that has multiple children then I want it to select the parent and all the children (which is how it already works).

Would be great if there was an option for recursive to work as above as currently if all children are selected, it automatically selects the parent.

In the meantime, I have a version of what I desire working using the `onSelectionChanged` event -- which adds the `dx-checkbox-indeterminate` class to the parent as needed but the moment the parent is collapsed or expanded the TreeList automatically clears it. Suggestions how I can prevent it from touching it on expand/collapse?

**Comment by genachka** [comment]
@Alyar666 @vconst or someone from DevExpress - would appreciate assistance / response?

**Comment by onebalaban** [comment]
Hello,

If all child nodes are selected, dxTreeList automatically checks the parent selection checkbox. This behavior is expected and relates to dxTreeList recursive selection. In this mode, the parent selection checkbox can't be in the intermediate state if all child nodes are selected. We don't plan to modify this behavior or add extra options in the near future - see our [Roadmap ](https://js.devexpress.com/Roadmap/)for 2020. However, we may consider enhancing this functionality in future releases. Please stay tuned to our news.

> I have a version of what I desire working using the onSelectionChanged event -- which adds... TreeList automatically clears it

dxTreeList re-renders its markup when a node is collapsed or expanded. You can re-assign the required CSS class to a particular element in the onContentReady event handler. If you have issues with this approach, please submit a ticket to our [Support Center](https://www.devexpress.com/Support/Center/Question/List/1) and describe the issue in detail. Also, attach a simple project demonstrating it and your current progress.

Regards,
Romeo
