### ISSUE TITLE
TreeView - Selection enhancements

### ISSUE THREAD

**Issue by novsstation** [DevExpress/DevExtreme#12161]
# TreeView - Selection enhancements

## The Problem
The TreeView widget doesn’t provide a built in API to retrieve selected nodes/keys.

## The Proposed Solution

The new `getSelectedNodes`/`getSelectedNodeKeys` methods which allow you to retrieve selected nodes/keys.

```js
let selectedNodes = treeViewInstance.getSelectedNodes();
let selectedKeys = treeViewInstance.getSelectedNodeKeys();
```

## Show selected employees

```js
export class AppComponent {
  selectedEmployees: Employee[] = [];
  ...
  treeViewSelectionChanged(e) {
    const selectedEmployees = e.component.getSelectedNodes()
        .map((node: dxTreeViewNode) => { return {
            fullName: node.itemData.fullName,
            prefix: node.itemData.prefix,
            position: node.itemData.position
        } });
    this.selectedEmployees = selectedEmployees;
  }
```

# Try It

## Live Sandbox

[JQuery](https://codepen.io/SNovikov/pen/bGdpZPX?editors=1111)
[Angular](https://codesandbox.io/s/item-selection-and-customization-devextreme-tree-view-ph6i9)
[React](https://codesandbox.io/s/item-selection-and-customization-devextreme-tree-view-6pwze)
[Vue](https://codesandbox.io/s/item-selection-and-customization-devextreme-tree-view-k5t6e)

# We Need Your Feedback

## Take a Quick Poll

[Do you find this feature useful?](https://docs.google.com/forms/d/e/1FAIpQLSfFBXEJCklaEyVmS5Ad6zuQCKJx55dWXMm6yPv4f3KZGADD9g/viewform)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by jsdmitry** [comment]
These features are now available in the [v20.1](https://github.com/DevExpress/DevExtreme/releases/tag/20.1.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
