### ISSUE TITLE
Change return type on CustomStore methods

### ISSUE THREAD

**Issue by krilllind** [DevExpress/DevExtreme#12160]
Is there a reason why `CustomStore` and `CustomStoreOptions` has different typings on for example the `load()` method?

If i create a new class and extend CustomStore, I have to implement a load method with the return signature of `Promise<any> & JQueryPromise<any>` while if a create a new CustomStore and pass CustomStoreOptions, the signature for load method is `Promise<any> | JQueryPromise<any> | Array<any>`.

This makes it really hard to create a class which extends CustomStore, because you simply cannot return a plain `Promise<any>` or a `jQuery.Deferred().promise()`.

Is it possible to change [Store](https://github.com/DevExpress/DevExtreme/blob/caa1a6bb33b7597a32c8dcf3dd760a906f28b575/ts/dx.all.d.ts#L1449) to have the same return type on all methods as in [CustomStoreOptions](https://github.com/DevExpress/DevExtreme/blob/caa1a6bb33b7597a32c8dcf3dd760a906f28b575/js/data/custom_store.d.ts#L11)?

When I use CustomStore in Angular, I like to create a Service which extends CustomStore and allows me to use DI to inject things like HttpClient.

**Comment by artem-kurchenko** [comment]
Hi,

CustomStore supports jQuery.Promise (it's mainly used in jQuery, ASP.NET Core and MVC) and native Promise for Angular, React, Vue. That's why we use the `Promise<any> & JQueryPromise<any>` signature.

**Comment by krilllind** [comment]
@artem-kurchenko But shouldn't that signature also be `Promise<any> | JQueryPromise<any>` then?
Why is there a difference between load signature as parameter in constructor for CustomStore vs load signature when you extend CustomStore?

**Comment by artem-kurchenko** [comment]
@krilllind 
We support both types at the same time and not only one of them So, we use `&` in this case. However, I'm not sure about the second part.  Could you post an example for testing so I can check how you decided to extend CustomStore in action?

**Comment by krilllind** [comment]
@artem-kurchenko Hi, I created a gist where I wrote two versions. One is extending a CustomStore and one is just creating a new instance, passing options.

Both of my examples are written in TypeScript and Angular (as I am trying to using a CustomStore as an Angular service).

https://gist.github.com/krilllind/c37610442ae309e354c8ca9c7c1d2d0d

By extending CustomStore, I can implement my own logic for caching (just an example), and all of my logic can be shared by just injecting the service into another component.

**Comment by hakimio** [comment]
@krilllind I think you are over-complicating it. Here is an example of how we use CustomStore in Angular project without any need to change CustomStore typings: https://gist.github.com/hakimio/0799288b6436aeb48025490649b44842

EDIT: you can use [Angular http interceptor](https://angular.io/guide/http#caching) to [cache responses](https://github.com/angular/angular/blob/master/aio/content/examples/http/src/app/http-interceptors/caching-interceptor.ts).

**Comment by artem-kurchenko** [comment]
Hi @krilllind,

I agree with @hakimio. In this case, it's more efficient to make a custom wrapper around CustomStore.
We use a similar technique in our [DevExtreme.AspNet.Data](https://github.com/DevExpress/DevExtreme.AspNet.Data) library. This way, you can add new options\extend basic features without relying on our internal structure.
