### ISSUE TITLE
About SelectBox

### ISSUE THREAD

**Issue by pssrecom** [DevExpress/DevExtreme#12182]
.SelectBox()
.DataSource(d => d.Mvc().Controller(..).LoadAction(...)
.Value(...)

In software projects, if the data is large, we always load the display value first when displaying the card. When click on SelectBox, then look up the data from the database.

Recommendation:

1. Add displaytext or modify displayvalue property to display field text.
2. When click on a field, look up the data from the database. And then it matches with Value.

**Comment by flagmanAndrew** [comment]
Hello,
Thank you for the suggestion, but it's unclear why a new option for display text is needed for such cases.

SelectBox doesn’t load records until you open its drop down or start typing. If you initially assign a value to SelectBox, the editor loads only one record by its key (the editor’s value is a record’s key). Usually, this operation is immediately executed. Especially, if a table in your connected data base is indexed.

Are you experiencing any issues with this scenario? If so, would you please describe them and share the complete SelectBox configuration and the server-side code responsible for data loading? 

I hope to hear from you soon.

**Comment by pssrecom** [comment]
I'm sorry that I didn't notice the query data according to the Key when I used it.

Let me give you an example:
I have a purchase order, It is divided into Head and Body.
Head include Template, Organization, Customer, Department, Employee,  etc.
Body include Items, Position, Price, Quantity, Amount, etc.

There is a lot of information on this purchase order. 
Now this purchase order has been approved and can only be viewed.

Suppose the information is queried through SQL(Oracle) and displayed:

Select head.lngOrganizationID, 
          head.lngCustomerID, 
          head.lngDeparmentID,  ...
          Organization.strOrganizationCode || ' '  || Organization.strOrganizationName As Organization,
          Customer.strCustomerCode || ' '  || Customer.strCustomerName As Customer,
          Deparment.strDeparmentCode || ' '  ||  Deparment.strDeparmentName As Deparment, ...
From PurchaseOrder head, Organization, Customer,  Deparment, ...
Where head.lngPurchaseOrderID = 1000 ...

When the Organization is set up, the data is found by Key(lngOrganizationID) from database, it's OK.
However, when the data cannot be found, SelectBox displays as an empty string.

Therefore, when displaying the data, we only need to load: "Organization.strOrganizationCode ||" '|| Organization.strOrganizationName As Organization",
Instead of querying the data again from the database according to the Key(lngOrganizationID).

That's Why：
"When click on a field, look up the data from the database. And then it matches with Key."

However, there are no performance problems with Key. Therefore, for reference only.

Thank you！

**Comment by flagmanAndrew** [comment]
Hello,
SelectBox displays an empty string when it has a value and cannot locate it in a key field in its data source. In your case, the editor queries the server you specified in the editor config. If nothing is found, SelectBox will display an empty string even after you open its dropdown. If the SelectBox data source has such a key, the editor will show it without querying all data to show it in the dropdown. Thus, it is unclear why pre-loading OrganizationId and OrganizationCode is necessary.
Below you can find my sample demonstrating how SelectBox queries data. In the browser’s console you can see that it obtains a single row by a key when the page shows. The editor fetches all data when you open the dropdown for the first time.
Would you please modify my sample to demonstrate the scenario where SelectBox cannot locate its value before opening the dropdown and pre-loading values is required?
 
In fact, if you only want to display OrganizationName on a page, you can load the required value and display it in a separate TextBox.
[DXTSelectBoxTest.zip](https://github.com/DevExpress/DevExtreme/files/4348728/DXTSelectBoxTest.zip)

**Comment by pssrecom** [comment]
Thank you for your care. There is no problem with SelectBox. I provided documentation to explain.
[about selectbox.docx](https://github.com/DevExpress/DevExtreme/files/4365052/about.selectbox.docx)

**Comment by flagmanAndrew** [comment]
Thank you for the detailed explanation. Currently, we don't have plans to extend the SelectBox API to provide a way to set a display text so that you can use preloaded texts for multiple editors. Nevertheless, we will take your scenario into account when planning our future updates. Please watch for them in our [What's New](https://js.devexpress.com/New/19_2/).

I'm happy to hear that you are OK with the performance of SelectBox.
