### ISSUE TITLE
PolarChart Annotations

### ISSUE THREAD

**Issue by pavelgruba** [DevExpress/DevExtreme#12207]
# The Problem 
In DevExtreme v19.1, we introduced [Chart Annotations](https://community.devexpress.com/blogs/javascript/archive/2019/04/30/devextreme-charts-annotations-v19-1.aspx). However, this functionality is not available in other widgets.

# The Proposed Solution
We are planning to implement annotations in other data visualization widgets. In this release, we are focusing on the **PolarChart**.

PolarChart Annotations are configured similarly to Chart Annotations. PolarChart Annotations support the polar coordinate system (angle and radius) and other coordinate types. However, PolarChart Annotations do not have the same `axis` option as the Chart because the PolarChart does not support multiple value axes.

The following sections demonstrate different scenarios for annotation placement. The values used in each sample are also displayed as labels in the annotations.

## Use chart coordinates
```js
annotations: [{ 
  value: 15,  
  argument: "April"
}]
```
![Chart coordinates](https://user-images.githubusercontent.com/19471748/75755141-1ed7bf80-5d3f-11ea-8525-bb6493dec24d.png)

## Display an annotation on an axis 
```js
annotations: [{ 
  // this annotation is shown on the value axis 
  value: 15
}, { 
  // this annotation is shown on the argument axis 
  argument: "May"
}]
```
![On axes](https://user-images.githubusercontent.com/19471748/75755139-1e3f2900-5d3f-11ea-99cd-ff6c200697ca.png)

## Anchor an annotation to a series 
```js
annotations: [{
  argument: "October",
  series: "Series 1"
}]
```
![Series](https://user-images.githubusercontent.com/19471748/75755138-1e3f2900-5d3f-11ea-8a00-cd1b91085675.png)

## Use polar coordinate system
```js
annotations: [{
  radius: 100,
  angle: 45
}]
```
![Polar coordinates](https://user-images.githubusercontent.com/19471748/75770674-784ce800-5d59-11ea-94d0-fab9be1c5e41.png)

## Use pixel coordinates 
```js
annotations: [{
  x: 70,
  y: 120
}]
```
![Pixel coordinates](https://user-images.githubusercontent.com/19471748/75755128-18e1de80-5d3f-11ea-8126-81118cf10f3f.png)

## Mixed anchoring 
You can use different coordinate types simultaneously. In the following example, we use polar and chart coordinates:

```js
annotations: [{ 
  radius: 120,  
  argument: "July"
}]
```
![Mixed](https://user-images.githubusercontent.com/19471748/75755137-1da69280-5d3f-11ea-8f10-4826e27e9988.png)

# Try It
## Live Sandbox
[Angular](https://codesandbox.io/s/annotations-devextreme-polar-charts-24vfc)
[React](https://codesandbox.io/s/annotations-devextreme-polar-charts-50vtc)
[VueJS](https://codesandbox.io/s/annotations-devextreme-polar-charts-rhx4v)
[jQuery](https://codepen.io/pavelgruba-the-scripter/pen/xxGrmMv?editors=0010)

# We Need Your Feedback
## Take a Quick Poll
[How does the new Feature meet your needs?](https://forms.gle/QbeBZSa9xfk7fmok9)

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by alexanderPolosatov** [comment]
Thanks to everybody who gave us early feedback on this feature. The feature is now available in the [v20.1 release](https://github.com/DevExpress/DevExtreme/releases/tag/20.1.3). I'm closing this thread. In the case of bugs or questions, feel free to create new [GitHub issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
