### ISSUE TITLE
HtmlEditor - Multiline toolbar

### ISSUE THREAD

**Issue by jsdmitry** [DevExpress/DevExtreme#12236]
# The Problem

The width of the toolbar in the Html Editor does not always fit all items, and extra items are hidden in an overflow menu. The user should scroll the menu when there are many items.

# The Proposed Solution

We plan to implement a multi-line toolbar which can be enabled via the `multiline` option:

```js
toolbar: {
    multiline: boolean  
}
``` 

## UI Design
![HtmlEditor - multiline](https://user-images.githubusercontent.com/11206389/75861888-118a0600-5e0f-11ea-8b5d-4604b3082ca2.gif)

# Try It
## Live Sandbox
[Angular](https://codesandbox.io/s/overview-devextreme-html-editor-fitm4)
[React](https://codesandbox.io/s/overview-devextreme-html-editor-14brw)
[VueJS](https://codesandbox.io/s/overview-devextreme-html-editor-gjqs7)
[jQuery](https://codepen.io/Doka/pen/jOPXbgg?editable=true)

# We Need Your Feedback
## Take a Quick Poll

[Do you find multiline toolbar in the HtmlEditor useful?](https://forms.gle/rFduh1NtRsPAnUTS7)

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by DokaRus** [comment]
A new DevExtreme package `devextreme@20.1-next` is available now.
You can test this feature using examples that reside in the Live Sandbox section of the discussion page.
