### ISSUE TITLE
Number Box deactivate mouse wheel

### ISSUE THREAD

**Issue by JD2k** [DevExpress/DevExtreme#12233]
I tried to deactivate mouse wheel functions (increasing and decreasing) in a number box in react. Is this possible? If not, would be nice to implement this feature.

Thanks

**Comment by DokaRus** [comment]
You can refer to the following tickets in our SC:
[NumberBox - How to disable changing on mouse wheel](https://supportcenter.devexpress.com/ticket/details/T588916/numberbox-how-to-disable-changing-on-mouse-wheel)
[NumberBox - How to prevent only the mouse wheel event and keep arrows active](https://supportcenter.devexpress.com/ticket/details/T741892/numberbox-how-to-prevent-only-the-mouse-wheel-event-and-keep-arrows-active)
