### ISSUE TITLE
TextBox mask and NumberBox format causes flickering (jumping focus) on editor fields in iOS Chrome

### ISSUE THREAD

**Issue by OmniAndy** [DevExpress/DevExtreme#12256]
**Package versions:**
devexteme version:  **19.2.6**
devextreme-angular version:  **19.2.6**
iOS: **13**
Chrome: **latest**

**Steps to reproduce:**
I know this occurs on NumberBox and TextBox.
**NumberBox** - if you have two numberboxes (each having their own binded value) and one numberbox changes the value of another numberbox's value, focus will jump back and forth between the two numberboxes.  focusStateEnabled="false" removes this behaviour and the controls act as expected - except you cannot tab to the controls, obviously.

**TextBox** - if you have multiple textboxes with a mask applied to each, focus jumps between the textboxes on init.  focusStateEnabled="false" removes this behaviour.

This behaviour ONLY occurs on iOS Chrome from our testing.  So I am not sure if it is a Chrome bug or DevExtreme bug.

**Comment by OmniAndy** [comment]
I think the core problem here is applying Formats and Masks to NumberBox and TextBox.  FocusStateEnabled="false" is just a band-aid.  However, disabling focusStateEnabled="false" is causing the values to not bind.  Again, this is only happening on iOS Chrome (latest versions).

**Comment by OmniAndy** [comment]
Also using Angular v8.2.13

**Comment by OmniAndy** [comment]
The issue does not occur in Angular v6.0.3

**Comment by OmniAndy** [comment]
I created an example in StackBlitz

This is the code:
https://stackblitz.com/edit/angular-utu2s8

Sharing the StackBlitz App URL was not working, so I deployed the example to Firebase:
https://od-stack.firebaseapp.com/?76967

The example is three NumberBoxes.  When you input a value into NumberBoxes 1 and 2, a method is called to calculate the product of the two values and place them in NumberBox 3.  If you go to the Firebase url on an iOS Chrome browser, enter values into NumberBox 1 and 2, it will lock the screen up and the keyboard will start flickering.

The issue also occurs if you have more than one TextBox with masks applied.

**Comment by alexander-kotov-dx** [comment]
Hello,

Thank you for pointing this behavior out. We will research it in context of the [T870443](https://supportcenter.devexpress.com/Ticket/Details/T870443/textbox-mask-and-numberbox-format-causing-focus-issues-in-ios-chrome) and [T870784](https://supportcenter.devexpress.com/Ticket/Details/T870784/numberbox-the-use-of-several-editors-with-bound-values-can-cause-focus-issues-in-chrome) tickets in our Support Center.
