### ISSUE TITLE
Possibility to add a tooltip to form item

### ISSUE THREAD

**Issue by JD2k** [DevExpress/DevExtreme#12250]
I found no possibility to add a tooltip to a simple form item. Is this possible?

My code looks something like this:

`<Form>`
`<Item itemType="group" caption="Test group" colCount={2} colSpan={2}>`
         `<Item dataField="Test1"/>`
         `<Item dataField="Test2" />`
 `</Item>`
 `</Form>`

I am using it inside editing from a datagrid.

Thanks in advance

**Comment by jsdmitry** [comment]
How do you plan to use tooltip in the simple item? For a label or an editor?

**Comment by JD2k** [comment]
I thought about extension, that would use the helptext value.

In the meantime i realised it with a custom editor an an Overlay. In case some needs it:

    renderTooltipEditor(cell) {
        let onValueChanged = this.onValueChanged.bind(this, cell);
        return <OverlayTrigger
            placement="bottom"
            trigger={'focus'}
            overlay={
                <Tooltip id={cell.item.dataField} className="my-tooltip">
                    TooltipContent
                </Tooltip>
            }>
            <div><TextBox
                defaultValue={cell.value}
                onValueChanged={onValueChanged}
            /></div>
        </OverlayTrigger>;
    }

Thanks for your reply
