### ISSUE TITLE
Hide checkbox for nested rows in TreeList

### ISSUE THREAD

**Issue by zlannin** [DevExpress/DevExtreme#12255]
# Support Question

I'm using the TreeList with a hierarchical structure. Can I hide the select checkbox for nested items?

I don't want `Jane Doe` to have a checkbox.
![image](https://user-images.githubusercontent.com/11505024/75450981-5efd0380-5935-11ea-8401-ee877d3d35ec.png)

**Comment by onebalaban** [comment]
Hello,

Please refer to the [TreeList - How to allow selecting child nodes only](https://supportcenter.devexpress.com/ticket/details/t632675/treelist-how-to-allow-selecting-child-nodes-only) ticket where we answered a similar question.

Regards,
Romeo
