### ISSUE TITLE
treelist hang on huge amount of data

### ISSUE THREAD

**Issue by muhammedMoussa** [DevExpress/DevExtreme#12290]
I'm running v `19.1.4` and have a grid with dataSource +24k record tree list shows no data only, remaining tree lists works fine.

error: 
`
core.js:3828 ERROR DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'Accounts' exceeded the quota.
`

**Comment by onebalaban** [comment]
Hello,

Please create a repository / sample project demonstrating the issue and send it to us for further research.

Regards,
Romeo

**Comment by muhammedMoussa** [comment]
you want me to share endpoint?
