### ISSUE TITLE
DataGrid breaks its layout when rows are grouped by a band column

### ISSUE THREAD

**Issue by AnReZa** [DevExpress/DevExtreme#12309]
As an experiment, I've added a band of three already-existing columns to my column list. When grouping to this virtual column, the grouping itself works as expected. However, in the header column, it doesn't hide the three columns under the band and breaks the layout.

````c#
this.columnSettings.push({
    caption: 'Artikelbezeichung',
    columns: this.columnSettings.slice(0, 3),
    allowGrouping: true,
    calculateCellValue: dataRow => dataRow.articleNo + ' ' + dataRow.description0 + ' ' + dataRow.description1,
    allowGrouping: true
})
````

Before:
![image](https://user-images.githubusercontent.com/42647891/76631429-fa02f980-6541-11ea-999c-52c604caad2d.png)

After:
![image](https://user-images.githubusercontent.com/42647891/76631463-0ab36f80-6542-11ea-9872-da9cc553f904.png)

Is there a way to fix this? I'm using the latest version from NPM.

**Comment by NickMitrokhin** [comment]
Hi,

When you group DataGrid by a certain column, the grid specifies the [groupIndex](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#groupIndex) option of this column. However, the option is not supported by band columns. See the [isBand](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#isBand) option. 

So, DataGrid does not support grouping rows by a band column.
