### ISSUE TITLE
`Cannot read property 'type' of undefined` error message on deleting row 

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#12321]
### Steps to Reproduce:

1. Open this sandbox [https://codesandbox.io/s/row-editing-and-editing-events-devextreme-data-grid-x7fus?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/row-editing-and-editing-events-devextreme-data-grid-x7fus?fontsize=14&hidenavigation=1&theme=dark)
2. click on delete button
3. select Yes

### Results You Received:
`Cannot read property 'type' of undefined` shows in console

### Results You Expected:
Record be deleted

4. click on delete button again, and select yes
5. This time record is deleted

This behavior happens on each row

### Environment Details:
Devextreme 19.2.6

![devexterme-delete issue](https://user-images.githubusercontent.com/10086092/76815317-b0c9d880-67d3-11ea-8f51-f2deaadead53.gif)

**Comment by vconst** [comment]
Hi,

The bug is already fixed in the context of the [T865833](https://supportcenter.devexpress.com/Ticket/Details/T865833) ticket.
