### ISSUE TITLE
when entering duplicate tags in dx-tag-box it removed the values

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#12343]
### Steps to Reproduce:

1. Open [https://codesandbox.io/s/overview-devextreme-tag-box-wmeb5?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/overview-devextreme-tag-box-wmeb5?fontsize=14&hidenavigation=1&theme=dark)
2. type `test` in tag box, confirm it shows the `test`
3. type `test` again

### Results You Received:
Both `test` tags are removed
(also both are removed from valueChange event argument)

### Results You Expected:
It shows both `test`, or if it doesn't let duplicates should keep one of them

### Environment Details:
Devexterme: 19.2.6

![devexterme-tag-box-issue](https://user-images.githubusercontent.com/10086092/76896624-8ece6580-6868-11ea-8913-842e68edb570.gif)

**Comment by Bykiev** [comment]
@RezaRahmati, hi!

Seems to be a really bug for me, but you can change the logic of [onCustomItemCreating](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTagBox/Configuration/#onCustomItemCreating) callback function to prevent adding duplicate values.

**Comment by RezaRahmati** [comment]
@Bykiev  can you please clone and modify my code, (as I tried before not able to do that)

**Comment by Bykiev** [comment]
@RezaRahmati, here is a sample of implementation of onCustomItemCreating function. I tried it, but it still resets all selected values, but prevents adding duplicate values to dataSource...

```
onCustomItemCreating(args) {
    let newValue = args.text;

    if (this.editableProducts.indexOf(newValue) == -1) {
      this.editableProducts.unshift(newValue);
      args.customItem = newValue;
    }
  }
```

**Comment by RezaRahmati** [comment]
@Bykiev yes, exactly, I tried it before too, just wanted to be sure we are on same page.

**Comment by Bykiev** [comment]
@RezaRahmati, it seems behaviour in https://github.com/DevExpress/DevExtreme/issues/12343#issuecomment-604974145 is correct, just try to type in already selected item, select it and it'll be removed from selection

**Comment by RezaRahmati** [comment]
@Bykiev I tried, still same behavior, tags will be removed
check my updated sandbox [https://codesandbox.io/s/overview-devextreme-tag-box-wmeb5?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/overview-devextreme-tag-box-wmeb5?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Bykiev** [comment]
@RezaRahmati, not all tags will be removed, but only duplicated. I belive this behaviour is correct, check [this](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TagBox/Overview/Angular/Light/) demo with search mode and try to select item multiple times and it'll be remove from selection. But let's wait for offical response from DevExpress team

**Comment by artem-kurchenko** [comment]
Hi all,

TagBox doesn't support duplicated tags. You can implement unique keys for each item if you wish to have the same display text for them. Please test the following example:
https://codesandbox.io/s/overview-devextreme-tag-box-9xtz3

Alternatively, you need to validate values before applying them. Please refer to [DxTagBox generates duplicate items when acceptCustomValue equals true](https://supportcenter.devexpress.com/ticket/details/T865400/dxtagbox-generates-duplicate-items-when-acceptcustomvalue-equals-true) where we discussed this task.

**Comment by RezaRahmati** [comment]
@artem-kurchenko Hi Artem, 
I don't know why I missed your response.

What I want is if user enters an item that already exists, don't do anything, right now it removes it, even with checking in onCustomItemCreating

How can I implement this behavior?

**Comment by seanoz** [comment]
> @artem-kurchenko Hi Artem,
> I don't know why I missed your response.
> 
> What I want is if user enters an item that already exists, don't do anything, right now it removes it, even with checking in onCustomItemCreating
> 
> How can I implement this behavior?

Did you ever manage to figure this out? Banging my head against the wall right now, trying to do the same.

**Comment by RezaRahmati** [comment]
> > @artem-kurchenko Hi Artem,
> > I don't know why I missed your response.
> > What I want is if user enters an item that already exists, don't do anything, right now it removes it, even with checking in onCustomItemCreating
> > How can I implement this behavior?
> 
> Did you ever manage to figure this out? Banging my head against the wall right now, trying to do the same.

No, unfortunately

**Comment by gabbyfreed-co** [comment]
Is there any update on this ticket? Having the same issue as described in the original ticket submission. If two duplicate custom items are added, I want the tagbox to only keep one of the tags, not remove them both entirely...

**Comment by stevecurrey** [comment]
I am also facing the same issue. If someone enters a custom tag twice, why are both values removed? It should only remove the duplicate.
