### ISSUE TITLE
Feature request / suggestions: control tooltip, whether to display checkbox, whether to expand, display radio on single select

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#1237]
Kodus on the new TreeList! Loving it! We're evaluating moving an existing competitors grid to this on a couple of customer projects as it solves a bunch of hacks. Thanks for creating it and supporting such awesome consistency between the grid with the features and APIs like filtering, sorting, columns, selection, etc. I hope you continue to evolve it.

On that note, a couple feature requests / suggestions for it:
* Instead of having to do a tooltip dynamically for the row on mouse over via `onRowPrepared` why not add to the columns a property that can be mapped to the data field? A couple other grid controls we've used do it this way and it's very handy. Though I realize it would be specific to the cell that way, so maybe having a `rows` object with a property for that in addition to the cell to satisfy both needs.
* When multiple select is enabled, it would be helpful to control per row whether a row can be selected. Sometimes the parent of the hierarchy should never be selected. Rather than unselecting in `onSelectionChanged`, the checkbox shouldn't even been shown and would be helpful to control that through a property that can come in the data as a boolean for each item.
* It would be helpful to control per hierarchy parent whether it's automatically expanded or collapsed. Would be helpful to control that through a property that can come in in the data as a boolean for each item.
* For single selection, in addition to support showing that the row is selected, it would be great to also support showing radio buttons and showing the selected radio button instead. Of course like above, it would need to support same as a checkbox not showing on certain items and would be great to control much the same way via data on each item.
* Update the selected row CSS. When `rowAlternationEnabled` is enabled, a row selection is really hard to tell apart from the dark background of the alternating row.
* Add support for export, including JSON, CSV, XLS/XLSX, and PDF

And of course we'd want you to add this to the other grid controls for consistency as they become useful there too.

**Comment by vconst** [comment]
Hi,
 
Thanks for the feedback. During implementation, we tried to reuse most of the DataGrid functionality. So, each new feature in DataGrid will be automatically added to TreeList.

Now, let me comment on your suggestions.
1. I do not quite understand what you mean by "a property that can be mapped to the data field". Please describe this in more detail. To show a custom tooltip, you can assign a title attribute to each cell in the onCellPrepared event handler. See the example [here](https://codepen.io/anon/pen/mMgRvJ). Also the TreeList has the onCellHoverChanged event, which can be used for showing dxTooltip with custom content and position.
2. The capability to disable selection for certain rows is in our to-do list. But we cannot say for sure when it will be implemented. Currently, to hide checkboxes for specific rows, you can use the onCellPrepared event handler.
3. Expanded rows' state in TreeList is stored in the expandedRowKeys option. We have some important reasons for this. But to accomplish the task, you can set the expandedRowKeys option to TreeList in the onNodesInitialized event handler. See an [example](https://codepen.io/anon/pen/mMgOpj).
4. The use of radio buttons to indicate selection seems strange to me. But you can implement this functionality using the onCellPrepared and the onSelectionChanged event handlers. See the [example](https://codepen.io/anon/pen/XaQpYq).
5. We aren't aware of any problems with the colors contrast. The selection color is the same for all our widgets and very similar to the selection color in bootstrap. You can always change the selection color in the ThemeBuilder tool - https: //js.devexpress.com/ThemeBuilder/. Also, we have plans to implement the focused row functionality in the future. The focused row will be darker than the selected one.
6. Export for TreeList is in our to-do list. But at present, we cannot provide any precise time frames as to when it will be implemented.

**Comment by genachka** [comment]
@vconst thanks for your followup.

1. Using the events such as onCellPrepared for something like that requires extra effort, and processing since it will be triggered for each and every cell. Imagine a list that is a couple thousand rows (which could grow to millions) by about 20 columns. Putting in if statements to check if it's that one field being worked on for a specific column where a title attrib needs to be customized seems excessive. What I was hoping for and other grids I've worked with allow simply to do this (see tooltip callback):
```
columns: [
                    {caption: 'id', dataField: 'id', visible: false},
                    {caption: 'source', dataField: 'source', visible: false},
                    {caption: 'Employee ID', datafield: 'employeeID', tooltip: function(e) {
                          return 'Employee Name: ' + e.employeeFirstName + ' ' + e.employeeLastName;
                       }
                    },
                    {caption: 'File Name', dataField: 'fileNamePath', width: '25%', encodeHtml: false, tooltip: function(e) {
                          return 'Created: ' + e.fileNameCreated + ', Modified: ' + e.fileNameModified;
                       }
                    }
]
```
2. Looking forward to that feature  eagerly. Using onCellPrepared for now as suggested (thanks).
3. Again, same as 1 above, with lots of rows, seems inefficient using the event handlers and having potentially lots of if / switch statements. Was hoping some something like this (see expandRow):
```
columns: [
                    {caption: 'id', dataField: 'id', visible: false},
                    {caption: 'source', dataField: 'source', visible: false},
                    {caption: 'Employee ID', datafield: 'employeeID', expandRow: true},
                    {caption: 'File Name', dataField: 'fileNamePath', width: '25%', encodeHtml: false}
]
```
4. I suppose that isn't too common, thanks for the workaround.
5. I'll give that a shot, thanks.
6. Eagerly await this one too.

**Comment by onebalaban** [comment]
Hello,

Your scenario is quite specific and can be covered by the workaround we suggested earlier. We didn't register similar requests for the past two years. Thus, we decided not to implement this functionality for now.

Regards, 
Romeo
