### ISSUE TITLE
Pager not showing when pageSize is greater than or equal to datasource length

### ISSUE THREAD

**Issue by zlannin** [DevExpress/DevExtreme#12459]
# Bug Report

If you set paging.pageSize greater than or equal to your datasource length, the pager doesn't show.

**Package versions:**

    devexteme version:
    devextreme-angular version:

**Steps to reproduce:**

Go to https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RecordPaging/Angular/Light/ and update pageSize to 20.

**Current behavior:**
Pager is hidden because the page size is >= to datasource length.

**Expected behavior:**
The pager should still show because the user may want to change the pageSize back down to 5 or 10.

**Comment by Bykiev** [comment]
@zlannin, hi!

you can workaround the issue by setting pager's [visible  ](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/pager/#visible) option to true

**Comment by onebalaban** [comment]
Hello,

@Bykiev's solution is correct. Set the **pager.visible** option to **true**.

Regards,
Romeo
