### ISSUE TITLE
linkFromLineEndExpr and linkToLineEndExpr in diagram not work in last release (v19.2.7 and v20.1.1-sprint.6)

### ISSUE THREAD

**Issue by fgvicente** [DevExpress/DevExtreme#12531]
this functions (linkFromLineEndExpr and linkToLineEndExpr) is ignored in the new release (v19.2.7 and v20.1.1-sprint.6) and does not work anymore

example:
in [https://js.devexpress.com/Demos/WidgetsGallery/Demo/Diagram/AdvancedDataBinding/jQuery/Light/](url)
change function for this
`function linkFromLineEndExpr(obj) {
        return 0;
    }
    function linkToLineEndExpr(obj) {
        return 0;
    }`

**Comment by LanetteDevEx** [comment]
Hello,

To make these functions work in the latest version, it's necessary to return a "none" or "arrow" string value instead of 0. Try this approach and let us know if this helps.

We will consider describing this specificity in our documentation.

**Comment by fgvicente** [comment]
Hi. I do not understand well. Before you could specify from what point to which point the arrow is drawn. How do I specify that now? can you give me an example? what you need is to specify that at each node the arrows come out from below the node and always go up to the destination node

**Comment by LanetteDevEx** [comment]
Hello,

The linkFromLineEndExpr and linkToLineEndExpr functions define whether an arrow is shown at the end of the connector or at its start. You can return the "none" or "arrow" string in these functions to render an arrow or show no ending at the start/end of a connector.

However, these functions do not define which point is the start of a connector and which one is the end. This specificity is defined in the edges data source's "from" and "to" fields.

Would you please describe your task in greater detail? Do you need to specify a certain connector's end and start or do you need to show an arrow next to the connector's start/end? If possible, send us your sample project or your data and a picture of the required result. This will help us provide you with the most suitable approach.

**Comment by fgvicente** [comment]
![image](https://user-images.githubusercontent.com/3626864/78368917-c6dce480-759a-11ea-92a5-4903506c4678.png)

ok I understood ... but before that function defined which point of the four pink points of the first image.
I need to specify that the arrow go to that pink point or to any of the other four depending on the situation.

![image](https://user-images.githubusercontent.com/3626864/78368691-62218a00-759a-11ea-85dc-0eb595e9a946.png)

thanks in advance @LanetteDevEx

**Comment by LanetteDevEx** [comment]
Hello,

By default, certain points connected by a connector are chosen automatically according to the auto-layout algorithm applied.

If you need to specify what shape connection points are used to draw a connector specified in your data source explicitly, it's necessary to define the [fromPointIndexExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDiagram/Configuration/edges/#fromPointIndexExpr) and [toPointIndexExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDiagram/Configuration/edges/#toPointIndexExpr) properties of the edge collection.

**Comment by fgvicente** [comment]
Hello @LanetteDevEx any suggestion?

**Comment by fgvicente** [comment]
Hi @LanetteDevEx that doesn't work either
see example

[example](https://codesandbox.io/s/advanced-data-binding-devextreme-diagram-ceyds)

**Comment by vicentefederico** [comment]
Hello @LanetteDevEx any suggestion?

**Comment by LanetteDevEx** [comment]
Hello,

I checked your sample project and see that the way of connecting points, which is defined in the fromPointIndexExpr and toPointIndexExpr properties, is not applied because auto-layout is enabled in your Diagram.

The default way is selected automatically according to the auto-layout algorithm applied.
To resolve the problem, I suggest you set the [autoLayout](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDiagram/Configuration/nodes/autoLayout/) option to "off". See the [modified sample project](https://codesandbox.io/s/advanced-data-binding-devextreme-diagram-5o0r7).

**Comment by fgvicente** [comment]
Ok thans in last beta fixed. Thanks
