### ISSUE TITLE
Feature request: option to send all data when editing DataGrid successful

### ISSUE THREAD

**Issue by mskovacic** [DevExpress/DevExtreme#12742]
Hi,

We have many issues with the way the DataGrid is currently sending data when you edit it.
The Insert mode is works fine because it sends all data (because all is modified), however Edit mode sends only modified data fields.

This causes us 2 problems:
1. We use ASP.NET Core and having only modified data sent makes server side validation complicated. 
2. Handling partial updates is also more complicated when one data field is deleted. In that case an empty value (from e.g. textbox) or null (from e.g. tagbox) is sent which has to be differentiated from no property in value string.

Current solution:
a lot of code is necessary to bypass this problems and for the worst part it has to be handled in each case (controller method) separately.

```
public class MyModel
{
    [Required]
    public int? A;
    [Required]
    public int? B;
    [Required]
    public int? C; 
}
```
```
public IActionResult InsertPoint(string values)
{
    var data = JsonSerializer.Deserialize<MyModel>(values);

    if (!TryValidateModel(data))
    {
        return BadRequest(ModelState);
    }

    _m.InsertPoint(data.A.Value, data.B.Value, data.C.Value);
    return  NoContent();
}
```
^- Clean -^
ˇ- Ugly -ˇ

```
public IActionResult EditPoint(int key, string values)
{
    var data = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(values);

   var a = data.TryGetValue("A", out var a1) ? a1.ValueKind == ValueKind.Null ? null : a1.GetInt32 : null;

.
.
.

    _m.EditPoint(key, a, b, c);
    return  NoContent();
}
```

Proposed solution:
bool switch option to enable sending all data fields on save changes.

**Comment by NickMitrokhin** [comment]
Hi,

When you update a data row, the grid sends a key value of the modified row along with modified fields. The key value should help you identify a data item on the server side. Please take a look at the [DataGrid - Web API Service](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/WebAPIService/NetCore/Light/) demo showing how to update data fields on the server side. See **DataGridWebApiController.cs**.

Have you tried the same approach in your case?

**Comment by mskovacic** [comment]
The proposed approach works but is still a workaround around a simple issue.
We aren't currently using Newtonsoft.Json and have a multi-layered architecture in our application.

**Comment by NickMitrokhin** [comment]
The approach in the demo shows a possible solution for this case. As for the special option, it is not an optimal solution to send unnecessary data that can be got on the server side via the key value. That is why we do not have plans to add such an option.

You can modify the **newData** object in the [onRowUpdating](https://js.devexpress.com/Documentation/20_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowUpdating) event handler as shown below:

```js
function onRowUpdating(e) {
    e.newData = Object.assign({}, e.oldData, e.newData);
}
```

This will help you get the entire data object on the server side.
