### ISSUE TITLE
Feature request, clear() method to clear TreeList contents

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#1282]
Would be helpful to have a method `.clear()` and simply do: `$("#treeList").dxTreeList('clear')` for example instead of having to do:
```
var instance=$("#treeList");
instance.option('dataSource', []);
```
Same for DataGrid and PivotGrid.

Took me hours and lots of searching in forums to figure that out whereas this one method could be well documented in API.

**Comment by vconst** [comment]
Hi genachka,

The approach that should use the clear method is dependent on the data binding engine and therefore, the code should be different in each approach (e.g., Angular, MVC and so on). It is impossible to implement the clear method that will work for all scenarios. 
 
We will take your feedback into account about this scenario and consider adding information about data clearing to our documentation.
