### ISSUE TITLE
Scheduler component (React) does not respect injected components styles

### ISSUE THREAD

**Issue by nrakochy** [DevExpress/DevExtreme#12856]
### Steps to Reproduce:

1.  Load Scheduler in React with custom resource component 

```
      <Scheduler
        dataSource={events}
        currentView={currentView}
        currentDate={currentDate}
        groups={groups}
        cellDuration={60}
        firstDayOfWeek={0}
        startDayHour={6}
        endDayHour={20}
        resourceCellComponent={ResourceCard}
        timeCellComponent={TimeComponent}
      >
       ...
    </Scheduler>
```
Custom ResourceCard component 
```
    <ResourceContainer>
        <DescriptionContainer>
          <h3>{name}</h3>
          <h4>{capacityText}</h4>
        </DescriptionContainer>
         ...more_implementation...
   </ResourceContainer>
```
Styles
```
const DescriptionContainer = styled.div`
  display: flex;
  flex-direction: column;
  flex: 1 1 0;
  align-items: flex-start;
  justify-content: center;
`;

const ResourceContainer = styled.div`
  height: 100px;
  display: flex;
  flex-direction: row;
  flex: 1 1 0;
  padding-left: 12px;
  justify-content: space-between;
`;
```

### Results You Received:

![devextreme_resource_card](https://user-images.githubusercontent.com/3740177/80123500-97474980-8554-11ea-90e7-39b04a058f1d.png)

The component is rendered to the DOM, but not visible 

### Results You Expected:

I would expect the Scheduler to respect the defined size(s) for a given component. That is, if the `cell height` is `100px`, the row should be `100px`. 

### Environment Details:
version 19.2.0
latest Chrome

**Comment by Yarovaya** [comment]
Hi @nrakochy,

Scheduler has a static layout. So, it is impossible to change cell size using customization in a template. But you can use [css-classes](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/CSS_Classes/#dx-scheduler-cell-sizes-horizontal) to customize sizes of Scheduler table cells.
