### ISSUE TITLE
Scheduler component (React) misplacing appointments on scheduler

### ISSUE THREAD

**Issue by lidorbt** [DevExpress/DevExtreme#12865]
### Steps to Reproduce:

1. Enter the official react's "limit appointments per cell" example (https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/LimitAppointmentCountPerCell/React/Light/)

2. Resize the scheduler or simply zoom in / out (I don't know what specifically is the size / ratio / resolution causes the bug)

### Results You Received:
![image](https://user-images.githubusercontent.com/15897688/80186936-798ee880-8617-11ea-83de-ecdd641326a7.png)
![image](https://user-images.githubusercontent.com/15897688/80186954-80b5f680-8617-11ea-988a-6d4229851687.png)
![image](https://user-images.githubusercontent.com/15897688/80186971-87dd0480-8617-11ea-9302-b51eff930134.png)

### Results You Expected:

![image](https://user-images.githubusercontent.com/15897688/80186993-91ff0300-8617-11ea-8c84-b816cf79328b.png)
![image](https://user-images.githubusercontent.com/15897688/80187004-96c3b700-8617-11ea-9200-780224f054ef.png)
![image](https://user-images.githubusercontent.com/15897688/80187018-9c210180-8617-11ea-932c-e6925af7008d.png)

### Environment Details:

version 19.2.0
latest Chrome

**Comment by Yarovaya** [comment]
Hi @lidorbt  ,

Thank you for the report. We'll research this behavior in the context of the [t885595 ](https://supportcenter.devexpress.com/internal/ticket/details/t885595) Support Center thread.
