### ISSUE TITLE
Gantt - Validation break tree

### ISSUE THREAD

**Issue by egerasimov71** [DevExpress/DevExtreme#12916]
### Steps to Reproduce:

After adding:          
.Validation(conf => {
    conf.AutoUpdateParentTasks(true);
})

1. In additional column disappear data
2. dataSource has error on editing if AutoUpdateParentTasks = false
example: https://codepen.io/egerasimov/pen/povYLov 

### Environment Details:
v 20.1.3, google chrome / opera

**Comment by natashaash** [comment]
Hello,
Thank you for your report. 
I replicated the issue and created public threads in our Support Center to research them:

1. [Gantt for Java Script - Data is not displayed in custom columns in the tree list area if autoUpdateParentTasks is set to True](https://supportcenter.devexpress.com/ticket/details/t887279/gantt-for-java-script-data-is-not-displayed-in-custom-columns-in-the-tree-list-area-if)

2. [Gantt for Java Script - An error occurs on an attempt to edit DataSource if autoUpdateParentTasks is set to false](https://supportcenter.devexpress.com/ticket/details/t887281/gantt-for-java-script-an-error-occurs-on-an-attempt-to-edit-datasource-if)

As a temporary workaround for the second issue, you can use [CustomStore](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/CustomStore/).
`var ds = new DevExpress.data.CustomStore({
            key: 'ProjectWorkDataValueGUID',
            load: function (loadOptions) {
                return data;
            }, ... `

We will update the threads in our Support Center as soon as we have any results.
