### ISSUE TITLE
How to hide selectBox popup by jQuery.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#12997]
I want to hide selectBox popup after load custom value and reload by jQuery. Please help someone.

**Comment by DokaRus** [comment]
Use the [close](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Methods/#close) method or change the [opened](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Configuration/#opened) option value when necessary.

You can use the Support Center to get additional help with your issue: https://devexpress.com/sc
