### ISSUE TITLE
Can DevExtream work in .Net core Razor Pages?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13041]
May i know DevExtream are work only in .Net core MVC or Razor pages?

**Comment by AlekseyMartynov** [comment]
I greatly appreciate your interest in our ASP.NET products.

You can use DevExtreme-based ASP.NET Core Controls with either MVC Views or Razor Pages. For a quick start, check our [Visual Studio project template](https://docs.devexpress.com/AspNetCore/401026#create-a-new-project) that allows you to choose between the Views or Pages app types.

For further ASP.NET-related questions, I kindly ask you to use [Support Center](https://devexpress.com/sc).
