### ISSUE TITLE
Can DevExtream List Item template support conditions?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13049]
I would like to do condition base element show in item template of SelectBox of devextream. How can i archive it. I want to do like if else and show particular element 

Something like this.
.ContentTemplate(@<text>
if (<%- state %> == "null") {'sorry not found state'}
</text>

**Comment by AlekseyMartynov** [comment]
Please refer to the [ERB-style Constructs](https://docs.devexpress.com/AspNetCore/401029#erb-style-constructs) documentation section. It explains how to use control flow statements within templates.

For short conditional expressions, the [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) may also work.

For further ASP.NET-related questions, I kindly ask you to use [Support Center](https://devexpress.com/sc).
