### ISSUE TITLE
How to add asp.net core tag helper in devextream control

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13062]
I'm building form and need to pass asp-for tag in devextream textbox. how can i do it?

**Comment by San4es** [comment]
The `asp-for` attribute is available for native HTML elements only (`<input>`, `<label>`, `<textarea>`, `<select>`).

To bind a TextBox to the model property in the jQuery approach, use the [`name`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTextBox/Configuration/#name) and [`value`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTextBox/Configuration/#value) options:

```html
<div id="textbox"></div>

<script>
    $(function () {
        $("#textbox").dxTextBox({
            name: "@Html.NameFor(m => m.CustomerName)"
            value: "@Html.ValueFor(m => m.CustomerName)"
        });
    });
</script>
```

If you are using DevExtreme ASP.NET Core controls, you can make it via [strongly-typed Html Helpers](https://docs.devexpress.com/AspNetCore/401273/devextreme-based-controls/concepts/razor-syntax/strongly-typed-helpers):

```razor
@Html.DevExtreme().TextBoxFor(m => m.CustomerName)
```

If you need additional assistance, please submit a ticket to our [Support Center](https://devexpress.com/sc).
