### ISSUE TITLE
Adjusting a DataSource on a DxLayer results in an error

### ISSUE THREAD

**Issue by darnfish** [DevExpress/DevExtreme#13061]
### Steps to Reproduce:

1. Create a DxVectorMap
2. Add a DxLayer with a DataSource that gets updates every x seconds with a new Marker
3. Observe the error

```vue
<template>
	<DxVectorMap
		:title="{ visible: null }"
		:zoomingEnabled="false"
		:controlBar="{ enabled: false }"
		:background="{ color: 'transparent', borderColor: 'transparent' }"

		:layers="[{ dataSource: mapData, color: '#999999', borderColor: 'transparent' }, { type: 'marker', dataSource: markerData }]"

		projection='miller'
		:bounds="[-160, 85, 180, -60]"
	/>
</template>
<script>
import mapData from './world.js'

import DataSource from 'devextreme/data/data_source'
import { DxVectorMap, DxLayer } from 'devextreme-vue/vector-map'

export default {
	components: {
		DxVectorMap,
		DxLayer
	},
	data() {
		return {
			mapData,
			markerData: new DataSource({
				store: {
					type: 'array',
					data: []
				}
			})
		}
	},
	methods: {
		handleLocation(location) {
			this.markerData.store().push([location])
		}
	},
	props: ['markers']
}
</script>
```

### Results You Received:
```
Uncaught TypeError: Cannot read property 'resolve' of null
    at MapLayer._update (map_layer.js?ccd8:1069)
    at MapLayer._dataSourceChangedHandler (map_layer.js?ccd8:979)
    at MapLayer.eval (data_helper.js?39d2:69)
    at Callback._fireCore (callbacks.js?718c:24)
    at Callback.fireWith (callbacks.js?718c:76)
    at EventsStrategy.value (events_strategy.js?0cb5:69)
    at inheritor._fireChanged (data_source.js?fb5d:259)
    at inheritor._onPush (data_source.js?fb5d:361)
    at inheritor.eval (utils.js?211b:304)
    at eval (utils.js?211b:293)
```
![Screenshot 2020-05-16 at 09 25 51](https://user-images.githubusercontent.com/8293444/82114886-3ed02a00-9757-11ea-8bef-42abe81d9a9e.png)

### Results You Expected:
The marker would be added to the map without any issues.

### Environment Details:
Using`devextreme` 20.1.3 with `devextreme-vue` 20.1.3 in conjunction with`nuxt` 2.12.2 on macOS Catalina 10.15.4 (19E287)

**Comment by darnfish** [comment]
Fixed it by updating the `handleLocation` method to this!
```js
async handleLocation(location) {
	await this.markerData.store().insert(location)
	this.markerData.load()
}
```

**Comment by darnfish** [comment]
Nevermind, turns out the issue is still happening :(

**Comment by darnfish** [comment]
Looks like https://github.com/DevExpress/DevExtreme/pull/9467 is the PR where the line that causes the error was introduced

**Comment by alexanderPolosatov** [comment]
Hi,
Thank you for the sample. I created a [ticket](https://supportcenter.devexpress.com/ticket/details/t890687) about this issue in our Support Center and suggest you track it to be notified of our progress.

**Comment by darnfish** [comment]
I fixed the issue by using an Array for the `DxLayer` `data-source` and setting `type` to `marker`:

```js
<DxLayer
    type="marker"
    :data-source="[]"
/>
```
