### ISSUE TITLE
Incoherent docs about ContextMenu against DxDataGrid

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#13126]
I needed to add a right click functionality on my dxDataGrid whenever a row was right clicked.
To accomplish such, I've found a ticket pointing to this example:
https://github.com/DevExpress-Examples/datagrid-how-to-utilize-crud-operations-using-the-context-menu-t123309/blob/19.2.4%2B//JS/index.html

Such example clearly explains how to do that and **it actually works as intended**.

However, if you take a look at this:
```js
e.items = [{
  text: "edit",
  onItemClick: function () {
      e.component.editRow(e.row.rowIndex);
  }
 },
```
It's actually not meant to work from the official contextMenu docs, where `items` don't seems to have any `onItemClick` event which is, instead, on the parent:
![image](https://user-images.githubusercontent.com/1898880/82447187-36098c00-9aa8-11ea-962a-108826e5ee89.png) (reference here: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxContextMenu/Configuration/items/ ).

This might not be a big issue, although I needed to do that in angular and I was quite confused, since the `dxContextMenuItem` interface has no `onItemClick` event, despite if you actually force it, it does work as intended.

Am I losing something or are the docs somewhat outdated or wrong?

Thanks

**Comment by novsstation** [comment]
Hi Marco,

We researched this case and found out that this is a mistake in our documentation.
Currently the dxContextMenuItem interface does not have the onItemClick event. This event belongs to the grid items only.
The dxContextMenu widget has only a global event for all menu items.
Thank you for bringing our attention to this issue. We will update the documentation soon.

We also agree that this functionality might be useful for our customers in another widget.
So, we will keep it in mind during further development.

**Comment by briosheje** [comment]
> Hi Marco,
> 
> We researched this case and found out that this is a mistake in our documentation.
> Currently the dxContextMenuItem interface does not have the onItemClick event. This event belongs to the grid items only.
> The dxContextMenu widget has only a global event for all menu items.
> Thank you for bringing our attention to this issue. We will update the documentation soon.
> 
> We also agree that this functionality might be useful for our customers in another widget.
> So, we will keep it in mind during further development.

Perfect, thank you!
