### ISSUE TITLE
How can i add marker and get geo data runtime on .net core?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13141]
I am making food supply web application. and i would like to add custom marker by double click or single click (it might issue while dragging, so may not preferable) on runtime and get geo data so i can save in database. Also i need to make searchbox where user can search the address like bing and google have.

After my delivery boy will get perfect location where they want to deliver item.
Please help me someone. and thanks in advance.

**Comment by San4es** [comment]
Hi @kingsanu,

>to add custom marker by double click or single click and get geo data so i can save in database

Use the [`onClick`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxMap/Configuration/#onClick) event to add a new marker and its `location` parameter to get the location of the clicked point.

> Also i need to make searchbox where user can search the address like bing and google have.

Try to use our TextBox widget with search [mode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTextBox/Configuration/#mode) for this purpose.
