### ISSUE TITLE
Noticed bug in HTML Editor.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13142]
I noticed when i use numbering in html editor.
Ex; Pressed 1. so numbering will be start, and then press again enter second number will be add in next line, and if i use mention as @ the mentioned @<value> remove from current line and set at first line prefix.

**Comment by San4es** [comment]
Hi @kingsanu,

I could not reproduce the issue you described. I used this example: [https://codepen.io/San4esZ/pen/KKVdLaZ](https://codepen.io/San4esZ/pen/KKVdLaZ).

These are the steps that I used to reproduce this issue:

* Press the Enter key;
* Type `1`;
* Type `@John Heart`;
* Press the Enter key;
* Type `@Kevin Carter`;
* Press the Enter key;
* Type `@Olivia Peyton`.


This scenario works properly on my side:
![](https://user-images.githubusercontent.com/1420883/84406902-d0c23a00-ac12-11ea-919f-75a7ec4b3607.png)

Please specify additional conditions and steps we should take into account to reproduce it.

Thank you.
