### ISSUE TITLE
Need display exp with combination of field in .net core.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13143]
I  need a  one help where i would like show combined field of data in display exp at HTML editor by mention.

Second help related to it:
I want to add **BoldedText**: NormalText in HTML editor when i press @mention.

**Comment by San4es** [comment]
Hi @kingsanu,

>I need a one help where i would like show combined field of data in display exp at HTML editor by mention.

You can use a function as [displayExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/mentions/#displayExpr) to combine data fields any way you want:
```js
$("#htmleditor").dxHtmlEditor({
    mentions: [{
        displayExpr: function(data) { 
            return data.firstName + " " + data.lastName 
        }
    }]
});
```

>I want to add BoldedText: NormalText in HTML editor when i press @mention.
It can be achieved by setting the corresponding toolbar option:
```
$("#htmleditor").dxHtmlEditor({
    toolbar: {
        items: [ "bold", "italic" ]
    }
});
```

I created an example to demonstrate both cases: https://codepen.io/San4esZ/pen/KKVdLaZ. Let us know if it works for you.
