### ISSUE TITLE
Could you not make component of expression editor as report have?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13157]
Could you make component as report have like expressions editor with syntax editor, intelligence for .net core?

**Comment by San4es** [comment]
We already have a similar component - dxFilterBuilder.

See:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/FilterBuilder/
https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFilterBuilder/
