### ISSUE TITLE
Can i make mention as editable in htmleditor?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13158]
I want mention value as editable in html editor when i choose from selection popup. also i want to remove @ when i choose item

**Comment by San4es** [comment]
Hi @kingsanu,

> I want mention value as editable in html editor when i choose from selection popup

This functionality is not supported at present. We don't have immediate plans to implement it and at the moment we collect customer feedback. Is this feature crucial in your use case?

> also i want to remove @ when i choose item

You can use the [template](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/mentions/#template) option to achieve this. For instance:
```js
$("#editor").dxHtmlEditor({
    mentions: {
        displayExpr: function(item) {
            // NOTE: "item" can be null
            return item && (item.firstName + " " + item.lastName);
        }
    }
});
```
