### ISSUE TITLE
DevExtreme RangeSelector does not contains name property to pass data to Razor Pages.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13164]
Razor pages uses asp.net tag, so we can manually add those tag value in name property of devextream control but range selector does not have property like Name.

**Comment by alexanderPolosatov** [comment]
At present RangeSelector does not support this functionality. If you need to pass RangeSelector's [value](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxRangeSlider/Configuration/#value) to the server, I suggest you create a hidden [input ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input)and update this input's value in the [valueChanged](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxRangeSlider/Events/#valueChanged) event.
