### ISSUE TITLE
How can i add event onHidden of popup in jQuery?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13163]
I would like to add event where when popup close the event fire i would add this OnHidden event in jquery

**Comment by San4es** [comment]
Hi @kingsanu.

To add/remove a 'hidden' event handler, you can use one of the following:
- the [onHidden](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxPopup/Configuration/#onHidden) option:
```js
$("#popup").dxPopup({
    onHidden: function() {
       // event handler
    }
});
```
- the [on](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxPopup/Methods/#oneventName_eventHandler) method:
```js
var popup = $("#popup").dxPopup("instance");
popup.on("hidden", function() {
    // event handler
});
```
