### ISSUE TITLE
FileManager Drawer is always on if initialized in Popup

### ISSUE THREAD

**Issue by mohamed-adly** [DevExpress/DevExtreme#13215]
### Steps to Reproduce:

1. Create a Popup component 
2. Create  file manager inside the Popup component
3. Set popup visibility 

### Results You Received:

FileManager Progress panel/drawer is always on and the close button not working 

### Results You Expected:

to have the progress panel visible only when there is a notification

### Environment Details:

DevExtreme 20.1
React
![image](https://user-images.githubusercontent.com/57298072/82932144-a3c62400-9f90-11ea-9399-6ff733c267ed.png)

**Comment by mohamed-adly** [comment]
worked fine with "contentRender" method

**Comment by CodeKarno** [comment]
Hi @mohamed-adly
Thank you for reporting the issue to us. I reproduced this behavior in File Manager v20.1.3 and we will start working on a fix.
