### ISSUE TITLE
[PivotGrid] Html entities incorrectly rendered in filtering

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#13263]
Html entities rendered nice in grid:
![image](https://user-images.githubusercontent.com/1198848/83396335-810a9400-a404-11ea-86e2-fefda35ec451.png)

but badly in filter:
![image](https://user-images.githubusercontent.com/1198848/83396382-91227380-a404-11ea-88cc-c19cfc26a46b.png)

---

I need `&nbsp;` for correct line breaking in cell.

I am not sure where broblem is, I created the same in Angular repo:
https://github.com/DevExpress/devextreme-angular/issues/1078

**Comment by Semigradsky** [comment]
I found that this rendering depends on `encodeHtml` option - https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/columns/#encodeHtml

https://github.com/DevExpress/DevExtreme/blob/4a46c3a58e8275d4c3933506efb07c5fb4795334/js/ui/pivot_grid/ui.pivot_grid.field_chooser_base.js#L333

But I don't know how I can specify this option for Pivot Grid filter.

---

UPD: That is not solution because I don't want to render potentially dangerous html. So `encodeHtml` option should remain `true`. Maybe it can be okay if it is possible to change `encodeHtml` for individual fields.

**Comment by Semigradsky** [comment]
https://github.com/DevExpress/DevExtreme/blob/4a46c3a58e8275d4c3933506efb07c5fb4795334/js/ui/pivot_grid/ui.pivot_grid.area_item.js#L76-L84

^ That is why I see correct html entities in row fields. Text encoded only if contains `<` or `>` character.

**Comment by novsstation** [comment]
Hi Dmitry.

You can customize the text of any cell (even in the filter area) using the [customizeText](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/PivotGridDataSource/Configuration/fields/#customizeText) property and write any [Unicode character](https://www.fileformat.info/info/unicode/char/00a0/index.htm) in it. Something like this:

``` js

dataSource: {
	...
	fields: [{
		dataField: "date",
		groupInterval: "day",
		customizeText: function (cellInfo) {
			return cellInfo.valueText.replace('-', ' '); // replaced text is no-break space - Alt + 255
		}
	}]


```
 
Could you please check this approach and let me know your results.

**Comment by Semigradsky** [comment]
@novsstation Thanks, it helps! 👍
