### ISSUE TITLE
[SUGGESTION] DataGrid: method for return the current cell position

### ISSUE THREAD

**Issue by cesco69** [DevExpress/DevExtreme#13311]
Hi, i want to suggest a method for return at runtime the current cell position (current focused/selected cell) from a DataGrid.

After a lot of debugging I have found into dataGrid object the `keyboardNavigation` controller that expose a `_focusedCellPosition` object and with `dataGrid._controllers.keyboardNavigation._focusedCellPosition` i can retrive the current cell position

This is my snippet (in typescript):

```ts
import dxDataGrid from 'devextreme/ui/data_grid';

/**
* Return the current cell position
*/
getCurrentCellPosition(dataGrid: dxDataGrid): { columnIndex: number, rowIndex: number } | null {
    const cellPosition: { columnIndex: number, rowIndex: number } = (dataGrid as any)._controllers.keyboardNavigation._focusedCellPosition;
    if (cellPosition && cellPosition.columnIndex >= 0 && cellPosition.rowIndex >= 0) {
        return cellPosition;
    }
    return null;
}
```

is a workaround that use private field and don't guaranteed to works in future release.

My suggestion is to expose an official method.

**Comment by MikeVitik** [comment]
Hi.
Have you tried using [focusedRowIndex](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#focusedRowIndex) and [focusedColumnIndex](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#focusedColumnIndex) like in the following code snippets?
```javascript
const focusedCellPosition = {
  rowIndex: dataGrid.option('focusedRowIndex'), 
  columnIndex: dataGrid.option('focusedColumnIndex')};`
