### ISSUE TITLE
[HtmlEditor] - onValueChange doesn't work right when the editor is cleared.

### ISSUE THREAD

**Issue by AdrianIONICA** [DevExpress/DevExtreme#13375]
### Steps to Reproduce:

1. Write down a text into the HTML Editor.
2. Delete the entire content/text from it.
3. Check the value received in the onValueChanged(value, previousValue) event handler.

### Results You Received:
The current value is the same with the previous value.

### Results You Expected:
The value from the event handler shall be an empty one.

### Environment Details:
everywhere

**Comment by San4es** [comment]
Hi @AdrianIONICA,

I have not reproduced the issue you described. See:
[https://codepen.io/San4esZ/pen/PoZNqXb?editors=1011](https://codepen.io/San4esZ/pen/PoZNqXb?editors=1011)

Please tell us what additional conditions we should take into account to reproduce it.

>Check the value received in the onValueChanged(value, previousValue) event handler.

Additionally, I noticed that you are using wrong parameters in the event handler. See:
[https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/#onValueChanged](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/#onValueChanged)

Thank you.

**Comment by AdrianIONICA** [comment]
Hi @San4es ,
You can reproduce it using this: https://codesandbox.io/s/agitated-hermann-x70v1?file=/App.js
Please follow the console logs.

I know about the name of the parameters, in the code side the parameters are named right.

Thank you!
Adrian

**Comment by San4es** [comment]
Hi @AdrianIONICA,

I reproduced this issue on my side and created a public ticket in our Support Center: 
https://supportcenter.devexpress.com/ticket/details/t900915/

We will update the ticket once we have any results. Thank you for your patience!
