### ISSUE TITLE
[PivotGrid] Cannot see selected values in filter if there are no data

### ISSUE THREAD

**Issue by roma-lukashik** [DevExpress/DevExtreme#13374]
Hello, I faced an issue with PivotGrid component. I have data which I want to show in Pivot Grid. This data can be filtered outside (for instance there is a date range and I can chose particular range and load data regarding to selected range into PIvot Grid).
What is the issue about?

### Steps to Reproduce:

1. Choose the particular range.
2. Filter data by any value using PivotGrid (Filter by "Campaign Name" on my screenshot).

<img width="329" alt="Снимок экрана 2020-06-09 в 15 14 43" src="https://user-images.githubusercontent.com/13499995/84146386-4d62e600-aa64-11ea-8d4b-4215a5a07ee9.png">

3. Change the range so that there are no data with filtered values (Test 1, Test 2 in my example). Data with any other "Campaign Name" are still present. 
4. The table is empty (that's OK). The filter by "Campaign Name" is active (that's also OK) but there are no selected value in the filter.

<img width="329" alt="Снимок экрана 2020-06-09 в 15 15 04" src="https://user-images.githubusercontent.com/13499995/84147275-c878cc00-aa65-11ea-993b-74d810d8e317.png">

### Results You Received:

I can't see which values I selected by.
I can't deselect values.

### Results You Expected:

Would be nice to see selected value whatever there are filtered data or not.

**Comment by jsdmitry** [comment]
Hi,

I saw your issue in our Support Center. Let's continue the dialog there.
