### ISSUE TITLE
Scheduler - Full Recurrence Support

### ISSUE THREAD

**Issue by AntonSermyazhko** [DevExpress/DevExtreme#13378]
# Scheduler - Full Recurrence Support

# The Problem

The DevExtreme Scheduler has its own recurrence engine that works according to the iCalendar RFC 2445 specification, with a few exceptions. Due to technical limitations, the engine does not support rules that use an offset from the end of the repetition frequency, or specify intervals between repetitions. Below are examples of currently unsupported rules:

- `FREQ=MONTHLY;BYDAY=FR;BYSETPOS=-1` (Every last friday of every month)
- `FREQ=MONTHLY;BYDAY=FR;BYMONTHDAY=22,23,24;INTERVAL=2` (Every 2 months on Friday the 22nd, 23rd or 24th)
- `FREQ=MONTHLY;BYMONTHDAY=22,23,24;INTERVAL=2;COUNT=2` (Every 2 months on the 22nd, 23rd and 24th, 2 times)

# The Proposed Solution

Instead of refining our recurrence engine, we decided to replace it with the [RRule](https://github.com/jakubroztocil/rrule) library. It is an open-source solution used in more than 1800 projects on GitHub, and it fully supports the iCalendar RFC 2445 specification.

# We Need Your Feedback

## Take a Quick Poll

[Do you find full recurrence support in the Scheduler useful](https://docs.google.com/forms/d/e/1FAIpQLSeenJba7TynHIwQ9Y7saqQ-Zi8a-MOhi4wcIM1XAv4BmNeFuA/viewform)?

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by MaximKudriavtsev** [comment]
Thanks to everybody who gave us early feedback on this feature. The feature is now available in the [v20.2 release](https://github.com/DevExpress/DevExtreme/releases/tag/20.2.3). I'm closing this thread. In the case of bugs or questions, feel free to create new [GitHub issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
