### ISSUE TITLE
When I input Chinese characters into the row filter, it started searching before I had finished typing them

### ISSUE THREAD

**Issue by ClementeGao** [DevExpress/DevExtreme#13416]
![image](https://user-images.githubusercontent.com/16145998/84584574-aa7de380-ae38-11ea-8442-0268a2ff0378.png)

**Comment by NickMitrokhin** [comment]
Hi,

Have you tried to reproduce the issue with the [Filtering](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/jQuery/Light/) demo? Would you please describe what steps we should perform with the demo on our side to see the issue?

**Comment by NickMitrokhin** [comment]
This issue was closed due to inactivity. If you found a bug or have a question about our product, [create a new issue](https://github.com/DevExpress/DevExtreme/issues) on GitHub or submit a ticket in our [Support Center](https://www.devexpress.com/Support/Center/).
