### ISSUE TITLE
Help me to remove @ and gry background color when add mention in dxHTMLeditor

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13414]
Help me to remove @ and gry background color when add mention in dxHTMLeditor

**Comment by hakimio** [comment]
Check out [displayExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/mentions/#displayExpr) and [itemTemplate](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxHtmlEditor/Configuration/mentions/#itemTemplate) configs.

**Comment by San4es** [comment]
This issue was closed due to inactivity. If you found a bug or have a question about our product, create a new issue on GitHub or submit a ticket in our Support Center.
