### ISSUE TITLE
DevExtreme: Selecting an item in DropdownBox list does not work in React using UseState Hook

### ISSUE THREAD

**Issue by maniani-dev** [DevExpress/DevExtreme#13509]
### Steps to Reproduce:

1. See example here: https://codesandbox.io/s/admiring-glade-v9dqh?file=/App.js:0-1988
2. Select an item in the list
3. The item does not get selected haha

I have attached the example if useful 

### Results You Received:

The item does not get selected 
[v9dqh.zip](https://github.com/DevExpress/DevExtreme/files/4806665/v9dqh.zip)

### Results You Expected:

I believe I should be able to select an item

**Comment by San4es** [comment]
Hi @khlynet,

We see a ticket with this subject in our Support Center:
https://supportcenter.devexpress.com/ticket/details/t901412/

We will address this issue there. I am closing this thread.
