### ISSUE TITLE
I want to hide popup of TagBox

### ISSUE THREAD

**Issue by kingsanu-production** [DevExpress/DevExtreme#13533]
I'm using tagbox without any datasource, and adding email id, but when i adding or click on tagbox popup gonna show with "NO DATA FOUND". I don't want this popup anymore.

please me plz.

**Comment by San4es** [comment]
Hi,

Try setting the [openOnFieldClick](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTagBox/Configuration/#openOnFieldClick) option to `false`. Is that what you need?

**Comment by hakimio** [comment]
@kingsanu-production 
Take a look at the following support ticket: [TagBox - How not to display the drop-down list when it is empty](https://supportcenter.devexpress.com/ticket/details/t876253/tagbox-how-not-to-display-the-drop-down-list-when-it-is-empty).

EDIT: Also, [this older ticket](https://supportcenter.devexpress.com/ticket/details/t561039/avoid-items-dropdown-in-dx-select-box) might be useful as well.
