### ISSUE TITLE
 Toolbar: Buttons of the Default, Success, and Danger type have a transparent background when located in a menu

### ISSUE THREAD

**Issue by FabianoCastro** [DevExpress/DevExtreme#13586]
Hi, please see the attachment, I have a problem in Common CSS in the toolbar, when item have locateInMenu: 'auto'

![Erro CSS](https://user-images.githubusercontent.com/34251113/85737363-b342a500-b6d5-11ea-9502-aecbe8e9af2a.png)

**Comment by jsdmitry** [comment]
Hi,

Thank you for your patience. We researched the issue and found that it is not possible to fix it without rewriting the entire toolbar's inner architecture. Such changes can affect existing projects of our customers, and it is necessary to test these changes thoroughly before publishing. That is why, we are unable to fix this issue at the moment. We have plans to enhance our control in the future, but I can't give you any estimates.

As a workaround, you can override CSS styles for a button inside the menu. The following [example](https://codepen.io/pilgrimanto/pen/RwabzNa?editors=0100) demonstrates this approach.

**Comment by FabianoCastro** [comment]
Hi,

Thanks for return, but when the user change the theme (ex. blue to dark), how can I change the color with this approach? 

Some suggestion?

**Comment by AlisherAmonulloev** [comment]
Hello Fabiano,

Thank you for the update. The solution applies only if you use one theme in your application. Unfortunately, we do not see a straightforward solution to programmatically apply another set of custom CSS styles when you switch a theme. To make the solution applicable for multiple themes, it is necessary to modify styles of each theme you plan to use in your application.

**Comment by flagmanAndrew** [comment]
In v22.2 and later, the Toolbar's overflow menu takes the [button.type](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxButton/Configuration/#type) option into account when it styles buttons.
