### ISSUE TITLE
Add `headerFilter.hideSelectAllOnSearch` option to d.ts files

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#13661]
In this PR (https://github.com/DevExpress/DevExtreme/pull/12373) `hideSelectAllOnSearch` option was added but not documented. Could you add this field to `d.ts` files (for Angular and React)?

Current behaviour with hiding 'Select All' in filter is unappreciated, I need the same behaviour as in MS Excell (always show 'Select All' option). As I see I can do it with `hideSelectAllOnSearch`.

**Comment by NickMitrokhin** [comment]
Hi,

We added the **hideSelectAllOnSearch** option in the context of the following breaking change:

[Select All item behavior has changed in the Header Filter if built-in search is used](https://supportcenter.devexpress.com/ticket/details/t872400/select-all-item-behavior-has-changed-in-the-header-filter-if-built-in-search-is-used)

This option enables the behavior that was before the breaking change by default. However, we consider the previous behavior incorrect and that is why we do not want to allow our users to enable it. In any case, if you want to use this option, enable it using **defaultOptions** as it is described in the breaking change. This approach does not require TypeScript definitions.

In the meantime, please describe why you need this option. What behavior do you expect when a user types in a search string and clicks the "Select All" option? Should this option select all items or only items that a user searches?

**Comment by Semigradsky** [comment]
Hi, thank you for response!
Ok I will try to add `hideSelectAllOnSearch` via `defaultOptions`.

I expect to select items that a user searches. That is the same as it works in 'Microsoft Excel' and 'Google Spreadsheets'.

In 'Microsoft Excel' we have 'Select All Search Results' option:

![image](https://user-images.githubusercontent.com/1198848/88663847-de5d5180-d0e4-11ea-8ff0-4cb851aa92a5.png)

In 'Google Spreadsheets' we have 'Select All' link:

![image](https://user-images.githubusercontent.com/1198848/88663782-ca195480-d0e4-11ea-9278-9441737eabd5.png)

**Comment by NickMitrokhin** [comment]
Thank you for your clarification. We will consider it in future development and maybe add a documented API that will help you achieve your goal.
