### ISSUE TITLE
[suggestion] Better Typescript Support (strict type)

### ISSUE THREAD

**Issue by cesco69** [DevExpress/DevExtreme#13756]
I want to suggest to improve typescript subbort by export the proper interface of each method.

An example, customizeText from dxDataGridColumn has no exported interface, the only way for make strict typed the cellInfo parameter is define an interface

```html
<dx-data-grid [columns]="columnDefs"></dx-data-grid>
```

without interface cellInfo is any

```ts
public columnDefs: Array<dxDataGridColumn> = [{
  customizeText: (cellInfo: any) => 'Hello ' + cellInfo.valueText
}]
```
with interface

```ts
public columnDefs: Array<dxDataGridColumn> = [{
  customizeText: (cellInfo: DxCustomizeTextEvent) => 'Hello ' + cellInfo.valueText
}]
```

the interface:

```ts
/**
 * Customizes the text displayed in column cells.
 * @see https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#customizeText
 */
export interface DxCustomizeTextEvent {
    groupInterval: string | number;
    target: string;
    value: string | number | Date;
    valueText: string;
}
```

Why dx don't export all the interfaces...?

**Comment by IlyaKhD** [comment]
Hello,

We're currently working on type system enhancement. Once we have any news, we'll update this thread.
As for now, I suggest you try the following:

```diff
public columnDefs: Array<dxDataGridColumn> = [{
-  customizeText: (cellInfo: any) => 'Hello ' + cellInfo.valueText
+  customizeText: (cellInfo) => 'Hello ' + cellInfo.valueText
}]
```

Then the correct type is used and IDE Assistance should work properly.
