### ISSUE TITLE
Unable to use both lookup and headerfilter in a table, it shows "(BLANKS)" as on of the filter value

### ISSUE THREAD

**Issue by sujitharavi123** [DevExpress/DevExtreme#13879]
Unable to use both lookup and headerfilter in a table, it shows "(BLANKS)" as one of the filter value

`<dxi-column dataField="employeeId" caption="Name of Holder">
              <dxo-lookup [dataSource]="empList" displayExpr="employeeName" valueExpr="employeeId">
              </dxo-lookup>
            </dxi-column>`

![Annotation 2020-06-17](https://user-images.githubusercontent.com/33145777/84853296-7c88e100-b07c-11ea-991d-074fef491d49.jpg)

**Comment by MikeVitik** [comment]
You should customize the headerFilter for a lookup column as shown in the [filtering demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/Angular/Light/) (search the orderHeaderFilter).
And use the to the following code snippets: 
```html
<dxi-column dataField="employeeId" caption="Name of Holder"> 
<dxo-lookup [dataSource]="empList" displayExpr="employeeName" valueExpr="employeeId"> 
</dxo-lookup>
<dxo-header-filter 
            [dataSource]="lookupColumnHeaderFilter"></dxo-header-filter>
</dxi-column>
```
```ts
    lookupColumnHeaderFilter(data) {
        data.dataSource.postProcess = (results) => {
            return results.slice(1);
        };
    }
```
