### ISSUE TITLE
The locale function does not work for 'de-DE'

### ISSUE THREAD

**Issue by MarioGruda** [DevExpress/DevExtreme#1393]
```
// import it to change locale and load localization messages
import { locale, loadMessages } from 'devextreme/localization';

import 'devextreme-intl';

// Load localized messages (English included by default)
const messagesDe = require('devextreme/localization/messages/de.json');

loadMessages(messagesDe);

// Set locale according the browser language
locale(navigator.language);
// ------------------ navigator.language is in IE and EDGE de-DE. In Chrome 'de'
```

### Steps to Reproduce:

1. use `locale(navigator.language);` in IE or Edge with german languagesettings. navigator.language is 'de-DE' and does not work
2. use `locale('de')` in IE or Edge. This works for me.

### Results You Received:
localization works only for 'de' not for 'de-DE'

### Results You Expected:
Should work for 'de-DE' and 'de'

### Environment Details:
Devextreme 17.1.5
InternetExplorer and Edge

**Comment by artem-kurchenko** [comment]
Hi,
 
Thanks for the report. Currently, there is no built-in logic that determines a base locale for such cases. We'll research if it's possible to support this and make an update here.
