### ISSUE TITLE
One serious question.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13931]
I'm using Devextream for .netCore. I noticed when i use devextream control in razor syntax it generate some 4-5 lines of inline JS code.
Now the question is, when devextream generate HTML code? either from server or when that JS load on client machine?

**Comment by artem-kurchenko** [comment]
Hi @kingsanu,

We generate the script on the server.

I also need to note that DevExtreme ASP.NET Core is not a part of our community support. For more detailed assistance on this product, feel free to contact us at [https://supportcenter.devexpress.com/ticket/create](https://supportcenter.devexpress.com/ticket/create).
