### ISSUE TITLE
Hour and Minute is not show full number in compact mode with default styles filled

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#13961]
### Steps to Reproduce:

1. open this sandbox [https://codesandbox.io/s/romantic-snowflake-l41d1](https://codesandbox.io/s/romantic-snowflake-l41d1), material compact there + default style filled
2. click on date time
3. set the hour or minute to something more than 10

### Results You Received:
compact theme
![image](https://user-images.githubusercontent.com/10086092/88324310-847a1780-ccf1-11ea-8789-8f52ac9ef5f8.png)

normal theme
![image](https://user-images.githubusercontent.com/10086092/88324570-de7add00-ccf1-11ea-805a-8e0e86708949.png)

### Results You Expected:

Display full numbers

### Environment Details:

		"devextreme": "^20.1.4",
		"devextreme-angular": "^20.1.4",

**Comment by San4es** [comment]
Hi @RezaRahmati,

Thank you for your report. We reproduced this issue and created a new ticket in our Support Center regarding it: [T919659](https://supportcenter.devexpress.com/ticket/details/T919659). Please track it to get updates.
