### ISSUE TITLE
I would like to hide Gridlines & heading in DevExtream Spreadsheet by jquery code. Please help for it.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#13997]
I would like to hide Gridlines & heading in DevExtream Spreadsheet by jquery code. Please help for it.

**Comment by artem-kurchenko** [comment]
@kingsanu

We don't have a Spreadsheet widget in our HTML\JS suite. If you experience issues with ASP.NET Core products, feel free to contact us at [https://supportcenter.devexpress.com/ticket/create](https://supportcenter.devexpress.com/ticket/create).
