### ISSUE TITLE
dx-scheduler ANGULAR - how to implement pagination in the scheduler with angular

### ISSUE THREAD

**Issue by massytaleb22** [DevExpress/DevExtreme#14027]
# Support Question

I want to implement a pagination for the scheduler dev extrem because I have a lot of grouped recording, the problem is that I tried with this code but it doesn't work :

   this.chedulerDataSource = new DataSource({
        store: new CustomStore({
            loadMode: 'raw',
            load: () => {
                return this.intervenantData;
            },
        }),
        paginate: true,
        pageSize : 5,
     });

do you have any idea to implement paging for a devExpress scheduler ??

![question-devexpress](https://user-images.githubusercontent.com/30523684/87153042-17a95b00-c2b7-11ea-95ec-59a147e6e0a8.png)

**Comment by andrewmakarov** [comment]
Hi @massytaleb22 ,
Currently, the DevExtreme Scheduler widget does not provide this functionality.
