### ISSUE TITLE
Multiple doubts for react scheduler

### ISSUE THREAD

**Issue by brijrajsinh** [DevExpress/DevExtreme#14031]
Hello,

I need help for following points:

I am using react scheduler as here : https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/jQuery/Light/

1. I want to display edit, delete button in custom appointment tool tip.
2. When we have more than one appointment in "timelineMonth" view I want to display display "more 3" in bottom of appointment not on top of it which is as default.
3. Is there any scroll event so i can achieve lazy loading by API and add more resource.
4. How to disable previous days than today without using cellData event.
5. How to create tooltip view for resource.
6. Is there any inbuilt time overlapping validation functionality?

thanks

**Comment by andrewmakarov** [comment]
Hi,
1. Yes, it is possible. You can use this demo as a starting point: 
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/CustomTemplates/jQuery/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/CustomTemplates/jQuery/Light/)
2. We do not support this functionality out of the box. It is necessary to implement this functionality manually.
3, 4, 6 No, we do not have such functionality
5. You can use dxTooltip to solve this issue. Use our demo as a starting point: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tooltip/Overview/jQuery/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tooltip/Overview/jQuery/Light/)

If you have any additional questions regarding implementing a certain functionality, feel free to contact us at [https://supportcenter.devexpress.com/](https://supportcenter.devexpress.com/)
