### ISSUE TITLE
DataGrid headerFilter loads all data for big datasets.

### ISSUE THREAD

**Issue by sdanyliv** [DevExpress/DevExtreme#1411]
### Steps to Reproduce:

1.  Check this codepen link: https://codepen.io/sdanyliv/pen/oGZJNY
2.  Click on header filter icon over `Product Name` column

### Results You Received:
headerFilter loads ALL data with all columns when using OData datasource

### Results You Expected:
Correct OData query that uses **distinct**, selects **only one field** that interested for header filter, and uses **paging**.
Possibility to cache these values instead of querying OData service for each click.

### Environment Details:

Version: 17.1.6

**Comment by AlekseyMartynov** [comment]
We have a similar ticket registered in the Support Center.
Please check https://devexpress.com/issue=T488329

The **distinct** operation which you suggest to use, is not supported by the generic OData protocol (https://stackoverflow.com/a/3840624). Though, it can be implemented manually in a [service operation](https://js.devexpress.com/Documentation/Guide/Data_Layer/Data_Source_Examples/#OData/Invoking_Service_Operations) and used specifically in the [header filter data source](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/headerFilter/#dataSource).

/cc @vconst
