### ISSUE TITLE
Form - Invisible item with DateField with array element doesn't work

### ISSUE THREAD

**Issue by TimGameDev** [DevExpress/DevExtreme#1413]
### Steps to Reproduce:
ASP.NET MVC Core 2.0 DevExtreme

1. Create class with array of elements like this:
   public class TestElement {
      public string Id { get; set; }
   }
   
   public class Test{
       public List<TestElement> SomeArray { get; set;}
   }
2. Add form with Test object - Html.DevExtreme().Form().FormData(TestObject)
3. Add SimpleItem with data field to array element - 
    AddSimple().DataField($"SomeArray[0].Id").Visible(false);
4. Add to page Model the following handlers
    public void OnPost(Test request){   }
    public void OnGet() {
        TestObject = new Test() { SomeArray = new List<Test>() { new TestElement { Id = Guid.NewGuid().ToString() } } }
    }
5. Submit form

### Results You Received:
Id in array element is null

### Results You Expected:
Id in array element is specified guid 

!!! If you change Visible to true everything works fine

**Comment by AlekseyMartynov** [comment]
Form items with `visible=false` are not equivalent to HTML `<input type=hidden>`. They are removed from the DOM completely.

To pass any additional data, use the standard `@Html.Hidden()` helpers within your HTML form.

**Comment by TimGameDev** [comment]
I see, thanks, so what the actual reason for Visible?

EDITED: html.hidden solution works fine

**Comment by TimGameDev** [comment]
And one more thing.
I've tried put @html.hiddenfor inside Html.BeginForm near with Html.DevExtreme().Form()

and it doesn't work.

**Comment by AlekseyMartynov** [comment]
> what the actual reason for Visible?

The primary purpose is to dynamically show/hide form items using the client-side API. As an example, consider a form in which additional fields appear depending on the selection of a drop-down editor.

**Comment by TimGameDev** [comment]
Got it. Thank you for your time.
