### ISSUE TITLE
When using group pagging, group expand by row click now work

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#14170]
BUG: devextream datagrid when used by group pagging, expand group by row click not work. only buttonclick work when would like to expand group row.

**Comment by NickMitrokhin** [comment]
Hi,

Please refer to the following examples:

[example1](https://codepen.io/nickmitrokhin/pen/ExKgGaW)
[example2](https://codepen.io/nickmitrokhin/pen/BaKLvyb)

The first example uses the **groupPaging** option and the second one does not use the option. Both examples operate in the same manner. Would you please clarify how we can reproduce the issue with the examples? Feel free to modify them to show the issue and send them back to us.

**Comment by NickMitrokhin** [comment]
This issue was closed due to inactivity. If you found a bug or have a question about our product, [create a new issue](https://github.com/DevExpress/DevExtreme/issues) on GitHub or submit a ticket in our [Support Center](https://www.devexpress.com/Support/Center/).
