### ISSUE TITLE
Chart - Axis Label Templates

### ISSUE THREAD

**Issue by Krijovnick** [DevExpress/DevExtreme#14184]
## The Problem

Currently labels on axes can only contain text. You can use the `customizeText` function to format the text. However, the current implementation does not allow you to add images, links, SVG or HTML elements. 

## The Proposed Solution

We plan to implement a `template` option for the axis labels. It has access to the object with information about axis label:
1. `value` - the raw value
2. `valueText` - the formatted value converted to a string

For example, the following API will be available in Angular for the labels on the argument axis:

```
<dx-chart>
...
    <dxo-argument-axis>
        <dxo-label template=”content”></dxo-label>
    </dxo-argument-axis>
    <svg *dxTemplate="let info of 'content'">
        <image attr.href="images/{{info.value}}.gif" width="50" height="50" attr.alt="info.value"/>
    </svg>
</dx-chart>
```

![Axis Templates](https://user-images.githubusercontent.com/8238559/88037860-1ea15a80-cb4e-11ea-8bc4-5218fd5eccec.png)

### Live Sandbox

[Angular](https://codesandbox.io/s/muddy-night-j9lf8)

### Take a Quick Poll

[Do you find to add images or any html elements in the axes labels useful?](https://forms.gle/zKvfVaJTpUHyhw3x6)

## Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by MaximKudriavtsev** [comment]
Thanks to everybody who gave us early feedback on this feature. The [Chart Axis Label Templates](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/AxisLabelsTemplates/) feature is now available in the [v20.2 release](https://github.com/DevExpress/DevExtreme/releases/tag/20.2.3). I'm closing this thread. In the case of bugs or questions, feel free to create new [GitHub issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
