### ISSUE TITLE
PieChart - Annotations

### ISSUE THREAD

**Issue by Krijovnick** [DevExpress/DevExtreme#14183]
## The Problem

Previously, we introduced annotations in the [Chart](https://community.devexpress.com/blogs/javascript/archive/2019/04/30/devextreme-charts-annotations-v19-1.aspx) and [Polar Chart](https://community.devexpress.com/blogs/javascript/archive/2020/05/07/devextreme-charts-polar-chart-annotations-v20-1.aspx) widgets. However, annotations are still unavailable for the Pie Chart. 

## The Proposed Solution

In DevExtreme v20.2, we are going to bring annotations to PieChart in the similar way as we did for other data visualization widgets.

The following sections demonstrate different scenarios for annotation placement. In these examples, we use a PieChart with multiple series: 

### Anchor an annotation to a series point 
```
<dxi-annotation
    series="Export"
    argument="France"
/>
```
![Series Point](https://user-images.githubusercontent.com/8238559/88277315-319c6200-cce9-11ea-96e1-3f8245647f09.png)

If you have only one series, specify the annotation argument as follows: 
```
<dxi-annotation argument="France" />
```

### Anchor an annotation to an argument edge

To define an annotation position on the surface of a specific argument, use the `location` option. This option can have one of the following values:

1. `center` - default value, places an annotation in the center of the argument.
2. `edge` - anchors the annotation to the edge of the argument.

```
<dxi-annotation
    argument="France"
    series="Export"
    location="edge"
/>
```
![Edge series point](https://user-images.githubusercontent.com/8238559/89321850-1d167d00-d68c-11ea-9255-b06d88b43773.png)

### Use pixel coordinates

```
<dxi-annotation
    [x]="70"
    [y]="120"
/> 
```
![Pixel coordinates](https://user-images.githubusercontent.com/8238559/88277232-09acfe80-cce9-11ea-85bd-01bd566c5a8e.png)

### Live Sandbox

[Angular](https://codesandbox.io/s/boring-banzai-uluf1)

### Take a Quick Poll

[How do PieChart annotations meet your needs?](https://forms.gle/sYaixyPxFk9ffeXo9)

## Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by MaximKudriavtsev** [comment]
Thanks to everybody who gave us early feedback on this feature. The [Pie Chart Annotations](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/PieWithAnnotations/) feature is now available in the [v20.2 release](https://github.com/DevExpress/DevExtreme/releases/tag/20.2.3). I'm closing this thread. In the case of bugs or questions, feel free to create new [GitHub issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
