### ISSUE TITLE
Tabbed content layout Application template

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#14215]
Please add tabbed content layout Application template

**Comment by hakimio** [comment]
Something like [this](https://js.devexpress.com/Demos/SalesViewer/Sales)? What do you mean exactly by "tabbed content layout"?

**Comment by softboy99** [comment]
Hi,
No, in the current applcation template, left part layout is a navigation tree. right is the content layout. When click the item in the navigation tree,  the content should be rendered to the right Tabs rather than replaced. Is it clear?

**Comment by hakimio** [comment]
Then just use [tab-panel](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TabPanel/Overview/Angular/Light/) plus url fragment. Seems simple enough.

EDIT: there is also [hash change event](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) which you could use in your case.

**Comment by softboy99** [comment]
Hi,
Of course, i know we should use tabpanel to do it manually. But, if you can embed it in an application template. It is out of the box,especially for beginner, a much more project starting point. Isn't it?

**Comment by IlyaKhD** [comment]
@softboy99, do you mean adding a TabPanel to the main content area? So that a view has both a side navigation menu on the left and a kind of top navigation in the center? If so, this looks like a sample page rather then a layout:

![image](https://user-images.githubusercontent.com/14272298/90539490-8caa6300-e188-11ea-858e-1dbc4dcab44f.png)

**Comment by softboy99** [comment]
Hi,
no, what i mean is one menu item on the left to one tabbed page on the right tabpage, when click one menu item, the content should be rendered to a tabpage. when click another menuitem, its content should be rendered to another tabpage.

**Comment by IlyaKhD** [comment]
Like this?

![image](https://user-images.githubusercontent.com/14272298/90665136-50dccf80-e254-11ea-9a0e-68bf4053c8e1.png)

**Comment by softboy99** [comment]
no, something like chrome tabs on the right content area, has a close button on each tabpage

**Comment by softboy99** [comment]
like the following:
![tabs](https://user-images.githubusercontent.com/228731/90722448-681bcb80-e2ed-11ea-8495-1aa7520f6369.png)

**Comment by IlyaKhD** [comment]
I got it, thanks.
We're currently collecting information about layouts. When the research is finished and we get results, we'll create a discussion
