### ISSUE TITLE
timelineWeek schedule width issue.

### ISSUE THREAD

**Issue by brijrajsinh** [DevExpress/DevExtreme#14223]
Hello support,

In below screen short you can see i am using timelineweek view and able to hide time from it but i want schedule full width same as timelineMonth view. Also want to display "2 More" functionality for more schedule.

![Screenshot 2020-08-04 at 3 12 37 PM](https://user-images.githubusercontent.com/43439111/90127246-811efc80-dd82-11ea-8ddb-e07ade01e49e.png)

Actually i want timelineMonth UI for 7/14 day UI in react.

How can i achieve this?

thanks in advance.

**Comment by brijrajsinh** [comment]
Any update please.

**Comment by AntonSermyazhko** [comment]
Hello,

To resolve the issue, I suggest you hide unnecessary cell elements in the [contentReady](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Events/#contentReady) event.
I created a simple [codesandbox sample](https://codesandbox.io/s/nostalgic-turing-5z314?file=/App.js) where the Tuesday column is hidden (hideTuersday() function).

**Comment by brijrajsinh** [comment]
Hi AntonSermyazhko, 

Your answer seems irrelevant to me. I want timelinemonth view with 7/14 day. In screenshot you can see ui issue in timelineweek view, i want to achieve same view as timelinemonth for timeline week. 

Your answer is related to workweek view. Also your code sample seems not working. 

I really appreciate you help. Waiting for your replay.

**Comment by AntonSermyazhko** [comment]
> I want timelinemonth view with 7/14 day

To achieve this, hide unnecessary day columns from the timelineMonth view. In the sample above I am hiding a Tuesday column. I [modified ](https://codesandbox.io/s/dazzling-ives-20ybu?file=/App.js)[the sample](https://codesandbox.io/s/dazzling-ives-20ybu?file=/App.js) to display only the first week in the timelineMonth view. In addition, you must filter the dataSource to retrieve only data for the displayed part of the view.
Let me know if any questions arise. I will be happy to follow up.
