### ISSUE TITLE
DxDataGrid.config.onRowUpdated(e), get updated all row data  but not only updated data of the row from e.data

### ISSUE THREAD

**Issue by steelcg** [DevExpress/DevExtreme#14360]
DxDataGrid.config.onRowUpdated(e), get updated all row data not the updated data of the row from e.data
### Steps to Reproduce:

1. go to [https://codepen.io/steelcg/pen/oNxZjGN](https://codepen.io/steelcg/pen/oNxZjGN)
2. click on any edit button, then edit any data cell
3. click on save butoon. the e.data will be alerted.

### Results You Received:
all row data cotains haven't edited cell

### Results You Expected:
only the updated data. For example, i edit John to John2. e.data should return {FirstName:"John2"}
refer to [https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowUpdated](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowUpdated)

### Environment Details:

DevExtreme version: i use 20.1.6 for test, but this issue happens on 18.2.3 and above.
browser: Chrome latest
this issue happens on DevExtreme-vue also.

**Comment by NickMitrokhin** [comment]
Hi,

The **data** parameter should contain the entire row with the updated data. If you wish to get only modified data, use the **newData** parameter in the [onRowUpdating](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowUpdating) event handler.
