### ISSUE TITLE
DataGrid renders white gap between fixed column and next columns

### ISSUE THREAD

**Issue by nareshsuda** [DevExpress/DevExtreme#14379]
@jmarcelfpg,

We have released the [1.11.1 version](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1111-2019-06-14) of DevExtreme Reactive Grid with this fix.

_Originally posted by @MaximKudriavtsev in https://github.com/DevExpress/devextreme-reactive/issues/2046#issuecomment-502094938_

**Comment by San4es** [comment]
Hi @nareshsuda,

How we can reproduce this issue?
