### ISSUE TITLE
Can't build or serve with latest EAP Version

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#14373]
Cannot build using ng b --prod with latest EAP Version 20.2.2-alpha-20232-1710

ERROR in ./node_modules/devextreme/ui/scheduler/recurrence.js
Module not found: Error: Can't resolve 'rrule' in '..\node_modules\devextreme\ui\scheduler'

**Comment by hakimio** [comment]
Same here.

**Comment by AntonSermyazhko** [comment]
Hello,

The latest version of the `rrule` library (2.6.5) that we use in our project is broken due to [https://github.com/jakubroztocil/rrule/issues/416](https://github.com/jakubroztocil/rrule/issues/416).
I recommend you downgrade to v.2.6.4 in the `package.json`.

```
"dependencies": {
. . . 
 "rrule": "2.6.4" 
. . . 
}
```

**Comment by hakimio** [comment]
@AntonSermyazhko maybe you should fix your package by setting correct version on your end instead of expecting users to know that they have to install correct "rrule" version?

**Comment by hakimio** [comment]
Also, this shouldn't be closed until it's fixed on your end.

**Comment by AntonSermyazhko** [comment]
We apologize for the confusion and inconvenience.

We've already fixed this: [https://github.com/DevExpress/DevExtreme/pull/14342/files?file-filters%5B%5D=#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](https://github.com/DevExpress/DevExtreme/pull/14342/files?file-filters%5B%5D=#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

But for EAP it is recommended to downgrade.
