### ISSUE TITLE
TimelineMonth UI for week view

### ISSUE THREAD

**Issue by brijrajsinh** [DevExpress/DevExtreme#14387]
Hi,

I am facing appointment width challenges in timelineweek view like below if i hide time cell. like below image:
![image](https://user-images.githubusercontent.com/43439111/91314648-6ada5d00-e7d4-11ea-8d96-788e8d1f2c0a.png)

So, how to achieve week and 14 days view same as timelinemonth view?

**Comment by AntonSermyazhko** [comment]
Hello,

Please refer to #14223.
