### ISSUE TITLE
Pager Adds unnecessary Top Border to dx-data-grid in latest EAP

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#14397]
In the latest EAP Version if you have a pager component at the bottom of the datagrid you get unnecessary borders added.

Screenshot enclosed

![image](https://user-images.githubusercontent.com/4225690/91539443-3ddf9480-e911-11ea-98c5-7c0b3a447ab9.png)

**Comment by AlisherAmonulloev** [comment]
Double borders are present in the current version as well. Check the following demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RecordPaging/jQuery/Light/
The second border visually separates the row view from the pager.

**Comment by bobskigit** [comment]
Ok, I'll close the issue

**Comment by bobskigit** [comment]
Ok thanks
