### ISSUE TITLE
How to get color of legend/series in chart?

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#14502]
I want boostrape table based on series . now these series have a random color. that i want to get all. in chart.

**Comment by alexanderPolosatov** [comment]
Hi,

To get the color of a series, you can use the [getColor](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Chart_Elements/Series/Methods/#getColor) method of a [series](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Chart_Elements/Series/).
