### ISSUE TITLE
Server Side Validation in  dxDataGrid when inline editing(form edit mode)

### ISSUE THREAD

**Issue by mostify** [DevExpress/DevExtreme#1451]
### Steps to Reproduce:

1. we have model state errors and we expected to show error in edit form of data grid in inline editing
2. errors post to view as BadRequest(ModelState)
3. we didn't use validationRule because dosen't care about modelstate

### Results You Received:

 errors post to view but not shown in edit form like validation of form widget. 

### Results You Expected:

we expected to see validation errors on edit form when datagrid in edit mode.

### Environment Details:
Asp.net core
DevExtreme 17.1.6
Chrome

**Comment by AlekseyMartynov** [comment]
We have a sample showing how to display server-side validation errors in DataGrid:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/WebAPIService/
![untitled](https://user-images.githubusercontent.com/4426185/31224270-e3098a2a-a9d5-11e7-918d-3d72dd65d593.png)

If your requirements are different, please submit a ticket to [Support Center](https://devexpress.com/sc).
This repo and our Non-Commercial license don't include/cover ASP.NET MVC Controls, see https://js.devexpress.com/Licensing/#NonCommercial

**Comment by AlekseyMartynov** [comment]
**UPDATE**
I see that the .NET Core version of the demo has problems.
Reopening.

/cc @jsdmitry @San4es

**Comment by AlekseyMartynov** [comment]
After additional research, I found that Northwind model classes from the .NET Core demo don't have validation attributes attached. This will be fixed in the context of https://devexpress.com/issue=T562071

Despite this, the approach I descibed in https://github.com/DevExpress/DevExtreme/issues/1451#issuecomment-334433590 works fine.
