### ISSUE TITLE
Cannot find 'node_modules/devextreme/ui/dialog'

### ISSUE THREAD

**Issue by tjgeni** [DevExpress/DevExtreme#14559]
Why devextreme dialog module not exist?
How to fix that?

Thankyou
![image](https://user-images.githubusercontent.com/17794532/92842956-646ff600-f40e-11ea-84b8-22c3a55ff14c.png)

### Environment Details:
I using latest version of devextreme + devextreme-angular + angular 10:
"devextreme": "20.1.7",
"devextreme-angular": "20.1.7",
![image](https://user-images.githubusercontent.com/17794532/92843089-8e291d00-f40e-11ea-85f9-4c76db6332b7.png)

**Comment by DokaRus** [comment]
Please refer to the [DevExtreme Modules Structure](https://js.devexpress.com/Documentation/Guide/Common/Modularity/DevExtreme_Modules_Structure/#ui/dialog) guide.
You should import a named dialog export like below
```js
import { alert } from "devextreme/ui/dialog";
```
or
```js
import { confirm, alert, custom } from "devextreme/ui/dialog";
```

**Comment by tjgeni** [comment]
OK thankyou @DokaRus
