### ISSUE TITLE
How to generate report based on value and generate PDf and save in azure blob.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#14573]
I would generate PDF and save in Azure blob in .net core. I don't want to show any end user view/designer. just at backend on save i would to EF call pass all data to reporter, generate PDF and save in Blob.

I know this step in winForm, but don't know about .net core with devextream.
So my concern is, give me step to generate report without enduser view/designer at backend and save in blob.

Thank you so much.

**Comment by artem-kurchenko** [comment]
Hi @kingsanu,

DevExtreme doesn't include the Reports suite. For all questions about Reports, please contact our team in the Support Center: https://supportcenter.devexpress.com/ticket/create.
