### ISSUE TITLE
Document `customOverlayCssClass` and add to typescript typing

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#14610]
Currently we have possibility to add custom class to DropDownEditor popup. It is useful for customization (for example I use it for customizing different backgrounds and paddings) but not documented.

https://github.com/DevExpress/DevExtreme/blob/79a90a58a056c14d4917e403897ea3b05efa02da/js/ui/drop_down_editor/ui.drop_down_editor.js#L476-L477

**Comment by San4es** [comment]
Hi,

Thank you for your idea! Currently, we have no plans to publish this option. It's highly likely that we will remove it and introduce a new public API for this purpose. Probably, it will be something like `dropDownOptions.cssClass` or
`dropDownOptions.wrapperAttr`. At the moment, we cannot give you an ETA. If we decide to work on this, we will post an announcement on GitHub, in our blogs, and Roadmap.
