### ISSUE TITLE
I want popup animation like Adobe.

### ISSUE THREAD

**Issue by kingsanu** [DevExpress/DevExtreme#14611]
Please review this link https://documentcloud.adobe.com/view-sdk-demo/index.html#/customize/LIGHT_BOX/Bodea%20Brochure.pdf

here click on sample PDF, and see the popup animation. i see such animation almost everywhere, and i want to archive this in devextream popup.

please help me. thank you in advance 10 times.

**Comment by CollinHerber** [comment]
Based on the Roadmap: https://js.devexpress.com/Roadmap/#DataGridTreeList 
Export to PDF is coming very soon and I imagine that doing something like this with the exported PDFs would be fairly simple once accomplished.

I love the idea of this, but think there are a ton of solutions for this already in the npm world.  Take a look at this one for example: https://www.npmjs.com/package/pdfjs

Then having a viewer for it, maybe an iframe overlay? Would be pretty simple beyond that.

Gl! Obviously would be great to see this natively with DevExtreme but this is a far backburner item for me.

**Comment by AlisherAmonulloev** [comment]
@CollinHerber thank you for your comment. Our research showed that the pdfJS library from the following repository has all the functionality we require to export data to PDF: [https://github.com/MrRio/jsPDF](https://github.com/MrRio/jsPDF)
From what I gather, you want to preview the exported PDF file before saving it. To be honest, we did not discuss introducing a demo or a built-in functionality to do this. I will discuss it with the team. In the meantime, you can share your ideas about the upcoming Export to PDF functionality in this discussion page: [https://github.com/DevExpress/DevExtreme/issues/14345](https://github.com/DevExpress/DevExtreme/issues/14345)
