### ISSUE TITLE
AngularJS - dxForm bindings are not working after reassign

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#14643]
Hi,

When the formData variable is changed (assigned to another variable) the binding is stop working. It seems the issue is quite old.

Here is a demo: https://codepen.io/predatorz/pen/XWdYPYW
Change any value (First Name for ex.), press 'Save' button and view console - value is changed, then try to change value second time, press 'Save' button again and now binding is broken.

similar case: https://codepen.io/predatorz/pen/yLOERLB

Steps to reproduce:

- Change first name and press 'Save' button
- Press 'Save' button again
- Change Second name and press 'Save' button again. Check the console and see the value is not updating. Why did it happen? Then binding is broken for some reason and it's a more like a Devextreme bug.

**P.S.** firstly, I've created a ticket t931204, but support agent don't treat it as a bug and tries to find a workaround to manually update form/object, but the purpose of bindingOptions is to have a two-way bindings and all AngularJS bindings are working fine after object reassign except the form.

**Comment by artem-kurchenko** [comment]
Hi @Bykiev, 

Thank you for the report. We're working on this ticket and will update it once we have any results.
