### ISSUE TITLE
DataGrid - Chinese text input finishes arbitrarily in the Filter row 

### ISSUE THREAD

**Issue by jamokop** [DevExpress/DevExtreme#14708]
### Steps to Reproduce:

1. try to type some chinese in  filter box , before i find the word i need , it's like auto type a "enter" . instead of type chinese ,  i can only get english letter. for example , i try to type "gc" ,the word i 'm looking for is "工廠", but i will get "g'cgc" .

### Results You Received:
g'cgc

### Results You Expected:
工廠

### Environment Details:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/Vue/Light/

**Comment by NickMitrokhin** [comment]
Hi,

From what I gather, you cannot enter the filtered text before DataGrid starts to filter data. DataGrid synchronizes column widths on filtering and restores focus for the last focused editor. However, the editor does not allow you to continue entering characters according to your requirements. We are going to improve this behavior in future versions. 

In the meantime, I recommend that you set the [valueChangeEvent](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTextBox/Configuration/#valueChangeEvent) option of editors that reside in the filter row to "change". In this case, the entered value will be applied only when you press the "Enter" key or your editor loses focus. The [onEditorPreparing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onEditorPreparing) event handler will help you do this. Please take a look at the following example showing this approach in action:

[https://codesandbox.io/s/loving-roentgen-hsht7](https://codesandbox.io/s/loving-roentgen-hsht7)
