### ISSUE TITLE
How to customized toolbar for PivotGrid？

### ISSUE THREAD

**Issue by luweiymy** [DevExpress/DevExtreme#14722]
### Steps to Reproduce:

For Datagrid we used "onToolbarPreparing" function to push custom items to it, Please provide your suggestions to add custom items like datagrid in pivotgrid.

**Comment by novsstation** [comment]
Hi,

Unfortunately, there is no public API that allows implementing this task out of the box.
So, the only way to accomplish your task is to use css.
You can add a button and position it over the widget with position = absolute.
I created a [small sample](https://codepen.io/SNovikov/pen/ExKBKpX) for you.

I agree that the scenario you described may be useful, and we will take your feedback into account when planning our future updates.
Should you have any further questions, feel free to contact us.
