### ISSUE TITLE
DataGrid - scrolling mode "infinite" hides the expand button for grouping 

### ISSUE THREAD

**Issue by ghost** [DevExpress/DevExtreme#14906]
Setting a DataGrid's scrolling mode "infinite" hides the expand button for grouping.
Changing the value of `grouping.allowCollapsing` [has no change](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#mode).

### Steps to Reproduce:

1. create a DataGrid with scrolling mode infinite
2. group by a field
3. https://codepen.io/julesbrx/pen/RwRPmma?editors=0010

### Results You Received:

The expand button is not shown

### Results You Expected:

It should be
![Screenshot_1](https://user-images.githubusercontent.com/47182539/95761216-48c96b00-0cac-11eb-9924-3eaa5ab314af.png)

### Environment Details:

Chrome 86
jQuery 3.5.1
DevExtreme 20.1.7 (dx.all.js)

**Comment by NickMitrokhin** [comment]
Hi,

Group rows cannot be collapsed when infinite scrolling mode is used. That is why expand/collapse buttons are not rendered. See the [scrolling.mode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#mode) option description to learn more.
