### ISSUE TITLE
DxScheduler - Disabling appointment popup form

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#14921]
### Steps to Reproduce:

Example with react:
1. Use a scheduler with any kind of options, like this:
```js
         <Scheduler
            dataSource={dataSource}
            views={[ 'agenda', 'week', 'month' ]}
            currentView={view}
            defaultCurrentDate={new Date(2020, 11, 14)}
            appointmentComponent={BookingAppointment}
            appointmentTooltipComponent={BookingAppointmentTooltip}
            onAppointmentClick={console.log}
            startDayHour={8}
            endDayHour={22}
            startDateExpr='date'
            textExpr='type'
            onAppointmentFormOpening={onAppointmentFormOpening}
            onOptionChanged={onOptionChanged}
          />
```
2. Try to programmatically disable the editing form (which appears everytime you click on an appointment and then click on the appointment popup).

We've tried all the possible overrides (editing, onAppointmentClick and so on) but we didn't manage to find any way to prevent the default mechanism which is opening the editing popup by default.

### Results You Received:
The edit popup always appears.

### Results You Expected:
Expected the possibility to either prevent the popup from spawning or to just disable the edit popup.

### Environment Details:
Devextreme 20.1-stable
Devextreme-react 20.1-stable
Browsers: google chrome and safari

**Comment by andrewmakarov** [comment]
Hi @briosheje ,
For solve your task, subscribe on [onAppointmentFormOpening](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#onAppointmentFormOpening) event and use e.cancel argument to manage visibility of Appointment Popup Form.

**Comment by briosheje** [comment]
> Hi @briosheje ,
> For solve your task, subscribe on [onAppointmentFormOpening](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScheduler/Configuration/#onAppointmentFormOpening) event and use e.cancel argument to manage visibility of Appointment Popup Form.

Thanks, I didn't notice that event at all, sorry for prompting about a non-existing issue.
