### ISSUE TITLE
dxPivot column resize

### ISSUE THREAD

**Issue by ani2479** [DevExpress/DevExtreme#14923]
### Steps to Reproduce:

1. Added [columnResizingMode] to the dxPivot

### Results You Received:
1. Error in console [columnResizingMode] is not part of dxPivot

### Results You Expected:
1. Be able to resize columns at run time

### Environment Details:

I'm using chrome, devextreme 20.1.7, Visual Studio 2019

Hi, I found multiple tickets regarding this topic, but not an actual solution for it.
Final users are requesting the ability to resize the columns at run time as they do in the dxGrid.

**Comment by novsstation** [comment]
Hi,

Currently, our PivotGrid does not support this functionality.
We will take your feedback into account when planning further development.
However, I cannot give you any promises or estimates here.
If we decide to start working on this feature, it will appear in our Roadmap or on GitHub.

Should you have any questions, feel free to contact us.
