### ISSUE TITLE
Get control over Gantt edit task popup

### ISSUE THREAD

**Issue by edubskiy** [DevExpress/DevExtreme#15052]
### Steps to Reproduce:

1.  Load Gantt chart
2. Edit task
3. No way to provide additional controls for edit task popup

### Results You Received:
Basic controls in popup

### Results You Expected:
I should have option to provide custom dialog renderer OR submit different stack of items OR get access to form state to be able add/delete/modify items with custom function

I am using "devextreme": "20.2.2-beta"

Based on this sample:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Gantt/Overview/React/Dark/

Sandbox:
https://codesandbox.io/s/lvlli

**Comment by natashaash** [comment]
Hello,
We have just released v20.2.3 where we implemented the API to accomplish this task. If you wish to add an extra editor to the "Task Detail" dialog, you will need to create your own custom form for it. Gantt has the [taskEditDialogShowing](https://js.devexpress.com/Documentation/20_2/ApiReference/UI_Widgets/dxGantt/Events/#taskEditDialogShowing) event. Handle it, cancel the default dialog showing using the cancel argument. Then, build your custom form and display it. Use the [updateTask](https://js.devexpress.com/Documentation/20_2/ApiReference/UI_Widgets/dxGantt/Methods/#updateTaskkey_data) method to apply changes to Gantt. 
See also:
[dxGantt - Methods](https://js.devexpress.com/Documentation/20_2/ApiReference/UI_Widgets/dxGantt/Methods/)

Let me know if you have further questions.

**Comment by edubskiy** [comment]
Hello. Thank you for your response. Please assist on how to access updateTask method from React, not jquery. 

I've subscribed to ```onContentReady``` event where i receive object:
```
{
    component: {}, // is the update function somewhere here? I did not find it.
    element: HTMLElement
}
```
But there is not method updateTask inside this object. How do I access it (not using jquery)?

**Comment by natashaash** [comment]
Hello,
Please review the [Getting Widget Instance](https://github.com/DevExpress/devextreme-react/blob/18.2/README.md#getting-widget-instance) help topic where we described this in detail.
Let us know if anything remained unclear.

**Comment by edubskiy** [comment]
@natashaash , thank you. I found all methods I need in the prototype chain. I guess we can mark the issue as resolved now

**Comment by edubskiy** [comment]
Hope the next releases of Gantt will include task details popup customisation.

**Comment by natashaash** [comment]
I am happy to help.
Thank you for your feedback. We will take it into account when planning further development.
