### ISSUE TITLE
Problems with Inconsistent Date object format on scheduler

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#15106]
On the latest scheduler 20.2.3 the date object returned is different depending on the date selected. 

on October 31st Date chooser gives  Sat Oct 31 2020 00:00:00 GMT+0000 
on October 30th Date chooser gives Fri Oct 30 2020 00:00:00 GMT+0000
on October 27th Date picker gives 2020-10-27T00:00:00+00:00

![image](https://user-images.githubusercontent.com/4225690/97811422-7a61a080-1c72-11eb-9346-5df2efa9a534.png)

**Comment by andrewmakarov** [comment]
Hi @bobskigit ,
please attach a sample project that reproduce on our side and list the steps to reproduce.
