### ISSUE TITLE
DataGrid - change dynamically column dataType

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#15115]
Using version 20.2.3, I load initial data in to grid with 10 columns with columns 9 and 10 having a `dataType` of **date** and then on a specific user action, I retrieve different data from backend and I want to reuse the same grid and columns but now the columns 9 and 10 need to have a `dataType` of **boolean** for column 9 and `dataType` of **string** for column 10. I also do have the `filterRow` enabled (I really still wish that the column filters had most of that functionality like other grids so a row isn't wasted but that's another thing) so I tried to dynamically set: `this.grid.columnOption('somefield', 'dataType', 'boolean')` 
But nothing happens. I can see the dataType returned as `date` when I do: `this.grid.columnOption('somefield', 'dataType')` 
but can't seem to set it on the column(s)?

How can this be accomplished?

**Comment by NickMitrokhin** [comment]
Hi,

Data type should not be changed at runtime. To resolve the issue, change the [DataGrid.columns](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/) option as shown below:

```js
   const columns = this.grid.option('columns');
   columns.filter(col => col.dataField === 'someField')[0].dataType = 'boolean';
   this.grid.option('columns', [...columns]);
```

**Comment by genachka** [comment]
Interesting. So this approach is going to clear out all the existing columns and recreate them with the new dataType. But that's still at runtime as well is it not? The only difference is that it's not changing the specific column(s) directly but all. I suppose it's not significantly less efficient than changing the specific columns. So this I think would work in my case. I'll give it a try, thanks.

**Comment by NickMitrokhin** [comment]
You are always welcome! Let us know if this helps.
