### ISSUE TITLE
DataGrid 20.2.3 .clearFilter() not always clearing row filter

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#15164]
DataGrid 20.2.3 - when doing something like:
`.columnOption(3, 'filterValue', ['2020-10-01', '2020-10-15'])`
and then issuing a 
`.clearFilter()`
The `filterValue` of the row filter is cleared but the operation dropdown is not reset and it messes with later additional API calls to set the filterValue. As a temp workaround I found that doing `selectedFilterOperation` to blank resets it but shouldn't `.clearFilter()` always automatically take care of that?

**Comment by NickMitrokhin** [comment]
Hi,

The [clearFilter](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#clearFilter) method should not clear the current filter operation. You will need to do this manually. So, your solution is correct. 

In addition, please take a look at the following ticket where we discussed a similar issue:
[DataGrid remove column level filter operation on clearFilter](https://supportcenter.devexpress.com/ticket/details/t638500)

**Comment by genachka** [comment]
@NickMitrokhin that doesn't make a whole lot of sense. The method name is `clearFilter` and the filter operation is part of the filter so I don't see how it's unreasonable to expect that everything would be reset. I would even settle for `clearFilter('all') or a `clearFilter(true)` if you won't want to break existing. Or even a `clearFilterAll()` as it's a fairly common thing to do and having to add additional boiler plate code for a tool that's supposed to speed things isn't ideal. :( My 2 cents.
