### ISSUE TITLE
DataGrid / Treelist filter enhancement request - option to have the row filter capability in column header search instead

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#15165]
The row filter is a great and powerful search / filter. But because it's always there it takes away screen real estate. For most of our users, they hate the limited capability of the header search and the checkbox selection approach yet love what they can do with the row filter. I get that there are use cases where the search on the header may be enough or preferred for folks but it would really be great if there was option to perhaps toggle a setting to instead have the column search open a dropdown which would allow you to set the value to filter/search on and that dropdown would allow you to specify the filter operation -- essentially embedding the filter row capability in to use as a "header search/filter".

This is the default behavior of so many grids out there and it's always been something our users have disliked about this grid and treelist. :(

**Comment by jsdmitry** [comment]
Hi,

I researched several data grid components, and I think found similar functionality - see the image below.
![image](https://user-images.githubusercontent.com/11206389/101172613-713d6800-3652-11eb-9c52-e19213396e2b.png)

Am I right that this is the desired behavior?

**Comment by genachka** [comment]
@jsdmitry yes more of less though it would be good to control whether the second dropdown can be an input instead and of course it column filter dropdown would need to know the datatype so that it can present an input that you can type the date in with an icon to open a calendar (like the filter row does already) or if it's a number, etc... I'd like to see a little more functionality (and would be even better if the various functionality options set during grid init as well as can be API toggled on/off). 

Here's one that has consistently received high marks from our users:
(from jqxGrid - https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/index.htm#demos/jqxgrid/filtering.htm)
![image](https://user-images.githubusercontent.com/7947294/101186503-2a834a00-3621-11eb-9c0b-63fda11164f3.png)

Another one our users like is:
(from ag-grid https://www.ag-grid.com/javascript-grid-filter-provided-simple/)
![image](https://user-images.githubusercontent.com/7947294/101187134-f8beb300-3621-11eb-86d5-d6ce60403d23.png)

What both of these grids have in common as you can see is the ability to do based on datatype options for things like `starts with`, `contains`, `ends with`, `not contains`, `equals`, `not equals`, etc. and also very important is the ability to type in the values desired as well as the `and` / `or` conditions to make it a very powerful filter without requiring that extra row from the UI. The ag-grid one actually also allows for the user to dynamically toggle from a simple checkbox selection of items as you currently have to the more powerful filter, i.e.:
(from ag-grid, scroll to demo on bottom: https://www.ag-grid.com/javascript-grid-filter-provided/)
![image](https://user-images.githubusercontent.com/7947294/101187960-0fb1d500-3623-11eb-8334-f44d3e6b1895.png)
vs
![image](https://user-images.githubusercontent.com/7947294/101188169-54d60700-3623-11eb-9f9b-fdfed4c02c92.png)

and they also add in that same dropdown column filter have a "tab" for pinning columns, reset, changing sort, controlling autosize and I think (though not enabled in the demo) they can control hiding and showing columns. Kind of great so that there's no longer a need for another dedicated "row" area for adding/hiding columns and visually giving users some additional features all within a consistent space that would in future potentially receive additional features (i.e. export column, select all column cells, toggle column editing, etc.)
![image](https://user-images.githubusercontent.com/7947294/101188609-f2313b00-3623-11eb-835c-28cf35228afc.png)

**Comment by jsdmitry** [comment]
Thank you for your feedback! We will keep it in mind when planning future enhancements.
