### ISSUE TITLE
[Calendar] Navigator text changed only after animation

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#15177]
The month name changes only after the dates block animation completes, creating lagging feeling. It happens when I change current day via `calendar.option('currentDate', date)`. But month name changes immediately when I click on navigator buttons (prev/next month).

As possible solution I can change navigator text manually:
```ts
import { formatDate } from 'devextreme/localization'
...
(calendar as any)._navigator.option('text', formatDate(date, 'monthandyear'))
```
But would be nice if it was fixed.

**Comment by DokaRus** [comment]
Hi,

Thank you, it sound reasonably.
We'll take this suggestion into account in our further plans.
Currently I'll cannot give you any ETA on this. If we decide to work on this, we'll post an announce on GitHub and add a new comment to this issue.
