### ISSUE TITLE
dxBarGauge - Is it possible to assign an array of objects to the widget's value option

### ISSUE THREAD

**Issue by FabianoCastro** [DevExpress/DevExtreme#15276]
Hi guys

Is possible, change the values to a array of objects? To have, a label and value, like a comparative chart

**Comment by AlisherAmonulloev** [comment]
Hi Fabiano,

The BarGauge widget's "values" option should be initialized with an array of Number objects. Check this help topic for more information: https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxBarGauge/Configuration/#values
Currently, it is not possible to assign an array of objects to this option.
