### ISSUE TITLE
CheckBox - How to use custom values for indicating the True and False states 

### ISSUE THREAD

**Issue by FabianoCastro** [DevExpress/DevExtreme#15272]
Hi guys

I have a editor with dxCheckBox, where the value in database is "S" or "N".

It would be very helpful if I could set up custom value in the editor, like customTrueValue and customFalseValue.

😃

**Comment by AlisherAmonulloev** [comment]
Hi Fabiano,

Currently, this functionality is not supported. Unfortunately, we do not have examples on how to implement it. I will forward your suggestion to the team.
