### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'columnName' in null

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#15331]
I have this error on DevExtreme@20.2.3 for DateGrid component in `objectsEqualByValue` function.
https://github.com/DevExpress/DevExtreme/blob/7b16996944d8e1db002a05401b6b69be4651cc93/js/core/utils/common.js#L290

As I see after updating items library calls `_updateItemsCore` which calls `_updateEditRow`:
https://github.com/DevExpress/DevExtreme/blob/c8e30e4a86e31aaf93e8b4fd5f48dfc88bc08e27/js/ui/grid_core/ui.grid_core.editing.js#L2775-L2776

[By default `editing.editRowKey` is `null`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#editRowKey). So it send `null` to `objectsEqualByValue` which thrown. As a result I see blank table.

**Comment by jtammen** [comment]
@Semigradsky I also experienced this error. It only happens for me when the grid's datasource does **not** define a `key` property.

**Comment by NickMitrokhin** [comment]
Hi,

If you are going to edit data using DataGrid, do not forget to specify the key field using the [DataGrid.keyExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#keyExpr) option if you bind your grid to an array of items. If you bind the grid using a data source, please specify the key field name using the [key](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ArrayStore/Configuration/#key) option. 

If this does not help, feel free to modify the following example to show the issue and send it to us.

[https://codepen.io/nickmitrokhin/pen/LYRbzRQ](https://codepen.io/nickmitrokhin/pen/LYRbzRQ)

 We will be happy to help you.

**Comment by ynslmz** [comment]
Hi, 
Even if you have used key option, this error exists after version 20.1.9
It seems that the last working version is 20.1.9

I'm trying to feed datagrid in my dynamic widget with SSE.

So I downgraded the version and it fixed.

I hope it helps you too.
