### ISSUE TITLE
Editors: Validations messages are invisibles after validation triggered / component focused

### ISSUE THREAD

**Issue by messaoudi-mounir** [DevExpress/DevExtreme#15371]
### Steps to Reproduce:

1.  use the same example in the demo https://js.devexpress.com/Demos/WidgetsGallery/Demo/Validation/Overview/Angular/Light/
2.  When applying the validation 

### Results You Received:

the <div> with class **.dx-invalid-message** containing the validation message still invisible

### Results You Expected:

the <div> with class **.dx-invalid-message** visibility must be set to "visible"

### Environment Details:

tested on V20.2 and 21.1 and failed :

```
src\scss\widgets\common\_validation.scss contain the code bellow, 

.dx-invalid-message {
  &.dx-overlay {
    position: relative;
  }

  &.dx-overlay-wrapper {
    width: 100%;
    visibility: hidden;                                      <--------------------------------------  visibilty applied to dx-overlay-wrapper
    pointer-events: none;
  }
  ......
}

.
.
.....

.dx-state-focused.dx-invalid .dx-invalid-message-auto,
.dx-invalid-message-visible.dx-invalid .dx-invalid-message-auto,
.dx-lookup.dx-dropdowneditor-active .dx-invalid-message-auto,
.dx-dropdownbox.dx-dropdowneditor-active .dx-invalid-message-auto,
.dx-invalid-message.dx-invalid-message-always {  <------------ .dx-overlay-wrapper selector is missed in css rules 
  visibility: visible;                   
}
```

Worked on Version 20.2.3 

dx.common.css contain the expected css rules 
```
.dx-dropdownbox.dx-dropdowneditor-active .dx-invalid-message-auto .dx-overlay-wrapper,
.dx-invalid-message-always .dx-overlay-wrapper,
.dx-invalid-message-visible.dx-invalid .dx-invalid-message-auto .dx-overlay-wrapper,
.dx-lookup.dx-dropdowneditor-active .dx-invalid-message-auto .dx-overlay-wrapper,
.dx-state-focused.dx-invalid .dx-invalid-message-auto .dx-overlay-wrapper {
  visibility: visible;
}
```

**Comment by flagmanAndrew** [comment]
Hello,
We can reproduce this issue only when using our CSS of v20.2.4 and JS of v20.2.3. Make sure that your project uses the DevExtreme CSS and JS files of the same version. Versions are specified at the top of the files.

If the versions are the same, please send us a sample demonstrating the problematic behavior.
