### ISSUE TITLE
How can I inject a data from my API using Candlestick chart? 

### ISSUE THREAD

**Issue by hayderjebur** [DevExpress/DevExtreme#15456]
the API that I am using has  stock prices for one day at a different time on the same day, but the library data structure as monthly, anyone knows how to implement this

**Comment by alexanderPolosatov** [comment]
Hi,

Could you please clarify what you wish to see in the Chart? You can provide a picture or a link to one of [our online demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/Overview/React/Light/).

**Comment by hayderjebur** [comment]
I want the chart shows stocks for only one day but at different time, so the data value divided into hours or even minutes not days or months

**Comment by alexanderPolosatov** [comment]
Chart shows the whole range of provided data. If the range of data covers one day (as it is shown in [this live example](https://codepen.io/p_alexander/pen/eYdJYZm?editors=0010)), the chart shows data, but labels on the argument axis have   hours/minutes, etc. But if the range of data is greater than one day, the chart draws all data, but labels on the argument axis have days/months, etc. In this case, to show only one day, you can use the [visualRange](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/argumentAxis/visualRange/) and [zoomAndPan](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/zoomAndPan/) options.
I suggest you take a look at our [SignalR Service](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/SignalRService/jQuery/Light/), [Load Data On Demand](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/LoadDataOnDemand/jQuery/Light/) and [Zooming and Scrolling](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ZoomingAndScrolling/jQuery/Light/) online demos.
Let us know if you have more questions.

**Comment by hayderjebur** [comment]
I am using a candleStick chart, and when I fetched the data that covers one day the chart showed nothing, so I wonder how the data structured in candleStick? Also, I want to build an app where the user able to fetch range data for one day, week, the month. I wonder if I am able to do that in this library?

**Comment by alexanderPolosatov** [comment]
> I am using a candleStick chart, and when I fetched the data that covers one day the chart showed nothing, so I wonder how the data structured in candleStick?

You can see what data structures are supported in the Candlestick chart in [our online demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/Candlestick/jQuery/Light/). You can group them in a similar way to achieve your goal.
> Also, I want to build an app where the user able to fetch range data for one day, week, the month. I wonder if I am able to do that in this library?

Yes. In this scenario, I recommend you use the [visualRange ](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/argumentAxis/visualRange/)and [zoomAndPan ](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/zoomAndPan/)options.

Should you have further questions, feel free to contact us in our Support Center: www.devexpress.com/ask. We will be happy to assist you.
