### ISSUE TITLE
Duplicate export 'hideCallback' node_modules\devextreme\mobile\hide_callback.js

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#15455]
51: export { hide_callback as __moduleExports };
52: export { hideCallback_1 as hideCallback };
53: export { hideCallback_2 as hideCallback };

**Comment by artem-kurchenko** [comment]
Hi,

I cannot reproduce this issue in v20.2.4. Could you please double-check with the recent version?

![hideCallback](https://user-images.githubusercontent.com/22076961/101024831-ba73b600-3585-11eb-9ef4-7a0614d45106.png)

**Comment by softboy99** [comment]
Hi,
The probelem still exists, Steps to reproduce:
$ npm init vite-app <project-name>
$ cd <project-name>
$ npm install
$ npm install devextreme@20.2.4 devextreme-vue@20.2.4 --save --save-exact
$ npm run dev

**Comment by clemvnt** [comment]
For more information : 

I have the same issue when I try to use DevExtreme Vue components with the build dev tool/bundler [Vite](https://github.com/vitejs/vite).

I have no issue with other component libraries. I don't know if it's an issue from DevExtreme or Vite.

You can reproduce the issue with this repo : https://github.com/clemvnt/devextreme-vite (`npm run dev` or `npm run build`)
![image](https://user-images.githubusercontent.com/19864578/101203807-8c68a180-366b-11eb-8415-9de6a0198b89.png)

Also, when I try to exclude `devextreme` of the deps optimization (in the `vite.config.js` file), I have an another error in the browser : 
![image](https://user-images.githubusercontent.com/19864578/101202412-7e198600-3669-11eb-981a-fa0749a9d88f.png)

I hope I can use your components without Webpack.

**Comment by artem-kurchenko** [comment]
Hello @clemvnt and @softboy99

Thank you for your cooperation. I reproduced this issue and created a report in our Support Center for further research: [The "Duplicate export 'hideCallback" error occurs on an attempt to build an application with DevExtreme using Vite](https://supportcenter.devexpress.com/ticket/details/t956025/the-duplicate-export-hidecallback-error-occurs-on-an-attempt-to-build-an-application)

We'll update it once we have any news.
