### ISSUE TITLE
Missing key prop in onTaskUpdating event (and other events like onTaskMoving etc)

### ISSUE THREAD

**Issue by edubskiy** [DevExpress/DevExtreme#15458]
### Steps to Reproduce:

1. Subscribe to onTaskUpdating method inside <Gantt ... /> component and load Gantt chart
2. Start moving task dates on UI
3. Expect receive event with key property inside onTaskUpdating method

### Results You Received:

cancel: false
component: Gantt
element: div.dx-widget.dx-gantt
newValues:
  end: Thu Nov 26 2020 17:04:45 GMT+0300 (Moscow Standard Time) {}
  start: Sat Nov 07 2020 03:00:00 GMT+0300 (Moscow Standard Time) {}
values:
  color: ""
  end: Sat Nov 28 2020 17:04:45 GMT+0300 (Moscow Standard Time) {}
  parentId: "parenId22"
  progress: 100
  start: Mon Nov 09 2020 03:00:00 GMT+0300 (Moscow Standard Time) {}
  title: "test title"

### Results You Expected:

I expected key property at the root level of event object.

### Environment Details:
I am using React version of Gantt

Latest chrome
"devexpress-gantt": "1.0.10",
"devextreme": " 20.2.2-beta",
"devextreme-react": "20.2.2-beta",

**Comment by edubskiy** [comment]
ping

**Comment by natashaash** [comment]
Hello,
Please accept my apologies for a delayed response. 

We fixed this issue in the following thread: [Gantt for Java Script - The key argument is missing in the taskMoving and taskUpdating events](https://supportcenter.devexpress.com/ticket/details/t942915/gantt-for-java-script-the-key-argument-is-missing-in-the-taskmoving-and-taskupdating#). Please update your project to v 20.2.4 to resolve the problem.
