### ISSUE TITLE
Splitting CSS By Component rather then all in one css

### ISSUE THREAD

**Issue by mrparag94** [DevExpress/DevExtreme#15491]
I think it is very efficient to have CSS by component base... like if I import a button I only need button.css but right now I have to import base + theme which is not an optimal solution for large application.

**Comment by hakimio** [comment]
Have you seen: [DevExtreme Style Sheets - Migration to Sass](https://github.com/DevExpress/DevExtreme/issues/13654)?

**Comment by babich-a** [comment]
ThemeBuilder also has a 'widgets' option. It allows you to build a bundle for selected widgets only: [https://js.devexpress.com/Documentation/20_1/Guide/Common/DevExtreme_CLI/#ThemeBuilder/Command-Line_Arguments](https://js.devexpress.com/Documentation/20_1/Guide/Common/DevExtreme_CLI/#ThemeBuilder/Command-Line_Arguments)

**Comment by mrparag94** [comment]
Well, It Has A Huge Amount Of Limitations...

Theme Builder is only about changing colors and Border Radius there nothing I can do more than that. Let Assume I Want To Add Padding on a Single Element then how should I do it..?

a button component should have a stylesheet specific to that component only and have nothing to do with another component's stylesheet.

if I import a button then I only need a button stylesheet.. if I don't use anything else... and it should contain all the variables that can change the appearance of the button and also it should have some class that a user can override.
for example, if I want to use a material theme and only the button component I want to another theme then what should I do in that case...?

if you look at the ant design for react you will understand what I am talking about... ant design appearance can be customized so heavily by the user... but DevExtrem doesn't give 10 percent of it... i know it is not DevExtream react but the concept is the same for everything...

Another example could be syncfusion components. they have a class that user can override to change it completely.
I am just stating the statement -> "Button can be customized through the e-custom class for all states (hover, focus, and active)"

**Comment by hakimio** [comment]
Using [devextreme-cli](https://js.devexpress.com/Documentation/Guide/Common/DevExtreme_CLI/#ThemeBuilder/Command-Line_Arguments) or [sass module system](https://github.com/DevExpress/DevExtreme/issues/13654) you can create (S)CSS bundle with only the components you are using.

You should also be able to customize all the [SCSS variables](https://github.com/DevExpress/DevExtreme/blob/21_1/scss/widgets/material/button/_sizes.scss) marked with `!default` post-fix, not only colors.
