### ISSUE TITLE
Can i make commercial app with this opensource devextream?

### ISSUE THREAD

**Issue by kingsanu-production** [DevExpress/DevExtreme#15563]
I want to do business with web app include this opesource devextream, can i do without pay and use this opesource?

**Comment by mrparag94** [comment]
The Simple And Short Answer is "NO"

**Comment by jsdmitry** [comment]
DevExtreme is free of charge If you're developing non-commercial applications. Please refer to the [License Agreement](https://js.devexpress.com/Licensing)  for license restrictions. If you have additional inquiries, I suggest you contact our Client Services department: clientservices@devexpress.com. They can answer any questions on the subject.
