### ISSUE TITLE
Version 20.2.4 breaks our stylesheet

### ISSUE THREAD

**Issue by buu700** [DevExpress/DevExtreme#15570]
Version 20.1.9 has the following rule in the various stylesheets (e.g. `dist/css/dx.material.purple.dark.compact.css`):

```
.dx-rtl .dx-icon-spinprev:before {
  content: "\f04e";
}
```

After upgrading to 20.2.4, that now looks like:

```
.dx-icon-spinnext::before {
  content: "�
�";
}
```

This causes our production bundled CSS to not be recognized (reproduced in Chrome, Firefox, and Safari).

**Comment by babich-a** [comment]
Hi. Devextreme stylesheets use utf8 encoding now.  Can you give a simple project that reproduce the issue?

**Comment by buu700** [comment]
Got it, thanks. It's probably something to do with the particulars of my project's bundling/post-processing, but for now just converting the stylesheets back to ASCII does the job:

```
for f in node_modules/devextreme/dist/css/*.css ; do
	node -e "fs.writeFileSync('${f}', fs.readFileSync('${f}').toString().
		replace(/^@charset .UTF-8.;\n/, '').
		replace(/[^\\x00-\\x7F]/g, c => \`\\\\\${c.codePointAt(0).toString(16)}\`)
	)"
done
```
