### ISSUE TITLE
Splitting CSS by Componenets rather then all in one

### ISSUE THREAD

**Issue by mrparag94** [DevExpress/DevExtreme#15618]
let assume I only add devextreme button I'm my project but for the styling part I have to add the full css to get the styling done.. is there any way to reduce the css to the component level css..?

**Comment by LexDX** [comment]
Hi @mrparag94,

I see that you asked the same question in this issue: https://github.com/DevExpress/DevExtreme/issues/15491. If you have further questions, please feel free to reactivate the initial thread.
