### ISSUE TITLE
Custom store and no JQuery dependency

### ISSUE THREAD

**Issue by ZeBobo5** [DevExpress/DevExtreme#15685]
Hi, 

I'm creating a csutom store and DevExtreme require a JQuery Promise to validate the store... How could I make it if JQuery is required...

**Comment by DokaRus** [comment]
CustomStore [supports](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/CustomStore/Configuration/#load) jQuery and native promises as well. Please refer to the following guide for more examples of the Custom Data Sources implementation [Specify a Data Source - Custom Data Sources](https://js.devexpress.com/Documentation/Guide/Data_Binding/Specify_a_Data_Source/Custom_Data_Sources/).

If you face any issues, feel free to create a ticket in our [Support Center](https://supportcenter.devexpress.com/).

**Comment by ZeBobo5** [comment]
'fail' and 'done' methods do not exists on native Promise... Only on JQuery. But they are used on a lot of your components...
