### ISSUE TITLE
latest v21.1.1 npm package is different with the github

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#15850]
after running npm install, the package downloaded are different with here

**Comment by softboy99** [comment]
the npm package version is in fact 21.1.0, rather than 21.1.1

**Comment by onebalaban** [comment]
Hello,

The latest version is 21.1.1-alpha-20350-0313. Since major v21.1 is not released yet, we don't have minor versions for it. Each alfa version is v21.1.0. You can see this in source files:
`Version: 21.1.0 (build 20350-0313)
 Build date: Tue Dec 15 2020`
