### ISSUE TITLE
Can i use Angular DevExtream + razor DevExtream in same project?

### ISSUE THREAD

**Issue by kingsanu-production** [DevExpress/DevExtreme#15924]
I'm using .net core angular where i would like to use devextream in angular as well as in razor page. can i do this? and if i do than will be start performance problem?

**Comment by onebalaban** [comment]
Hello,

It seems that it is possible to render Angular content in Razor pages as shown at: [Adding Angular Components to an Existing Razor Page in an ASP.Net Core App](https://momonet.io/posts/2020-03-11-adding-angular-app-to-an-existing-razor-page/). However, we didn't test this scenario and cannot guarantee that our components will work as expected. I recommend you use our ASP.NET Core controls in Razor Pages, and our Angular components in Angular. 
As for performance, both product lines are actually the same components written in JavaScript. There should be no difference in their performance.
