### ISSUE TITLE
'dxNavBar' is deprecated in 20.1. Use the 'dxTabs' widget instead.

### ISSUE THREAD

**Issue by wpitallo** [DevExpress/DevExtreme#15935]
Hi receiving this warning:

'dxNavBar' is deprecated in 20.1. Use the 'dxTabs' widget instead.

Is this true?

**Comment by onebalaban** [comment]
Hello,

Thank you for contacting us.
dxNavBar is an old component that we developed for our SPA mobile suite. We don't plan to develop it in the future. Please consider switching to dxTabs.
It seems that we forgot to add info about deprecation in our help topics. We'll check and revise this.
