### ISSUE TITLE
`tagTemplate` received empty string instead of item (object)

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/DevExtreme#15976]
### Steps to Reproduce:

```js
const items = [{ name: '', value: '' }]

new dxTagBox(fieldContainer, {
  displayExpr: 'name',
  value: items,
  tagTemplate: (item) => {
  	// here item should be { name: '', value: '' }
  },
  ...
});
```

### Results You Received:
The item is `''`

### Results You Expected:
The item is `{ name: '', value: '' }`

---

The error here: https://github.com/DevExpress/DevExtreme/blob/96b04313251759374e113c48e8f615f9eaae1cb5/js/ui/tag_box.js#L1061-L1062

You should compare `displayValue` with null/undefined

**Comment by DokaRus** [comment]
Hi, @Semigradsky 

I reproduced this issue on my side and created a public ticket in our Support Center:
https://supportcenter.devexpress.com/ticket/details/T965054

We will update the ticket once we have any results. Thank you for your patience!
