### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by bkniffler** [DevExpress/DevExtreme#16]
You deep support quite some frameworks, but how about react? Anything on the roadmap?

**Comment by Mehul** [comment]
Hi Yes, sign up at https://devexpress.com/webinars to learn about our plans.

**Comment by lukyanovas** [comment]
Hi,
You can use npm to try the alpha version of [DevExtreme React wrappers](https://www.npmjs.com/package/devextreme-react). Please give us any feedback by creating an issue on [GitHub](https://github.com/DevExpress/devextreme-react)
