### ISSUE TITLE
Chart Axis Label Template Needs More Data

### ISSUE THREAD

**Issue by ppoisson** [DevExpress/DevExtreme#16029]
If you ever create a Chart Axis Label Template you'll notice there are only two useful values you can get back, value and valueText. Both being essentially the same, there is no way to access the property/values for the data relating to that label.  In my case I needed a way to create a multi-column SVG table as a label.  The only way I could achieve this is either finding a way to create multiple side by side axes without adding a series, or use the Chart Axis Label Templates.  What I did was use the argumentValue property that is set to the value and valueText as an index to the datasource itself, thus giving me access to all the properties in the array object. 

It would be much more useful if you gave an option to send through more data aside from the property that delivers the value and valuerText.  In this case you could add a new object called 'data' to the payload. Why stop at a single property allowed to come through the data template. Give me more data related to the object if there is more.  Similar to the data object that comers through the point click event.

### Steps to Reproduce:

1. Create an Axis label Template
2. Notice you only get value and valueText properties that directly correspond to the argumentValue property

### Results You Received:

Not enough data. if my datasource looks like:
[
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;argumentValue: 'string that comes through the template' // only one as value/valueText
&nbsp;&nbsp;&nbsp;&nbsp;label0: '12345', // why not this
&nbsp;&nbsp;&nbsp;&nbsp;label1: ''abcde", // or this
&nbsp;&nbsp;}
]

### Results You Expected:

I would expect the data in the template to deliver all my data in the object, argumentValue, label0, label1, etc.instead of the single value as the label.  If it was returned as an object with all my properties then I can decide which property or properties I want to use as the label(s).

Example:

label0 | label1 | argumentValue in a column next to the bar as the label. | bar chart point...
etc...

### Environment Details:

DevExtreme 20.2
Nothing else matters its an architecture request.

**Comment by alexanderPolosatov** [comment]
Hi,

To get additional information in axis.template, I recommend you use a widget instance. For this, you can use the [onInitialized](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxChart/Configuration/#onInitialized) event. I created an [example](https://codepen.io/p_alexander/pen/ExNyNEj?editors=1010) that illustrates how to get all [points](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxChart/Chart_Elements/Point/) related to the current argument.

Let us know if you have any questions.
