### ISSUE TITLE
The problem of displayFolder in field chooser.

### ISSUE THREAD

**Issue by luweiymy** [DevExpress/DevExtreme#16032]
### Steps to Reproduce:

1. In field chooser these 2 columns shown under folder named "test". 

### Results You Received:
When i clicked checkbox of folder it only checks for the first column
![image](https://user-images.githubusercontent.com/6321099/104891246-a48e4900-59ab-11eb-8248-dc27d034a68e.png)

### Results You Expected:

 i want it to check all columns under that folder
![image](https://user-images.githubusercontent.com/6321099/104891272-ae17b100-59ab-11eb-81fb-8751326f1aa9.png)

**Comment by onebalaban** [comment]
Hello,

We use our [support center](https://supportcenter.devexpress.com/ticket/list) to review technical questions. Please submit a ticket there. In the ticket, describe the issue and attach a simple project to demonstrate your entire implementation and the issue. We will be happy to review your project and help you.
