### ISSUE TITLE
Error: Cannot read property 'brokenRules' of undefined - DataGrid with setCellValue and editTemplate

### ISSUE THREAD

**Issue by oixan** [DevExpress/DevExtreme#16030]
### Steps to Reproduce:

1.  Click on the first row of the column "Owner" , 
2.  Choose any value
3.  Click next cell. 
4.  Error: BrokenRule of undefined

### Live Example:
https://codesandbox.io/s/custom-editors-devextreme-data-grid-forked-nork1?file=/App.vue

### Results You Received:
Error: Cannot read property 'brokenRules' of undefined

### Results You Expected:
Focus move on the next cell

### Environment Details:
Devextreme 20.2.4 - devextreme-vue: "20.2", vuejs 2.6.11

**Comment by onebalaban** [comment]
Hello,

I cannot reproduce the "Cannot read property 'brokenRules' of undefined" error in your example. I got the "An error has occurred" in DataGrid. The console and Network tab indicate this error as the "500" server-side error. This means that some error occurred on the server in the UpdateTask method. Could you please clarify how to reproduce the initial error?

**Comment by oixan** [comment]
Sure, this is a video example of the problem. 

[https://screencast-o-matic.com/watch/crVFYC92Pk](url)

Anyway something is not working properly becouse i cant leave the cell after i choose some value.

**Comment by onebalaban** [comment]
Hello,

Please accept my apologies for the delayed response. I checked the steps you shared. However, I don't understand why you need multiple clicks on the same cell. Could you please elaborate on this?

As for leaving the current cell, this issue may be related to the error that occurs in your DataGrid when editing. Please fix the error first. If you need assistance with this technical task, please submit a ticket to our Support Center. We'll be happy to help you.

**Comment by oixan** [comment]
Hi, thank for the reply.

After some investigation i tried that replace the mistaken row of code in setCellValueDescizioneArticolo

  currentRowData.Owner = "Samantha Bright";
  newData = Object.assign(newData, currentRowData);

with the correct

  currentRowData.Owner = 2;
  newData = Object.assign(newData, currentRowData);

all work fine

**Comment by onebalaban** [comment]
As I understand, the issue is resolved. I didn't manage to reproduce any errors in your CodeSandBox with your updated code. Thank you for informing us about your progress.
