### ISSUE TITLE
Wrong @use statement in material scss file

### ISSUE THREAD

**Issue by BrandoCaserotti** [DevExpress/DevExtreme#16031]
### Steps to Reproduce:

1. Go to file `node_modules\devextreme\scss\widgets\material\list\_sizes.scss`
2. See `@use "../list/colors" as *`.  Other widgets are not using `_colors.scss` in `_sizes.scss`

### Results You Received:

This is preventing me from doing :

```
@use "~devextreme/scss/widgets/material/list/colors"
with(
 $list-item-hover-bg: transparent,
 $list-item-selected-bg: transparent,
 $list-item-selected-hover-bg:transparent,
 $list-item-focused-selected-bg: transparent
);

@use "~devextreme/scss/widgets/material/list/sizes";

@use "~devextreme/scss/widgets/material/list";
```

removing the wrong statement makes everything work as expected, as pointed out in #13654.

List is the only widget i've found with this issue.

### Environment Details:
```
"devextreme": "20.2.4",
"devextreme-angular": "20.2.4"
```

**Comment by babich-a** [comment]
Hi @BrandoCaserotti . Can you send a full example?
I have tried this one, and it compiles successfully:

```
// set theme settings
@use "node_modules/devextreme/scss/widgets/material/colors" as themeColors with (
    $color: "blue",
    $mode: "light"
);
@use "node_modules/devextreme/scss/widgets/material/sizes" as themeColors with ($size: "default");

// set list settings
@use "node_modules/devextreme/scss/widgets/material/list/colors"
with(
 $list-item-hover-bg: transparent,
 $list-item-selected-bg: transparent,
 $list-item-selected-hover-bg:transparent,
 $list-item-focused-selected-bg: transparent
);

@use "node_modules/devextreme/scss/widgets/material/list/sizes";

@use "node_modules/devextreme/scss/widgets/material/list";
```

Actually, you do not need `@use "node_modules/devextreme/scss/widgets/material/list/sizes";`. The size scheme is defined in `@use "node_modules/devextreme/scss/widgets/material/sizes" as themeColors with ($size: "default");`
