### ISSUE TITLE
feature request: scheduler component in a timeline/hour.

### ISSUE THREAD

**Issue by bbortt** [DevExpress/DevExtreme#16130]
### Steps to Reproduce:

I tried making somewhat of a timeline/hour using your `Scheduler` component (in Angular).

1. use the `Scheduler`
2. select type `timelineDay`
3. set `startDayHour` to 8:00 AM (value = 8)
3. input interval of anything less than 1 (floating point number), let's say 0.5

### Results You Received:

the scheduler does not load anymore.
```bash
ERROR DOMException: Element.querySelectorAll: '[id='dx-query-children'] td:nth-child(18.666666666666668n)' is not a valid selector
```
of course, this is an interesting `nth-child` selector.

### Results You Expected:

the scheduler shows me a timeline from 8.00 AM this day to 8.00 AM the next day.

### Question:

Hi guys
do you have any solution to the above problem ("Results You Expected")?
I was wondering why there is no such thing as `timelineHour`. were there any problems implementing it? or just "nobody ever asked for"? I'd be happy to contribute too, if your company allows it. 
thanks in advance,
Timon

**Comment by andrewmakarov** [comment]
Hi,
cellDuration property expects an integer value. More details you can found in our [documentation](https://js.devexpress.com/Documentation/21_1/ApiReference/UI_Components/dxScheduler/Configuration/#cellDuration). 
We don't have built-in solution for display a view based an hour.

**Comment by bbortt** [comment]
thanks for your feedback. I mostly discovered that by my self already.
would you be willing to accept a PR if I implement an hour-based timeline?

**Comment by andrewmakarov** [comment]
@bbortt 
We can review PR. But we can merge it on conditions that:
- the code must match our requirements(code styles, code rules, code design)
- all test must pass 
- new functionality needs to be tested according to our requirements(unit testing, functional testing and screenshot testing)

**Comment by MaximKudriavtsev** [comment]
Hi @bbortt,

As you mentioned before "nobody ever asked for" this functionality. It would be helpful if you describe your use-case in detail. Your scenario, some pictures, or screenshots - everything might be useful for us in future development.

**Comment by bbortt** [comment]
@MaximKudriavtsev sure can. I am a little short in time lately, especially because spring term has just started. but, I was able to start coding a little yesterday: https://github.com/DevExpress/DevExtreme/compare/21_1...bbortt:feature/timeline-hour?expand=1.

So, I am planning a big event with a group of people. By big I mean around 7000 attendants spread over two weekends. Well, at least that was the plan before COVID-19. Anyways, we need a very strict timetable for this happening. As I couldn't find any program that fits our needs I quickly started my own project: [bbortt/event-planner](https://github.com/bbortt/event-planner). And when looking for a timetable which integrates well with Angular I found this component library. But, because that timetable has to be very detailed: A view per day (timetable/day) is almost too big. I'd like the users of my application to be able to show only events let us say occurring on Tuesday from 08:00 AM to 06:00 BM.

That is how it currently looks:

![image](https://user-images.githubusercontent.com/12272901/108851827-272aa980-75e5-11eb-96ee-ab9ee6503bf1.png)

As you can see the users can filter by days (top right corner) and adjust an interval. But, already now it's quit big and one has to scroll to the right. A timetable/hour would do much bedder!

**Comment by MaximKudriavtsev** [comment]
@bbortt,

Thank you for sharing your materials. Please correct me if I misunderstand something, but I'm not sure how this `timeline hour` view can reduce the amount of content.

You mentioned: "But, already now it's quit big and one has to scroll to the right. A timetable/hour would do much bedder!"

The Timeline Hour view represents one hour and consists of minutes. Why do you need such detalization - with minutes? According to your materials, your app will show a time period from 6 am to 8 pm. It's 12 hours, and it will be shown as a very long timetable.

To reduce the timeline day, you can use the [cellDuration](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#cellDuration), [startDayHour](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#startDayHour), and [endDayHour](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#endDayHour) properties. I created an [example](https://codesandbox.io/s/timelines-devextreme-scheduler-forked-dtotk?file=/src/app/app.component.html). Let me know if these properties cover your needs.

**Comment by bbortt** [comment]
@MaximKudriavtsev ok, maybe "reduce the amount of content" is the wrong word choice :) let's say it opens up more filter possibilites which then "reduce the amount of content"..
I already knew these properties. but what if I want to show, let's say, day 1 from 6 am to day 2 and 6 am. it's not possible without manually calculating two scheduler components side by side as far as I know. or am I wrong?

**Comment by MaximKudriavtsev** [comment]
@bbortt 

> I already knew these properties. but what if I want to show, let's say, day 1 from 6 am to day 2 and 6 am. it's not possible without manually calculating two scheduler components side by side as far as I know. or am I wrong?

You are right.

**Comment by bbortt** [comment]
just leaving a "followup comment" here.. in case anyone stumbles upon this issue. we no longer request this feature. it became quickly clear, that the idea of a horizontal scrolling timeline does not scale. when having multiple days, multiple groups and so on, all in one place - the view just got too huge.
we are using the calendar view now, with daily, weekly and monthly grids. showing all groups by default and having a multi-select-dropdown which allows the user to filter particular interests. that does a good job so far 🚀 
BR, Timon
