### ISSUE TITLE
devexpressJs  filxed bug

### ISSUE THREAD

**Issue by vizgold** [DevExpress/DevExtreme#162]
Hello, when I'm using devexpressJs, I find some problems with using filxed column in IE browsers.
1, the reset of $(document.body).Click event will expire and will only be triggered by clicking on the text or the border border.
2, using the right-click menu event will fail and will only be triggered by clicking on the text or the border border.
3, when more than 26 data, the last two data in addition to the frozen column (filxed Colmun), the other are merged into a cell.
4, in a lot of time to move to the right, in the IE browser will appear flashing, the experience is not good.

**Comment by MarinaRukavitsyna** [comment]
Hi @jikex,
According to the information on the README page, we provide support via DevExpess Support Center. Please contact our support at www.devexpress.com/support
