### ISSUE TITLE
DxDrawer - Dynamic changing minSize causes a padding-right to be added

### ISSUE THREAD

**Issue by arndwestermann** [DevExpress/DevExtreme#16249]
Hello there, i found an issues in Version 20.2.4 where i dynamically setting the minSize property of a drawer. I used an observable to detect if i'm on a small screen size or not. If it is a small size minSize will be set to 0 resulting in a disappearing side nav and if it is a bigger screen size, the side nav displays the icons. But when i rotate the screen to landscape and back the drawer gets a padding to the right. This is the same as the minSize for none small screens.

I've created three Stackblitz projects, from version 20.2.3 to 20.2.5. It is perfectly working an v20.2.3, but on the other two versions it is broken.

### Steps to Reproduce:

1. https://stackblitz.com/edit/angular-2avrz3?file=src%2Fapp%2Fapp.component.ts  -> v20.2.3
2. https://stackblitz.com/edit/angular-qvyulm?file=src%2Fapp%2Fapp.component.ts -> v20.2.4
3. https://stackblitz.com/edit/angular-iccc5x?file=src%2Fapp%2Fapp.component.ts  -> v20.2.5

1. Open the repos
2. Press 'Open in New Window'
3. Open the console
4. Toggle device toolbar
5. Set it to iPhoneX
6. Reload the page
7. Rotate the screen

### Results You Received:
A Padding on the right side, set to the value of minSize

### Results You Expected:
No Padding to the right, like in v20.2.3

### Environment Details:
Angular 11.1.1
Devextreme 20.2.5
Devextreme-Angular 20.2.5
Chrome Version 88.0.4324.96 (Official Build) (x86_64)
MacOS Mojave v10.14.6

Reproduceable on Stackblitz

**Comment by IgnatovDan** [comment]
Please accept our apologies for the delay. We've been very busy for the last days. We are researching this issue.

![image](https://user-images.githubusercontent.com/2094015/109540793-04602f80-7ad4-11eb-8dad-8846f714d754.png)

**Comment by arndwestermann** [comment]
Absolutely no worries, I'm glad that someone is taking care of this problem!

**Comment by IgnatovDan** [comment]
In order to better serve and track this issue I created a new entry in our Support Center: [T978380 - Drawer - Incorrect padding is added after minSize is changed](https://supportcenter.devexpress.com/ticket/details/t978380)
Please add it to your Favorites to be notified when its status is changed.
