### ISSUE TITLE
Error in  Odata with selectbox customitem insert.

### ISSUE THREAD

**Issue by kingsanu-production** [DevExpress/DevExtreme#16376]
Hello Team!
I'm using razor page for selectbox to add custom item with OData. Getting record is well, insert is also well, but after insert selectbox doesn't able to show inserted value.

Razor Page
![image](https://user-images.githubusercontent.com/65809324/107881681-739e2700-6f0b-11eb-94e7-a52d6d307dfa.png)

Javascript
![image](https://user-images.githubusercontent.com/65809324/107881688-7dc02580-6f0b-11eb-945d-d789948a64c2.png)

Chrome Event
![image](https://user-images.githubusercontent.com/65809324/107882716-07bebd00-6f11-11eb-82cb-a6e5ce6d3b2d.png)

**Just for your infrmation getall look like this**
![image](https://user-images.githubusercontent.com/65809324/107883202-8ddc0300-6f13-11eb-8849-52161e6f3202.png)

**Comment by artem-kurchenko** [comment]
Hi @kingsanu-production

The `clearRawDataCache` method exists for a CustomStore only. You can use the technique we demonstrated in our demo: [Search And Editing](https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/jQuery/Light/). It should work for OData as well.

If this doesn't help, send us a **JS** example that demonstrates the issue in action. We'll perform more detailed research.
