### ISSUE TITLE
Column Fixing brakes render of expanded columns

### ISSUE THREAD

**Issue by nikitashum** [DevExpress/DevExtreme#16399]
### Steps to Reproduce:

1.  Have an expandable table with columns that include dx-tab-panel
2. Enable column fixing
3. Expand the column
4. The table doesn't resize or adjust to a new column size

### Results You Received:
![image](https://user-images.githubusercontent.com/36233163/108075286-7bc0a880-706a-11eb-8228-c587e90fc681.png)

### Results You Expected:
![image](https://user-images.githubusercontent.com/36233163/108075184-5a5fbc80-706a-11eb-8b93-30eab7567f57.png)

### Environment Details:
Version: 20.1.8
Chrome, Windows 10, AngularJS

**Comment by onebalaban** [comment]
Hello,

We need to reproduce the issue and debug the code to check if this is a bug. We cannot do that with screenshots only. Please share a simple project to demonstrate the issue. You can use our [Angular template](https://github.com/DevExpress/devextreme-angular-template) to create this project.

**Comment by onebalaban** [comment]
Hi,

I haven't heard from you in a while. We'll close this issue for now. Feel free to reopen it should you require further assistance.
