### ISSUE TITLE
remove vscode problem tab theme builder and cli dart error when devextreme-themebuilder and cli in package.json devdependency

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#16464]
Is there a way to remove vscode problem tab theme builder and cli dart error when devextreme-themebuilder and cli in package.json devdependency?

**Comment by onebalaban** [comment]
As you may know, we don't offer technical support on GitHub. Please submit a ticket to our Support Center and describe the exact steps to reproduce the issue. We'll be happy to help you.
