### ISSUE TITLE
groupedData[0] can be undefined. groupedData[0].allDayPanel blows up

### ISSUE THREAD

**Issue by ThomasGHenry** [DevExpress/DevExtreme#16516]
There are a few places where getting and setting `groupedData[0].allDayPanel` blows up because `groupedData` is empty.

**Comment by artem-kurchenko** [comment]
Hi @ThomasGHenry  

Thank you for pointing to this.  Null checks will help you to avoid JS errors, but the widget may not properly work. Do you have a test case that demonstrates this issue? This should help us understand how to fix the issue.
