### ISSUE TITLE
HtmlEditor - Table management enhancements

### ISSUE THREAD

**Issue by jsdmitry** [DevExpress/DevExtreme#16538]
# HtmlEditor - Table management enhancements

## The Problem
Before we release our HTML/Markdown editor as RTM, we would like to address the following table-related issues:

- It is impossible to add a table header, merge several cells, or enter cell text in multiple lines.
- Table management is now available only from the toolbar. We want to make this more user-friendly and allow users to manage the created table without moving the mouse pointer or finger between the table and the toolbar. This also makes the toolbar less cluttered.

## The Proposed Solution

We plan to introduce the following enhancements:
- Add a context menu for table operations and customization
- Render a table header as the `<thead>` tag in table markup
- Support multiline text in cells
- Implement the split and merge operations for table cells
- Add a popup window for table/cell appearance customization

### Table/cell customization using a context menu
We plan to make table operations available in the context menu:

![Customize-a-table-cell-with-context-menu](https://user-images.githubusercontent.com/11206389/108025110-ed7eff00-7036-11eb-8708-ffd634bc8e6a.png)

### Table header support
Users can add header rows when they create a table. The header rows will become `<thead>` tags in the resulting markup:
```html
<table style="border: 1px solid #000;">
  <thead>
    <tr>
      <td><br></td>
      <td><br></td>
      <td><br></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><br></td>
      <td><br></td>
      <td><br></td>
    </tr>
  </tbody>
</table>
```
### Multiline text in cells
We will implement the capability to write multiline text in cells.

### Cell merging
The merge and split cell operations will be available:

![Cell-merging](https://user-images.githubusercontent.com/11206389/108025122-f4a60d00-7036-11eb-8cd9-2cd3bd5446f1.png)

### Table/cell appearance customization

You will be able to change the following settings for a table or cell:
- Border (style, color, width)
- Background color
- Dimensions
- Text alignment within a table or cell

![Table/cell-appearance-customization](https://user-images.githubusercontent.com/11206389/108025386-71d18200-7037-11eb-9927-264b69850120.png)

#### Table resizing and Context menu with common table operations
https://js.devexpress.com/Demos/WidgetsGallery/Demo/HtmlEditor/Tables

#### Soft breaks in Block Elements
- [jQuery](https://jsfiddle.net/mkx7p5t9/)
- [Angular](https://codesandbox.io/s/tables-devextreme-html-editor-forked-ubzm6?file=/src/app/app.component.ts)
- [Vue.js](https://codesandbox.io/s/tables-devextreme-html-editor-forked-z98dv)
- [React](https://codesandbox.io/s/tables-devextreme-html-editor-forked-oqnu2?file=/App.js)

### Take a Quick Poll

[Do you find the table enhancements helpful?](https://forms.gle/SVk4qyU863yabUxB6)

Subscribe to this thread for updates on this topic.

**Comment by statler** [comment]
This is absolutely essential work and we desperately need it. Is there a preview version of this available? We have clients requesting the ability to manage their tables. Thanks

**Comment by DokaRus** [comment]
We have updated the discussion page with a live sandbox examples:

#### Table Resizing
- [jQuery](https://jsfiddle.net/dzeu5qjt/)
- [Vue.js](https://codesandbox.io/s/tables-devextreme-html-editor-forked-k1fh6)
- [React](https://codesandbox.io/s/tables-devextreme-html-editor-forked-hsl62)

#### Context menu with common table operations
- [jQuery](https://jsfiddle.net/cxhj58ve/)


#### Soft breaks in Block Elements
- [jQuery](https://jsfiddle.net/u0n917p3/)
- [Vue.js](https://codesandbox.io/s/tables-devextreme-html-editor-forked-z98dv)
- [React](https://codesandbox.io/s/tables-devextreme-html-editor-forked-oqnu2?file=/App.js)

**Comment by UXDart** [comment]
this is great! one question, it seems the soft breaks, uses shift+enter, why not just enter? you are in a cell you want a new line, you press enter IMO

extra points, on resize if press some key like alt or shift while resizing the last vertical line (or maybe the last vertical line works like that), it resize all columns. the use case is you want the grid to be smaller, so you resize from the last vertical col line, but that changes only last column. Thanks!

**Comment by DokaRus** [comment]
@UXDart 
>this is great! one question, it seems the soft breaks, uses shift+enter, why not just enter? you are in a cell you want a new line, you press enter IMO

We plan to enable multiple paragraphs (`<p>` tag) within a table cell, soon. That is, enter will just add a new line to the cell. Stay tuned :)

>extra points

Thank you! We'll take that into account

**Comment by Prasad814359** [comment]
Is the "table property","cell property" options available in angular version??

**Comment by DokaRus** [comment]
In v21.2 we added the following improvements:

- [Context menu](https://js.devexpress.com/Documentation/21_2/ApiReference/UI_Components/dxHtmlEditor/Configuration/tableContextMenu/) for table operations and customization
- Render a table header as the `<thead>` tag in table markup
- Support multiline text in cells
- [Soft-break](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxHtmlEditor/Configuration/#allowSoftLineBreak) support
- Dialog for table and cell appearance customization
- [Table resizing](https://js.devexpress.com/Documentation/21_2/ApiReference/UI_Components/dxHtmlEditor/Configuration/tableResizing/)

You can find the full list of DevExtreme component enhancements on our [What's New](https://js.devexpress.com/New/21_2/#HTMLEditor) page.

**Comment by ksercs** [comment]
We released most of the improvements described in this thread in v21.2. The Cell Merge/Split feature is temporarily postponed, but we'll consider the ability to implement it in future releases.

Thanks to everybody who gave us feedback on Table management enhancements. I'm closing this thread. In case of future questions, feel free to create a new ticket in our [Support Center](https://www.devexpress.com/Support/Center/).
