### ISSUE TITLE
dxtoolar labelLocation=left like dxForm

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#16584]
dxtoolar labelLocation=left like dxForm

**Comment by onebalaban** [comment]
The toolbar component doesn't have labels. Please elaborate on your requirements.

**Comment by softboy99** [comment]
Yes, but when i add editor widgets in onToolbarPreparing with code dynamically, i.e. textbox, the label is always above the textbox

**Comment by onebalaban** [comment]
Thank you for the clarification. This inquiry is not related to the Toolbar functionality. Please submit a ticket to our Support Center and describe the issue in detail. We'll be happy to assist you. It will be helpful if you attach a simple project to your ticket to demonstrate the issue. This will help us find a solution faster.

**Comment by softboy99** [comment]
Thanks. I think it's very important feature for grid/treelist ui. Without it, why we should use it? why not use dxForm based ui to input one by one?
