### ISSUE TITLE
feature requestment for multiple cell selection for DataGrid

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#16580]
feature requestment for multiple cell selection for DataGrid

**Comment by onebalaban** [comment]
Please elaborate on your final goal. Why do you need to select multiple cells? How should a user select them? What do you do after these cells are selected?

**Comment by softboy99** [comment]
I want to implement copy up/copy down which belongs to same column, when selected an cell range

**Comment by onebalaban** [comment]
Thank you for the clarification. We'll keep in mind this information in our future development.
