### ISSUE TITLE
MemoEx widget

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#16594]
Please add MemoEx widget

**Comment by onebalaban** [comment]
Thank you for the suggestion. We don't plan to implement new widgets in 2021. However, we can do it in the future. In the meantime, could you please tell us more about this widget and share screenshots with us so that we can better understand your needs?

**Comment by softboy99** [comment]
for long text, display an icon, when click show and edit in popup, like your winform MemoEx

**Comment by onebalaban** [comment]
Thank you for your description.
