### ISSUE TITLE
Need an example of moving an item between two grouped dxList

### ISSUE THREAD

**Issue by pikhovkin** [DevExpress/DevExtreme#16706]
Need an example of moving an item between two grouped dxList.

Here is my attempt to do it https://codesandbox.io/s/item-drag-drop-devextreme-list-forked-88s8v?file=/App.js
The added element just jumps to the end without grouping.

**Comment by onebalaban** [comment]
We don't have such a pre-built example. As you may know, we don't offer technical support on GitHub. Please submit a ticket to our Support Center, describe your task in detail, and attach your CodeSandBox project to the ticket. We'll be happy to review it and assist you.
