### ISSUE TITLE
DataGrid - FilterRow with Int dataType

### ISSUE THREAD

**Issue by lmorningstar116** [DevExpress/DevExtreme#16731]
### Problem:

In a filter for a column, only numbers must be allowed.
If you specify dataType = 'number' for a column, then you can enter a floating point number in the filter field.

How can you allow only whole numbers to be entered in a field?

**Comment by onebalaban** [comment]
Hello,

As you may know, we don't offer technical support services on GitHub. Please submit a ticket to our Support Center and describe the issue in detail. We'll be happy to assist you. It would be also helpful if you attach a simple project to your ticket to demonstrate the issue. This will help us find a solution faster.
