### ISSUE TITLE
Devextreme React Datagrid Filter Row Dropdown flickering on hover

### ISSUE THREAD

**Issue by nageshwar-nuvolo** [DevExpress/DevExtreme#16782]
### Steps to Reproduce:

1. Add DataGrid with FilterRow to React Component
2. Mouse over on column filter search dropdown icon

### Results You Received:
Column Filter Row Dropdown will be flickering on mouse over on search icon

Live Reproducible Link:
[https://codesandbox.io/s/datagrid-filter-row-flickering-issue-ew342](https://codesandbox.io/s/datagrid-filter-row-flickering-issue-ew342)

### Results You Expected:
Column Filter Row Dropdown should be stable on mouse over on search icon

### Environment Details:

Devextreme: 20.1.7
Browser: Google Chrome
OS: MacOS Catalina 10.15.6

**Comment by onebalaban** [comment]
Hello,

We are working on this issue in your ticket (T983143). Please do not post the same inquiries in different resources. This will make it difficult for us to process your requests. We'll answer you in that ticket shortly.
