### ISSUE TITLE
New WYSIWYG text editor/viewer with support for docx for quill

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#16841]
New WYSIWYG text editor/viewer with support for docx for quill

**Comment by CollinHerber** [comment]
Would love to see this. Adding some research material:

Quill -> DocX
https://github.com/quilljs/quill/issues/1996 (Here is a code framework for Quill to DOCX)

DocX -> Quill
https://github.com/quilljs/quill/issues/2157 (Uploading Docs (i.e. Google Docs, Word, Office Docs, etc) 
- > https://github.com/immense/quill-drag-and-drop-module
- > https://www.npmjs.com/package/docx2html

**Comment by alexander-kotov-dx** [comment]
Hello. Thanks for the feedback and for sharing your findings.

As you may know, we have [HtmlEditor](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxHtmlEditor/), which is built on top of Quill. We do not have plans to support the DOCX format for our HTML Editor or create a similar editor for DOCX. Nevertheless, we will take your request into account when planning our future updates.

Meanwhile, use our RichEditor. It can be used in ASP.NET Core, Vue, React, Angular, and other applications - [https://docs.devexpress.com/AspNetCore/400373/rich-edit](https://docs.devexpress.com/AspNetCore/400373/rich-edit). It also supports DOCX.

If it doesn't meet your requirements, please describe important features that you wish to see implemented.

**Comment by softboy99** [comment]
Hi,
Is your RichEditor can use in vue,react,angular without .net backend or any other backend?

**Comment by alexander-kotov-dx** [comment]
Our Rich Editor doesn't require any back-end and you can use it directly in your client-side app.

For example, check the [angular app demo](https://github.com/DevExpress-Examples/richedit-angular-app) and our guide that describes how to achieve this: [https://docs.devexpress.com/AspNetCore/401527/rich-edit/get-started/angular-application](https://docs.devexpress.com/AspNetCore/401527/rich-edit/get-started/angular-application)

If you encounter issues with our Rich Editor in your project, we recommend you contact us at the [DevExpress Support Center](https://www.devexpress.com/Support/Center). This is our main channel for technical assistance.
