### ISSUE TITLE
HtmlEditor - Raw Code Editing Enhancement

### ISSUE THREAD

**Issue by CollinHerber** [DevExpress/DevExtreme#16854]
# Html Editor - Raw Code Editing

## Problem
Allowing raw code editing for the WYSIWYG Editor opens up a world of potential with customization. Not having this option is very limiting. This would allow people to write inline styles, add classes, all sorts of great options!

## Future Potential
1. One huge thing that comes to mind is some sort of customizable syntax for advanced features, imagine you being able to do something like  `{{id: 1; table=Blog; field=Title}}` which you can then wire up some backend logic to fill that in dynamically based on the syntax. This is just one of the FAR more advanced options I could think of.
2. For those like myself using frameworks that allow you to create customizable elements, `<my-element>` for example. we would be able to allow the front end users to use these components freely with an interpreter built into the front end to build and display those components. Right now you're stuck with `<p><my-element></p>` which in most cases is fine but can result in some unexpected behavior.

## Proposed Solution
Check out this quill plugin recently published: https://www.npmjs.com/package/quill-html-edit-button

Adding an option to turn this on/off in the configuration
```javascript
items: [ rawEditor: true ]
```

**Comment by b1tzer0** [comment]
I tend to have to extend the buttons on quill to add new elements that are needed.  Have the Raw HTML option would be ideal.

**Comment by alexander-kotov-dx** [comment]
Hello. Thank you for your feedback and research.

We currently have no plans to implement the raw code editing feature for our HTML Editor widget, but we will take your feedback into account for future development.

Our widget has the ability to [add custom modules](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxHtmlEditor/Methods/#registercomponents) or [modify existing ones](https://js.devexpress.com/Documentation/Guide/UI_Components/HtmlEditor/Formats/#Customize_Built-In_Formats_and_Modules), so you can implement a custom solution with our Html Editor and an external [raw code editing](https://www.npmjs.com/package/quill-html-edit-button) module.

But pay special attention that Quill optimizes inner markup and removes unsupported tags and attributes. So, we cannot guarantee that the final markup will completely match the raw markup.
