### ISSUE TITLE
Lookup loading panel not appear when get data over load function if message "No data to display" shown.

### ISSUE THREAD

**Issue by nsnayp13** [DevExpress/DevExtreme#16863]
### Problem:
Hello.
Lookup loading panel not appear when i try get data over load function if message "No data to display" shown.

### Steps to Reproduce:

1. Create lookup and set dataSource as 
```javascript 
this.dataSource = {
      store: new CustomStore({
        loadMode: 'processed',
        key: 'id',
        /** load return data orray or empty [] */
        load: (args) => {
          return this.contractorService
            .findContractor(args.searchValue)
            .toPromise();
        },
      }),
};
```
2. Create component lookup
```html
<dx-lookup [dataSource]="dataSource">
    <div *dxTemplate="let itemObj of 'item'">
        <div *ngIf="!isLoading">
            {{ itemObj.title }}        
        </div>
    </div>
</dx-lookup>
```
3. Open lookup, load function called and show loading panel
4. Service return empty array and lookup show "no data" message
5. Type text in search field, load function called and there is no loading panel 

If load return empty array, next search starts without loading panel

### Environment Details:

devextreme: 20.2.4
devextreme-angular: 20.2.4
angular/core: ~11.0.5

**Comment by DokaRus** [comment]
Hi @nsnayp13,

I reproduced this issue and created a public ticket in our Support Center:
[T985917 - Lookup - the LoadPanel isn't shown during filtering if there are no items in the data source at the start of filtering](https://supportcenter.devexpress.com/ticket/details/t985917)
Please track it to get updates.
