### ISSUE TITLE
What to use instead of exportToExcel(boolean) as it has been deprecated in 20.2

### ISSUE THREAD

**Issue by romua** [DevExpress/DevExtreme#16865]
Like how to start exporting process from controller(previously I used this.dataGrid.instance.exportToExcel()) but not from template  built in button. I want to have, actually already have, my custom button? (it's not even in the same component as my table).

**Comment by EugeniyKiyashko** [comment]
Hi,

In your scenario, you can use [the exportDataGrid(options)](https://js.devexpress.com/Documentation/ApiReference/Common/Utils/excelExporter/#exportDataGridoptions) method instead. You need to pass your dataGrid.instance to the ['component'](https://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/ExcelExportDataGridProps/#component) property of the configuration object in the following way:

```
exportGrid(e) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Companies");

    exportDataGrid({
      component: this.dataGrid.instance,
      worksheet: worksheet
    ...
```

Refer to the following demo for a runnable sample: [CodeSandBox](https://codesandbox.io/s/cell-customization-devextreme-data-grid-forked-21e5c?file=/src/app/app.component.ts).

Please check the [Overview](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSOverview/jQuery/Light/), [Cell customization](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSCellCustomization/jQuery/Light/), [Export Header and Footer](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSHeaderAndFooter/jQuery/Light/), [Export multiple grids](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSExportMultipleGrids/jQuery/Light/), and [Export images](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSExportImages/jQuery/Light/) demos in our Widget Gallery and our [official documentation](https://js.devexpress.com/Documentation/ApiReference/Common/Utils/excelExporter/#exportDataGridoptions). You can use the sample and demos as a starting point and modify them according to your requirements.

If you have further questions, we will be happy to address them in our [Support Center](https://www.devexpress.com/ask).
