### ISSUE TITLE
Paging disappears when scroll is virtual

### ISSUE THREAD

**Issue by Duoquote** [DevExpress/DevExtreme#16935]
### Steps to Reproduce:

https://codesandbox.io/s/overview-devextreme-data-grid-forked-u6mt1

### Results You Received:

When enabling virtual scrolling, paging disappears.

### Results You Expected:

When virtual scrolling is enabled, the paging should stay.

**Comment by onebalaban** [comment]
You can use the `pager.visible` property to enable a pager:
` <Pager allowedPageSizes={pageSizes} showPageSizeSelector={true}  visible={true} />`
