### ISSUE TITLE
Angular HtmlEditor insertTable popup title and labels displayed as !TODO  

### ISSUE THREAD

**Issue by asetil** [DevExpress/DevExtreme#17159]
### Steps to Reproduce:

1. I have upgraded from version 19.2.9 to 20.2.6 to use html editor with table options but insert table popup captions are diplayed as !TODO

### Results You Received:
When i click to insertTable toolbar button the title, label and captions on the popup shown as !TODO

### Results You Expected:
The result at adress https://js.devexpress.com/Demos/WidgetsGallery/Demo/HtmlEditor/Tables/Angular/Light/

### Environment Details:
Angular v10.2
DevExtreme Angular 20.2.6
    

![editor component html](https://user-images.githubusercontent.com/9213691/115395331-6c85e480-a1ec-11eb-953b-7a24d9aaa40d.PNG)

![insert_table](https://user-images.githubusercontent.com/9213691/115395532-a5be5480-a1ec-11eb-95d3-8d2c14391b7f.PNG)

**Comment by hakimio** [comment]
Translations for your language are missing. You can create a pull request with those missing translations.
