### ISSUE TITLE
dx-scheduler does not redraw correctly on date change if mode = "virtual" on latest beta

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#17170]
If you use mode="virtual" type="both" for dx-scheduler in the latest beta the resources do not redraw correctly when the date is changed. If you don't use mode="virtual" its OK. 

Screen capture Video enclosed

https://user-images.githubusercontent.com/4225690/115428883-bfff2f00-a1fa-11eb-8aeb-1f8825eb4e5d.mp4

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for reporting this issue. We reproduced this bug and we will fix this as soon as possible.
