### ISSUE TITLE
require() and webpack support?

### ISSUE THREAD

**Issue by zabojad** [DevExpress/DevExtreme#1719]
DevExtreme doesn't seem to be usable with `require()`nor Webpack. Is it something you plan to support in the future?

**Comment by dxbykov** [comment]
Hi,

Webpack is supported, check the corresponding [documentation article](https://js.devexpress.com/Documentation/Guide/Common/Modularity/#Link_Modules/Use_Webpack), please. You can also find an example [here](https://github.com/DevExpress/devextreme-examples).

**Comment by zabojad** [comment]
Hey @dxbykov !

Thanks for answering... Good catch, I did not see this doc earlier. While it looks promising, I can't make it work:
```
var $ = require('jquery');
require("devextreme/ui/pivot_grid");

var _devXtremInstance = $("#my-elt").dxPivotGrid({}).dxPivotGrid("instance");
```

I get at runtime: `Uncaught TypeError: jQuery(...).dxPivotGrid is not a function`. Any idea what is going wrong?

**Comment by dxbykov** [comment]
Have you managed to run the example with a button? Try to follow [these steps](https://github.com/DevExpress/devextreme-examples/tree/17_1/webpack-jquery). It works on my side.

**Comment by zabojad** [comment]
I've found a solution for `Uncaught TypeError: jQuery(...).dxPivotGrid is not a function` but now I have another problem: How can we add support for € currency? (right now it displays all amounts in $ but I would like € instead)

**Comment by zabojad** [comment]
When using the non-modularized version of DevExtreme, we were doing this:

```
            DevExpress.config({
                defaultCurrency: "EUR"
            });
```

But how can this be done now that we are using only the components/modules we need (in this case a PivotGrid)?

**Comment by dxbykov** [comment]
You can use the [core/config](https://js.devexpress.com/Documentation/Guide/Common/Modularity/#DevExtreme_Modules_Structure/core) module.

**Comment by zabojad** [comment]
Hi @dxbykov !
Thank you for your help!
I've tried this:
```
require("devextreme/core/config");

DevExpress.config({
        defaultCurrency: "EUR"
});
```
It gives me an error: `Uncaught (in promise) ReferenceError: DevExpress is not defined`

And this:
```
var config = require("devextreme/core/config");

config({
        defaultCurrency: "EUR"
});
```
It doesn't crash but doesn't have any effect neither (I still have USD everywhere in my PivotGrids)...

How should it be done?

**Comment by zabojad** [comment]
Done! It seems that we cannot change the currency without loading the proper Globalization data like [done there](https://github.com/DevExpress/devextreme-examples/blob/16_2/webpack-angular-globalize/src/localization.ts).

Thank you for your help!

**Comment by cesaralbuquerque** [comment]
> I've found a solution for `Uncaught TypeError: jQuery(...).dxPivotGrid is not a function` but now I have another problem: How can we add support for € currency? (right now it displays all amounts in $ but I would like € instead)

Hi @zabojad 
I have the same problem for "Uncaught TypeError: $(...).dxPivotGrid is not a function"
What's the solution that u find?
