### ISSUE TITLE
dxList is not implementing ControlValueAccessor for Angular Reactive Forms

### ISSUE THREAD

**Issue by arndwestermann** [DevExpress/DevExtreme#17216]
The dx-list is not implementing the `ControlValueAccessor` to work with Angular Reactive Forms. Setting the `ngDefaultControl` directive removes the error, but it still isn't displaying the list.

I've setup a Stackblitz-Project, for you to play around
https://stackblitz.com/edit/angular-ivy-gk5o6g

### Steps to Reproduce:

1.  Create a form with a `FormGroup` and a `new FormControl(['Some array item'])`
2.  Add appropriate field as `formControlName` to the dx-list

### Results You Received:
Error: No value accessor for form control with name: 'list'

### Results You Expected:
dx-list working with Angular Reactive Forms

### Environment Details:
Angular 11
Devextreme 20.2.6
Devextreme-Angular 20.2.6

**Comment by hakimio** [comment]
Why do you want to use list as form control in the first place? I am pretty sure you can only use [one of the editors](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxForm/Item_Types/SimpleItem/#editorType).

**Comment by arndwestermann** [comment]
I have two lists where I drag'n'drop items around. One of them i have to keep track of and do some validation, because the items get send in a form to the backend. So it would be awesome if I can just track it in a form. I guess i'll implement my own wrapper, if it is not possible on your side to implement that.
