### ISSUE TITLE
why onToolbarPreparing is called on createvnode? can we get the toolbar items dynamically from the remote server and push it in ontoolbarpreparing event?

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#17343]
why onToolbarPreparing is called on createvnode? can we get the toolbar items dynamically from the remote server and push it in ontoolbarpreparing event?
we are getting the toolbaritems during onMonted hook(vue). But the onToolbarPreparing is fired before onMonted. When we do that? During  onBeforeMont hook still failed

**Comment by onebalaban** [comment]
Hi,

Please submit a ticket to our [Support Center](https://supportcenter.devexpress.com/ticket/list) and describe the issue in detail and how to reproduce it. It would be also helpful if you attach a simple project to demonstrate the issue. This way, we will be able to find a solution much faster.
