### ISSUE TITLE
HtmlEditor i18n problem

### ISSUE THREAD

**Issue by oleg-barash** [DevExpress/DevExtreme#17345]
Hi everyone!
I meet problem with i18n. Component html editor doesnt pick localization strings for buttons in toolbar.
Steps:
1. Install devextreme (i use 21.1.2-beta) 
2. Setup i18n
3. Add HtmlEditor on page

Result:
Component localozed partially

![image](https://user-images.githubusercontent.com/4728300/116881408-e7f38700-ac2b-11eb-8296-7f486eee57b6.png)

I changed one line, and it worked for me: `text: buttonText` -> `text: localize(buttonText),`

https://github.com/DevExpress/DevExtreme/blob/af8685c7225392cc96129ef3c7d29c521071e4de/js/ui/html_editor/modules/toolbar.js#L542

**Comment by DokaRus** [comment]
Hi @oleg-barash 

Thank you for reaching out to us.
We fixed it in v21.1. Our next release (21.1.3) will contain a fix.
