### ISSUE TITLE
PieChart crush when use props contentRender in Tooltip

### ISSUE THREAD

**Issue by ghost** [DevExpress/DevExtreme#17458]
### Steps to Reproduce:

1. go to link https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/TooltipHTMLSupport/React/Light/
2. hover mouse on graph part of PieChart

### Results You Received:
PieChart disapered error in chromeDevTools: 
react-dom.development.js:7730 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
### Results You Expected:
Tooltip must show

### Environment Details:
     "devextreme": "20.2.7",
     "devextreme-react": "20.2.7",
     "react": "^17.0.2",

**Comment by LexDX** [comment]
Hi @alexeysanin,

The issue was fixed in the context of this report: https://supportcenter.devexpress.com/ticket/details/t998346/chart-gantt-diagram-the-notfounderror-failed-to-execute-removechild-on-node-the-node-to
