### ISSUE TITLE
Angular v12 compile error

### ISSUE THREAD

**Issue by Horizont77** [DevExpress/DevExtreme#17518]
### Steps to Reproduce:

1. ng new client-app
2. install devextreme devextreme-angular
3. adding devextreme settings :
![image](https://user-images.githubusercontent.com/12067363/118271029-12153680-b4c1-11eb-8224-c0e251c46060.png)
![image](https://user-images.githubusercontent.com/12067363/118271104-2822f700-b4c1-11eb-81e2-e88d1afa95f3.png)

4. npm run build:prod

### Results You Received:
![image](https://user-images.githubusercontent.com/12067363/118271158-3709a980-b4c1-11eb-83b1-25d8d90fda3d.png)

### Environment Details:
Visual Studio Code
DevExtreme: 20.2.6, 20.2.7
Angular V12

I think the problem is dx styles (theme.base.css). Without styles I don't get an error.

**Comment by babich-a** [comment]
Hi. It seems you use angular-cli to create an application. In this case, the `devextreme build` command (`build-themes`) does not work as expected. Moreover, it is not called. So, the theme.base.css file does not exist. I recommend adding devextreme to your project as described [here](https://js.devexpress.com/Documentation/Guide/Angular_Components/Getting_Started/Add_DevExtreme_to_an_Angular_CLI_Application/)

**Comment by Horizont77** [comment]
Hi, i tried everything again. but i still get the same error.

Without dx.light.css I can build (npm run build:prod) the project but with css I can't. I'll send you the project. 

[ng12-dx.zip](https://github.com/DevExpress/DevExtreme/files/6513726/ng12-dx.zip)

**Comment by babich-a** [comment]
Angular 12 has an issue with inlined images https://github.com/angular/angular-cli/issues/20760

**Comment by Horizont77** [comment]
Thank you for quick feedback

**Comment by dansabirov** [comment]
The same issue after updating my project to angular 12 (we are using devextreme 20.2.7)

**Comment by bryanvam** [comment]
also getting this issue

**Comment by sezerkorkmaz** [comment]
Angular.json's optimization section change inlineCritical to false

```
       "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": false
              },
```

**Comment by Adeyosola** [comment]
> Angular.json's optimization section change inlineCritical to false
> 
> ```
>        "optimization": {
>                 "scripts": true,
>                 "styles": {
>                   "minify": true,
>                   "inlineCritical": false
>                 },
>                 "fonts": false
>               },
> ```

This only works for production build. The error still persists in Angular v12 with ng build. (We're using devextreme 21.1.3)

**Comment by hamduc7** [comment]
Dear All, is there any solution on this error?

**Comment by MarjanGood** [comment]
> This issue was closed due to inactivity. If you found a bug or have a question about our product, [create a new issue](https://github.com/DevExpress/DevExtreme/issues) on GitHub or submit a ticket in our [Support Center](https://www.devexpress.com/Support/Center/).

hi everybody I have the same issue, Is there any solution for this issue?

**Comment by MarjanGood** [comment]
dear lexDX, 
I am trying to fix my error and this is my error while I am building my project,
 
√ Copying assets complete.
× Index html generation failed.
undefined:5:142920: property missing ':'

, but this solution doesn't work for me,
  "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": false
              },

The error still persists in Angular v12 with ng build. (We're using devextreme 21.1.3)
Is there any other solution to solve this error?
