### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by Horizont77** [DevExpress/DevExtreme#17642]
dart-sass has deprecated / in favor of math.div. Compiling scss files with many sass warnings.

### Steps to Reproduce:

1. npm update
2. npm run build-themes

### Results You Expected:

![image](https://user-images.githubusercontent.com/12067363/119637764-49b3a500-be16-11eb-8ac8-de25243959ae.png)

**Comment by LexDX** [comment]
Hi @Horizont77,

We are researching this issue in the context of this report: https://supportcenter.devexpress.com/ticket/details/t1002219/the-deprecation-warning-using-for-division-is-deprecated-and-will-be-removed-in-dart
Please add this ticket to your Favorites to receive updates on this issue.
