### ISSUE TITLE
Compiling Error: Typescript: TS7006: Parameter 'path/value' implicitly has an 'any' type

### ISSUE THREAD

**Issue by swagner30** [DevExpress/DevExtreme#17684]
Unfortunately there are some compiling issues. 

### Steps to Reproduce:

1. ng new client-app

2. install devextreme devextreme-angular
3. use some Component
4. run ng serve

### Results You Received:
![image](https://user-images.githubusercontent.com/58978329/119996218-c4272500-bfce-11eb-9739-a6e5ca5d686c.png)
![image](https://user-images.githubusercontent.com/58978329/119996787-5a5b4b00-bfcf-11eb-8ce6-d82a103ebc65.png)

### Environment Details:
Angular Version: 12.0.2
TypeScript Version: 4.2.4
Devextreme Version: 21.1.3

**Comment by hakimio** [comment]
PR #17699

**Comment by LexDX** [comment]
Hi @swagner30,

@hakimio is right. This PR should fix the issue. We merged it, so the issue should be fixed in the next release.
