### ISSUE TITLE
DevExtreme CLI "build-theme" installs "devextreme-themebuilder" every time

### ISSUE THREAD

**Issue by ghost** [DevExpress/DevExtreme#18165]
The DevExtreme CLI's "build-theme" command tries to install "devextreme-themebuilder" every time I run it.
I work at a place with a slow connection, so when this occurs, node times out, and the build fails.

![Screenshot_1](https://user-images.githubusercontent.com/47182539/123965911-336cac00-d9b5-11eb-9cf2-da326b817c21.png)

It also tries to install the 20.2.5 version when I'm using the 20.2.3 for the main DevExtreme package.

### Steps to Reproduce:

1. run `devextreme build-theme` with any options

### Results You Received:
The CLI tries to install `devextreme-themebuilder` every time without checking if it is already installed locally.

### Results You Expected:
Either :
* it asks if you want to install it as a dev dependency if it is not already
* throws an error if it is not installed

### Environment Details:
```
devextreme 20.2.3
devextreme-cli 1.2.11
npm 7.13.0
node 16.2.0
Windows 10 64bit 20H2
```

**Comment by softboy99** [comment]
same problem

**Comment by babich-a** [comment]
Hi @julesbrx `devextreme-cli` always installs the `devextreme-themebuilder` package because it can work with different versions of the `devextreme` package. It never uses the version installed in the project. However, it should not install the same version twice.

To resolve the issue, we need to reproduce it on our side. Could you please share the content of your json metadata file (you can remove any private info, such as `items` or private paths) and the structure of you project (folders' structure, package.json files).

**Comment by julesbrx** [comment]
Attached my package.lock.json file.
[lock.txt](https://github.com/DevExpress/DevExtreme/files/6769777/lock.txt)

**Comment by babich-a** [comment]
> 
> 
> Attached my package.lock.json file.
> [lock.txt](https://github.com/DevExpress/DevExtreme/files/6769777/lock.txt)

I mean themebuilder metadata dx.generic....json

**Comment by ghost** [comment]
My bad.
[dx.generic.myapp.txt](https://github.com/DevExpress/DevExtreme/files/6769811/dx.generic.myapp.txt)

**Comment by babich-a** [comment]
> 
> 
> My bad.
> [dx.generic.myapp.txt](https://github.com/DevExpress/DevExtreme/files/6769811/dx.generic.myapp.txt)

>It also tries to install the 20.2.5 version when I'm using the 20.2.3 for the main DevExtreme package.

Your config contains 20.2.5 version. Auto-detection does not work in this case. As for double-install we'll continue to check.

**Comment by babich-a** [comment]
It seems I reproduced the issue with a simple project.

```
{
  "name": "devextreme-cli-issue",
  "version": "1.0.0",
  "scripts": {
    "d": "devextreme build-theme"
  },
  "dependencies": {
    "devextreme": "^21.1.3"
  },
  "devDependencies": {
    "devextreme-cli": "latest"
  },
  "author": "",
  "license": "ISC"
}
```

If I run

```
npm i
npm run d
npm run d
```

devextreme-themebuilder is installed only on the first build (first run of `npm run d`). For the second time it uses the installed version of the package.

But if I run

```
npm i
npm run d
npm i
npm run d
```

it is installed both times `npm run d` is launched.
Maybe you mean a different issue?
I think we can consider including the `devextreme-themebuilder` package in the peerDependencies of `devextreme-cli` and make it use the installed version.

**Comment by ghost** [comment]
> 
> 
> > My bad.
> > [dx.generic.myapp.txt](https://github.com/DevExpress/DevExtreme/files/6769811/dx.generic.myapp.txt)
> 
> > It also tries to install the 20.2.5 version when I'm using the 20.2.3 for the main DevExtreme package.
> 
> Your config contains 20.2.5 version. Auto-detection does not work in this case. As for double-install we'll continue to check.

I'll upgrade my version to 20.2.5 to fix the issue.


> But if I run
> 
> ```
> npm i
> npm run d
> npm i
> npm run d
> ```
> 
> it is installed both times `npm run d` is launched.
> Maybe you mean a different issue?

This is my issue. `npm i` is run every time my project is built, and since `npm i` uses cache, it's fast, but when the builder is installed, somehow the cache is not used, and it times out.

> I think we can consider including the `devextreme-themebuilder` package in the peerDependencies of `devextreme-cli` and make it use the installed version.

That would be nice.

**Comment by babich-a** [comment]
>  `npm i` uses cache

@julesbrx do you use some special settings for the npm cache?

**Comment by ghost** [comment]
This is a clean install so its all default settings. I'll investigate.

**Comment by babich-a** [comment]
Starting from 1.2.21 `devextreme-cli` try to find `devextreme-themebuilder` in the current working folder. So, if you have this package in your `node_modules` folder and the version is correct `devextreme-cli` will use it.
