### ISSUE TITLE
You are running production build of Inferno in development mode. Use dev:module entry point.

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#18222]
Hi,
the warning give hint for use dev:module enty point. But how to do that?
environment:
vue 3.1.4 +  vite 2.4.0;
devexreme 21.1.4

**Comment by Bykiev** [comment]
@softboy99, hi!

You should point to 'inferno/dist/index.dev.esm.js' in dev environment. In angular we're using custom webpack config:

```
module.exports = {
  resolve: {    
    alias: {
      'inferno': 'inferno/dist/index.dev.esm.js'
    }
  }
};
```

**Comment by softboy99** [comment]
Hi,
How to do that in vite?

**Comment by MikeVitik** [comment]
You can simply ignore this warning. The development build mode is only needed for internal use.
