### ISSUE TITLE
Cannot read property 'endDate' of undefined

### ISSUE THREAD

**Issue by lennygir** [DevExpress/DevExtreme#18310]
Hello, 
I'm encountering some issues wit devextreme scheduler.
I always have the issue :

jQuery.Deferred exception: Cannot read property 'endDate' of undefined

![image](https://user-images.githubusercontent.com/50408139/125413994-3710be9f-cd39-4d89-abc1-97b2500e16e9.png)

This error occurs even when my list of appointment is empty. I use the version 21.0.4 with aspx and vb.

The error doesn't show up when i replace the "DevExpress.data.AspNet.createStore" by the list that I obtain with my console log of api response.

**Comment by andrewmakarov** [comment]
Hello,

Please submit a ticket to our [Support Center](https://devexpress.com/sc). In the ticket description, attach a test project to demonstrate your implementation and describe steps to reproduce the issue. We'll review them to find the most suitable solution.
