### ISSUE TITLE
Typescript definition for `CustomDialogOptions` missing `popupOptions` property

### ISSUE THREAD

**Issue by alfeg** [DevExpress/DevExtreme#18366]
Typescript definition for `CustomDialogOptions` missing `popupOptions` property

### Steps to Reproduce:

Using following typescript snippet
```typescript
import { custom } from "devextreme/ui/dialog"
const dialog = custom({
        popupOptions: {
            position: {
                my: "center",
                at: "center",
                of: "#app",
            },
        },
}
})
```

### Results You Received:
Typescript error 
```
Argument of type '{ title: any; messageHtml: any; showTitle: boolean; buttons: { text: string; type: "back" | "danger" | "default" | "normal" | "success"; visible: boolean; onClick(): boolean; }[]; dragEnabled: false; popupOptions: { ...; }; }' is not assignable to parameter of type 'CustomDialogOptions'.
  Object literal may only specify known properties, and 'popupOptions' does not exist in type 'CustomDialogOptions'.ts(2345)
```

### Results You Expected:
No errors, as custom dialog accepts this property: https://github.com/DevExpress/DevExtreme/blob/601b0c7f495df682f59f5545ddafbef80d1d50ee/js/ui/dialog.js#L174

### Environment Details:
devextreme: 21.1.4

**Comment by Bykiev** [comment]
Hi @alfeg, 

according to the [docs](https://js.devexpress.com/Documentation/ApiReference/Common/Utils/ui/dialog/#customoptions), custom dialog doesn't containt `popupOptions` property (at least for public). 

For you purpose, consider using [Popup](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxPopup/) with custom template

**Comment by alfeg** [comment]
@Bykiev nice catch. Have been using this several years, haven't realize it's internal API.

We need to show confirmation popup from non .vue code...
