### ISSUE TITLE
Search to accent insensitive and RegExp

### ISSUE THREAD

**Issue by Iskander1220** [DevExpress/DevExtreme#18455]
Hi, and sorry for my english!

How to combine these two functions for insensitivity to accents and search for regular expressions? Since they do not work together.

-------------------------------------------

//regex
function gCalculateFilterExpression (value, selectedFilterOperations, target, self) {  
        if (target === "filterRow") {
            return [function(dataItem) {
        var pattern = new RegExp(value, 'i');
        if (dataItem[self.dataField].match(pattern)) {  
                    return true;  
                }  
                else {
                    return false;  
                }  
            }, "=", true];  
        }  
        else {  
            return self.defaultCalculateFilterExpression.apply(self, arguments);  
        }  
    }

-------------------------------------------

//accent
calculateFilterExpression: function(value, selectedFilterOperation, target){  
    var getter = function(data) {  
      return data['bbb'].normalize('NFD').replace(/[\u0300-\u036f]/g,"");  
    };  
     value = value.normalize('NFD').replace(/[\u0300-\u036f]/g,"");  
     return [getter, selectedFilterOperation || "contains", value];  
}

**Comment by onebalaban** [comment]
Hello,

Please submit a ticket to our [Support Center](https://devexpress.com/sc). In the ticket description, attach a test project to demonstrate your implementation and describe steps to reproduce the issue. We'll review them to find the most suitable solution.
