### ISSUE TITLE
dxSortable, how to get values from card?

### ISSUE THREAD

**Issue by carlospereira21** [DevExpress/DevExtreme#18870]
Hello, i started now to using this lib in js and jquery, and i have troble to get some informations that come from card, after an event like onDragEnd.

How i get a value from card ? some value like, name, id, the drag action to know what column i dragged my item.
When the action end, all that i recieve is alot of information did i don't now how to use.

![image](https://user-images.githubusercontent.com/7553123/130372922-a141cf63-732c-4e57-be9d-a03a72c54bcb.png)

### Steps to Reproduce:
https://codepen.io/carlos-eduardo-pereira/pen/VwWZgYb

### Results You Received:
![image](https://user-images.githubusercontent.com/7553123/130372850-006d84b0-9ae4-4278-a12b-48e70282bb2f.png)

### Results You Expected:
I expted access my card values with obj, like card.item.id or access some obj inside all this return to get actual column my card is in.

Can anyone help-me pleasE?

**Comment by onebalaban** [comment]
Hi,

Our channel for technical inquiries is Support Center: [https://devexpress.com/sc](https://devexpress.com/sc)
Please submit a ticket there with the description above and a test project (CodePen). We'll research it and try to find a solution.
