### ISSUE TITLE
DateBox only 5 weeks, but need 6?

### ISSUE THREAD

**Issue by n0isy** [DevExpress/DevExtreme#18985]
In August'21?
Browser Firefox 91.0.2

![изображение](https://user-images.githubusercontent.com/8371968/131360267-7bb1558c-35f8-4593-a962-9a68bf73430e.png)

**Comment by n0isy** [comment]
In Chrome
![изображение](https://user-images.githubusercontent.com/8371968/131360716-1d94f0b6-ea36-473f-ac7d-8d73430375f2.png)

**Comment by hakimio** [comment]
Your custom theme seems to be broken. It works as expected with standard themes:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Calendar/Overview/Angular/Light/
