### ISSUE TITLE
DxAccordion onSelectionChanged event documentation is missing information

### ISSUE THREAD

**Issue by jakehockey10** [DevExpress/DevExtreme#19039]
### Steps to Reproduce:

1. Visit the following documentation pages: 
  - https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxAccordion/Events/#selectionChanged
  - https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxAccordion/Configuration/#onSelectionChanged
2. Handle the event and log out event args to the console
3. See issue

### Results You Received:

There are `addedItems`, `component`, `element`, and `removedItems` in the event args

### Results You Expected:

The documentation pages are missing the documentation for the full list of event arguments.  The first page listed above doesn't have any details or links to further documentation like the rest of the events on that page.  The second page listed above doesn't mention any event args beyond `addedItems`.

### Environment Details:

version 21.1

I just wanted to point out the documentation needing an update so that other users can know about the event arguments that are there.

**Comment by novsstation** [comment]
Hi,

Thank you for your patience.
We researched this issue and found out that this is a mistake in our documentation.
Thank you for bringing our attention to this. The updated version of our documentation will be published soon.

Please feel free to contact us if you have any other questions. We will do our best to help you.
