### ISSUE TITLE
DevExpress consumes more memory - ng build

### ISSUE THREAD

**Issue by aravindfz** [DevExpress/DevExtreme#1912]
### Steps to Reproduce:

1. Create a repository with starter files
2. Install `devexpress` node_modules
3. Import any one module and add to imports array of AppModule
4. `ng build` response are as below

![image](https://user-images.githubusercontent.com/22231525/32692996-baf956ce-c748-11e7-9f19-0a51952a1dd2.png)
 
Alternatively, removed the module declaration and ran `ng build` it results in very few memory
![image](https://user-images.githubusercontent.com/22231525/32693002-dbbd0fae-c748-11e7-84e6-7abf9ad26812.png)

**Comment by dxvladislavvolkov** [comment]
Hello @aravindfz ,
 
To reduce the size of the bundle, build it in the production mode as shown below:
`ng build --prod -sc=true`
 
If you want to use the developer mode, use long paths to modules. For example:
`import { DxButtonModule } from 'devextreme-angular/ui/button';`

If this does not help, please submit a ticket regarding this issue in our [Support Center](https://www.devexpress.com/support/center). We will do our best to help you.
