### ISSUE TITLE
SpeedDialAction causes Deprecation warning in 21.2.2-alpha

### ISSUE THREAD

**Issue by PaulTodd** [DevExpress/DevExtreme#19483]
### Steps to Reproduce:

1. Include SpeedDialAction on page

### Results You Received:
W0001 - dxPrivateComponent0 - 'elementAttr' option is deprecated in 21.2. Use the "wrapperAttr" option instead. See:
http://js.devexpress.com/error/21_2/W0001

### Results You Expected:

No deprecated warning when using SpeedDialAction

### Environment Details:
    "devextreme": "^21.2.2-alpha-21246-1323",
    "devextreme-react": "^21.2.2-alpha-21246-1323",

**Comment by AlisherAmonulloev** [comment]
I submitted a public bug report in our Support Center: https://supportcenter.devexpress.com/ticket/details/t1033961/speeddialaction-the-w0001-dxprivatecomponent0-elementattr-option-is-deprecated-warning
We will update the report once we have any news. Thank you for your input!
