### ISSUE TITLE
Add box-plot in Chart

### ISSUE THREAD

**Issue by agafonovslava** [DevExpress/DevExtreme#19608]
https://github.com/DevExpress/DevExtreme/issues/8278

@alexanderPolosatov

**Comment by alexanderPolosatov** [comment]
Hello Slava,
We agree that the Box Plot chart would be a good addition to DevExtreme but it's not yet in our current development [Roadmap](https://js.devexpress.com/Roadmap/). We are unlikely to add it this year or next. I’ve registered your request for future development plans. Once we decide to implement it, you will find a corresponding section on our Roadmap.



Meanwhile, let me share one more workaround apart from the one we described in the original thread. You can combine the [CandleStick](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxChart/Series_Types/CandleStickSeries/)and [RangeBar](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxChart/Series_Types/RangeBarSeries/) series on a single pane. If you require our further assistance with this, feel free to submit a ticket to our Support Center: [https://devexpress.com/ask/](https://devexpress.com/ask/).
