### ISSUE TITLE
Virtual scrolling is not really virtual and causes DOM to "explode"

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#1961]
### Steps to Reproduce:

1.  Open virtual scrolling demo (Demo/DataGrid/VirtualScrolling)
2.  Open DOM inspector
3.  Expand "table" with "dx-datagrid-table dx-datagrid-table-fixed dx-datagrid-table-content" class node
4. Scroll the data grid using **mouse wheel**
5. Watch as loads of extra "tbody" elements are added to the "table" node

### Results You Received:
![dev-extreme-virtual-scrolling_geq33q](https://user-images.githubusercontent.com/768105/32881674-4aa53ec0-cab2-11e7-88e8-e79bba7fd48f.gif)

### Results You Expected:
No more than 2 "tbody" elements

### Environment Details:
Chrome 62
Latest stable DevExtreme ( 17.1?)

**Comment by NickMitrokhin** [comment]
Hi Hakimio,

We are aware of this behavior and will improve it in one of our future versions. Please take a look at the [It takes much time to show dxDataGrid with large data at runtime](https://www.devexpress.com/Support/Center/Question/Details/T519056) ticket where we discussed a similar issue.

**Comment by hakimio** [comment]
It should not be closed until you have proper fix for this major memory leak.
Basically, you don't have proper virtual scrolling implementation and should not advertise that you have one.
