### ISSUE TITLE
DataGrid: Checkbox needs to be displayed when adding a new record

### ISSUE THREAD

**Issue by zoey-jr** [DevExpress/DevExtreme#19666]
### Steps to Reproduce:

1. 
2. 
3.

**Comment by AlisherAmonulloev** [comment]
Your scenario is not clear. Would you please describe it and the issue you encountered in greater detail?

**Comment by zoey-jr** [comment]
In the multiple mode, when adding a record, the new record does not display the checkbox, but I need to display the checkbox at this time and do some checking. How can I achieve it。

**Comment by zoey-jr** [comment]
<img width="1020" alt="截屏2021-10-25 下午5 12 11" src="https://user-images.githubusercontent.com/42338699/138669751-5e99ed4a-eea1-4ebf-bba2-7e1a850e4627.png">

**Comment by AlisherAmonulloev** [comment]
DataGrid does not support this functionality. Selected rows do not have a data field reflecting a row's selection state. Hence, we do not show the check box for the new item row. You can select a row after it was added by using the onRowInserted callback:
```js
onRowInserted: function(e) {
   if(your custom condition){
     e.component.selectRows([e.key], true);
   }
},
```
