### ISSUE TITLE
DxTreeViewNode deprecated

### ISSUE THREAD

**Issue by foegen-juan** [DevExpress/DevExtreme#19812]
### Steps to Reproduce:

1. code within a selection changed
2. using it to respond with type safety to the action
3.     public cartTypeItemSelectionChanged(event: any) {
        if (event && event.node && event.component) {
            const treeView: dxTreeView = event.component as dxTreeView;
            const treeNode: dxTreeViewNode = event.node as dxTreeViewNode;

            if (treeNode.selected) {
                if (treeNode.children && treeNode.children.length > 0) {

2. 
3.

**Comment by LexDX** [comment]
Hi @foegen-juan,

Currently, we are in the process of enhancing our TypeScript definitions, and we are making significant changes in our code. I recommend you check the following GitHub issue for more details: [Internal Types](https://github.com/DevExpress/DevExtreme/issues/17885). Also, in this GitHub issue, you will find updated definitions and will be able to share your current code and the issue. Our team will be happy to assist you in this thread.

**Comment by IlyaKhD** [comment]
@foegen-juan, use the `Node` type instead. This replacement was added in v21.1.6.

**Comment by foegen-juan** [comment]
Thanks.  That works, but defining something like dxNode would cause a lot less namespace collisions than something as generic as Node.
