### ISSUE TITLE
Latest  v21.2.3 Issues with Speed Dial Action

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#19938]
In the latest release using speed dial action buttons in Angular v12.2 causes console errors

**HTML Template**
<dx-speed-dial-action
    icon="download"
    [label]="'Generic.export' | translate"
    (onClick)="exportUsers()"
></dx-speed-dial-action>

### Console Output

vendor.js:166801 W0001 - dxPrivateComponent4 - 'elementAttr' option is deprecated in 21.2. Use the "wrapperAttr" option instead. See:
http://js.devexpress.com/error/21_2/W0001
how 41 more frames
vendor.js:166801 W0001 - dxPrivateComponent4 - 'elementAttr' option is deprecated in 21.2. Use the "wrapperAttr" option instead. See:
http://js.devexpress.com/error/21_2/W0001
Show 28 more frames
vendor.js:166801 W0001 - dxPrivateComponent5 - 'elementAttr' option is deprecated in 21.2. Use the "wrapperAttr" option instead. See:
http://js.devexpress.com/error/21_2/W0001

**Comment by AlisherAmonulloev** [comment]
We are aware of this issue: https://supportcenter.devexpress.com/ticket/details/t1033961/speeddialaction-the-w0001-dxprivatecomponent0-elementattr-option-is-deprecated-warning
Please add the ticket to your Favorites to be notified of our progress.
