### ISSUE TITLE
DxButton: dxTemplate breaks submit behavior

### ISSUE THREAD

**Issue by arndwestermann** [DevExpress/DevExtreme#19973]
Hello folks,

I just updated to devextreme and devextreme-angular to v21.2.3 and now my login form doesn't work properly.

My form looks something like this

```
<form [formGroup]="loginFormGroup" (ngSubmit)="login()">
	<dx-text-box formControlName="username"></dx-text-box>
	<dx-text-box mode="password" formControlName="password"></dx-text-box>

	<dx-button type="success" [width]="100" [useSubmitBehavior]="true">
		<div *dxTemplate="let data of 'content'">
			<dx-load-indicator *ngIf="loading$ | async" class="button-indicator"> </dx-load-indicator>
			<span class="dx-button-text">{{ 'Login' }}</span>
		</div>
	</dx-button>
</form>
```

This results in neither enter key hit nor button click to fire the submit behavior. 
Unfortunately I couldn't spin up a stackblitz repo, cause adding devextreme to a stackblitz with angular resulting in nearly infinit compile time. So i got a bit creative and reproduced it on your [button demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Button/PredefinedTypes/Angular/Light/)

Just copy'n'paste the following

HTML

```
<div class="buttons-demo">
 <form [formGroup]="loginFormGroup" (ngSubmit)="login()">
		<dx-text-box formControlName="username"></dx-text-box>
		<dx-text-box mode="password" formControlName="password"></dx-text-box>

		<dx-button type="success" [width]="100" [useSubmitBehavior]="true">
			
			<div *dxTemplate="let data of 'content'">
				<span class="dx-button-text">Login</span>
			</div>
		</dx-button>
	</form>
</div>
```

TS

```
import { Component, NgModule, enableProdMode } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { DxButtonModule, DxTextBoxModule } from 'devextreme-angular';
import notify from 'devextreme/ui/notify';

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

@Component({
  selector: 'demo-app',
  templateUrl: 'app/app.component.html',
  styleUrls: ['app/app.component.css'],
})

export class AppComponent {
  capitalize = (text) => text.charAt(0).toUpperCase() + text.slice(1);

  click = (e) => {
    const buttonText = e.component.option('text');
    notify(`The ${this.capitalize(buttonText)} button was clicked`);
  };

  constructor() { }

public loginFormGroup = new FormGroup({
		username: new FormControl('', Validators.required),
		password: new FormControl('', Validators.required),
	});

public login() {
		const username = this.loginFormGroup.get('username').value;
		const password = this.loginFormGroup.get('password').value;
		console.log(username, password);
	}
}

@NgModule({
  imports: [
    BrowserModule,
    DxButtonModule,
    DxTextBoxModule,
    ReactiveFormsModule
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})

export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

```

### Steps to Reproduce:

1.  Create a form
2. Add <div *dxTemplate="let data of 'content'"></div> to the DxButton
2. Enable the useSubmitBehavior on DxButton 
3. Submit the Form
4. Watch the console

### Results You Received:
Form doesn't submit

### Results You Expected:
Form to submit on either enter key or button click

### Environment Details:
Angular v12.x
devextreme v21.2.3
devextreme-angular v21.2.3

**Comment by LexDX** [comment]
Thank you for the report, @arndwestermann. We are aware of this issue and are researching it in this ticket: [Form - Button lost its customization when the template option is specified in v.21.2.3 in Vue and Angular](https://supportcenter.devexpress.com/ticket/details/t1041677/form-button-lost-its-customization-when-the-template-option-is-specified-in-v-21-2-3-in). You can add it to your favorite list to receive notifications of the progress.
