### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by ghost** [DevExpress/DevExtreme#20]
Are there any suggestions/examples on how to integrate the devextreme components with the react.js view renderer?

**Comment by NickMitrokhin** [comment]
Hi,

Please take a look at the [Integration with ReactJS](https://www.devexpress.com/Support/Center/Question/Details/T360499) ticket where we discussed a similar issue.

**Comment by lukyanovas** [comment]
Hi,
You can use npm to try the alpha version of [DevExtreme React wrappers](https://www.npmjs.com/package/devextreme-react). Please give us any feedback by creating an issue on [GitHub](https://github.com/DevExpress/devextreme-react)
