### ISSUE TITLE
[Suggestion] Optimize SASS import

### ISSUE THREAD

**Issue by cesco69** [DevExpress/DevExtreme#20057]
Importing the root style

```css
@import "~devextreme/scss/bundles/dx.material.blue.light";
```

this style also import

```css
@use "../widgets/material";
```

this style also import

```css
@use "./scheduler";
```
Now, if i don't want the scheduler, I can't disable the import...

A possible solution is make the import of the widget conditionally.

Just wrap your styles in the optional file as a sass mixin:

```css
@mixin scheduler {
    // styles here
}
```

Then use the if-statement of sass to include the mixin

```css
@import "scheduler";
@if $importScheduler == true {
    @include scheduler;
}
```

at this point the developer can exclude some widget, eg.:

```css
$importScheduler: false;

@import "~devextreme/scss/bundles/dx.material.blue.light.scss";
```

**Comment by nigrosimone** [comment]
Really good idea. Now the final CSS is very large.
