### ISSUE TITLE
DataGrid: Virtual scrolling with duplicate keys

### ISSUE THREAD

**Issue by shant1988** [DevExpress/DevExtreme#20725]
When virtual scrolling is enabled and duplicate keys are present, the DataGrid seems to re-render constantly.
Workaround: Set the DataGrid option "scrolling.legacyMode" to true.

### Steps to Reproduce:
React:
1. Go to: https://codesandbox.io/s/data-grid-duplicate-keys-w-virtual-scrolling-hhy8w?file=/App.js
2. Click on "Edit" in either row

jQuery:
1. Go to: https://codepen.io/s-bay/pen/vYeZLLp
2. Click on "Edit" in either row
3. Try to edit the "First Name" input

### Results You Received:
React: Editor popup continuously opens and closes
jQuery: Unable to edit "First Name" input

### Results You Expected:
DataGrid should behave like it does when the option "scrolling.legacyMode" is true

### Environment Details:

DevExtreme: 21.2.4
DevExtreme-React: 21.2.4

**Comment by onebalaban** [comment]
Hello,

The keys MUST be unique in order for editing, sorting, filtering, etc. to work properly. Could you please elaborate on how such keys have appeared in your data source?
