### ISSUE TITLE
Need locale option for ODataStore when using "filterToLower: true" 

### ISSUE THREAD

**Issue by sceyhuns** [DevExpress/DevExtreme#20747]
When using ODataStore with option "filterToLower: true" it lowers filters with js default locale, but we need to set locale maually.

**Comment by onebalaban** [comment]
Hi,

Could you please submit a ticket to our [Support Center](https://devexpress.com/ask) and attach a [test project](https://community.devexpress.com/blogs/ctodx/archive/2009/01/08/a-request-for-simple-example-programs.aspx) to demonstrate the issue? We'll research it and do our best to find a solution.
