### ISSUE TITLE
[Question] Tailwind Theme

### ISSUE THREAD

**Issue by mrparag94** [DevExpress/DevExtreme#20828]
Any plan to make a tailwind Theme for DevExtrem...?

**Comment by onebalaban** [comment]
Hi,

Could you please elaborate on this? Do you mean the [Tailwind](https://tailwindcss.com/) support or something else?

**Comment by mrparag94** [comment]
@it's kinda like this you have support for talwind and also have a default ui theme (built in)

**Comment by onebalaban** [comment]
We don't have a pre-built Tailwind theme for our components. As for Tailwind support, our components use their own CSS rules and don't depend on third-party CSS frameworks like Bootstrap, Tailwind, etc. In the meantime, you can add Tailwind to your project and use its CSS classes to stylize markup/elements of DevExtreme components.
