### ISSUE TITLE
OnRowPrepared is being called repeatedly to the point of crashing the page.

### ISSUE THREAD

**Issue by gabestrom** [DevExpress/DevExtreme#21066]
**Package versions:**

    devexteme version: 21.2.4
    devextreme-react version: 21.2.4

**Steps to reproduce:**

- I have reproduced the issue here: https://codesandbox.io/s/t1064490-forked-i91bl?file=/App.js
- To repo change scroll mode from normal to virtual and watch the console logs.

**Current behavior:**
When loading the page if virtual scrolling is enabled OnRowPrepared is immediately thrown into an infinite loop.
I have noticed that part of this seems to be from duplicate keys being provided by the data. However in version 21.1.4 I did not have any issue with this so maybe something has changed?

**Expected behavior:**
Datagrid is able to render even when provided with duplicate keys and OnRowPrepared is not causing the page to crash.

**Screenshots:**
![datagridCrash](https://user-images.githubusercontent.com/59144199/152242244-bc49fc0e-d5ef-4b6c-8fa0-c3db71cadbce.gif)

**Comment by onebalaban** [comment]
Hello,

Keys MUST be unique in order for editing, sorting, filtering, etc. to work properly. Please refer to the ticket you recently submitted (T1064490).
