### ISSUE TITLE
Problem With CustomStore Remove

### ISSUE THREAD

**Issue by MattiaFontana997** [DevExpress/DevExtreme#21170]
### Steps to Reproduce:

1.  Create CustomStore
2.  Create Remove  with Key Method

### Results You Received:
Can't Bind PromiseLike<Void> to Promise<void>

### Results You Expected:
Promise<void>

### Environment Details:

Version 21.2.5
Firefox 
Windows 10

**Comment by onebalaban** [comment]
Hi,

Please submit a ticket to our [Support Center](https://devexpress.com/sc). Attach a test project to the ticket to demonstrate the issue. We'll review it and do our best to find a solution.
