### ISSUE TITLE
Scheduler appointment collector not honoring allowDragging

### ISSUE THREAD

**Issue by jaggedaz** [DevExpress/DevExtreme#2149]
### Steps to Reproduce:

Issue can be reproduced in this CodePen: https://codepen.io/jaggedaz/pen/ZaPRmE

1. Configure the Scheduler to disable appointment dragging.
2. Add several events to a single day so that the appointment collector drop-down is generated.
3. Click the "More" item to show the appointment collector drop-down.
4. Click and drag one of the appointments out of the collector onto the calendar.

### Results You Received:

Allows the user to begin dragging the appointment.

### Results You Expected:

Should not allow the user to drag the appointment.

### Environment Details:

devexteme version: 17.2.3

**Comment by KsyushaM** [comment]
Hello,
We will process this issue in the context of the following Support Center thread: https://www.devexpress.com/Support/Center/Question/Details/T584003/scheduler-appointment-collector-not-honoring-allowdragging
