### ISSUE TITLE
Scheduler appointment collector - can't cancel appointment click or double click event

### ISSUE THREAD

**Issue by jaggedaz** [DevExpress/DevExtreme#2150]
### Steps to Reproduce:

The issue can be re-created with this CodePen: https://codepen.io/jaggedaz/pen/YEgvme

1. Configure the Scheduler so that the onAppointmentClick and onAppointmentDblClick event handlers set event.cancel to true.
2. Add several events to a single day so that the appointment collector drop-down is generated.
3. Click the "More" item to show the appointment collector drop-down.
4. Click or double click one of the appointments.

### Results You Received:

Displayed the appointment detail pop-up.

### Results You Expected:

Should do nothing, should not display the appointment detail pop-up.

### Environment Details:

devextreme 17.2.3

**Comment by MarinaRukavitsyna** [comment]
Hello,
We will process this issue in the context of the following Support Center thread:
https://www.devexpress.com/Support/Center/Question/Details/T584004/scheduler-appointment-collector-can-t-cancel-appointment-click-or-double-click-event
