### ISSUE TITLE
popup elementAttr deprecation

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#22636]
Hi, since popup `elementAttr` prop is deprecated it's not possible to get dataGrid editing popup instance via `id` property. It needed to enable/disable popup fullScreen mode with toolbar buttons (similar to maximize/minimize in Windows). Is any way to get editing popup another way?

**Comment by AlisherAmonulloev** [comment]
You can use the wrapperAttr option instead:
```js
 wrapperAttr: {
    class: "custom-class"
},
```
