### ISSUE TITLE
improve typescript typing

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#22635]
Hi, to get the component in Angular the recommended way is casting component instance to specific type:

`const popup = Popup.getInstance(popupElement) as Popup;`

But in strict mode it will cause such error: 

> Conversion of type 'DOMComponent<Properties>' to type 'dxPopup<Properties>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

I believe it should be a better way than casting to unknown. It'll be better if `getInsance` method will return `Popup` instead of `DomComponent<Properties>`

**Upd**: with PivotGrid there is another error:

>  Type 'DOMComponent<Properties>' is missing the following properties from type 'dxPivotGrid': bindChart, exportToExcel, getDataSource, getFieldChooserPopup, and 4 more.

with DataGrid:

> Type 'DOMComponent<Properties>' is missing the following properties from type 'dxDataGrid<any, any>': addColumn, addRow, clearGrouping, collapseAll, and 63 more.

**Comment by artem-kurchenko** [comment]
Hi @Bykiev ,

Thank you for the report. I created a ticket in our Support Center: [t1136071](https://supportcenter.devexpress.com/ticket/details/t1136071/the-conversion-of-type-domcomponent-to-type-x-may-be-a-mistake-because-neither-type)

Please refer to it for further correspondence.
