### ISSUE TITLE
DataGrid RowFilter OData Lookup Bug

### ISSUE THREAD

**Issue by necipsunmaz** [DevExpress/DevExtreme#22800]
# Bug Report

Hi, we upgraded devextreme-angular 21 to 22 with Angular 13 major version. But all pages grid row filter doesn't work expected. I created sample app for this issue, please check it.

Thanks.

**Package versions:**

    devexteme version: 22.1.5
    devextreme-angular version: 22.1.5
    angular version: 13.3.0

**Steps to reproduce:**
Sandbox Example App: https://m894v5.csb.app/
Sandbox Example App Code: https://codesandbox.io/s/m894v5

**Current behavior:**
![Screen Recording 2022-09-27 at 12 28 14](https://user-images.githubusercontent.com/20782752/192491261-141b3be2-8e91-48fe-8beb-9e8df43df5dc.gif)

**Comment by artem-kurchenko** [comment]
Hi @necipsunmaz ,

We introduced the new [syncLookupFilterValues](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/#syncLookupFilterValues) property that additionally fetches records for proper calculation. You can disable it to avoid this error.

If your usage case is more specific please submit a ticket in the [Support Center](https://supportcenter.devexpress.com/ticket/create) 

We'll perform detailed research
