### ISSUE TITLE
TreeView - Parent node loses selection after search

### ISSUE THREAD

**Issue by sometimesElen** [DevExpress/DevExtreme#2284]
This issue can be reproduced with this [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeView/TreeViewWithSearchBar/jQuery/Light/) by adding the following options to TreeView:
`selectNodesRecursive: false,
searchEnabled: true`

Steps to reproduce:
1. Set `selected: true` for any parent node.
2. Search something via the search box.
3. Remove a search value from the search box.
4. The preselected item becomes unselected.

**Comment by ajaybhasy-experion** [comment]
I too have the same issue. This can be seen in this [demo](https://codepen.io/ajaybhasy/pen/MrKEMg).

The **parent element Key** is selected initially on loading but **loses selection after searching**.

**Comment by sometimesElen** [comment]
Fixed by #2344
