### ISSUE TITLE
[feat] TreeList - export to excel

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#22884]
Export to Excel is very old issue, but still is not in a roadmap. I don't know why it's so difficult to implement, but it's still not in TODO list.

**Comment by markallenramirez** [comment]
Hello,

We consider TreeList export an essential feature, and it is definitely a part of our long-term development strategy. We'll update our [Roadmap](https://js.devexpress.com/Roadmap) for next year if we decide to work on this feature.
