### ISSUE TITLE
[feat] DateBox - allow selecting ranges

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#22885]
Many date controls support selecting date range, but not DevExtreme. Let's make a poll and see if'll be useful for anyone.

**Comment by artem-kurchenko** [comment]
Hi,

Yes, we realize that this feature will be useful out of the box.  We'll update our [Roadmap ](https://js.devexpress.com/Roadmap)for next year if we decide working on this feature.
