### ISSUE TITLE
[feat] Popup - add maximize/restore and collapse/expand buttons in toolbar

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#22883]
Hi, it'll be very useful if you'll add maximize/restore and collapse/expand (to right/left corner) buttons on popup toolbar. While it's technically possible to implement it by myself, it'll be more easy to use. Let's make a poll and see results.

**Comment by AlisherAmonulloev** [comment]
Thank you for your suggestion. I forwarded it to the team.
