### ISSUE TITLE
Html editor toolbar predefined items have wrong hint on remote server

### ISSUE THREAD

**Issue by regazzoj** [DevExpress/DevExtreme#23135]
# Bug Report
I have a bug on a component using HTML Editor.
I am using some toolbar items, and to do so, I am just using the predefined items with predefined hints.
The problem is that on my local computer, toolbar items have a correct hint provided by default, but when my changes are pushed to the remote server, all hints become "TODO"...
Is it a misconfiguration ? Or a bug somewhere ?

**Package versions:**

    devexteme version: 21.1.6
    devextreme-angular version: 21.1.6

**Current behavior:**
When moving my mouse onto "Redo" toolbar button of HTML editor, a tooltip "TODO" is displayed.

**Expected behavior:**
When moving my mouse onto "Redo" toolbar button of HTML editor, a tooltip "Redo" is displayed.

**Screenshots:**
On remote server =>
![wrong_hint_remote](https://user-images.githubusercontent.com/6738167/139258702-855e2662-5edd-46da-af5c-52b23758315d.png)

On local computer (while developing) =>
![correct_hint_local](https://user-images.githubusercontent.com/6738167/139258716-72450967-c453-4f72-b73e-8723e2447611.png)

**Comment by H-Frederick** [comment]
Hi,

This behavior occurs for localized projects. We have [dictionaries](https://js.devexpress.com/Documentation/Guide/Common/Localization/#Dictionaries) curated from community contributions. You can see them here: https://github.com/DevExpress/DevExtreme/tree/22_2/js/localization/messages

Not all texts have been translated yet. It is necessary to override dictionary strings as a workaround. The following support ticket describes how to override the TODO texts in greater detail: [HtmlEditor - The TODO text is shown in Font and Size toolbar items](https://supportcenter.devexpress.com/internal/ticket/details/T1111722)

If you'd like to submit your translated texts, you can fork this repository and modify your dictionary file from the localization messages folder I linked above. Then, create a pull request to submit your changes.
