### ISSUE TITLE
Grid and TreeList scrollbar hard to use and sometimes impossible to see

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#2349]
Using 17.2.4, but this was issue in previous releases as well. Users are having difficulty seeing the vertical and horizontal scrollbars. Some don't hover long enough for the scrollbars to appear, and even when they do, the height / width of them is difficult to work with. Please please please add an option to always display the scrollbars in the standard sizes.

Also, when there are a lot of rows in the TreeList, the vertical scrollbar height is so tiny it's very hard to even see it and hard to grab it. Can you spot the vertical scrollbar it in the screenshot?
![scrollbar](https://user-images.githubusercontent.com/7947294/34361634-d7eecb7e-ea39-11e7-8126-ffea7cb59e80.png)

**Comment by San4es** [comment]
@genachka 

Did you try to use the ["scrolling.useNative"](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#useNative) option? Is this what you need?

**Comment by genachka** [comment]
@San4es yes this was exactly what I was looking for! Completely missed this option. Thank you!
