### ISSUE TITLE
ODataStore and promise

### ISSUE THREAD

**Issue by genusP** [DevExpress/DevExtreme#2386]
Use Devexreme and devextreme-angular 17.2.4

1.  Many methods in ODataStore return  Promise. Returned instance not contains method catch
2. I call method ODataStore.insert, if server response set http status 500 then returned promise not call any branch.

**Comment by GoshaFighten** [comment]
The `catch` event will be added in the next 17.2 version (17.2.5). See the [Add "catch" method for Deferred utils](https://github.com/DevExpress/DevExtreme/pull/2406) pull request.

As for the second question, you can use the following code to handle errors in ODataStore:

``` TypeScript
var ds = new DataSource({
  store: {
    type: 'odata',
    url: 'http://www.example.com/dataservices/odata/targetData',
    key: 'Id'
  },
  paginate: false
})
ds.load().then(() => {
  alert("resolve");
}, () => {
  alert("fail");
});
ds.store().insert({id: 1}).then(() => {
  alert("resolve");
}, () => {
  alert("fail");
});
```

See the [sample](https://stackblitz.com/edit/angular-oz7bh1?file=app/app.component.ts) that illustrates this. If this approach does not work, please open a new [Support Center ticket](https://www.devexpress.com/Support/Center/Question/Create) for the issue.

**Comment by genusP** [comment]
@GoshaFighten  I use similar code. This problem actual for HTTP code 500, no calls for "resolve" and "fail"
