### ISSUE TITLE
Html Editor Predefined Items are missing in release version 23.1.2-alpha-23114-0308

### ISSUE THREAD

**Issue by ducthangchin** [DevExpress/DevExtreme#24692]
### Problem:
I have noticed that in the latest version of DevExtreme, which I am currently using for my React application, there are certain predefined item names missing in the Html Editor component compared to the provided [documentation](https://js.devexpress.com/Documentation/23_1/ApiReference/UI_Components/dxHtmlEditor/Types/#HtmlEditorPredefinedToolbarItem).

### Steps to Reproduce:
Predefined Items in documentation
![image](https://github.com/DevExpress/DevExtreme/assets/69846657/a2b183c4-f990-4951-afe2-52b0902ca591)

When inspecting the source code of the DevExtreme React package, specifically the html-editor.ts file, I came across the following section:
![image](https://github.com/DevExpress/DevExtreme/assets/69846657/d8d9ea7e-5732-4b78-8bc7-1eb4b72b0cd8)
In text: `    name?: "background" | "bold" | "color" | "font" | "italic" | "link" | "image" | "strike" | "subscript" | "superscript" | "underline" | "blockquote" | "increaseIndent" | "decreaseIndent" | "orderedList" | "bulletList" | "alignLeft" | "alignCenter" | "alignRight" | "alignJustify" | "codeBlock" | "variable" | "undo" | "redo" | "clear" | "insertTable" | "insertHeaderRow" | "insertRowAbove" | "insertRowBelow" | "insertColumnLeft" | "insertColumnRight" | "deleteColumn" | "deleteRow" | "deleteTable" | "cellProperties" | "tableProperties";
`
The predefined name does not include 'header', 'size', and 'separator'.

### Results You Received:
```
import HtmlEditor, { Toolbar, Item } from 'devextreme-react/html-editor';

const sizeValues = ['8pt', '10pt', '12pt', '14pt', '18pt', '24pt', '36pt'];
const Test = () => {
  return (
    <HtmlEditor>
      <Toolbar multiline={true}>
        <Item
          name='size' // Error: 'size' is not assignable to name type
          acceptedValues={sizeValues}
        />
      </Toolbar>
    </HtmlEditor>
  );
};

export default Test;`
```

### Environment Details:
DevExtreme version: 23.1.2-alpha-23114-0308
Code Editor: Visual studio Code

**Comment by ducthangchin** [comment]
` Overload 1 of 2, '(props: IItemProps | Readonly<IItemProps>): Item', gave the following error.
    Type '"size"' is not assignable to type '"bold" | "link" | "strike" | "blockquote" | "image" | "underline" | "italic" | "color" | "font" | "background" | "subscript" | "superscript" | "increaseIndent" | "decreaseIndent" | ... 22 more ... | undefined'.
  Overload 2 of 2, '(props: IItemProps, context: any): Item', gave the following error.
    Type '"size"' is not assignable to type '"bold" | "link" | "strike" | "blockquote" | "image" | "underline" | "italic" | "color" | "font" | "background" | "subscript" | "superscript" | "increaseIndent" | "decreaseIndent" | ... 22 more ... | undefined'.
 <Item name='size' />`
 
 This problem occurs during the build process due to TypeScript's strict type checking. It seems that the type declaration was inadvertently omitted here. Surprisingly, despite the type error, the functionality still works as expected. To overcome this type check issue, I have devised a solution that involves casting the value to the appropriate type. Here is my solution
 
 ```
 import HtmlEditor, { Toolbar, Item } from 'devextreme-react/html-editor';

const sizeValues = ['8pt', '10pt', '12pt', '14pt', '18pt', '24pt', '36pt'];
type IItemNameProps = "background" | "bold" | "color" | "font" | "italic" | "link" | "image" | "strike" | "subscript" | "superscript" | "underline" | "blockquote" | "increaseIndent" | "decreaseIndent" | "orderedList" | "bulletList" | "alignLeft" | "alignCenter" | "alignRight" | "alignJustify" | "codeBlock" | "variable" | "undo" | "redo" | "clear" | "insertTable" | "insertHeaderRow" | "insertRowAbove" | "insertRowBelow" | "insertColumnLeft" | "insertColumnRight" | "deleteColumn" | "deleteRow" | "deleteTable" | "cellProperties" | "tableProperties";

const Test = () => {
  return (
    <HtmlEditor>
      <Toolbar multiline={true}>
        <Item
          name='size' as IItemNameProps
          acceptedValues={sizeValues}
        />
      </Toolbar>
    </HtmlEditor>
  );
};

export default Test;`
 
 
 ```

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. We'll address this issue in the context of this thread: https://supportcenter.devexpress.com/ticket/details/T1167826
