### ISSUE TITLE
DateRangeBox for zoom level year is glitchy

### ISSUE THREAD

**Issue by tim-breitenstein-it** [DevExpress/DevExtreme#24909]
### Steps to Reproduce:

Goal: Select a DateRange for full month only

1. 
```
<DateRangeBox
    calendarOptions={{
        firstDayOfWeek: 1,
        maxZoomLevel: 'year',
        minZoomLevel: 'decade',
        zoomLevel: 'year'
     }}
  />
```

### Results You Received:

![image](https://github.com/DevExpress/DevExtreme/assets/65597245/165c1c8e-7f6f-41dc-a6f0-39bdc57619c0)

### Results You Expected:

![image](https://github.com/DevExpress/DevExtreme/assets/65597245/5c9cb2ea-88e9-42f6-b626-932357473597)

### Environment Details:

- "devextreme": "23.1.3"
- "devextreme-react": "23.1.3"

https://codesandbox.io/s/overview-devextreme-date-range-box-forked-gtxy7h?file=/App.js

**Comment by AlisherAmonulloev** [comment]
Hi Tim,

I apologize for the delayed response.

Currently, the selection functionality is supported when the zoom level is `month`. However, we agree that the component should not render artifacts in the scenario you described. To research why this happens, I created a public ticket in our Support Center: [https://supportcenter.devexpress.com/ticket/details/t1186223](https://supportcenter.devexpress.com/ticket/details/t1186223). If you have a DevExpress account, you can add that ticket to Favorites to track our progress.

Regards,
Alisher
