### ISSUE TITLE
FileManager: change selection event raised on dir change is indistinguishable from the human-made one

### ISSUE THREAD

**Issue by vyshkant** [DevExpress/DevExtreme#24929]
`onSelectionChanged` is currently raised in two different cases:
1) when the actual human user changes the selection by clicking a row or a checkbox
2) when uses performs actions on changing directory, **without actually deselecting any rows**

these two cases are currently indistinguishable one from another, so there's no way to understand "does user actually change the selection" or "is user just changing dir"

**Comment by AlisherAmonulloev** [comment]
You are right, the FileManager component does not distinguish what action led to triggering the onSelectionChanged event. As a possible solution, you can set a flag in the [onDirectoryChanged](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxFileManager/Events/#currentDirectoryChanged) event handler and then check this flag in the onSelectionChanged event handler.
If this is not a suitable solution, please submit a support ticket in our Support Center and describe your ultimate goal in greater detail. Use the following link to submit a ticket: [https://devexpress.com/ask](https://devexpress.com/ask)
