### ISSUE TITLE
Run tests locally using Travis in docker

### ISSUE THREAD

**Issue by eloekset** [DevExpress/DevExtreme#2681]
Some time ago, I was working on a PR for T487901, but I want to test my changes locally before submitting a PR.

I've been following the description to build and test DevExtreme locally here: https://github.com/DevExpress/DevExtreme/blob/17_2/README_DEVELOPERS.md#locally-in-docker

But there's something I don't quite understand, since I get an error message that says `./docker-ci.sh` doesn't exist at the provided path.
![image](https://user-images.githubusercontent.com/791721/35473733-7447cd8c-0384-11e8-89c2-94365402b9c4.png)

Any hints on what's wrong, or links to more resources that can help me run the CI tests before opening a PR?

**Comment by AlekseyMartynov** [comment]
Try this command:

```bash
sudo docker run --rm -ti -e TARGET=test -v /home/eivind/GitHub/eloekset/DevExtreme:/devextreme devexpress/devextreme-build:17_1 ./docker-ci.sh
```

Note the [`-v` argument value](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems).

**Comment by eloekset** [comment]
Thanks! Now it works. 🙂 And when I read the description again, I can see that it says REPO_PATH should be replaced by the absolute path to the local git repository. 😂
