### ISSUE TITLE
[Idea] DevExtreme Web Components

### ISSUE THREAD

**Issue by selcukkutuk** [DevExpress/DevExtreme#2856]
1. Vuejs
2. Angular 2+
3. React
4. Angularjs
5. Ember
6. Aurelia
7. Knockout
8. Backbone
9. Dojo
10. Svelte

and more. The list grows every day.
   Do you have a plan to develop framework-independent web components instead of developing custom components for frames?

   Someone who loves Devexpress will not have to love angular. So we can choose which frame to use. You are focused on the core project. It's just an idea. :) regards to.

**Comment by dxbykov** [comment]
Hi @selcukkutuk,

Thank you for your idea and for your interest in DevExtreme. I should say that the issue you've raised is one of the most important for us, as a JS components vendor. Besides the new features we introduce, we are working hard on getting framework independent and having better integration with them. For instance, we've recently made DevExtreme core [jQuery-free](https://community.devexpress.com/blogs/donw/archive/2017/11/09/devextreme-with-and-without-jquery-v17-2.aspx) but kept jQuery integration available. 

The use of the Web Components approach could be one of the possible solutions. But this won't allow us to provide all possible benefits of each specific framework, such as Virtual DOM in React, for instance. We'll keep your ideas in mind while planning our further work. Currently, we have the [3rd-Party Frameworks Integration API](https://js.devexpress.com/Documentation/Guide/Widgets/Common/Advanced/3rd-Party_Frameworks_Integration_API/) article, which covers main integration aspects. Feel free to contact us in case you have problems using it.

**Comment by angel-menendez** [comment]
Please take a look to this video from ionic. They are adding all the best features from framework  to their web components(Including Virtual Dom). Take a look at the comparison with React Fiber. https://www.youtube.com/watch?v=UfD-k7aHkQE

Hope yo can become Framework Independent. 
Regards

**Comment by selcukkutuk** [comment]
@angel-menendez Thank you very much for your comment. I will review it as soon as possible.

**Comment by selcukkutuk** [comment]
@angel-menendez Thank you so much for comment. I follow very closely. I even wrote two articles on the stenciljs resources page. (in Turkish)

https://stenciljs.com/resources
