### ISSUE TITLE
How load custom date names?

### ISSUE THREAD

**Issue by alexgwolff** [DevExpress/DevExtreme#2894]
I would load custom date names like to load as in messages, how to do this?

**Comment by nightskylark** [comment]
Hi.
You can use the [Globalize](https://js.devexpress.com/Documentation/Guide/Widgets/Common/UI_Widgets/Localization_-_Use_Globalize/) or [Intl](https://github.com/DevExpress/DevExtreme-Intl) localization engine to localize dates considering the locale you needed. If you need to set custom date names which do not suit any existing locale, I recommend using the Globalize localization engine. You could load CLDR-data files of required locale, and modify the date-data you want. For example, you can use [this CLDR-dates file](https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/pt/ca-gregorian.json)

**Comment by alexgwolff** [comment]
For those who also need this can be done with:


import * as devextreme from 'devextreme/localization';
import *  as defaultMessages from './default_messages_pt_BR.js';
devextreme.date.inject(defaultMessages);


default_messages_pt_BR.js is a copy of \devextreme\localization\default_messages
but with custom messages in portuguese
