### ISSUE TITLE
deprecated displayExpr AutoComplete

### ISSUE THREAD

**Issue by kodermax** [DevExpress/DevExtreme#3095]
Why did you remove the useful attribute?
https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxAutocomplete/Configuration/#displayExpr

**Comment by AlekseyMartynov** [comment]
It's not removed, it's been renamed to `valueExpr` back in v15.2.
Do you experience any issues with the `valueExpr` option?

**Comment by kodermax** [comment]
Yes, I have a complex object where I want to display the field Name, and the value must go from the Id field.

**Comment by AlekseyMartynov** [comment]
Now I understand your question.
It's discussed and answered in https://devexpress.com/issue=T210054
