### ISSUE TITLE
"Select all" checkbox has a wrong value in deffered selection mode

### ISSUE THREAD

**Issue by etumyan** [DevExpress/DevExtreme#3244]
### Steps to Reproduce:

1. Create a DataGrid widget with at least 2 rows and multiple selection mode enabled.
2. Follow this scenario: select first row -> select second -> deselect first -> deselect second.

### Results You Received:
"Select all" checkbox has an `undefined` state.

### Results You Expected:
"Select all" checkbox has a `false` state, since all rows are deselected.

### Tests

I have fixed the [select and deselect several items](https://github.com/DevExpress/DevExtreme/blob/17_2/testing/tests/DevExpress.ui.widgets/selection.test.js#L1389) test wich currently is broken I guess.
Here is the fix which represents the issue: https://github.com/etumyan/DevExtreme/commit/64fbba7271ad468145235ac193d07a44e3804a65
Please note if you deselect rows reversely against selection order everything works fine.

### Environment Details:

DevExtreme 17.2.6, Google Chrome

**Comment by etumyan** [comment]
Here is a strange behavior for the `selectionFilter` value also.
If you select/deselect rows in the way which described above you will get something like this:
```
[
  [['id', '=', 1], 'or', ['id', '=', 2]],
  'and', ['!', ['id', '=', 1]],
  'and', ['!', ['id', '=', 2]]
]
```
But if you deselect rows reversely, `selectionFilter` value will be `[]`, which is correct.

**Comment by Alyar666** [comment]
Hello,

We will process this issue in the context of the following Support Center thread:
[dxDataGrid - The "Select all" checkbox has a wrong value in deferred selection mode](https://www.devexpress.com/Support/Center/Question/Details/T615278)
