### ISSUE TITLE
Vector map -> Bubble Markers -> "palette" config bug

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#3346]
### Steps to Reproduce:

1.  Set "palette" config for vector map bubble marker layer 
2. 
3. 

### Results You Received:
Bubble marker color does not change

### Results You Expected:
Bubble marker color changes based on palette setting

### Environment Details:
DevExtreme 17.2

### Plunker example
https://plnkr.co/edit/gnP6mfvE6sdGdKOQrBke

PS: yes, I know that I can use "color" config instead.

**Comment by pavelgruba** [comment]
Hello,

We will process this issue in the context of the following Support Center thread:
[Vector map - Marker color does not reflect the layer.palette](https://www.devexpress.com/Support/Center/Question/Details/T617674)
