### ISSUE TITLE
dxTagBox issue with preselected items in 17.2.7 version

### ISSUE THREAD

**Issue by TigranOtaryan** [DevExpress/DevExtreme#3406]
1. I have preselected items in dxTagBox
2. Open dxTagBox list
3. See that preselected items are not selected in the list

[Fiddle NOT working example with 17.2.7 version](https://jsfiddle.net/s38ofe07/18/)

[Fiddle working example with 16.1.6 version](https://jsfiddle.net/s38ofe07/19/)

**Comment by mrjohn0011** [comment]
Hello, Tigran!
 
I have created a corresponding ticket in the DevExpress Support center. 
We will look for a solution. Please subscribe to [this ticket](https://www.devexpress.com/Support/Center/Question/Details/T619679/dxtagbox-does-not-select-initial-values-when-datasource-is-slow) to receive a notification when we fix this issue.
