### ISSUE TITLE
DateBox type=roller renders the year input under the other controls

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/DevExtreme#3686]
See this screenshot: https://i.imgur.com/87jpJm7.png.

You can clearly see that the year input field renders under the date & month inputs. The entire date-box doesn't get enough width because when I add another 10-20 pixels it works correctly.

**Comment by jsdmitry** [comment]
Hi,

I've reproduced this problem and created the [T626105](https://www.devexpress.com/Support/Center/Question/Details/T626105/dxdatebox-the-year-is-rendered-incorrectly-when-the-type-option-is-roller) issue in our Support Center. As a workaround, you can add the `dx-viewport` CSS class to a parent container. The following [codepen](https://codepen.io/anon/pen/XEvjQZ) demonstrates this.
