### ISSUE TITLE
dxNumberBox performs conversion of percent format values instead of the number localization parser

### ISSUE THREAD

**Issue by ltvan** [DevExpress/DevExtreme#3691]
Default number parser parses '15%' as 15, while Globalize parse '15%' as 0.15. DxNumberBox used to work by automatic divide parsed number by 100, but now with Globalize, it's failed to work because the Globalize parsed number is already divided by 100.

**Comment by DokaRus** [comment]
Hi,
I don't see any difference between using NumberBox with the `percent` format with or without Globalize.
I've prepared an example using the [default formatter](https://plnkr.co/edit/U0p98Si6nujdKng8I6vn?p=preview) and an example using [Globalize](https://plnkr.co/edit/pKrlTBw0pZboEuDxDsu3?p=preview).
Can you modify the first one to demonstrate the wrong behavior?

**Comment by ltvan** [comment]
I look at your example and see the problem here. Actually `numberLocalization.parse` never use Globalize (as if `format` is string, it will call the parent). It uses the `numberLocalization.format` to detect localized config and use built-in parser to parse the text. Therefore the application still works.

My problem is that Globalize cannot work with angular-cli, so I have to write another integration with `numeral` and use `numeral` to parse the text directly. That's why it behaves differently. `numeral` automatically parse `15%` as 0.15, but default `numberLocalization.parse` results in 15.

**Comment by ltvan** [comment]
I worked around my problem by the same way as the Globalize integration does. But I suggest that you should make it consistent in your code, that if the `format` automatically convert 0.15 to 15%, then the `parse` should do the same, i.e. 15% to 0.15. It's not the responsibility of `dxNumberBox` to divide the number to 100 after parsed.

**Comment by mrjohn0011** [comment]
Hello Itvan!
 
We will discuss the possibility of moving this functionality from dxNumberBox to numberLocalization. Thank you for your suggestion.
