### ISSUE TITLE
AutoComplete not show list on paste

### ISSUE THREAD

**Issue by genusP** [DevExpress/DevExtreme#3694]
### Steps to Reproduce:
1. Copy to clipboard text Je
2.  Open https://js.devexpress.com/Demos/WidgetsGallery/Demo/Autocomplete/Overview/jQuery/Light/
3.  Select FirstName TextBox
4.  Click right mouse button and select Pate item

### Results You Received:

Open list of suggestions

### Results You Expected:

Suggestions list not showing

### Environment Details:

Browsers: Chrome 65, Edge 41

**Comment by DokaRus** [comment]
Hi,
I've created a corresponding [T626122 ticket](https://www.devexpress.com/Support/Center/Question/Details/T626122) in our Support Center. You can subscribe to it to receive a notification when we fix this issue.
