### ISSUE TITLE
DataGrid - performance improvements

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#3713]
# Problem 1

The problem appears when using a DataGrid with [virtual scrolling](https://js.devexpress.com/Documentation/18_1/Guide/Widgets/DataGrid/Scrolling/). The more pages a user scrolls over, the slower the DataGrid becomes.

## The Solution

The mentioned performance issue is caused by HTML markup that is not removed from DOM when it’s invisible. Starting with 18.1, DataGrids cleans unnecessary markup when it scrolls away from the visible area.

# Problem 2

The problem appears when using a DataGrid with virtual scrolling. When scrolling fast, a user might see ‘white space’ for a while instead of data rows in the DataGrid. 

## The Solution

The mentioned behavior is caused by asynchronous data rendering while scrolling. Starting with 18.1, DataGrid renders data synchronously if using a local data source. We also introduced a heuristics that reverts a DataGrid to asynchronous rendering if a row markup is too ‘heavy’ and can't be rendered synchronously without performance downgrade.

Also, we added a loading indication when DataGrid is loading data remotely.

# Problem 3

The problem appears when using a DataGrid with a [pager](https://js.devexpress.com/Documentation/18_1/Guide/Widgets/DataGrid/Paging/). When page size is large, a user might face performance issues while working with the DataGrid. 

## The Solution

Starting with 18.1, it’s possible to enable virtual scrolling within the current page:

```js
 scrolling: {
   rowRenderingMode: 'virtual'
 }
```

# Problem 4

The problem appears when using a DataGrid with a huge number of columns. A user might face performance issues while working with the DataGrid.

## The Solution

Starting with 18.1, it’s possible to enable virtual scrolling over columns:
 
```js
 scrolling: {
   columnRenderingMode: 'virtual'
 }
```

In this case, a DataGrid renders only visible columns. Once a column becomes invisible during scrolling, it’s removed from DOM.
 
Note: to achieve the maximum performance in this mode, we recommend specifying the `columnWidth` option as well.

# Try It And Give Us Feedback 

## Live Sandbox

Here is an example of DataGrid with 10K rows and 500 columns (5 million cells):

[jQuery](https://codepen.io/anon/pen/XqrdJV) 
[Angular](https://embed.plnkr.co/uQkdv4TEKUpS5z6vytou/)

Here is a demo of using DataGrid with remote data in virtual scrolling mode:

[jQuery](https://codepen.io/dxbykov/pen/wjvybz) 
[Angular](https://embed.plnkr.co/ShmOHjgcqJUhBfSTBJ5D/)

## Installation

Follow the installation guide from the [release page](https://github.com/DevExpress/DevExtreme/releases) and leave us feedback on this topic.

**Comment by hakimio** [comment]
Tried the first demo. When using height "100%" horizontal scrollbar only appears when I scroll all the way to the bottom of the grid. Is that intended?

**Comment by komarovalexander** [comment]
@hakimio In the case of the height set to "100%", nothing will happen if the parent element has no specified height. So you need to set the height of parents. 
Here is a working sample: [https://codepen.io/anon/pen/jxPYQX](https://codepen.io/anon/pen/jxPYQX)

**Comment by troygould** [comment]
I dialed down the first Angular plunkr to 30 columns and 3000 rows.
Chrome is awesome. No lag like I used to get.
Edge is ok. Some lag. Is this just the data in the browser or not completely implemented for Edge?
IE 11 doesn't work at all. Missing polyfills?

**Comment by vconst** [comment]
@troygould Thank you for your feedback.
The lags are visible during scrolling because the Edge browser is slower than Chrome. We are aware of this issue and are working on it.
IE11 works on my side but with lags as in Edge. Can you send us additional information about your IE11 (an operating system version, the IE11 full version)?

**Comment by troygould** [comment]
Edge is usable. Just slower. Glad to know you are working on making performance better. As for IE 11:
Version 11.966.15063.0, Update Version: 11.0.56

**Comment by troygould** [comment]
Should have looked at IE dev console: 
![8431adf7](https://user-images.githubusercontent.com/12100826/39209551-4ca25f4e-47c3-11e8-9125-fedadb8e4a89.PNG)

**Comment by vconst** [comment]
@troygould I have found that the error in IE11 occurs in the embed plunker service and it is not related to DevExtreme. I have prepared a [plunker demo](https://plnkr.co/edit/hnwZuIAPg9MvnJ0DOUQB?p=preview) that works in IE11.

**Comment by dxbykov** [comment]
Thanks to everybody who participated in this discussion or gave us early feedback by other means. The feature is now available in the [v18.1](https://github.com/DevExpress/DevExtreme/releases/tag/18.1.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).

**Comment by dkt2000** [comment]
Hi @dxbykov  Right now we are using DxGrid, AngularJs Version. with 40 columns , doing some manipulation on run time also.

DxGrid performance not good. Because due to more columns DOM manipulation taking time. 

As per my understanding Angular , ReactJs and VueJs works on Virtual DOM concepts. And their Rendering speed much faster then AngularJs and Jquery based Grid.

So, my questions is that have you tired performance between AngularJs,Jquery grid vs Angular,ReactJs,VueJs with same data source ?

**Comment by dxbykov** [comment]
Hi @deepaktech94,

At the moment, our jQuery, AngularJS, Angular, React, and Vue DataGrids are wrappers over a pure JavaScript core. So, for instance, our React Data Grid doesn't use Virtual DOM. There shouldn't be much performance difference between all the mentioned frameworks.

> Because due to more columns DOM manipulation taking time.

Please try enabling the [Column Virtual Scrolling](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/HorizontalVirtualScrolling/) feature and let us know if it helps.
