### ISSUE TITLE
DateBox type=rollers doesn't remove/disable values that are below the min/max value

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/DevExtreme#3715]
### Steps to Reproduce:

1. Create a datebox with the pickerType='rollers' and type='time'
2. Set a min value e.g. 08:00.

### Results You Received:
The list is rendered with values that will never be valid like 07:00, 06:00 etc.

### Results You Expected:
I expect a list from the minimum time. So 08:00, 09:00, etc.

**Note: the same goes for the maximum value.**

**Comment by DokaRus** [comment]
Hi,
I've reproduced the same behavior and created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T627173) in our Support Center. You can subscribe to it to receive a notification of our progress.
