### ISSUE TITLE
DataGrid - Virtual scrolling over columns does not work with band columns

### ISSUE THREAD

**Issue by jneves92** [DevExpress/DevExtreme#3738]
Virtual scroll not working with fixed columns

1.  Set one column fixed
2.  <dx-data-grid #myGrid id="gridContainer"
                [columns]="planoTrabalhoColumns"
                [dataSource]="planoTrabalhoData">
    <dxo-paging [pageSize]="100">
    </dxo-paging>
    <dxo-scrolling **mode="virtual" rowRenderingMode="virtual" columnRenderingMode="virtual"**>
    </dxo-scrolling>
    <dxo-load-panel [enabled]="false"></dxo-load-panel>
  </dx-data-grid>

### Environment Details:
angular: 6.0.0-rc.5
angular/cli: 6.0.0-rc.5
devextreme: 18.1.1-pre-18103
devextreme-angular: 18.1.1-beta.6,

**Comment by vconst** [comment]
Hi @jneves92

I have created a plunkr example ([https://plnkr.co/edit/Ih04loNH3TD9HmjkirlJ?p=preview](https://plnkr.co/edit/Ih04loNH3TD9HmjkirlJ?p=preview)) based on your code, but couldn't reproduce the problem in it. Please modify the example so it illustrates the issue and describe the problem in more detail.

**Comment by jneves92** [comment]
Hi @vconst 

Thank you for reply.
I have modified example to illustrate my issue https://plnkr.co/edit/3NCUJh?p=preview

**Comment by vconst** [comment]
@jneves92 
I have found that your example contains band columns. In the current pre-release version, virtual scrolling over columns does not work with band columns. We're going to fix it.
