### ISSUE TITLE
Suggestion: integrity value for CDN

### ISSUE THREAD

**Issue by MihaMarkic** [DevExpress/DevExtreme#3759]
Can you provide script integrity attribute values (for sourcing from CDN)?

**Comment by BingoRUS** [comment]
Hello @MihaMarkic! Thank you for your suggestion. We are going to provide hashes for DevExtreme scripts hosted on CDN in our documentation. I will give you a link once we add this information.

**Comment by BingoRUS** [comment]
@MihaMarkic,
We added the [Subresource Integrity Hashes](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/CDN_Services/#Subresource_Integrity_Hashes) section in our documentation for all DevExtreme resources available via CDN from v17.1 and above.
