### ISSUE TITLE
Suggestion: allow steps in dx-date-box with rollers

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/DevExtreme#3815]
Hi,

We're currently using the dx-date-box directive  (for Angular 1.x) and it would be great addition if we can configure a step/interval to the rollers, e.g. 5 minutes. Currently this is always set to 1 minute and is not configurable.

**Comment by DokaRus** [comment]
Hi,
 
Thank you for the suggestion! We'll take it into account in further development.
