### ISSUE TITLE
Style component now that Angular deprecated the /deep/ selector

### ISSUE THREAD

**Issue by JacopoSciampi** [DevExpress/DevExtreme#3883]
This is the error message I recieve : 

[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

I wanted to know how to solve that. I'm using the latest version of DX. Thank you.

Jacopo.

**Comment by ovchinnikov** [comment]
I recommend that you refer to the following thread where a similar inquiry was discussed: [Alternative to /deep/ in the future](https://github.com/angular/angular/issues/17867)?
