### ISSUE TITLE
Bug: dx-date-box pickerType='list' shows incorrectly positioned on mobile

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/DevExtreme#3924]
### Steps to Reproduce:

1. Create a dx-date-box with pickerType='list' & type='time'
2. Load the dx-date-box on a mobile device or using the Chrome mobile mode (see screenshot)
3. The list pop-up will show incorrectly positioned.

Screenshot desktop OK:
![q](https://i.imgur.com/A9sM7oc.png)

Screenshot mobile NOK:
![w](https://imgur.com/iWFT1xJ.png)

I have also tested this on an actual Android device, and the same thing is happening as well.

**Comment by DokaRus** [comment]
Hi,
I've reproduced the same behavior and created a corresponding [Support Center ticket](https://www.devexpress.com/Support/Center/Question/Details/T633338). You can subscribe to it, and we'll send you a notification once we have any results.
