### ISSUE TITLE
VueJS Support

### ISSUE THREAD

**Issue by ningliaoyuan** [DevExpress/DevExtreme#40]
We've used VueJS for building our new product for enterprises. We really want to see some support for VueJS. So that we could start to leverage this powerful UI libraries. Is here the right channel to ask for this?

**Comment by dxbykov** [comment]
Hi,
 
We are doing research in this regard and considering VueJS support as one of the DevExtreme development directions. At the current stage, it would be extremely helpful to hear some thought and requirements from you.
 
1. What is the main reason you have chosen VueJS among the other alternatives (I mean Angular, React, jQuery)?
 
2. Is it important for you to have the VueJS component built natively in VueJS or have it just as a wrapper over a jQuery widget?
 
3. Are you already using any VueJS component libraries? If so, which components do they have and what do you think they are missing?
 
4. Which components are most important for your project that you would expect to get from DevExpress?
 
Thank you for your input in advance. It will help us correct our VueJS support direction and provide you with VueJS components that meet your needs better.

**Comment by ningliaoyuan** [comment]
Thanks @dxbykov. 

Glad to know you are already considering the support plan.Can't wait to see it. and we're willing to purchase a business license if VueJS is supported. 
Here is my answers to your questions:
1. Too many good articles talking about this in internet. For our case, a) light weight and easy to customize and extend; b) easy learning curve; c) Performance is relative good with almost none optimization effort. 

2. A handy wrapper would be good starting point. Of course, it would be much better if you could build it natively in VueJS. Shouldn't be very hard I guess.

3. We are using [element]( https://github.com/ElemeFE/element) today which is pretty neat. But we're really looking for enterprise quality UI control libraries for our product. Especially the advanced table and interactive charts where DevExpress owns the best in the world.

4. Data Grid, Charts, Sparklines, Custom Theme.

Help these make sense to you.

**Comment by dxbykov** [comment]
Thank you a lot, the information you've provided is really helpful. We'll take it into consideration when planning further VueJS development. 
 
I'm closing this thread for now. You are welcome to reopen it if you have any further questions.

**Comment by lyquocnam** [comment]
+1 support vuejs.
yeah, same with @ningliaoyuan vuejs really simple, fast and easy to resolve a problem.
reactive variable, model binding, storex... i like so much 👍.

Currently, have some framework to make vuejs work with cordova & electron ( [quasar framework](http://quasar-framework.org/) ).
So with DevExtreme controls, i think it can repleace winform, wpf... to write some simple app run anywhere with one source code. It make the future !
(sorry about my english :D)

**Comment by dxbykov** [comment]
@lyquocnam Thank you for sharing your thoughts and intentions. We'll take them into account.

**Comment by aidanxyz** [comment]
+1 support for Vue.js
We at our company had a huge benefit from just rewriting some pages originally written in jQuery to Vue.js. It's as easy to use as jQuery (just drop a file and good to go), but much more maintainable and shorter due to template directives and reactiveness, and at the same time it's not as complex as Angular or React (but if needed can scale to complex SPAs as well).

**Comment by dxbykov** [comment]
Hi @acutexyz,

Thank you for sharing your thoughts. Could you please tell us if you are already using any VueJS component libraries? Which components are most important for your project that you would expect to get from us?

**Comment by farnetani** [comment]
We have seen there the huge growth of the Vuejs framework, when do you think of porting this datagrid of yours to vuejs?

**Comment by cr1t** [comment]
I'd like to add my +1 

We have used AngularJS and JQuery before, The Learning curve on Angular 4 is too great for us, and React would also mean a complete rewrite of what we have done in the past. Vue.js slots in nicely and we can have a gradual transition to it, Even a decent VUE wrapper of the Jquery would be great.

**Comment by ldagistanli** [comment]
any Update??

**Comment by BoBiene** [comment]
This is closed, is there a Vuejs wrapper available for DevExtreme?

**Comment by dxbykov** [comment]
The CTP release of DevExtreme Vue Wrappers will be available soon. We'll let you, guys, know about it in this thread. In our [recent blog post](https://community.devexpress.com/blogs/aspnet/archive/2018/03/13/devextreme-access-v18-1-features-today-for-early-testing.aspx), we also mentioned some alternative methods of getting notified of new DevExtreme stuff. Thanks for being interested.

**Comment by IlyaKhD** [comment]
Hi everyone!
The alpha version of DevExtreme Vue Components is now available on [npm](https://www.npmjs.com/package/devextreme-vue).
Your feedback would be highly appreciated, please feel free to open an issue on our [GitHub](https://github.com/DevExpress/devextreme-vue).

**Comment by dxbykov** [comment]
Thanks to everybody who participated in this discussion or gave us early feedback by other means. The Vue support is now available as CTP. All the Vue related development is happening in [a separate GitHub repo](https://github.com/DevExpress/devextreme-vue). Please give your further feedback on Vue support in that repo.
