### ISSUE TITLE
Build 17.2.8 throws an exception when navigating between different views in scheduler module.

### ISSUE THREAD

**Issue by richie50** [DevExpress/DevExtreme#4014]
### Steps to Reproduce:

1. Update dev-extreme package to 17.2.8 ,Build date Tue May 08 2018
2. File: `DevExtreme (ui/scheduler/ui.scheduler.appointments.strategy.base.js)` 
3. Navigating between different views. for example navigating from day to weeks throws this error

![image](https://user-images.githubusercontent.com/7333599/40076129-164f8310-584c-11e8-80d9-b03d5fa49472.png)

### Results You Received:
core.js:1350 ERROR TypeError: Cannot read property 'index' of undefined
    at inheritor._getResultPositions (ui.scheduler.appointments.strategy.base.js:291)
    at inheritor.createTaskPositionMap (ui.scheduler.appointments.strategy.base.js:65)
    at inheritor.createAppointmentsMap (ui.scheduler.appointments.layout_manager.js:49)
    at inheritor._getAppointmentsToRepaint (ui.scheduler.js:604)
    at inheritor.<anonymous> (ui.scheduler.js:592)
    at Deferred._promise.(/anonymous function) [as done] 
    at inheritor._dataSourceChangedHandler (ui.scheduler.js:585)
    at inheritor.<anonymous> (data_helper.js:67)
    at Callback._fireCore (callbacks.js:25)
    at Callback.fireWith (callbacks.js:77)
### Results You Expected:
 No error , worked on build:
`"devextreme": "^17.2.7"`,
`"devextreme-angular": "^17.2.7"`, 

### Environment Details:
Angular CLI: 1.7.4
Node: 8.4.0
OS: darwin x64
Angular: 5.0.3
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic

@angular/animations: 5.2.10
@angular-devkit/build-optimizer: 0.0.35
typescript: 2.8.3
webpack: 3.8.1

**Comment by KsyushaM** [comment]
Hi,
I can't reproduce this problem. Would you please clarify your scenario and data? You can change this code [example ](https://plnkr.co/edit/3nSe22JaGnQhvBDaUkOZ?p=preview)to demonstrate the problem.

**Comment by richie50** [comment]
yes @KsyushaM i'm trying to reproduce it.its a strange one :) But from our observation it seems when the the scheduled date for a particular appointments extends to the next day we have this problem. Meanwhile i have a check to solve this issue which i will be committing soon.

**Comment by KsyushaM** [comment]
@richie50 We can't approve your [PR](https://github.com/DevExpress/DevExtreme/pull/4019) because it just avoids the problem, but doesn't solve it.
I added appointment data from your PR to simple Scheduler configuration, but can't reproduce it anyway. I assume the problem is somewhere else. Can you create a example with all the steps that lead to the problem?

**Comment by KsyushaM** [comment]
We didn't get enough information on reproducing the problem. Let us know if new details appear.
