### ISSUE TITLE
External icons bug

### ISSUE THREAD

**Issue by kodermax** [DevExpress/DevExtreme#4016]
### Steps to Reproduce:

1. open https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ToolbarCustomization/Angular/Light/
2.  include font awesome
3. change button optons 
```
{
                location: 'after',
                widget: 'dxButton',
                options: {
                    icon: 'fas fa-truck',
                    onClick: this.refreshDataGrid.bind(this)
                }
            }
```

### Results You Received:
![image](https://user-images.githubusercontent.com/590985/40104453-13bb208e-58f9-11e8-9c85-3e3fbd9e57f6.png)

### Results You Expected:

Where is truck?

### Environment Details:

Angular

**Comment by DokaRus** [comment]
Hi,
I see a misspelling in your definition of the `icon` option. If you replace `"fas fa-truck"` with `"fa fa-truck"` all will be OK.
I've prepared a [live example](https://plnkr.co/edit/7bMgtkAcHBNWqtu7Yu7s?p=preview).

**Comment by kodermax** [comment]
I use this css file 
```<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">```


and have bug.

**Comment by DokaRus** [comment]
I've checked the live example with your link and it works fine. [Here](https://plnkr.co/edit/XNFH4UQPOHMNIs4moxdt?p=preview) is an updated example. Can you modify it to demonstrate the issue?

**Comment by DokaRus** [comment]
I've reproduced the issue using a Button without text and created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T636219) in our Support Center. You can subscribe to it to be notified as soon as we make any progress with the issue.

WA: you can change an icon width via CSS
```
.dx-icon.fa-truck {
  width: 23px;
}
```
