### ISSUE TITLE
Accordion panel is missing titles when Material theme is used

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#4022]
### Steps to Reproduce:

1. Go to DevExpress demos
2. Select Navigation -> Accordion
3. Select Material design theme

### Results You Received:
Accordion titles are not visible

### Results You Expected:
Accordion titles are visible

### Environment Details:
Chrome 66
DevExtreme Angular 18.1

**Comment by hakimio** [comment]
Seems to be fixed now?

**Comment by groshenkovamarina** [comment]
Hi @hakimio! Thank you for the report. We fixed this issue and will publish this fix in the next minor release.
