### ISSUE TITLE
Suggestion: Include LESS styles in the NPM package

### ISSUE THREAD

**Issue by tomshane** [DevExpress/DevExtreme#4037]
Hello,

this is not an issue per se, but it would be great if the LESS styles could be included in the NPM package. We are using DX together with Bootstrap (they already include SCSS files), which we customize and we have to sync styles (colors, fonts...) with DX theme, so we build styles from the LESS source files and do not use Theme Builder. 

Now, with every new version, we have to download source codes from GitHub and manually copy the styles to our project. By including them in the NPM package, we could make the process pretty much automatic.

Thanks.

**Comment by b1tzer0** [comment]
I agree, having the less files would make the process of building the customized themes much easier.

**Comment by BingoRUS** [comment]
Hi @R74NN, @b1tzer0!

We are going to provide a ThemeBuilder CLI tool which you can use while building your project. Will it be enough to make automation possible for your projects?

**Comment by tomshane** [comment]
I can't tell, it depends how exactly it is going to work. In my opinion and for our use, including LESS styles in the package would be quite easy and would 100% work with our current build process.

**Comment by AlekseyMartynov** [comment]
@R74NN :

>  we build styles from the LESS source files and do not use Theme Builder.

How exactly do you build them? DevExtreme LESS files are quite specific, they are converted to CSS themes via the [style-compiler tool](https://github.com/DevExpress/DevExtreme/tree/18_1/build/style-compiler). But this and other build tools are not the part of the NPM package. My guess is that you make custom builds of DevExtreme. Am I right?

The general idea behind the CLI is to allow importing metadata and saving the output in automatic mode, without using the Theme Builder web UI.

**Comment by tomshane** [comment]
In our project, we are using webpack and less-loader to compile LESS files to CSS. I have created a "dx.less" file, where I import all LESS files needed (depending on components we are using from DevExtreme). We import LESS files as they are and only alter some variables (colors, borders, fonts...), so the final CSS is our custom theme. I only needed to figure out what files in what order to import.

The whole process is the part of webpack workflow and all changes to variables are immediately visible in the browser. It's like changing any other stylesheet, no need to run an extra tool or special build task.

I would prefer to keep this build workflow - having the DX styles part of the package would make it perfect for us.

**Comment by Brandinga** [comment]
would also like more customable styles.

currently my main problems are:
1) i only want the css for components that i'm using (complete css-theme files are huge)
2) no automation (ThemeBuilder CLI should help)

**Comment by AlekseyMartynov** [comment]
Thanks @Brandinga @R74NN 

Declaring LESS source files redistributable will imply compatibility guarantees from our side. On the other hand, we recognize the need for more modular styles. To achieve this, we might need to deeply restructure them in future. Thus said, it's unlikely that we redistribute LESS in their current form.

**Comment by Brandinga** [comment]
FYI
my use case for component based css would be angular with lazy-loading modules.
main-module: menu-css
lazy-module: grid-css

**Comment by onebalaban** [comment]
Hello,

Currently, we are not planning to implement this functionality. However, we may consider it in the future. Please stay tuned to our announcements.

**Comment by BingoRUS** [comment]
Hello everyone! I'd like to share more thoughts about why we closed this issue. First of all, DevExtreme CLI is available, and you can use it to generate stylesheets with modified theme constants and only those components that you need. You can find more information in [the DevExtreme CLI guide](https://js.devexpress.com/Documentation/Guide/Common/DevExtreme_CLI/#ThemeBuilder).
We are going to migrate our LESS styles to Sass in v20.2 for better support of modular styles. So, I wouldn't recommend using LESS files in your projects.
We are not planning to include Sass styles into the `devextreme` npm package right after the migration, but we may consider providing a way to use them with Webpack in the future.
