### ISSUE TITLE
Upgrade to jszip v3.1.5?

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#4074]
The jszip v3.1.5 is out and stable. Could you upgrade the dependency?

**Comment by AlekseyMartynov** [comment]
3.1.5 is compatible with the current spec:

https://github.com/DevExpress/DevExtreme/blob/bd128d49255d3cf95e0eda5b32f0304a43fdd241/package.json#L26-L28

You can use [`npm update`](https://docs.npmjs.com/cli/update) to upgrade projects.
