### ISSUE TITLE
Safari: Column for checkboxes is collapsed when an empty grid is shown.

### ISSUE THREAD

**Issue by Yura13** [DevExpress/DevExtreme#4078]
Column for checkboxes is collapsed when the first opening page with an empty grid. Reproduced only in safari browser.

### Steps to Reproduce:
1. dx-data-grid with next properties:
[columns]="columns"
[selection]="{mode: 'multiple', allowSelectAll: false}"

2. When try to inspect element:
In styles tab:
.dx-datagrid-content .dx-datagrid-table .dx-row .dx-command-select {
      width: 70px;
      min-width: 70px;
      padding: 0px;
}
In computed tab:
~3.5 x 71

3. After resizing or loading data into grid column width becomes correct.

### Results You Received:
Column for checkboxes is collapsed when the empty grid is shown
![image](https://user-images.githubusercontent.com/17030431/40351007-0759e734-5db4-11e8-8341-55aebe3611f3.png)

### Results You Expected:
Column for checkboxes is not collapsed when the empty grid is shown.

### Environment Details:
devextreme: 17.2.7
devextreme-angular: 17.2.7
angular: 5.2.9
safari: 11.1 (12605.1.33.1.3)

**Comment by Alyar666** [comment]
Hello,

We will process this issue in the context of the following Support Center thread:
[dxDataGrid - The selection column is collapsed when an empty grid is shown in the Safari browser](https://www.devexpress.com/Support/Center/Question/Details/T639160)
