### ISSUE TITLE
Suggestion: dxPivotGrid - "blank"/"empty" option for summaryDisplayMode

### ISSUE THREAD

**Issue by gordon-matt** [DevExpress/DevExtreme#4098]
I'd like to suggest a **"blank"/"empty"** option for **summaryDisplayMode** on the **dxPivotGrid**. The reason for this is the PivotGrid is great for displaying grouped fields for rows and columns. For example, consider this screenshot of something I tried:

![pivotgrid summary problem](https://user-images.githubusercontent.com/2860937/40465234-e12ced98-5f5e-11e8-8fed-f4392c68774b.PNG)

In this report, we are trying to compare prices of the same hotel rooms from different suppliers. Ideally I would like some option to stop the values from being summed up when collapsed, as it is not applicable in this scenario. Of course I can use the **dxDataGrid** instead with its multi-level grouping, but it's not quite the same. The pivot grid would be perfect if there was a way to just display a blank (`&nbsp;`) when collapsing the fields instead of trying to aggregate the values.

**Comment by roman-simionov** [comment]
Hello @gordon-matt,

As far I understand, you want to show values for last level fields only. If so, you can use a [calculateSummaryValue](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/PivotGridDataSource/Configuration/fields/#calculateSummaryValue) callback. I have prepared an [online sample](https://codepen.io/anon/pen/pKoewe) that demonstrates this approach.

Alternatively, I can suggest using another [summaryType](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/PivotGridDataSource/Configuration/fields/#summaryType), for example, avg/min/max.

**Comment by gordon-matt** [comment]
Excellent! No need for any new option then. Thanks for your time.
