### ISSUE TITLE
Feature request / suggestions: DataGrid editing icons buttons instead of text

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#4311]
If in options, `editing` mode is set to 'row' and 'allowUpdating' is true, I know that the texts `editRow` can be customized to say something else, but I'd like to use a FontAwesome icon there instead. Same for the `save` and `cancel` and if I enable `allowDeleting`. I may want an icon button and label as well. I tried putting an icon button where the editRow texts goes but it doesn't render the HTML.

Also, can the position of that column be changed? Wanted to put it as first column instead of last for example.

And one more thing, would be great to control the position of the `Add` new row and it's icon and text like above.

**Comment by Alyar666** [comment]
Hello @genachka,

Starting with version 18.1, you can enable the [dxDataGrid.editing.useIcons](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#useIcons) option for this purpose.


> Also, can the position of that column be changed? Wanted to put it as first column instead of last for example.

Please refer to the following online demo to learn how to change the position of a command column: [Customize Command Columns](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CommandColumnCustomization/jQuery/Light/)


> And one more thing, would be great to control the position of the Add new row and it's icon and text like above.

Could you explain what you mean? The Add button is rendered in the toolbar. You can configure it using the [onToolbarPreparing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onToolbarPreparing) event.

**See also:**
[Use External Icon Libraries](https://js.devexpress.com/Documentation/Guide/Themes/Icon_Library/#Use_External_Icon_Libraries)

**Comment by genachka** [comment]
@Alyar666 ahh missed that new feature, thanks I've enabled it and thanks for the info on moving the position of the icon column. Is it possible to replace the icons with those from Font Awesome?

> >And one more thing, would be great to control the position of the Add new row and it's icon and text like above.

> Could you explain what you mean? The Add button is rendered in the toolbar. You can configure it 
using the onToolbarPreparing event.

The Add button is rendered in the toolbar, but the toolbar is above the grid. What if I wanted the toolbar to be at the bottom? Or what if instead of the toolbar, I wanted to show an add button on every row within the command column? How can I accomplish that (we're doing A/B testing for what works better)?
