### ISSUE TITLE
Custom store as filterbuilder field lookup dataSource

### ISSUE THREAD

**Issue by d-rudak** [DevExpress/DevExtreme#4395]
dxFilterBuilder display incorrect text value in dx filterbuilder item, when data source is custom store (always display first value of data source).

I've prepared an example: https://codepen.io/d-rudak/pen/mKqWaM?editors=0010

### Steps to Reproduce:

1. Change filter dropdown value to "Televisions"
2. Onfocus dropdown

### Results You Received:

Displayed "Video Players" (first value of the list)

### Results You Expected:

Displayed "Televisions" (selected value)

### Environment Details:

Devextreme 18.1

There is a method, that returns incorrect text value for custom store: https://github.com/DevExpress/DevExtreme/blob/18_1/js/ui/filter_builder/utils.js#L462

**Comment by komarovalexander** [comment]
Hi, 
I've created a [corresponding ticket in the DevExpress Support center](https://www.devexpress.com/Support/Center/Question/Details/T646772/dxfilterbuilder-displays-an-incorrect-text-value-when-use-a-customstore-as-the).
You can subscribe to it to receive a notification of our progress.
