### ISSUE TITLE
Need the ability to create tables in a horizontal plane with using cellTemplate

### ISSUE THREAD

**Issue by pikhovkin** [DevExpress/DevExtreme#4421]
Need the ability to create tables in a horizontal plane with using cellTemplate

For example:

![grid_horizontal_cell_template](https://user-images.githubusercontent.com/630071/41585746-9a949624-73b3-11e8-9fbb-79dd4c088f73.png)

**Comment by AlekseyMartynov** [comment]
Based on the picture, it looks that you need a UI component called 'Vertical Grid'.
We don't have a vertical grid in DevExtreme, but to some extent it can be simulated with a Row Template.
Check the discussion at https://devexpress.com/issue=T543407.

**Comment by pikhovkin** [comment]
Row template must be string type in my task.

Thanks for `Vertical Grid` keyword.

**Comment by AlekseyMartynov** [comment]
> Row template must be string type in my task.

If you have a specific question about DataGrid templates, please ask.

**Comment by pikhovkin** [comment]
Resolved by compiling a script-tag template in the browser (with using [babel-standalone](https://github.com/babel/babel-standalone)) and wrapping over the DataGrid.rowTemplate
