### ISSUE TITLE
Can't type year in DateBox when pickerType="native"

### ISSUE THREAD

**Issue by botura** [DevExpress/DevExtreme#4484]
### Steps to Reproduce:

1. Go to the API reference: [DateBox](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/)
2. Change pickerType property: `pickerType: "native"`
3. Try to type the current date (my date format is dd/mm/yyyy): day and month are ok, but I can't type the  year, it seens that only the last digit is changing:

Typing 2 -> 1902
Typing 0 -> 0000
Typing 1 -> 1901
Typing 8 -> 1908

### Environment Details:
DevExtreme 18.1
Chrome 67 pt-BR

**Comment by mrjohn0011** [comment]
Hello,
I have reproduced this issue and created a public ticket in the [DevExpress Support center](https://www.devexpress.com/Support/Center/Question/Details/T649098). Please subscribe to it to receive a notification of any updates. This issue will be closed on GitHub. Our further discussion will be available in the Support Center.
