### ISSUE TITLE
Add the capability to re-validate a custom validation rule

### ISSUE THREAD

**Issue by valavrov** [DevExpress/DevExtreme#4502]
We have cutom validator. It should receive data from server and after compare result with field value. If result from server are equal field value the field should become invalid. Simple case for login: if login exists on server, then user should choose another.

Solution with setup reevaluate option to true is not acceptable because it leads to a large number of requests to the server.

Example https://next.plnkr.co/plunk/wD5t9ujXJwLOQJg4

### Steps to Reproduce:

1. Type "login" in login field.
2. Change focus.
3. Click submit button.

### Results You Received:

Login field still valid.

### Results You Expected:

Login field shuld be invalid, because valueFromServer are equal with field value.

**Comment by jsdmitry** [comment]
As I understand the problem, the value is valid when you set "oldLogin" to the editor and click on the submit button. This happens because you set another value to valueFromServer on the form submit event before the custom validation rule will check the value of an editor with valueFromServer.

**Comment by valavrov** [comment]
I try to explain.
We have two users whos want to register on our service in one time. Both choose "login" as login. After they taped this, custom validator send request to the server and server said what login are available. But, after users click submit button, we need to revalidate availability of current login, because this login alredy can be assigned to another user. With that situataion our custom validator should set to invalid state, but it's not.

**Comment by JuFrolov** [comment]
It seems you did not understand the problem.
The group validation method ignores custom rules. There is no way to force them into account only when this method is called, this is the problem.

**Comment by AlekseyMartynov** [comment]
> Solution with setup reevaluate option to true is not acceptable because it leads to a large number of requests to the server

An easy trick that should help in this case:

- Add `#loginValidator` to the login validator (like you do with `#groupToCheck`)
- Enable `reevaluate` just before validation on submit:

   ```js
   window.valueFromServer = 'login';

   const customRule = this.loginValidator.validationRules[1];
   customRule.reevaluate = true;
   this.valGroup.instance.validate();
   customRule.reevaluate = false;
   ```

P.S. Even with revalidation, there's a chance that a login becomes unavailable 1ms before the request hits the server. Or even during processing on the server. I understand that there might be requirements for the UI, but maybe you don't need to revalidate and instead can use [optimistic model](https://en.wikipedia.org/wiki/Optimistic_concurrency_control) (if the login is free, it will probably be  free during next minutes).

**Comment by JuFrolov** [comment]
AlekseyMartynov, thx for dirty trick.
It would be nice, nevertheless, to share the possibilities of calling a general check and the main purpose of reevaluate.

**Comment by jsdmitry** [comment]
Currently, we do not have a good solution to resolve this issue. However, we added a task to improve remote validation to our plans for the future.

**Comment by valavrov** [comment]
Thank you.
