### ISSUE TITLE
Add CommonJS branch to localization and vectormap-data artifacts

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme#4526]
For better compatibility.
Currently related Widget Gallery samples fail in CodeSandbox.

Files in question: 
- build/gulp/localization-template.jst
- build/gulp/vectormapdata-template.jst

Suggested change:
See vectormap-data.js in https://codesandbox.io/s/2x7l3k5qwn

**Comment by San4es** [comment]
Closed in 17.2, 18.1 and 18.2 via #4527, #4540 and #4541.
