### ISSUE TITLE
[18.1.4] It's not possible to set default value for grid editor's grouped column

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#4528]
### Steps to Reproduce:

1.  Define a grid
2.  Enable grouping
3.  Enable editing plugin with adding and editing options
4. Set default values for some editor fields using "onEditorPreparing" callback
5. Press the "Add a row" button

### Results You Received:
The grouped fields do not have default values set while not grouped ones do have them.

### Results You Expected:
All fields should have default values

### Demo
https://codesandbox.io/s/9zmrzn0wzw

### Environment Details:
DevExtreme: 18.1.4
DevExtreme-Angular: 18.1.4

**Comment by komarovalexander** [comment]
Hi @hakimio 

When you add a new row, you can set default values in [onInitNewRow](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onInitNewRow)

I've modified your example: [https://codesandbox.io/s/ppqy01lmqq](https://codesandbox.io/s/ppqy01lmqq)

**Comment by hakimio** [comment]
@komarovalexander 
Thanks for the info. I didn't know that.
Anyway, I still think it's strange that you can set value for one field but not the other in "onEditorPreparing()". Do you think it works as intended?

**Comment by komarovalexander** [comment]
@hakimio 
Yes, this works as expected. In onEditorPreparing, you can customize an editor, and setValue is a method that you should call to change a cell value after the editor's value is changed. If you need to set a default value for a new row, you shouldn't use onEditorPreparing.
