### ISSUE TITLE
LoadPanel Enhancements

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#4615]
Is there any reason why the LoadPanel is so complex to use when compared to something like BlockUI?  What cant be done to make this easier to use there should just be a way to call it like the dxToast.
IE https://js.devexpress.com/Documentation/ApiReference/Common/utils/ui/#notifymessage_type_displayTime

**Comment by jsdmitry** [comment]
Based on the provided information, it is difficult to determine why it is complex to use dxLoadPanel. Please describe issues that you faced when using the dxLoadPanel widget.

**Comment by bbakermmc** [comment]
Easy.  I dont want to write a div to the page and then toggle hide/show.  I just want to call .LoadPanel from the DevExtreme.UI Namespace and have it just work.

**Comment by jsdmitry** [comment]
Currently, we are not planning helpers to initialize dxLoadPanel without creating a div element. However, you can create a PR for us with your implementation.

**Comment by bbakermmc** [comment]
Please reopen and add to back log or provide a viable solution and dont just close the issue.  @jmbucknall Please address the lack of quality and premature closing of issues for your paying customers.
