### ISSUE TITLE
How to customize an alert

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#4616]
For the alerts, can it take a type to mimic SweetAlerts https://sweetalert2.github.io/.
It looks like an alert is just a popup?  Can it take custom templates?

**Comment by hakimio** [comment]
You have few different [dialog methods](https://js.devexpress.com/Documentation/ApiReference/Common/utils/ui/dialog/) to choose from.

**Comment by mrjohn0011** [comment]
Hello,
You can use dxPopup to get the required behavior. I have created a [CodePen ](https://codepen.io/anon/pen/vaBKYq) to demonstrate how to do this. The current issue will be closed. If you have any questions, feel free to contact us in the [DevExtreme support center](https://www.devexpress.com/Support/Center/).

**Comment by bbakermmc** [comment]
As usual you guys get it wrong.  Ill be sure to inform your VP that youre closing issues w/out actually answering the root issue.
I dont want to have to write a div tag to the page to use an alert, isnt it amazing how all the other 3rd part alerts do it with just a simple   .alert(message, title, options).   Send me an example of a custom defined template using that method.

**Comment by hakimio** [comment]
@bbakermmc Have you looked at the documentation page I have linked to? There is [DevExpress.ui.dialog.custom](https://js.devexpress.com/Documentation/ApiReference/Common/utils/ui/dialog/Methods/#customoptions) you can use.

**Comment by bbakermmc** [comment]
Clearly I looked at it.  Now you sent me a codepen that doesnt even use it.  Now tell me how useful that is.  Try sending relevant examples if you're going to suggest 1 thing, and also you sent 2x diff examples one for "custom" and 1 for using a popup. 

So send me a codePen thats easy to implement what Im looking to do.

**Comment by bbakermmc** [comment]
Please reopen and address the issues or add to back log.  @jmbucknall Please address the lack of quality and premature closing of issues for your paying customers.
