### ISSUE TITLE
Toast Enhancements

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#4617]
Its 2018 and we still cant render html or even '/r/n' w/out having to overwrite the message style?

Add option UseHtml = False.
Modify this line to render text/html? https://github.com/DevExpress/DevExtreme/blob/710d7b4fd9e582c53f97138f3e678aa3ce0356d5/js/ui/toast.js#L346

**Comment by hakimio** [comment]
From the documentation:
>  you can combine the HTML markup for the template in the contentTemplate function
[Toast > Customize the Content](https://js.devexpress.com/Documentation/Guide/Widgets/Toast/Customize_the_Content/)

**Comment by bbakermmc** [comment]
I dont want to write a DIV to the page to make this work.  Try again.

**Comment by jsdmitry** [comment]
Hi,
 
The [notify(options, type, displayTime)](https://js.devexpress.com/Documentation/ApiReference/Common/utils/ui/#notifyoptions_type_displayTime) method provides an overload with the options parameter. You can use the [notify(message, type, displayTime)](https://js.devexpress.com/Documentation/ApiReference/Common/utils/ui/#notifymessage_type_displayTime) method to create content. So, you don't have to create a separate DIV element in this case. 
For more detailed assistance regarding this API, feel free to contact our [Support Center](https://www.devexpress.com/Support/Center/Question/Create)

**Comment by bbakermmc** [comment]
Again, you close something w/out it being closed or addressed.  I want to render HTML using the .notify method.  Why if you read my first message it says make a property and implementing rending of HTML.

Please reopen the ticket.  Ill be sure inform @jmbucknall  of the lack of quality responses and premature closing of issues on GitHub.

**Comment by BingoRUS** [comment]
Hi, @bbakermmc!
According to our [Guidelines for Contributing](https://github.com/DevExpress/DevExtreme/blob/18_1/CONTRIBUTING.md#issues-and-feature-requests) we do not guarantee to implement all user requests on GitHub and recommend you using our [Support Center](https://www.devexpress.com/Support/Center/Question/Create) to post your questions and feature requests instead. You still can open a GitHub issue to inform us about critical bugs.
