### ISSUE TITLE
Function with error

### ISSUE THREAD

**Issue by valavrov** [DevExpress/DevExtreme#4643]
We have issue in filter builder with boolean values. After some research I found function that have error. In https://github.com/DevExpress/DevExtreme/blob/18_1/js/ui/filter_builder/utils.js
`function getFilterOperations(field) {
    var result = field.filterOperations || (field.lookup && LOOKUP_OPERATIONS) || DATATYPE_OPERATIONS[field.dataType || DEFAULT_DATA_TYPE];
    return extend([], result);
}`

If **field.filterOperations** be an empty array, then we have problems, because it will be assigned to result. But right way is check **field.filterOperations** **_lenght_** before assigned.

In my case I expect for **DATATYPE_OPERATIONS[field.dataType]** will be assigned to result, but that does not happen for the reason described above.

**Comment by komarovalexander** [comment]
@highwaymanorama 
We will process this issue in the context of the following Support Center thread: [dxDataGrid - Filter builder throws errors when boolean data type columns are used](https://www.devexpress.com/Support/Center/Question/Details/T653737/dxdatagrid-filter-builder-throws-errors-when-boolean-data-type-columns-are-used)
You can subscribe to it to receive a notification of our progress.
