### ISSUE TITLE
Validation error message inside DxDatagrid is hidden behind a grouped line

### ISSUE THREAD

**Issue by Yura13** [DevExpress/DevExtreme#4645]
### Steps to Reproduce:
![image](https://user-images.githubusercontent.com/17030431/42504635-0bc888ae-8445-11e8-8b50-8d4728f0db47.png)

1. Parameters of grid:
                  [dataSource]="data"
                  [columns]="columns"
                  [showRowLines]="true"
                  [allowColumnResizing]="true"
                  columnResizingMode="widget"
                  [scrolling]="{showScrollbar: 'always'}"
                  [selection]="{mode: 'multiple'}"
                  [selectedRowKeys]="[]"
                  [sorting]="{mode: 'none'}"
                  [paging]="{enabled: false}"
                  [editing]="{mode: 'cell', allowUpdating: true}"
                  [groupPanel]="{visible: true, allowColumnDragging: false}"
                  [grouping]="{allowCollapsing: false}"
2. We use custom validation on column with validationCallback function.
3. Also grid has few first fixed columns.

### Results You Received:
Validation error message inside DxDatagrid is not hidden behind a grouped line

### Results You Expected:
Validation error message inside DxDatagrid is hidden behind a grouped line

### Environment Details:
devextreme: 17.2.7
devextreme-angular: 17.2.7
angular: 6.0.6

**Comment by Alyar666** [comment]
Hello,

We will process this issue in the context of the following Support Center thread:
[dxDataGrid - Validation error message is hidden behind a grouped row when there are fixed columns](https://www.devexpress.com/Support/Center/Question/Details/T653933)
