### ISSUE TITLE
Select Box Value doesn't change when using keyboard and clicking out by mouse

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4770]
### Steps to Reproduce:

1. Open this link https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/Angular/MaterialBlueLight/
2. Click on second select box on screen to open it
3. Use keyboard arrow down
4. Navigate to Super Led 42 (or other records) by arrow down
5. Now without pressing any other keys, click out side of select box

### Results You Received:
Select box shows "Super Led 42", and value shows "HD Video Player" (in current product label)

### Results You Expected:
Value and Select box both show "Super Led 42" or both show "HD Video Player"

### Environment Details:
"devextreme": "^18.1.5-pre-18199",
Same is reproducible on 18.1.4 (and my be other versions)

![image](https://user-images.githubusercontent.com/10086092/43012637-ab2d7cca-8c14-11e8-8024-c66866386049.png)

**Comment by mrjohn0011** [comment]
Hello!
 
I have reproduced this issue and created a [ticket in the DevExtreme support center](https://www.devexpress.com/Support/Center/Question/Details/T657550/). The issue on GitHub will be closed. We will research this problem in the context of the newly created ticket. Please subscribe to it to receive any news.
