### ISSUE TITLE
"Is any of" and "is none of" filters doesn't work in filter panel

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4781]
### Steps to Reproduce:
https://stackblitz.com/edit/angular-8be2dm

1. Open above link (Open the result page in new window, original windows doesn't render css)
2. Click on Create Filter on filter panel
3. Add condition for employee column
4. Change "Contains" to "is any of"
5. Select two records
6. Click on OK

### Results You Received:
Filter dialog closed, and filter doesn't apply

### Results You Expected:
Filter applied to grid

### Environment Details:
		"devextreme": "18.1.5-pre-18201",
		"devextreme-angular": "18.1.4",

**Comment by komarovalexander** [comment]
@RezaRahmati 
We will process this issue in the context of the following Support Center thread: [dxDataGrid: The value for the "Is any of" and "Is none of" operations cannot be changed if filterBuilderPopup has closeOnOutsideClick=true](https://www.devexpress.com/Support/Center/Question/Details/T657917/dxdatagrid-the-value-for-the-is-any-of-and-is-none-of-operations-cannot-be-changed-if)
You can subscribe to it to receive a notification of our progress.
