### ISSUE TITLE
Group summaries come over fixed columns when scrolling horizontally

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4813]
### Steps to Reproduce:

1. Open this link and open result in new browser, https://codesandbox.io/s/yqkkxylyox
2. Resize browser so that there will be horizontal scrollbar on grid
3. Now try to scroll

### Results You Received:
1. Employee column grouping text is scrolling with grid
2. Summary items (Max : xxx) are comming over fixed columns

### Results You Expected:
1. Emloyees column grouping text not moving
2. Summary items (Max : xxx) going under fixed columns

### Environment Details:

devextreme: 18.1.4

![image](https://user-images.githubusercontent.com/10086092/43215872-5a0b315c-900b-11e8-87ed-19b3ee921f94.png)

![image](https://user-images.githubusercontent.com/10086092/43215885-612be224-900b-11e8-9fe2-3c4322888014.png)

**Comment by AntonSermyazhko** [comment]
We will process this issue in the context of the following Support Center thread: [DataGrid - Group summaries come over fixed columns when scrolling horizontally](https://isc.devexpress.com/Thread/WorkplaceDetails/T659127)
You can subscribe to it to receive a notification of our progress.

**Comment by RezaRahmati** [comment]
@AntonSermyazhko thanks, it seems that ticket is marked as duplicate with https://www.devexpress.com/Support/Center/Question/Details/T611868/datagrid-a-group-text-is-moved-during-scrolling-when-using-fixed-columns-and-a-group

BTW none of the plunkers are working and seems that is not solving my issue, can you please elaborate?

**Comment by RezaRahmati** [comment]
@andrewtelnov Please see attached file, it shows why it's a bug and is not duplicate with the other one

It works fine when column doesn't have summary (Type column in my screen shot), and doesn't work when you group with columns with summary (Appraisal Status column in my screen shot)
![group-summary](https://user-images.githubusercontent.com/10086092/43336058-618bdc80-919e-11e8-8e70-fed9d594f392.gif)

**Comment by AntonSermyazhko** [comment]
@RezaRahmati, thank you for additional information. We see that when you group by the "Appraisal Status" column, the workaround we suggested doesn't work.
 
We would like to reproduce this case. Would you please modify the [initial example](https://codesandbox.io/s/yqkkxylyox) so that it demonstrates the issue. We tried to add a group summary for the "State" column and group by it but the workaround worked fine.

**Comment by RezaRahmati** [comment]
@AntonSermyazhko I updated the sample, please see this link https://codesandbox.io/s/z3xx8opzlx

In this sample "Sales Amount" column has **grouping** and is **fixed**.
Now if you group by "Sales Amount" the issue happens, if you group by other columns it's working fine.

![grouping-2](https://user-images.githubusercontent.com/10086092/43468684-9ca774c0-94b2-11e8-88ff-a44dd43d4174.gif)

And this is same sample with workaround applied, which issue still reproducible
https://codesandbox.io/s/jl74rv6m8v

**Comment by AntonSermyazhko** [comment]
@RezaRahmati Unfortunately, I did not find a workaround in the last example.
I forked the last sample and added a workaround to it (https://codesandbox.io/s/l56o0pmp97). As a result, the problem was solved.
Could you please check if this problem persists in this example?

**Comment by RezaRahmati** [comment]
@AntonSermyazhko Thanks for response, yeah I see in your sample it's working, and I found out why it wasn't working for me, the fake column should be after all of initial fixed columns and if there is no initial fixed column should be the last column in grid (in your sample if you move it to the beginning it stops working)

Btw although work around solved my issue, I think it's good idea devexpress team address the issue and consider it as a bug for future releases

**Comment by AntonSermyazhko** [comment]
@RezaRahmati Right. The fake column should be at the end of all fixed column to prevent this issue. 
Also, I recommend placing a fake column at the end of all columns and setting [allowReordering](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#allowReordering) to "false" for the fake column to ensure that the fake column will be at the end of the fixed columns.
I have modified the previous [example](https://codesandbox.io/s/l56o0pmp97) to demonstrate this approach.

**Comment by RezaRahmati** [comment]
@AntonSermyazhko After we applied this workaround we are facing another issue, if we drag and drop a non fixed column to the fixed area, it goes to the end, and if we don't apply this workaround it goes to the begining

Please see this link [https://codesandbox.io/s/k20nzkojx3](https://codesandbox.io/s/k20nzkojx3)
Which workaround is applied, now drag and drop `city2` column and it goes to the end, while we expecting to go to the begining

should I report another bug for it?

![reordering-column-goes-to-end](https://user-images.githubusercontent.com/10086092/45116132-dc203180-b11f-11e8-95ca-c538e77fbc18.gif)
