### ISSUE TITLE
header filter values should be distinct after applying format with precision

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4817]
### Steps to Reproduce:

1. Open this link https://codesandbox.io/s/vypqw4jzn3
2. Open header filter for Sales Amount

### Results You Received:
- $11,800.00 is displayed 3 times 
- Seems it distinct filter values and then apply format on it, which should be the other way, first format then distinct

### Results You Expected:
- $11,800.00 should be displayed 1 time

Note: Please see the difference between Sales Amount, and Sales Amount Orig

### Environment Details:
18.1.4

![image](https://user-images.githubusercontent.com/10086092/43221691-990a9b9e-901b-11e8-93de-a879b82133a0.png)

![image](https://user-images.githubusercontent.com/10086092/43221708-aa665720-901b-11e8-8467-09a7194280cf.png)

**Comment by komarovalexander** [comment]
@RezaRahmati 
 
In your scenario, you can set the groupInterval 
[https://codesandbox.io/s/5v0z8xzz84](https://codesandbox.io/s/5v0z8xzz84)
 

> Seems it distinct filter values and then apply format on it

Yes, you are right, dxDataGrid operates this way.
 
As for your suggestion 

> should be the other way, first format then distinct

it is not quite clear to me. Let's imagine you have the following values in your header filter: 100.002, 100.003, 100.004. If you wish to group them by a display value, you will get a single value - 100.00. However, it is unclear what value should be used in the filter expression when a user selects it. Would you please describe your idea in greater detail?

**Comment by RezaRahmati** [comment]
thanks for response, this is what I meant

**Original Data:**
1,100.002
2,100.003,
3,100.004,
4,100.002,
5, 99.000

**What user see in grid (Apply format on column)**
1, 100.00
2, 100.00
3, 100.00
4, 100.00
5, 99.00

**What user expected to see in header filter**
100.00
99.00

**What user expect to see after choosing 100.00 in header filter**
1, 100.00
2, 100.00
3, 100.00
4, 100.00

So actually user doesn't know there are fractions as he see the values rounded by 2 previsions, so what he expect is to act on what he really see on screen

**Comment by komarovalexander** [comment]
Thank you for clarification. The [groupInterval](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/headerFilter/#groupInterval) should be used there
https://codesandbox.io/s/5v0z8xzz84
