### ISSUE TITLE
Grouping is broken when there are many columns and accessing both pageIndex and options same time in onContentReady

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4840]
### Steps to Reproduce:

1.  This issue is tricky to reproduce, open this link https://stackblitz.com/edit/devextreme-201-grid-grouping-issue
2. Group by City, then Empoyee, then Order Date
3. Expand first grouped record (City: Anaheim, CA)
4. Expand Employee: Harv Mudd

### Results You Received:
It should expand the group and show records

### Results You Expected:
It just show some text as column

Note
In app.component.ts if you comment out line 54 (which access to pageIndex() and pageCount()) or if you comment out line 55 (set instance.option) it works with no issue, **the issue happens when you have both lines together**

### Environment Details:
Reproducible on both 
18.1.5-pre-18201 and 18.1.4

![image](https://user-images.githubusercontent.com/10086092/43275416-bce84ea8-90cf-11e8-92ba-8ef65fc3d627.png)

**Comment by AlekseyMartynov** [comment]
Thanks for reporting.
Please use built-in placeholders instead ([docs](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/pager/#infoText)):

```js
this.dataGrid.instance.option('pager.infoText', 'My Page {0} of {1}');
```

I see that accessing `pageCount()` from `onContentReady` breaks grouping.
We'll check why and update this issue.

**Comment by RezaRahmati** [comment]
@AlekseyMartynov for simplicity of reproducing issue I remove unnecessary codes there, actually I really want to customize page info as below

```
let infoText = '';

		if (this.filteredCount > 0)
		{
			infoText = `Page ${this.grid.instance.pageIndex() + 1} of ${this.grid.instance.pageCount()}`;
		}

		if (this.totalCount > 0)
		{
			if (this.filteredCount !== this.totalCount)
			{
				infoText += ` (${this.filteredCount} of ${this.totalCount} found)`;
			}
			else
			{
				infoText += this.totalCount === 1 ? ' (1 item)' : ` (${this.totalCount} items)`;
			}

			if (this.configuration.selectionMode === DataGridSelectionMode.Multiple)
			{
				infoText += this.selectedCount === 0 ? ' [no items selected]' :
					this.selectedCount === 1 ? ' [1 item selected]' : ` [${this.selectedCount} items selected]`;
			}
		}

		this.grid.instance.option('pager.infoText', infoText);
```

**Comment by RezaRahmati** [comment]
@AlekseyMartynov btw as you suggested I changed the code to below, now it runs with no issue :D

```
let infoText = '';

		if (this.filteredCount > 0)
		{
			infoText = 'Page {0} of {1}';
		}

		if (this.totalCount > 0)
		{
			if (this.filteredCount !== this.totalCount)
			{
				infoText += ` (${this.filteredCount} of ${this.totalCount} found)`;
			}
			else
			{
				infoText += this.totalCount === 1 ? ' (1 item)' : ` (${this.totalCount} items)`;
			}

			if (this.configuration.selectionMode === DataGridSelectionMode.Multiple)
			{
				infoText += this.selectedCount === 0 ? ' [no items selected]' :
					this.selectedCount === 1 ? ' [1 item selected]' : ` [${this.selectedCount} items selected]`;
			}
		}

		this.grid.instance.option('pager.infoText', infoText);
```
