### ISSUE TITLE
instance.ClearFilter doesn't work with Filter Panel when Operand is something other than 'AND'

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#4855]
### Steps to Reproduce:

Scenario 1
1.  Open this link https://codesandbox.io/s/zr74x6684x
2.  Click on "Clear Filter"in filter panel
3.  Confirm filter clears
4.  Refresh the page
5. Click on "My Clear Filter"

### Results You Received:
Filter doesn't change, and no error on console

### Results You Expected:
Filter clear

Scenario 2
1.  Open this link https://codesandbox.io/s/zr74x6684x
2.  Click on filter to edit the filter
3.  Change Operand to "And"
4.  Click on "Clear Filter"in filter panel
5.  Confirm filter clears
6.  Refresh the page and do step 2,3
7. Click on "My Clear Filter"

### Results You Received:
Filter clears partially and no error on console
(Seems second scenario is related to customFilters, if you don't have custom filters it works fine)

### Results You Expected:
Filter clear

### Environment Details:
18.1.4

![filter](https://user-images.githubusercontent.com/10086092/43343476-63573800-91b4-11e8-832c-c68f4d3cfa6f.gif)

**Comment by komarovalexander** [comment]
@RezaRahmati 
I've reproduced this issue and created a public ticket in the [DevExpress Support Center](https://www.devexpress.com/Support/Center/Question/Details/T659816/datagrid-clearfilter-does-not-work-properly-if-filter-sync-is-enabled).
You can subscribe to it to receive a notification of our progress.
 
As a workaround, you can set filterValue to null.
[https://codesandbox.io/s/wnqk284y4w](https://codesandbox.io/s/wnqk284y4w)

**Comment by RezaRahmati** [comment]
@komarovalexander thanks, just notices in the example you provided the filter is "AND" so they might just fix that, if the filter was "OR" the behavior is different and this is the original bug, so may be it's beneficial to update your to "OR", or even updating your ticket in devexpress and mentioning it

for workaround, does it clear all kind of filters including row filter, header filter, search panel?

**Comment by komarovalexander** [comment]
>  just notices in the example you provided the filter is "AND" so they might just fix that, if the filter was "OR" the behavior is different 

I've updated the ticket, thanks

> for workaround, does it clear all kind of filters including row filter, header filter, search panel?

It clears the row filter and header filter. In the case of the search panel, you can call clearFilter ("search") - it should work for search panel.
