### ISSUE TITLE
dxForm and Rails

### ISSUE THREAD

**Issue by dmajkic** [DevExpress/DevExtreme#494]
I am experimenting with Rails and DevExtreme.

Rails, by default, is expecting name attributes of input elements to be like `model[field]` for example `name="article[caption]"`. At the moment, dxForm items ignores `name` for an item if there is `dataField` specified, and if formData contains keys like `"model[field]"` - binding is broken. 

Is it possible to force name of generated input element in dxForm?

### Environment Details:

DevExtreme 17.1

**Comment by jsdmitry** [comment]
You can set the name option for [editorOptions](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxForm/Item_Types/SimpleItem/#editorOptions) of a simple item as shown in the following example:

    $("#form").dxForm({ 
        formData: { name: "test" }, 
        items: [ {
            dataField: "test", 
            editorOptions: { 
                name: "customName" 
            } 
        }] 
    })

**Comment by dmajkic** [comment]
Thank you!
