### ISSUE TITLE
DxTagBox doesn't work with OData store and "showSelectionControls" option enabled

### ISSUE THREAD

**Issue by etumyan** [DevExpress/DevExtreme#5000]
Hello! Seems there is a bug with DxTagBox component.

![dx-tag-box-issue](https://user-images.githubusercontent.com/1096104/43914373-69f8a46c-9c10-11e8-9994-294f74fb2a7c.png)

I have slightly modified one of your samples to demonstrate the issue: https://codesandbox.io/s/x7o933xonq.

Environment: DevExtreme 18.1.5, Chrome 67, Windows 10.

**Comment by AlekseyMartynov** [comment]
Extra notes: 
- `grouped=true`

**Comment by mrjohn0011** [comment]
Hello!
 
I have reproduced this issue and created a ticket in the [DevExtreme support center](https://www.devexpress.com/Support/Center/Question/Details/T663390). The issue on GitHub will be closed. We will research this problem in the context of the newly created ticket. Please subscribe to it to receive any news.
