### ISSUE TITLE
Column filter panel opens in top left corner in firefox

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#5018]
### Steps to Reproduce:

1. Open this stackblitz https://stackblitz.com/edit/devextreme-1815-grid-column-filter-firefox-issue in **FIREFOX** (it doesn't reproduce constantly in chrome)
2. Filter "employee" column and choose "blanks"
3. Click on "employee" to sort
4. Filter "employee" and "Select All"
5. Click on Filter again

### Results You Received:
Column filter panel opens in top left

### Results You Expected:
Column filter panel should open under employee column

### Environment Details:
devextreme 18.1.5 (it's reproducible on 18.1.4 as well)
browser: Firefox

![grid-filter-firefox-issue](https://user-images.githubusercontent.com/10086092/44044662-4b313558-9ef4-11e8-8b79-9434ea4fa72e.gif)

**Comment by AntonSermyazhko** [comment]
I've reproduced this issue and created a [public ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T664522) in the DevExpress Support Center.
You can subscribe to it to receive a notification of our progress.

**Comment by RezaRahmati** [comment]
thanks, btw I don't see any description or steps to reproduce or link to this page in there

![image](https://user-images.githubusercontent.com/10086092/44151917-fa8a97e6-a071-11e8-8e7c-277bc242fd80.png)

**Comment by AntonSermyazhko** [comment]
@RezaRahmati,
Thank you for your remark. I just finished with the description.

**Comment by AntonSermyazhko** [comment]
We're processing the issue in the context of a [public ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T664522) in our Support Center.
The issue on GitHub will be closed. Please subscribe to it to receive any news.

**Comment by alexander-kotov-dx** [comment]
We have fixed the issue in the context of the [T664522](https://www.devexpress.com/Support/Center/Question/Details/T664522/) ticket. You can see the fix in #5397
