### ISSUE TITLE
About HTML Editor

### ISSUE THREAD

**Issue by FabianoCastro** [DevExpress/DevExtreme#5156]
Hi

I'm excited to use the "HTML Editor" in my projects, any news on?

I saw the "Drawner", spectacular 👍👍👍👍👍

**Comment by dxbykov** [comment]
Hi @FabianoCastro,

Thank you for your feedback and interest in our new features. I've just created a couple of discussion pages regarding the features you've mentioned. Check them out and feel free to leave your feedback in comments or privately via our [Support Center](https://www.devexpress.com/Support/Center/).
 
- [WYSIWYG editor discussion page](https://github.com/DevExpress/DevExtreme/issues/5163)
- [Drawer discussion page](https://github.com/DevExpress/DevExtreme/issues/5164)
