### ISSUE TITLE
New WYSIWYG text editor with support for HTML and Markdown formats

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#5163]
# The Problem
Certain business web applications should allow users to format textual content via the WYSIWYG editor, and store this content in HTML or Markdown format. However, DevExtreme does not provide an out-of-the box solution: you have to use third-party editors' API and adapt them to DevExtreme themes.
# The Proposed Solution
In v18.2, we are introducing a new text editor with basic text formatting capabilities.

Supported features:

* Bold, italic, underlined formats
* Headers
* Lists (ordered and unordered)
* Text alignment
* Code blocks
* Quotes
* Hyperlinks
* Text font, size, color changes (HTML only)
* HTML and Markdown formats support
* Inserting images (as a link or base64)
* Embedded blocks. Custom unchangeable content, for instance, mail-merge placeholders (%username% or similar) 
* Copy-paste rich content (and removing unsupported formats)
* Custom formats
* Additional features based on your feedback

Future features (v19.1 and later):

* Support for tables
* User mentions via @
* Inline formatting toolbar (bubble toolbar)
* Resizing, drag/drop and copy-paste upload, etc. media blocks
* Additional features based on your feedback

Features the text editor does not support:

* Layout editing. This text editor is designed to format textual content only.
* Full HTML support. Saving HTML content is not possible because the editor supports only a specified subset (built-in or custom) of formats. Everything else is discarded.

## API and Code Examples
Coming soon.

# We Need Your Feedback
## Take a Quick Poll

[Does the new text editor meet your needs?](https://docs.google.com/forms/d/e/1FAIpQLSebekn5qa8OHInKnq5xU83LC681Bj4os591K3zp7nal5APC_Q/viewform)

## Live Sandbox
[jQuery](https://codepen.io/Doka/pen/pxLpBV?editors=1010)

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by jimbodeni** [comment]
Hi guys,

I'm surprised tables are not in from day one to be honest. Any chance of this happening?

Other than that, looks good. The only thing we would want in the future is mail merge functionality similar to your ASP control to replace placeholders with data passed in.

**Comment by dxbykov** [comment]
Hi @jimbodeni,

Thanks for your feedback. We agree that table support is important. On the other hand, we know that it might produce numerous potential issues (according to our experience with the ASP.NET HTML editor). We are going to apply another approach to content editing in our client-side JS editor. It won't be the same as for the ASP counterpart. Having tested the basic formatting features with the new editor core, we'll extend its functionality to support tables. 
 
Regarding the mail merge functionality, we expect to support it in the upcoming 18.2 release. We'll update this thread with code examples as soon as we are done with it.

**Comment by jimbodeni** [comment]
Hi @dxbykov 

Great news about the mail merge. We're wanting to use this as a letter editor but without table support, we probably won't be able to use it from day one.

Will there be any RTF support?

Thanks

**Comment by dxbykov** [comment]
We don't plan built-in support for RTF at the moment. But I believe it will be possible to convert HTML to RTF using some third-party JS or server-side library. We might also port our [ASP.NET Rich Text Editor](https://demos.devexpress.com/ASPxRichEditDemos/) to the client-side JS in the future.

**Comment by anderschbe** [comment]
Is there a roadmap / broad ETA for this? I would be very interested to use this for a slowly developed project, though if a first usable version will be out in 2019 only ... well than I'd have to look elsewhere.

Basically is the ETA in weeks or months, knowing that things are done when they are done?

**Comment by dxbykov** [comment]
We expect to release the first preview (CTP) in one or two months. If no major issues are found, we may release RTM by the end of 2018.

**Comment by Shiko1st** [comment]
Great!

**Comment by artstalker** [comment]
Hi @dxbykov,

I would like to hear your comments on this one : 

> Full HTML support. Saving HTML content is not possible because the editor supports only a specified subset (built-in or custom) of formats. Everything else is discarded.

Does that mean that you do not support saving to HTML? Our usage for this is for editing emails and thus saving and loading HTML with CSS / style support is a must.  (Although limited support would be a-ok)

**Comment by dxbykov** [comment]
Hi @artstalker,

> Does that mean that you do not support saving to HTML?

No, it doesn't. Saving/loading to/from HTML will be supported. We won't support every tag/attribute from the HTML specification. For instance, it's unlikely you'll be able to design complex email layouts with it. It's a text editor at first place. Nevertheless, we expect to support the `class` and `style` HTML attributes with custom values that you can use to apply custom formats to email content.

**Comment by bturko** [comment]
Is it planned to support the insertion of formatted text (numbered lists, bullets etc., including multi-level lists) from for example MS Word? 
Will it be possible to customize the control panel?

**Comment by dxbykov** [comment]
Hi @bturko,

> Is it planned to support the insertion of formatted text (numbered lists, bullets etc., including multi-level lists) from for example MS Word?

Yes, we have this task on our To-Do list, but it may not be fully implemented in v18.2. If such, we'll complete it in further product updates.

> Will it be possible to customize the control panel?

Yes, it will be possible to add/remove items to/from the editor toolbar. Are there any specific features you'd like to implement? If you could share them, we would be able to consider their built-in implementation in future releases. Thank you for your input.

**Comment by Shiko1st** [comment]
> Are there any specific features you'd like to implement? If you could share them, we would be able to consider their built-in implementation in future releases. Thank you for your input.

I have one feature important to our applications. It is about inserting special fields for mail merge.
For example, we may use this editor to create templates for notification messages or so on. It will be good to have a possibility to insert a field from predefined set of tags.

**Comment by jimbodeni** [comment]
I would agree with @Shiko1st - this would be good feature to have.

**Comment by dxbykov** [comment]
> It will be good to have a possibility to insert a field from predefined set of tags.

Yes, We plan to implement it.

**Comment by rrein** [comment]
Couple of questions

1. A little confused, it was mentioned that the first preview (CTP) would be [available in one to two months](https://github.com/DevExpress/DevExtreme/issues/5163#issuecomment-421024859), but I thought that the HTML Editor was going to be included as part of 18.2 which is slated for mid-November. Is what is released in 18.2 considered the CTP?
2. If the HTML Editor is considered a CTP can it be used in a production application?
3. Is there a way to bring these bits into a demo asp.net core web app now to see whether the existing functionality would meet our needs? Based on the initial list and the comments it seems like it meets our needs but I would like to demo it for our business.

**Comment by dxbykov** [comment]
Hi @rrein,

1. HTML Editor is a quite complex control. Before making it RTM, we'd like to make sure it doesn't have any fundamental issues preventing using it in production. So, with the initial 18.2 release, we'll ship it as fully functional CTP. Once more people try it in their specific use cases and don't find any showstoppers, we'll make it RTM in the next minor update. 

2. You can use it in production if you find it works properly in the scenarios you need. You also should be aware of possible API or behavior changes between the CTP and RTM releases.

3. We are preparing a preview release that we expect to publish soon. We'll announce it in this thread. Thanks for being interested.

**Comment by ghost** [comment]
Any news about your preview release ??

**Comment by FabianoCastro** [comment]
Hi @reeax-ch, I downloaded last release "18.2 Sprint 8" and I´m testing it

**Comment by jeff-worm-osii** [comment]
Hi @dxbykov,

I've just downloaded the 18.2 beta today and I have been playing around with the HTML editor through devextreme angular. I have had a couple of issues with it, I have a couple of questions about using it, and I thought this would be a good place to post this.

This is roughly my html set up.
```
<dx-html-editor *ngIf='email'
    [(value)]='email.message'
    valueType='html'>
    <dxo-toolbar [items]='messageItems'></dxo-toolbar>
</dx-html-editor>
```

Issues:
 - When email gets set the editor is ignoring the newlines created by having p tags. For example: `<p>line one</p><p>line two</p>` line one and line two end up being on the same line.
 - Bold, italic, strike through, underline, and clear do not work in IE 11.
 - The messageItems above is the same list of items from your live sandbox provided above (w/o the separators) and I am unable to see most of the icons, I get the feeling I am just missing new icons you have provided, if that is the case where would I be able to get those icons.
 - The outline indicating we are in a text area and the outline around the toolbar are missing. Again I suspect I am missing some css, but I do not know where I would get the for unreleased components as I am currently using a theme, made from the theme builder.
 - The interactive configuration in the documentation for 18.2 is currently not working as it is missing the quill imports.

Question:
 - Is there a way to add my own icon to the toolbar with my own custom handler function that would have knowledge of the cursor position?
 - Is there a way to reset the history to make the undo button not go back anymore in the event that I would change what is passed into the value?

Edit:
Please ignore the issues about missing css and icons. I found where to get them from. "node_modules/devextreme/dist/css/" an apply on of the themes in the angular.json.

Edit2:
Added IE 11 bug and the second question.

**Comment by dxbykov** [comment]
Hi @jeff-worm-osii,

Thank you for your feedback. Allow me to comment on the points you've mentioned:

> The interactive configuration in the documentation for 18.2 is currently not working as it is missing the quill imports.

We have recently fixed this issue.

> When email gets set the editor is ignoring the newlines created by having p tags. For example: `<p>line one</p><p>line two</p>` line one and line two end up being on the same line.

> The messageItems above is the same list of items from your live sandbox provided above (w/o the separators) and I am unable to see most of the icons, I get the feeling I am just missing new icons you have provided, if that is the case where would I be able to get those icons.

We'll make sure these two points work properly.

> Bold, italic, strike through, underline, and clear do not work in IE 11.

We are aware of this issue and are working on it.

> The outline indicating we are in a text area and the outline around the toolbar are missing. Again I suspect I am missing some css, but I do not know where I would get the for unreleased components as I am currently using a theme, made from the theme builder.

Currently, it's by design. We'll discuss the possibility of changing this appearance. A custom editor border can be a workaround for now.

> Is there a way to add my own icon to the toolbar with my own custom handler function that would have knowledge of the cursor position?

Yes, it should be possible. We are working on documentation and demos and will include examples. In the meantime, please refer to the [API reference preview ](https://js.devexpress.com/Documentation/18_2/ApiReference/UI_Widgets/dxHtmlEditor/).

> Is there a way to reset the history to make the undo button not go back anymore in the event that I would change what is passed into the value?

The [clearHistory](https://js.devexpress.com/Documentation/18_2/ApiReference/UI_Widgets/dxHtmlEditor/Methods/#clearHistory) method should help.

I hope this helps. Your feedback and questions are always appreciated.

**Comment by jeff-worm-osii** [comment]
@dxbykov, thanks for the response. As I indicated in the edit of my last message. You can ignore the issue of the missing icons and border. That was a mistake on my end, but if you need any info about the ignored newlines that should come from the p tags just let me know.

**Comment by fguemara** [comment]
Hi, page break, header and footer would be great too !!

**Comment by YousefMMS** [comment]
@dxbykov Thank you for your effort.
Looking for 19.2 version specifically mention feature (@), do you've any idea when this coming.

**Comment by dxbykov** [comment]
FYI: We've published our [official Roadmap](https://community.devexpress.com/blogs/javascript/archive/2019/01/22/devextreme-javascript-2019-roadmap.aspx).

**Comment by dxbykov** [comment]
Thank you to everybody who gave us feedback on the HTML/Markdown Editor features. We've introduced several new features in the [v19.1](https://github.com/DevExpress/DevExtreme/releases/tag/19.1.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/). We will create separate threads for new HTML Editor features to discuss.

**Comment by Prasad814359** [comment]
I had table issues, the table is rendered properly in the editor, but when I get the value through "formControlName" the table part alone is not rendering properly. Just the table outer border alone is rendering but not the lines in between the cells. Kindly help me.

 `<dx-html-editor class="dx-html-container" formControlName="body" >
                <dxo-toolbar [multiline]="isMultiline">
                    <dxi-item name="bold"></dxi-item>
                    <dxi-item name="italic"></dxi-item>
                    <dxi-item name="strike"></dxi-item>
                    <dxi-item name="underline"></dxi-item>
                    <dxi-item name="separator"></dxi-item>
                    <dxi-item name="alignLeft"></dxi-item>
                </dxo-toolbar>
                <dxo-media-resizing
                    [enabled]=true>
                </dxo-media-resizing>
                <span [innerHTML] = "htmlBodyData | safeHTML"></span>
            </dx-html-editor>`

**Comment by DokaRus** [comment]
@Prasad814359 -> https://github.com/DevExpress/DevExtreme/issues/14724#issuecomment-924094470
