### ISSUE TITLE
Export to Excel customization improvements

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#5165]
# The Problem

The following Excel export customization tasks require a lot of custom code because we do not have a suitable API:

To be resolved in v18.2:

* Customize the exported grid cells’ appearance (font, background color, etc)
* Adding a custom header and footer to the exported document 

To be resolved in future updates:

* Export multiple controls to one file
* Export master-detail DataGrid
* Export images

# The Proposed Solution

## Exported Cell Customization

We have introduced a new `customizeExcellCell` callback function that accepts an argument with the source `gridCell` field and a set of target Excel cell fields. This allows you to modify the target Excel cell’s fill, border, font, alignment, data formats, etc. 

```js
   export: {
       enabled: true,
       customizeExcelCell: (e) => {
          if(e.gridCell.rowType === 'data' && e.gridCell.column.dataField === 'caption') {
              if(e.gridCell.data.name === 'HD Video Player') {
                e.backgroundColor = '#00FF00';
              }
          }
       }
   }
```
This approach applies to the [DataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/) and [PivotGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/). 

*Note: Currently, [TreeList](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/) doesn't support export to Excel, but we have plans to support it later.*

## Adding Custom Header & Footer
Coming soon.

# We Need Your Feedback

## Take a Quick Poll

[Do the new export to Excel capabilities meet your needs?](https://docs.google.com/forms/d/e/1FAIpQLSd9vD96Dv1La2sOcnwZYrBR28VMIhgqGO-MKiew3bktludsjg/viewform)

## Live Sandbox

Customization examples:
* [Excel Cell Value](https://codepen.io/dxbykov/pen/MPamQV)
* [Excel Cell Text Appearance](https://codepen.io/dxbykov/pen/ePpWPL)
* [Excel Cell Text Alignment](https://codepen.io/dxbykov/pen/EdGKxK)
* [Excel Cell Background](https://codepen.io/dxbykov/pen/GYpmzj)
* [Excel Cell Number Format](https://codepen.io/dxbykov/pen/ePNLvg)

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by chouex** [comment]
better if able to convert html to styled text
the header and footer usually merge all column and have custom height, 

only plain text cell content support?

**Comment by briosheje** [comment]
Will we be able to solve the issue mentioned here: https://www.devexpress.com/Support/Center/Question/Details/T521083/dxdatagrid-isn-t-exported-to-excel-correctly-when-it-has-columns-with-the-encodehtml with custom styling?

That would be great, since several columns needs some styles applied, but the export should be different.

Example: Column A has a boolean type, which renders "<b>Yes</b>" on true, "<b>No</b>" on false and "<b>Not yet defined</b>" on undefined. When this column is exported, it will export the column as html literally, so there is no way to export that properly. This would be a great fix imho.

**Comment by dxbykov** [comment]
@chouex, @briosheje Thank you for sharing your feedback. I'd like to comment upon the HTML cell content support. We agree that for a web developer, an ideal solution is to export the provided HTML markup and CSS styles 'as is'. Technically, that might lead to the points below:
 
- We should parse and transform HTML/CSS into the XLSX format
- The XLSX format must allow the provided subset of HTML/CSS as a cell value

Both points have their technical limitations. At the current stage, we expect to support formatting at the cell level treating it as a whole. We'll also support the exported cell value customization. For instance, you'll be able to export 'Yes' instead of 'True'. 
 
For some reason, Excel Online doesn't support inner cell content formatting (rich text as a cell value). At the same time, the desktop version does. We'll update this thread once we decide if we can technically support rich cell content and to what extent.

**Comment by sccrgoalie1** [comment]
I see a beta of 18.2 was released today, do the custom header and footer capabilities exist in this version for me to try out?

**Comment by dxbykov** [comment]
@sccrgoalie1 We are working on the custom header/footer features and export customization capabilities in PivotGrid. According to the current development state, they are not yet ready to become a part of the first v18.2 release. They may be shipped with one of the v18.2 minor updates.

**Comment by HaciKandemir** [comment]
I'm waiting for you  to Export master-detail DataGrid. How can I do this now?

**Comment by dxbykov** [comment]
@HaciKandemir Thank you for your interest. There is no easy way to implement master-detail export now. To make it possible, we need to refactor our export core. We hope we can provide this capability in 2019.

**Comment by hassankani** [comment]
v18.2.4 released 27 Dec 2018...does that one now include the above cell customisations for **pivotgrid**, as so far I have only seen the cell customisations come through for datagrid.

**Comment by dxbykov** [comment]
@hassankani No, it's not included into v18.2. We hope to implement similar functionality in our PivotGrid in 2019.

**Comment by wcypierre** [comment]
@dxbykov is there any workaround for the master-detail export?

**Comment by dxbykov** [comment]
@wcypierre For now, the only way you can try is to format a DataGrid cell value into a multi-line text using the [customizeExcelCell](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/export/#customizeExcelCell) callback.

**Comment by dxbykov** [comment]
We are testing a new approach to implementing the Excel Export API and have already covered some new exporting scenarios. Let's continue discussing it [here](https://github.com/DevExpress/DevExtreme/issues/7294). Thanks to everybody for the feedback.
