### ISSUE TITLE
Header is to Long 

### ISSUE THREAD

**Issue by EAGLEliuS** [DevExpress/DevExtreme#5204]
### Steps to Reproduce:

1. Header is to Long 
I don't want hide 
fieldPanel -->showDataFields
![pivot](https://user-images.githubusercontent.com/39791082/44705245-a8665b80-aad0-11e8-8186-e3c0c7d18328.png)

Is there any other way?

### Results You Expected:
I hope to become such a size

![image](https://user-images.githubusercontent.com/39791082/44758947-c9c75600-ab69-11e8-926e-3553e9acbcdd.png)

**Comment by vconst** [comment]
Hi @EAGLEliuS,

Currently, the PivotGrid renders data fields into one row. The only possible solution is to hide data fields from the field panel and use Field Chooser to configure data fields. But, we will consider improving the data fields layout in the future.

**Comment by EAGLEliuS** [comment]
Thank you @vconst
