### ISSUE TITLE
Sankey diagram widget

### ISSUE THREAD

**Issue by roman-simionov** [DevExpress/DevExtreme#5244]
# The Problem

Many analytics and reports in different economy sectors need visualizing data as flows or relationships between parts of systems.

# The Solution

The [Sankey diagram](https://en.wikipedia.org/wiki/Sankey_diagram) can solve this task. We are implementing this diagram as a new [Sankey widget](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/) in v18.2.
This widget supports the following features:

- Several predefined palettes, including a Material-style palette
- Node alignment and reordering
- Title and subtitle
- Client-side exporting and printing
- Tooltip
- User interactions (hover, click)

Below you will find code examples that use jQuery. However, you can use a similar API with React, Vue, and Angular.

## Simple Sankey diagram

Data for Sankey widget should contain [source](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/Configuration/#sourceField) of the flow, [target](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/Configuration/#targetField) of the flow and [weight](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/Configuration/#weightField) of the flow.

```js
$("#container").dxSankey({
 dataSource: [
        { source: "Brazil", target: "Portugal", weight: 5 },
        { source: "Brazil", target: "France", weight: 1 },
        { source: "Brazil", target: "England", weight: 1 },
        { source: "Canada", target: "Portugal", weight: 1 },
        { source: "Canada", target: "France", weight: 5 },
        { source: "Canada", target: "England", weight: 1 }
    ]
});
```

## Links styling

The Sankey widget allows you to style [links](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/Configuration/link/) and [nodes](https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Visualization_Widgets/dxSankey/Configuration/node/). For example, you can instruct the widget to paint links with a gradient.

```js
$("#container").dxSankey({
 dataSource: [
        { source: "Brazil", target: "Portugal", weight: 5 },
        { source: "Brazil", target: "France", weight: 1 },
        { source: "Brazil", target: "England", weight: 1 },
        { source: "Canada", target: "Portugal", weight: 1 },
        { source: "Canada", target: "France", weight: 5 },
        { source: "Canada", target: "England", weight: 1 }
 ],
 link: {
        colorMode: "gradient"
    }
});
```
![links-styling](https://user-images.githubusercontent.com/22078005/44856437-0e401800-ac76-11e8-942f-0f2f7465ec75.png)

# Try It And Give Us Your Feedback

## Live Sandbox

[Angular](https://codesandbox.io/s/yw177mpp4z)
[jQuery](https://codepen.io/anon/pen/oPYMGY?editors=1010)
[React](https://codesandbox.io/s/lrznw0jx4q)
[Vue](https://codesandbox.io/s/k26yvmkr0o)

## Take a Quick Poll

[Does the new Sankey component meet your needs?](https://docs.google.com/forms/d/e/1FAIpQLScfXzYK6Oz-dZBxefc4j3ObxxdrLU_-brlz-F2QTlzTbm_Hlg/viewform)

## Installation

Follow the installation guide from the [release page](https://github.com/DevExpress/DevExtreme/releases) and leave your feedback on this topic.

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by dxbykov** [comment]
Thanks to everybody who gave us early feedback on this feature. The feature is now available in the [v18.2](https://github.com/DevExpress/DevExtreme/releases/tag/18.2.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
