### ISSUE TITLE
Context Menu doesn't disappear on fixed column when scrolling

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#5260]
### Steps to Reproduce:

1.  Open this link [https://codesandbox.io/s/ox42yq931y](https://codesandbox.io/s/ox42yq931y)
2.  Right click on any column except "product"
3.  Context Menu appears, now scroll by mouse wheel
4.  Context Menu disapears (which is correct behavior)
5.  Right click on "Product"  column which is fixed to the left
6.  Context Menu appears, now scroll by mouse wheel

### Results You Received:
Context Menu stays

### Results You Expected:
Context Menu disappear

### Environment Details:
Devextreme: 18.1.5
![context-menu-fixed-columns](https://user-images.githubusercontent.com/10086092/44927136-6c760500-ad21-11e8-8e80-8e250c4798ee.gif)

**Comment by Alyar666** [comment]
Hello,

We will process this issue in the context of the following Support Center thread:
[dxDataGrid - Fixed column's Context Menu doesn't disappear on scrolling](https://www.devexpress.com/Support/Center/Question/Details/T669643)
