### ISSUE TITLE
TagBox dropdown closing unexpectedly while searching

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#5309]
### Steps to Reproduce:

1.  Open the [demo app on StackBlitz](https://stackblitz.com/edit/angular-9mtxeb) in **Chrome** browser
2. Scroll down
3. Remove selected tagbox items by pressing BACKSPACE key
4. Start typing to search

### Results You Received:
Tagbox dropdown keeps closing unexpectedly

### Results You Expected:
Tagbox dropdown stays visible while typing

### Environment Details:
DevExtreme: 18.1.6
devextreme-angular: 18.1.6
Browser: Chrome 68 

[Demo App](https://stackblitz.com/edit/angular-9mtxeb)

**Comment by hakimio** [comment]
Sorry, can also be reproduced with other themes, but when using original themes you have to set the form's height to much lower value (100, for example).

**Comment by DokaRus** [comment]
Hi,
I've reproduced the issue and created a [bug report](https://www.devexpress.com/Support/Center/Question/Details/T671061) in our SC. You can subscribe to it to get a notification once we have any news.

**Comment by hakimio** [comment]
@DokaRus any plans to fix this anytime soon?

**Comment by DokaRus** [comment]
This issue is still active and we are working on it. We will update the [SC ticket](https://www.devexpress.com/Support/Center/Question/Details/T671061) once we have any results.
