### ISSUE TITLE
Returning error message from data grid's "onRowValidating" event breaks editor's popup

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#5310]
### Steps to Reproduce:

1.  Open the [demo app](https://stackblitz.com/edit/angular-fahox6)
2. Click "Add a row" button
3. Enter required data
4. Click "Save"

### Results You Received:
Popup looks broken - popup's buttons are on top of the last form field.

### Results You Expected:
Scrollbar appears and the form's height stays the same.

### Environment Details:
DevExtreme: 18.1.6
devextreme-angular: 18.1.6
Theme: Material Teal
Browser: Chrome 68

[Demo App](https://stackblitz.com/edit/angular-fahox6)

**Comment by hakimio** [comment]
Actually, if you use the original theme and set editor popup's height to 200px or so, then try the same steps, the buttons will still end up on top of the fields, but it looks a bit better because the buttons are not transparent.

**Comment by DokaRus** [comment]
Thank you for a detailed bug report. I've reproduced the same behavior on my side and created a [ticket in our SC](https://www.devexpress.com/Support/Center/Question/Details/T671489). You can subscribe to it to get a notification once we make any progress. Please bear with us.
