### ISSUE TITLE
Required form fields lose validation state when binding sets them to empty (except DxTextBoxes)

### ISSUE THREAD

**Issue by bert2** [DevExpress/DevExtreme#5332]
### Steps to Reproduce:

1. Open the repro at [codesandbox.io](https://codesandbox.io/s/8pyvmno108) or clone and host the repro from my [github repo](https://github.com/bert2/devextreme-form-bug.git).
2. Clear the fields "Hire Date" and "Address".
3. Verify that both are marked red for being invalid (both are required).
4. Click the "Save" button.

### Results You Received:

![image](https://user-images.githubusercontent.com/1454629/45253334-df0c6380-b365-11e8-91e9-033212c096bd.png)

The field "Hire Date" is no longer marked as invalid. The field "Address" still is marked as invalid.

### Results You Expected:

![image](https://user-images.githubusercontent.com/1454629/45253329-c7cd7600-b365-11e8-9ddd-d98c2f1aa278.png)

Either both fields should be marked as invalid (my preference) or both should be marked as valid. The current behavior is incosistent.

### Environment Details:

- DevExtreme 18.1.6
- Angular 6.0.3

The save button simulates an HTTP PUT followed by an update of the `[formData]` with the HTTP reponse data.

Through debugging I found [this line](https://github.com/DevExpress/DevExtreme/blob/e88f7a10b7d5840d47d2c2dd036a79a0d07f9ddb/js/ui/form/ui.form.layout_manager.js#L1081) to be the culprit (see the stacktrace below). It is triggered by angular's change detection.
If the new value is `null` or `undefined` then the component's `editor` will be set to valid. When a `DxTextBox` is cleared however, it's value will be the empty string which is why text boxes keep their validation state.

Perhaps another way to look at it is that setting a required `DxDateBox` to empty via user input will correctly mark it as invalid, but setting a required `DxDateBox` to empty via a binding will *always* mark it as valid.

Stack trace when breaking at the line mentioned above:

```
(anonymous) (ui.form.layout_manager.js:866)
each (iterator.js:41)
_optionChanged (ui.form.layout_manager.js:859)
(anonymous) (class.js:17)
_notifyOptionChanged (component.js:324)
setOption (component.js:521)
(anonymous) (component.js:541)
(anonymous) (ui.form.js:514)
each (iterator.js:35)
(anonymous) (ui.form.js:511)
schedulerFn (core.js:3567)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:209)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:147)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:80)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:55)
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
push../node_modules/devextreme-angular/core/events-strategy.js.NgEventsStrategy.fireEvent (events-strategy.js:28)
fireEvent (events_mixin.js:28)
config.beforeExecute (component.js:389)
execute (action.js:61)
(anonymous) (component.js:366)
result (component.js:398)
_notifyOptionChanged (component.js:322)
setOption (component.js:521)
(anonymous) (component.js:541)
push../node_modules/devextreme-angular/core/component.js.DxComponent._setOption (component.js:130)
push../node_modules/devextreme-angular/ui/form.js.DxFormComponent._setOption (form.js:548)
set (form.js:235)
updateProp (core.js:9456)
checkAndUpdateDirectiveInline (core.js:9207)
checkAndUpdateNodeInline (core.js:10514)
checkAndUpdateNode (core.js:10476)
debugCheckAndUpdateNode (core.js:11109)
debugCheckDirectivesFn (core.js:11069)
(anonymous) (AppComponent.html:1)
debugUpdateDirectives (core.js:11061)
checkAndUpdateView (core.js:10458)
callViewAction (core.js:10699)
execComponentViewsAction (core.js:10641)
checkAndUpdateView (core.js:10464)
callWithDebugContext (core.js:11351)
debugCheckAndUpdateView (core.js:11029)
push../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges (core.js:8845)
(anonymous) (core.js:4581)
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick (core.js:4581)
(anonymous) (core.js:4473)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
onInvoke (core.js:3824)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
push../node_modules/@angular/core/fesm5/core.js.NgZone.run (core.js:3738)
next (core.js:4473)
schedulerFn (core.js:3555)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:209)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:147)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:80)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:55)
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit (core.js:3539)
checkStable (core.js:3793)
onLeave (core.js:3860)
onInvokeTask (core.js:3818)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
invokeTask (zone.js:1540)
globalZoneAwareCallback (zone.js:1566)
```

**Comment by DokaRus** [comment]
Hi,
I've reproduced the same behavior and created [a ticket in our Support Center](https://www.devexpress.com/Support/Center/Question/Details/T671435) to process the issue. You can subscribe to it to get a notification once we have any news.
