### ISSUE TITLE
Why does DxFormGroup not have property readOnly?

### ISSUE THREAD

**Issue by NorDroN** [DevExpress/DevExtreme#5346]
Hi!
Why does DxFormGroup not have property readOnly?
I see that DxForm has property readOnly, and every simple DxComponent has property readOnly.
But in my case I would like to have DxForm that will contain two groups and one of them will be readOnly.

**Comment by DokaRus** [comment]
Hi,
The Form's **GroupItem** isn't a standalone component. It's a widget's item like a [List](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxList/Default_Item_Template/) or [TagBox](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTagBox/Default_Item_Template/) item.
I'll share your issue with my colleagues, and we'll take it into account during further development.
