### ISSUE TITLE
Theming - Color swatches

### ISSUE THREAD

**Issue by BingoRUS** [DevExpress/DevExtreme#5381]
# The Problem
You cannot use more than one color scheme on a page. For instance, if a navigation sidebar should be dark and a content area should be light, you have to write CSS for the sidebar manually.
# The Proposed Solution
We are going to provide a capability to produce color swatches — secondary color schemes to be used along with the primary scheme. You will be able to generate color swatches in our [ThemeBuilder tool](https://js.devexpress.com/ThemeBuilder/) and upcoming ThemeBuilder CLI.

A color swatch is defined by scoped CSS rules that are prefixed with a specific selector: ‘dx-swatch-xxx’ (for instance, `dx-swatch-green`). To apply a color swatch to a part of the HTML document, you need to wrap this part as follows:

```html
<div>
  This content applies the primary color scheme

  <div class=”dx-swatch-green” >
     This content applies the ‘green’ color scheme
  </div>

  <div class=”dx-swatch-blue” >
     This content applies the ‘blue’ color scheme
  </div>
</div>
```

Note that color swatches are based on a single theme and do not allow compiling different themes.
## Use CLI to create a color swatch
The following command generates a new `custom` color swatch using [Generic Dark](https://js.devexpress.com/Documentation/Guide/Themes/Predefined_Themes/) as a base theme.

```bash
> devextreme build-theme –base-theme=”generic.dark”  --make-swatch --output-color-scheme=”custom”
```

Since an input file with metadata or Bootstrap variables is not specified, no changes to the base theme are made.

Refer to the [ThemeBuilder CLI discussion page](https://github.com/DevExpress/DevExtreme/issues/5380) for more information about the CLI tool.

## Use ThemeBuilder UI to create a color swatch
You will be able to specify the swatch’s name when exporting your custom theme.
# We Need Your Feedback
## Take a Quick Poll
[Does the new color swatches feature meet your needs?](https://docs.google.com/forms/d/e/1FAIpQLSdXnQZgFS-MbSzSb6OlkyygWNI5HICq46Pp8F2F48SfYWhH6Q/viewform)

## Installation

Follow the installation guide from the [release page](https://github.com/DevExpress/DevExtreme/releases) and leave us feedback on this topic. 

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by dxbykov** [comment]
Thanks to everybody who gave us early feedback on this feature. The feature is now available in the [v18.2](https://github.com/DevExpress/DevExtreme/releases/tag/18.2.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
