### ISSUE TITLE
[Material] Misaligned tree view toggle item visibility icon

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#5448]
### Steps to Reproduce:

1. Create a Material design theme tree view 
2. Assign some icons to tree view items

### Results You Received:
Toggle item visibility icons are not properly aligned to item icons

### Results You Expected:
Toggle item visibility icons are properly aligned to item icons

### Environment Details:
DevExtreme: 18.1.6
devextreme-angular: 18.1.6

### Reason for misalignment
The reason why the toggle item visibility icons are misaligned is that the item container (div) has a height of 54px while the visibility icon container has a height of 48px which results in the visibility icon being shifted up by 3px (6/2).

### Screenshots
![toggle-icon](https://user-images.githubusercontent.com/768105/45672908-a3258b00-bb29-11e8-80bb-1d11c904cb49.png)
![treeview-item](https://user-images.githubusercontent.com/768105/45672909-a3258b00-bb29-11e8-8f2b-bc61bcde7ee4.png)

**Comment by groshenkovamarina** [comment]
Hi,
Thanks for pointing this out. We created a [bug report](https://www.devexpress.com/Support/Center/Question/Details/T674241/) in our Support Center. You can subscribe to it to get a notification once we have any news.
