### ISSUE TITLE
ContextMenu disabled binding issue with AngularJS

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#5486]
### Steps to Reproduce:

1. Create a context menu
2. Change item's disabled property - property is changed
3. Change item's disabled property again - nothing changes

### Results You Received:

The binding is working only the first time

### Results You Expected:

Context menu item changes it's disabled state

### Environment Details:

DevExtreme: 18.1.6 and older

###Live demo:
https://codepen.io/anon/pen/mGgPdo
By default second item is enabled, press Change button, second item should be disabled. Press Change button again and menu item still disabled.

**Comment by artem-kurchenko** [comment]
Hi,
 
Thank you for the example. Our widgets don't automatically track changes performed within menu items assigned to dataSource. You need to define the dataSource option using the bindingOptions object as described at [Change Options ](https://js.devexpress.com/Documentation/Guide/Getting_Started/Widget_Basics_-_AngularJS/Change_Options/) to complete this task.
For instance, check the following example - https://codepen.io/ArtemDevExpress/pen/MqdodZ?editors=1010
