### ISSUE TITLE
DataGrid: How to replace cell of custom group summary?

### ISSUE THREAD

**Issue by pikhovkin** [DevExpress/DevExtreme#5790]
How to replace cell of custom group summary for DataGrid?
For example: to render svg element (chart) in cell on group summary panel.

**Comment by vconst** [comment]
Hi @pikhovkin, 

Currently, you can customize group summary cells in the onCellPrepared event handler. I have prepared an example (https://codepen.io/anon/pen/MPqGwN) to demonstrate it.
 
I'd like to clarify that we process support inquiries related to usage scenarios in the [Support Center](https://www.devexpress.com/Support/Center/Question/Create). For more detailed assistance, feel free to contact us there.

**Comment by pikhovkin** [comment]
@vconst, thanks a lot!
