### ISSUE TITLE
Mouse wheel scrolling doesn't work on popup when content is scrolling

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#5854]
### Steps to Reproduce:

1. Open this url [https://codesandbox.io/s/ol4ojlzr05](https://codesandbox.io/s/ol4ojlzr05)
2. Click on detail button
3. Verify you are able to scroll by clicking on scroll bar and dragging
3. Try to scroll  by using mouse wheel

### Results You Received:
Nothing happens

### Results You Expected:
Scroll the content

### Environment Details:
DevExtereme 18.1
Chrome and Firefox

![modal-scroll-2](https://user-images.githubusercontent.com/10086092/47171931-0dbc1900-d2d8-11e8-98dc-82b40a5c423b.gif)

**Comment by sometimesElen** [comment]
Hi @RezaRahmati ,
Popup doesn't support scrolling out-of-the-box. So I suggest you wrap a popup content with the [ScrollView](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxScrollView/) widget as follows:
```
<div *dxTemplate="let data of 'content'">
  <dx-scroll-view>
    <p>
        Full Name:
        <span>{{currentEmployee.FirstName}}</span>
        <span>{{currentEmployee.LastName}}</span>
    </p>
    <!-- your content -->
  </dx-scroll-view>
</div>
```

I also modified your online [sample](https://codesandbox.io/s/jnoqv4lz19). 

I'd like to clarify that we process support inquiries related to usage scenarios in the [Support Center](https://www.devexpress.com/Support/Center/Question/Create). Feel free to contact us there if you have any further questions.

**Comment by RezaRahmati** [comment]
@sometimesElen Thanks, I tried it, and works perfect
