### ISSUE TITLE
Vertical scroll bar is displayed on grid when it's not needed

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#5908]
### Steps to Reproduce:

1. Open this url [https://codesandbox.io/s/j3q2wnjx79](https://codesandbox.io/s/j3q2wnjx79)
2. Resize the browser to make sure grid has horizontal scroll bar
3. Refresh the page in that size
4. Filter the records to show a few rows (for example order date 2017 Jan 1)

### Results You Received:
Grid displays vertical scrollbar

### Results You Expected:
Since there are few records, no scroll bar should be displayed

### Environment Details:
Chrome, 
18.1

![grid-scroll](https://user-images.githubusercontent.com/10086092/47450640-c16b5000-d793-11e8-9d90-841d7d3b2134.gif)

**Comment by artem-kurchenko** [comment]
Thank you for the detailed steps. I checked this case and created a report in our Support Center: 
[DataGrid displays an unnecessary vertical scrollbar after filtering in Material](https://www.devexpress.com/Support/Center/Question/Details/T685940/datagrid-displays-an-unnecessary-vertical-scrollbar-after-filtering-in-material)
 
We'll update it once we have any results.
