### ISSUE TITLE
TabPanel repaint content when change badge for item

### ISSUE THREAD

**Issue by genusP** [DevExpress/DevExtreme#5966]
I paint in tab badge with total count records in datagrid.
When apply filter to grid and update badge value, content repainted and filter reset.
If enable state storing for datagrid then request to server as infinity loop.

**Comment by AlisherAmonulloev** [comment]
Hi,
The cause of the issue is unclear due to lack of information. Please share a simple project illustrating the problem so that we can examine it. Feel free to submit a support ticket in our Support Center by using the devexpress.com/ask link.

**Comment by genusP** [comment]
[Example](https://codesandbox.io/s/yk6qzn6j11)

Input 'i' to filter cell of Selector column.

**Comment by AlisherAmonulloev** [comment]
Thank you for sharing the project. I noticed the issue and we are currently looking for a possible solution. Please stay tuned.

**Comment by AlisherAmonulloev** [comment]
Hi,
 
In order to include this issue to the What's New list, I have created a public report in our Support Center: https://www.devexpress.com/Support/Center/Question/Details/T687958 Please check it.
