### ISSUE TITLE
Grid column filter keeps the value when temporary remove the filter

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#5968]
Disclaimer: I don't know if it's a bug or it's by design
### Steps to Reproduce:

1.  open this [https://codesandbox.io/s/yjrz00voo9](https://codesandbox.io/s/yjrz00voo9)
2.  Un-check the filter on filter panel
3. Verify the data in the grid is not filtered
4.  Open City column header filter

### Results You Received:
The cities are still secleted

### Results You Expected:
Filter values be consistent with data in the grid

### Environment Details:
18.1

![grid-filter-panel](https://user-images.githubusercontent.com/10086092/47725753-805dba80-dc2f-11e8-937a-1e484ce3ad47.gif)

**Comment by komarovalexander** [comment]
@RezaRahmati It's by design

**Comment by RezaRahmati** [comment]
@komarovalexander thanks for answer, may I know the philosophy behind it, because our QA team submit a bug for us to fix and we want to be able to reasoning

**Comment by komarovalexander** [comment]
@RezaRahmati Unchecking this check box does not clear filter values, it just temporarily disables the filter. For example, you can keep some filter values and change another filter value as shown at [https://www.screencast.com/t/y5O7nB47vB](https://www.screencast.com/t/y5O7nB47vB)
If you want to clear filter values, click the "Clear" button.
