### ISSUE TITLE
Scheduler - Recurrence with DST and difference timezones not correctly displayed

### ISSUE THREAD

**Issue by gercobrandwijk** [DevExpress/DevExtreme#6028]
### Steps to Reproduce:

See this CodeSandbox: https://codesandbox.io/s/6wqqwy99wn
We have a daily recurrence for 4 days starting at 2018-10-26 09:30. This event has as starting and ending timezone Europe/Amsterdam. For this timezone there is a DST time switch at 2018-10-28 03:00 to 2018-10-28 02:00 (one hour back). When you switch the timezone to +04:00  (no DST, so always +04:00), you will see that the first occurence event is starting at 11.30, which is correct because Europe/Amsterdam is on +02:00 at the 26th. When you go to the next week, and switch between the timezones, you will see that the hour difference is still 2 hours, but it should be 3 hours, because Europe/Amsterdam is now at +01:00.

### Results You Received:

Always 2 hours difference between the two zones. 

### Results You Expected:

Because the event is from the Europe/Amsterdam timezone, in the second week (occurence 3 and 4) the difference should be 3 hours.

I tested with the iCal (https://github.com/rianjs/ical.net/wiki/Working-with-time-zones) and NodaTime (https://nodatime.org/) library, and there I get the results I expect:

![image](https://user-images.githubusercontent.com/6197958/47997459-2b70e700-e0fc-11e8-92da-f29a75e760ee.png)

Above are the results of the following test:

            [Test]
            public void ProvingWrongOccurencesOnDxScheduler()
            {
                DateTimeZone zoneAmsterdam = DateTimeZoneProviders.Tzdb["Europe/Amsterdam"];
                DateTimeZone zoneGmtMinus4 = DateTimeZoneProviders.Tzdb["Etc/GMT-4"];
    
                Calendar calendarAmsterdam = new Calendar();
                calendarAmsterdam.AddTimeZone(new VTimeZone(zoneAmsterdam.Id));

                Calendar calendarGmtMinus4 = new Calendar();
                calendarGmtMinus4.AddTimeZone(new VTimeZone(zoneGmtMinus4.Id));

                ZonedDateTime zonedDateTimeStart = ZonedDateTime.FromDateTimeOffset(new DateTimeOffset(2018, 10, 26, 9, 30, 0, new TimeSpan(2, 0, 0)));
                ZonedDateTime zonedDateTimeEnd = zonedDateTimeStart.PlusMinutes(15);

                CalendarEvent calendarEvent = new CalendarEvent
                {
                    Start = new CalDateTime(zonedDateTimeStart.ToDateTimeUnspecified(), "Europe/Amsterdam"),
                    End = new CalDateTime(zonedDateTimeEnd.ToDateTimeUnspecified(), "Europe/Amsterdam"),
                    RecurrenceRules = new List<RecurrencePattern> {
                        new RecurrencePattern(FrequencyType.Daily, 1)
                        {
                            Count = 4
                        }
                    },
                };

                calendarAmsterdam.Events.Add(calendarEvent);
                calendarGmtMinus4.Events.Add(calendarEvent);

                var occurrencesAmsterdam = calendarAmsterdam.GetOccurrences(zonedDateTimeStart.ToDateTimeUnspecified(), zonedDateTimeStart.Plus(Duration.FromDays(30)).ToDateTimeUnspecified())
					.Select(o => new
					{
						Local = ZonedDateTime.FromDateTimeOffset(o.Period.StartTime.AsDateTimeOffset).WithZone(zoneAmsterdam).LocalDateTime,
						Utc = o.Period.StartTime.AsUtc
					})
					.OrderBy(o => o.Local)
					.ToList();

                var occurrencesGmtMinus4 = calendarGmtMinus4.GetOccurrences(zonedDateTimeStart.ToDateTimeUnspecified(), zonedDateTimeStart.Plus(Duration.FromDays(30)).ToDateTimeUnspecified())
                    .Select(o => new
                    {                    
				    	Local = ZonedDateTime.FromDateTimeOffset(o.Period.StartTime.AsDateTimeOffset).WithZone(zoneGmtMinus4).LocalDateTime,
                        Utc = o.Period.StartTime.AsUtc
                    })
                    .OrderBy(o => o.Local)
                    .ToList();
			}

A guess where the problem is: I think the scheduler is only looking at the offset of the start and end time to calculate the occurences for other timezones, but not at the startDateTimeZone, so the scheduler is not respecting the DST changes of the zone where the event is coming from.

### Environment Details:
DevExtreme 18.1.6

**Comment by Yarovaya** [comment]
Hi,
I've reproduced the same behavior and created a [ticket in our Support Center ](https://www.devexpress.com/Support/Center/Question/Details/T688610/scheduler-recurrence-appointments-with-dst-and-different-timezones-are-displayed) to process the issue. You can subscribe to it to get a notification once we have any news.

**Comment by gercobrandwijk** [comment]
When can I expect that this will be picked up and be fixed? You are actively prioritizing the issues from the Support Center?
