### ISSUE TITLE
Action buttons in dx-dropdown / dx-select-box

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#6044]
In many web applications user needs intuitive actions. The devextreme dropdown already provides intuitive actions, like selecting and resetting values intuitively, but it would be awesome to be able to customize additional actions.

A pretty easy sample would be having a custom lookup with an additional action button suggesting some kind of additional action (example: an help button).

Such behavior is implemented in many client frameworks, the easiest example I could think of is bootstrap, where `input groups` provides `addons`, like button addons or whatever (like this https://prnt.sc/lfd0kq): https://getbootstrap.com/docs/4.0/components/input-group/#button-addons

I've checked the documentation and notiched that the DropDown button can be customized, though no additional actions are allowed, and it's really hard to integrate any third-party library to actually work properly with the dx-dropdown graphically so, since there effectively already is an action binded to an "action button" (the reset value button), I would suggest to add an additional option to register additional buttons, so that the developer can customize their behavior and add them according to its needs.

Side note: this is already accomplished in the DateBox, where the calendar button is actually the kind of action button I'm talking about above.

**Comment by FabianoCastro** [comment]
Hi everybody

I would need in edits too, to trigger actions such as email, url, etc ...

**Comment by briosheje** [comment]
@FabianoCastro if you're using bootstrap (version 4 and above), you can use the flex layout as a workaround to render a dropdown button next to any devextreme form item (here is a sample using angular 7 and bootstrap 4):

```
<div class="d-flex flex-row w-100">
	<div class="w-100">
	  <!-- dropdown box here -->
	</div>
	<div class="flex-shrink-1 pl-1">
	  <div class="btn-group" role="group">
		  <button [id]="uniqueComponentId + '_editAddDropdown'" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Actions
		  </button>
		  <div class="dropdown-menu" [attr.aria-labelledby]="uniqueComponentId + '_editAddDropdown'">
			<a class="dropdown-item" (click)="$event.preventDefault(); spawnNewModal();" href="#">{{spawnAddModalLabel}}</a>
			<a class="dropdown-item" (click)="$event.preventDefault(); spawnEditModal();"  href="#">{{spawnEditModalLabel}}</a>
		  </div>
	  </div>
	</div>
</div>
```

Once rendered, it will look like this: http://prntscr.com/lozyz3

**Comment by FabianoCastro** [comment]
Hi @briosheje 

I´m using dxForm to render dxTextBox, I tried some sugestions in the help system the DevExpress, but did not solve my need.

I was able to render the button, but the value in the text field does not work, I will search more about the bind, I suggested here because an implementation as an array of buttons would help in many cases, something like

dxTextBox ({
value: 'Test',
buttons: [{text: 'Go'}, {text: 'Back'}],
})

See... I´m using "Item Template" in the dxForm, but the value does not show

![image](https://user-images.githubusercontent.com/34251113/49296388-3e7a9b00-f49f-11e8-8792-40cdb44ae131.png)

```
function EmailTemplate(aData, aItemElement) {
	var aValue=aData.component.option('formData')[aData.dataField];

	$("<div>").appendTo(aItemElement).css({
		width: "calc(100% - 30px)",
		float: "left"
	}).dxTextBox({value: aValue});

	$("<div>").appendTo(aItemElement).width(30).dxButton({ icon: "email"});
}
```

**Comment by briosheje** [comment]
@jsdmitry seeing that this feature is in the 2019 - 19.1 roadmap (https://community.devexpress.com/blogs/javascript/archive/2019/01/22/devextreme-javascript-2019-roadmap.aspx) may I ask whether there currently is any ETA for the 19.1 release? Thanks

**Comment by churkin** [comment]
Hello,

We are working on improving custom action buttons for text editors. I'd like to invite you to participate in our R&D process. We are posting related updates on the [corresponding discussion page](https://github.com/DevExpress/DevExtreme/issues/7290). Feel free to review the current state of development and comment if you have any feedback. There is a poll you can take to help us understand if the suggested solution meets your app requirements. Thanks for your input.
