### ISSUE TITLE
Focused row Demo bug

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6067]
### Steps to Reproduce:

1. Open data grid focused row demo
2. Select "Teal Light" Material Design theme
3. Press Up/Down arrow keys

### Results You Received:
JavaScript error: "Uncaught TypeError: Cannot read property 'class' of null" and broken page.

### Results You Expected:
The demo to work.

### Environment Details:
Chrome 70 browser

**Comment by AntonSermyazhko** [comment]
This issue was fixed in #5989. We created a public ticket [T689400](https://isc.devexpress.com/Thread/WorkplaceDetails/T689400) in our Support Center.
You can subscribe to it to receive a notification clarifying the version containing the fix.
