### ISSUE TITLE
Minor suggestion: Demo code simplification

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6069]
In some of your demos, for example ["Command Column Customization" Angular demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CommandColumnCustomization/Angular), you set function context by calling bind() on the function in the class constructor. Instead you could just use ES6 arrow function the following way to create the function with correct context:
```TS
    cloneIconClick = (e) => {
        var clonedItem = Object.assign({}, e.row.data, { ID: this.service.getMaxID() });

        this.employees.splice(e.row.rowIndex, 0, clonedItem);
        e.event.preventDefault();
    }
```

**Comment by AlisherAmonulloev** [comment]
Your suggestion definitely makes sense. Although we do not have immediate plans to update all our demos to use this approach, we will consider using arrow functions while adding new demos or updating current ones.
