### ISSUE TITLE
dxTagBox - When Tab to next field the value is removed

### ISSUE THREAD

**Issue by andrii-oleksyshyn** [DevExpress/DevExtreme#6117]
### Reproduction:
https://codesandbox.io/s/6zkk1wvnw
![dx-tagbox-tab-issue](https://user-images.githubusercontent.com/1427132/48409946-e70dc880-e745-11e8-921d-dac9e796dcc8.gif)

### Steps to Reproduce:

1. Use Tab and arrow keys for navigation
2. Focus on tagbox with Tab key.
3. Press Space to open the popup with tags.
4. Select 2 items using arrow keys and Enter.
5. Navigate to next input with Tab key.

### Results You Received:
Only one tag is saved in the tagbox. Focus is changed to input field.

### Results You Expected:
Two selected tags are saved in the tagbox. Focus is changed to input field.

### Environment Details:
devexteme version: 18.2, 17.2.11
devextreme-angular version: 18.2, 17.2.11

Chrome 70, Windows 10 x64 (1920x1080 resolution)

**Comment by DokaRus** [comment]
Hi,
I've reproduced the issue on my side and created a [ticket in our Support Center](https://www.devexpress.com/Support/Center/Question/Details/T690720) to further research it. You can subscribe to it to get a notification once we have any results.
