### ISSUE TITLE
DataGrid breaks when resizing with virtual scroll and fixed columns

### ISSUE THREAD

**Issue by korapp** [DevExpress/DevExtreme#6147]
DataGrid breaks after some time of using it with a large set of data updated periodically. It occurred after upgrade from devexpress 17.2 and use rowRenderingMode: "virtual".

CodePen: https://codepen.io/anon/pen/bQeeeM

Not all steps seem to be crucial but they were used to fail fast.

### Steps to Reproduce:

1. Enable columnFixing and columnAutoWidth
2. Set scrolling.mode and scrolling.rowRenderingMode to "virtual"
3. Set at least one column as fixed
4. Add summary row
5. Refresh the component periodically with changing its size simultaneously

### Results You Received:

After several changes the component breaks with:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at t._getClientHeight (dx.all.js:57)
    at t.synchronizeRows (dx.all.js:57)
    at t.setColumnWidths (dx.all.js:57)
    at t.setColumnWidths (dx.all.js:9)
    at t._columnOptionChanged (dx.all.js:27)
    at t._columnOptionChanged (dx.all.js:82)
    at t._columnOptionChanged (dx.all.js:9)
    at i._fireCore (dx.all.js:10)
    at i.fireWith (dx.all.js:10)
    at i.fire (dx.all.js:10)

### Environment Details:
browser: Chrome 70 / Firefox 63
devexpress: 18.2.3
angularjs: 1.7.5

**Comment by AntonSermyazhko** [comment]
Seems like a bug. We're processing the issue in the context of a [public ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T691574) in our Support Center.
The issue on GitHub will be closed. Please subscribe to the support center ticket to get all the notifications and news.
