### ISSUE TITLE
How to create a custom JS bundle with data components only

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#6184]
What files do I need to just use the
`JS
 DevExpress.data.DataSource(store);
`
We want to use the datasource on some pages but no other controls, so we dont want to bloat the JS on these pages with extra things.

**Comment by DokaRus** [comment]
Hi,
You can create a custom bundle. Please refer to this documentation [topic.](https://js.devexpress.com/Documentation/Guide/Common/Modularity/Create_a_Custom_Bundle/)
