### ISSUE TITLE
inconsistent behavior on dx-date-box using disabledDates (forms vs no forms vs forms + null min-max)

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#6315]
### Steps to Reproduce:

1. Open this [https://stackblitz.com/edit/devextreme-datebox-issue-to-report](https://stackblitz.com/edit/devextreme-datebox-issue-to-report)
- having disabledDates as below

```
this.disabledDates = (args) => {
      const maxDate = new Date('2018-10-31');
      const minDate = new Date('2018-08-09');
      if (args.date > maxDate || args.date < minDate) {
        return true;
      }

      return false;
    };
```

Scenario 1
Open first datebox (Without form) 

Scenario 2
Open second datebox (With reactive form) 

Scenario 3
Open second datebox (With reactive form and bind min and max to null values) 

### Results You Received:
Scenario 1 - It shows current month and if you click on next it jumps to Jan 1st 3000
Scenario 2 - It jumps to Jan 1st 3000
Scenario 3 - It shows current month and if you go forward it shows next month and a random day is selected and selected day is increasing while you go forward

### Results You Expected:
- Consistent bahvior
- it shows last enabled date or current date whichever is greater
- if no date is enabled after current month and user clicks on forward, doesn't go forward 

Note: Same thing for going backward, it jumps to Jan 1st 1000 

Please see this recording:

![devextreme-date-box-issue](https://user-images.githubusercontent.com/10086092/49384004-15008000-f6e8-11e8-89b4-d58912a0f9dd.gif)

### Environment Details:
Devextreme 18.2.3

**Comment by RezaRahmati** [comment]
@DokaRus Hey Dmitry, any update on this issue?

**Comment by DokaRus** [comment]
Hi Reza,
 
Thank you for the example. This behavior related to the Calendar widget.
I've created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T701103) in the our SC to further research this issue. You can subscribe to it to get a notification once we have any results.
Would it be suitable for you define max and min options to avoid checks like `(args.date > maxDate || args.date < minDate)`?
