### ISSUE TITLE
Question: How to set formatter on dxNumberbox in Angular

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#6318]
Hey

I have tried to assign formatter to dxNumberbox but no success

[https://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/format/#formatter](https://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/format/#formatter)

[https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxNumberBox/Configuration/#format](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxNumberBox/Configuration/#format)

I have tried below

```
export class AppComponent { 
    @ViewChild('numberbox') numberbox : DxNumberBoxComponent;
    
    ngOnInit() {
        this.numberbox.format = this.formatter;
        // this.numberbox.format = this.format;
    }
    
    format = {
        formatter: (event) => {
            console.log(event);
            return event;
        }
    }
    
    formatter = (event) => {
            console.log(event);
            return event;
        }
}
```
```

<dx-number-box #numberbox></dx-number-box>
<dx-number-box #numberbox [format]="format"></dx-number-box>
<dx-number-box #numberbox [format]="formatter"></dx-number-box>
```

**Comment by hakimio** [comment]
There seems to be a bug in DevExtreme itself. Even with jQuery, it tries to call "indexOf()" on the formatter function.

![numberbox formatter](https://user-images.githubusercontent.com/768105/49434179-e7810880-f7b3-11e8-83eb-c923bdedaacf.PNG)

**Comment by mrjohn0011** [comment]
Hello

Your formatter returns incorrect data. The formatter should be a function converting a number to a string. The parser should be a function converting a string to a number. I have modified your functions to get rid of this exception:

```
format: {
	formatter: (value) => {
		console.log(value);
		return String(value);
	},
	parser: (text) => {
		console.log(text);
		return +text;
	}
}
```

**Comment by RezaRahmati** [comment]
@mrjohn0011 thanks for answer, I see some weird behavior, with out entering any value I see these on my console, seems some tests is left on the source code ;)

[https://codesandbox.io/s/0ql7w4rjll](https://codesandbox.io/s/0ql7w4rjll)

![image](https://user-images.githubusercontent.com/10086092/49458044-02567b80-f7ba-11e8-9f6e-968bb1f4be40.png)

**Comment by mrjohn0011** [comment]
When you are using a custom format, dxNumberBox doesn't know how to detect some kind of symbols like decimal separator or numbers less than zero. It should call your custom formatter for some built-in constants to define these rules.
