### ISSUE TITLE
Grouping bug with infinite scrolling

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [DevExpress/DevExtreme#6362]
### Steps to Reproduce:

https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/InfiniteScrolling

Open link and set this configration:

        groupPanel: {
            visible: true
        }

Group expand-collapse not working as expected when scrolling mode is **"infinite"**.

### Results You Received:
Both grouping and scrolling works as expected.

### Results You Expected:
Expand button not showing.

### Environment Details:
DevExtreme 18.2

**Comment by Alyar666** [comment]
Hello @ibrahimyilmaz7,

The grouping functionality is not fully compatible with infinite scrolling. The expand/collapse group button is not rendered when you enable the infinite scrolling mode. See [DataGrid - Scrolling](https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Scrolling/).
