### ISSUE TITLE
Selection checkbox column slows down scrolling

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6383]
The selection column has hard-coded width property 'auto':
https://github.com/DevExpress/DevExtreme/blob/18_2/js/ui/grid_core/ui.grid_core.selection.js#L161

This causes widths to be recalculated on every scroll event:
https://github.com/DevExpress/DevExtreme/blob/18_2/js/ui/grid_core/ui.grid_core.grid_view.js#L235

The selection column has fixed width and should not require width calculations on every scroll event.

Workaround:  
Hide the checkbox column by setting selection.showCheckBoxesMode to "none".

**Comment by Alyar666** [comment]
Hello,

At the moment, this is needed to calculate the width of [command columns](https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Columns/Column_Types/Command_Columns/) based on styles. We will consider improving this behavior in future versions. 

As a possible workaround, you can specify the selection column width:
```
columns: [
    {
        type: "selection",
        width: 70
    },
    .....
]
```
