### ISSUE TITLE
DateBox masked input mode ux issue

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6404]
### Steps to Reproduce:

1.  Enable date box masked input mode
2. Set display format to "dd/MM/yyyy"
3. Try to enter the date manually by typing the numbers

### Results You Received:
When there are more than one digit in a group it's unclear which digit will be modified next when typing in the numbers.

### Results You Expected:
A single digit which will be modified next is selected in the input area instead of multiple digits being selected at once.

### Environment Details:
DevExtreme 18.2

**Comment by mrjohn0011** [comment]
The selection is a part of the formatting mechanism and it cannot be easily changed. Your idea definitely makes sense, and we will consider improving the selection mechanism in future releases.

**Comment by hakimio** [comment]
@mrjohn0011 It's just that if users don't understand how it works and why typing "01" puts "31" for the day part, the feature is rather useless. 
Another possible solution could be allowing to enter dates left-to-right instead of the unusual right-to-left mode (some new config maybe?).
