### ISSUE TITLE
DataGrid "highlightChanges" config issue

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6405]
### Steps to Reproduce (with **grouping** feature):

1.  Enable record grouping and highlightChanges in a datagrid

### Results You Received:
Expanding and collapsing nodes causes expanded area to be highlighted

### Results You Expected:
Expanded area is not highlighted

----------------------------------------

### Steps to Reproduce (with **master-detail** feature):

1.  Enable masterDetail and highlightChanges features in a datagrid

### Results You Received:
Expanding and collapsing nodes causes expand/collapse button to be highlighted

### Results You Expected:
expand/collapse button is not highlighted

### Environment Details:
DevExtreme 18.2

**Comment by komarovalexander** [comment]
@RezaRahmati
I've reproduced this issue and created public tickets in the DevExpress Support Center.
1) [DataGrid: an expanded area is highlighted when expanding group nodes](https://www.devexpress.com/Support/Center/Question/Details/T700772/datagrid-an-expanded-area-is-highlighted-when-expanding-group-nodes)
2) [DataGrid: Expanding and collapsing nodes causes the expand/collapse button to be highlighted](https://www.devexpress.com/Support/Center/Question/Details/T700770/datagrid-expanding-and-collapsing-nodes-causes-the-expand-collapse-button-to-be)

You can subscribe to it to receive a notification of our progress.

**Comment by hakimio** [comment]
I am not RezaRahmati, but thanks for creating tickets in support center.
