### ISSUE TITLE
DxScheduler: Timeline views with cellDuration set to full day do not retain original start/stop time when dragged to new date

### ISSUE THREAD

**Issue by rmartin-omanco** [DevExpress/DevExtreme#6428]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.2.3
    devextreme-angular version: 18.2.3
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[x] feature request 
[ ] support inquiry 

With the following settings: startDayHour=0 endDayHour=24 cellDuration=1440
On the timeline views (timelineDay with a intervalCount set and timelineWeek), when an appointment time is set, and that appointment is dragged to a new date, the start time is reset to 12:00AM while the end time is set to however long the original appointment duration was set for.

This is how it was probably attended to work because smaller cells are probably expected (and it is switching it to the first value of that cell), but there should be a check in place that if the cellDuration is set to a full day that the time would be retained for the update of the appointment.

**Comment by Yarovaya** [comment]
Hi,
 
Thank you for your input. Currently, Scheduler does not allow setting the appointment position in a cell. We are planning to add this feature in future versions. When we implement it, we will add the required information in the [What's New](https://js.devexpress.com/New/18_2/) section of our web site.
