### ISSUE TITLE
Drawer: "closeOnOutsideClick" plus toggle button inside drawer's content area prevents the drawer from expanding

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6434]
### Steps to Reproduce:

1. Define DxDrawer component
2. Put drawer's state toggling button inside drawer's content area
3. Set "closeOnOutsideClick" to true

### Results You Received:
It's impossible to to expand the drawer

### Results You Expected:
Drawer would still work as expected

### Environment Details:
DevExtreme 18.2
Chrome 71

### Demo app
https://codesandbox.io/s/82y37omyjl

**Comment by Yarovaya** [comment]
Hi Tomas,
 
The Drawer behavior is quite logical. By clicking on the button, the Drawer opens, but it immediately closes, as the button is inside the content and 'closeOnOutsideClick' = true.
So, I've slightly changed the [example](https://codesandbox.io/s/8x8m1jq7m2) to make the Drawer work the way you expect.

**Comment by hakimio** [comment]
@Yarovaya 
I've tried with "event.preventDefault()" instead of "event.stopPropagation()" which didn't work.
Thanks for looking into this.
