### ISSUE TITLE
Validation error message inside DxDatagrid is hidden behind a fixed column

### ISSUE THREAD

**Issue by Yura13** [DevExpress/DevExtreme#6458]
### Steps to Reproduce:

Repo: https://codesandbox.io/s/moq1ll517j

![image](https://user-images.githubusercontent.com/17030431/50281138-320eb000-0457-11e9-9785-5b8eb581564d.png)

### Results You Received:
Validation error message inside DxDatagrid is not hidden behind a fixed column

### Results You Expected:
Validation error message inside DxDatagrid is hidden behind a fixed column

### Environment Details:
devextreme: 17.2.11
devextreme-angular: 17.2.11
angular: 6.1.10

**Comment by vconst** [comment]
@Yura13 
I've reproduced this issue and created [a public ticket](https://www.devexpress.com/Support/Center/Question/Details/T707313) in the DevExpress Support Center. You can subscribe to it to get a notification once we have any results.
