### ISSUE TITLE
Impossible to enter "01" with masked datebox input mode

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6461]
### Steps to Reproduce:

1.  Enable masked datebox input
2. Try to type "01" in the textfield
3. 

### Results You Received:
Input is changed to 31

### Results You Expected:
Input should stay 01

### Environment Details:
DevExtreme 18.2.4

Demo: https://codepen.io/hakimio/pen/EGZLYZ

----

T692930 says it's fixed in 18.2.4, but apparently it's not.

**Comment by hakimio** [comment]
@mrjohn0011 any thoughts on this?

**Comment by mrjohn0011** [comment]
Hello. I have fixed this behavior in [this pull request](http://github.com/DevExpress/DevExtreme/pull/6436)

**Comment by hakimio** [comment]
@mrjohn0011 is it not part of 18.2.4 release?
Because my demo uses 18.2.4 and it's still possible to reproduce the issue.

**Comment by mrjohn0011** [comment]
This is the part of the next 18.2.5 release.

**Comment by hakimio** [comment]
Then changelog for 18.2.4 is incorrect.
