### ISSUE TITLE
'Cannot read property 'items' of undefined' error occurs in Scheduler demo

### ISSUE THREAD

**Issue by baozhoutao** [DevExpress/DevExtreme#6467]
### Steps to Reproduce:
In the example "https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/ContextMenuIntegration/jQuery/Light/"
1.  right click -> Group by Room/Ungroup
2.  click on a blank cell
3.  right click -> Group by Room/Ungroup

### Results You Received:
Browser console error: "Cannot read property 'items' of undefined"

**Comment by Yarovaya** [comment]
Hello. I have fixed this behavior in this [pull request](https://github.com/DevExpress/DevExtreme/pull/6499).
