### ISSUE TITLE
DXGrid Lookup Datasource not shared

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#6524]
When the grid has multiple options to filter enabled, EX FilterPanel and HeaderFilters, when a filter is selected the data source should be shared across them as to prevent multiple db calls for the same data.

### Steps to Reproduce:

https://codepen.io/anon/pen/ZVXBrQ?&editable=true

### Results You Received:

![image](https://user-images.githubusercontent.com/30090055/50518842-ec20a000-0a85-11e9-8d27-c3aa5d0c6c34.png)

### Results You Expected:

No extra calls made to DB after initial load, or at least only 1x not 3x.

### Environment Details:

18.2.4

Ref Support Ticket:
https://www.devexpress.com/Support/Center/Question/Details/T703158/datagrid-lookup-column-loads-data-on-filtering

**Comment by komarovalexander** [comment]
I've reproduced this issue. We'll process the issue in the context of [the ticket of DevExpress Support Center](https://www.devexpress.com/Support/Center/Question/Details/T703158/datagrid-lookup-column-loads-data-on-filtering) - it will be updated once we obtain any news.
