### ISSUE TITLE
Pivot Grid not getting formatting from olap, and not using display groups

### ISSUE THREAD

**Issue by ZergRushJoe** [DevExpress/DevExtreme#6528]
When hooked up to a olap cube the pivot grid ignores formatting coming from the cube and does not show the fields in there display groups used by the cube. This feature is need because are data is view in excel as well as online and it should be the same formatting so I only must update the cube. Also, sometimes I can't know all the fields coming to format them using the pivot grids fields object. As a side on this there also need to be a value on fields that lets me tell the field where it should go but not to display it yet. Like hidden:true vs using the visible:false which hides it completely.

**Comment by vconst** [comment]
Hi @ZergRushJoe,
 
At the moment, there is no option to load the field format from OLAP. The only option I can suggest is to apply the format by specifying the [PivotGridDataSource.fields.format](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/PivotGridDataSource/Configuration/fields/#format) option. We will think about adding this capability in future versions.
 
Your other question about field visibility is not clear to me. Please describe it in more detail.

**Comment by ZergRushJoe** [comment]
So if I set visible to false it removes it from the field chooser. I need away to hide the field without taking it out of the field chooser.

**Comment by vconst** [comment]
As far as I understand, you want to specify a default area for a field where it must be placed after clicking on a checkbox in the field chooser. Currently there is no API to achieve this behavior. That task is in our backlog, but I cannot give you any time frame for it yet.

**Comment by ZergRushJoe** [comment]
@vconst 
I know you can send a "direct query" query to get the format of the fields
for measures:
`select TableId, [Name], FormatString, IsHidden, DataType, DisplayFolder from $SYSTEM.TMSCHEMA_MEASURES where not isHidden` 
for attributes:
`elect tableId,FormatString, explicitDataType, IsHidden, ExplicitName, DisplayFolder  from $SYSTEM.TMSCHEMA_COLUMNS where not isHidden`

there are several tables that can be used to get this info. the queries above are for tab database but mud has almost the exact same

**Comment by onebalaban** [comment]
Hello,

We will consider implementing this functionality in future releases. Please stay tuned to our announcements.
