### ISSUE TITLE
Pivot Grid Max Height

### ISSUE THREAD

**Issue by ZergRushJoe** [DevExpress/DevExtreme#6531]
When Using the pivot grid, I have a page with a standalone pivot field chooser under the pivot grid that I would like to grow to a max height as user adds too it but not have to have that space already allocated for the pivot grid. This allow the user to see the field chooser when they enter the page and ensure that the pivot grid can grow without bound leaving the field chooser way at the bottom of the page.

**Comment by vconst** [comment]
Hi @ZergRushJoe,
 
To set the max height for PivotGrid, you can use the max-height css style. I have prepared [an example](https://codepen.io/anon/pen/pqOxBb) to demonstrate it.
