### ISSUE TITLE
Chart doesn't work with UglifyJsPlugin

### ISSUE THREAD

**Issue by aidanxyz** [DevExpress/DevExtreme#654]
### Steps to Reproduce:

1. Setup DevExtreme with Webpack 1
2. Draw a simple chart like:
```
<div dx-chart="{
  dataSource: [
    { fruit: 'Oranges', total: 10 },
    { fruit: 'Apples', total: 15 },
    { fruit: 'Bananas', total: 9 }
  ],
  series: { argumentField: 'fruit', valueField: 'total' }
}"></div>
```
3. Use webpack plugin `UglifyJsPlugin` to uglify your javascript code

### Results You Received:
Chart plugin draws only the background but not the actual chart

### Results You Expected:
Beautiful chart is drawn

### Environment Details:
DevExtreme 17.1
Angular 1.5.7
Webpack 1.12.11
Latest Chrome

**Comment by NikitaKunashov** [comment]
Hello,
We need to know specifics of your building system to check why the chart is not drawn when the UglifyPlugin is used. Would you please send us a minimal project that includes your Webpack config so that we can perform detailed research?
