### ISSUE TITLE
DxScheduler draw changes despite of cancel with promise, but not update its datasource

### ISSUE THREAD

**Issue by juangranados** [DevExpress/DevExtreme#6542]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.2.4
    devextreme-angular version: 18.2.4
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

Hello! On Scheduler, when updating an appointment by resizing or dragging it, if you use e.cancel with jQuery promise:

```javascript
onAppointmentUpdating(e) {
    var item = Object.assign(e.oldData, e.newData);
    let d = new $.Deferred();
    this.restservice.update(item).subscribe((data) => {
        d.resolve();
    }, (error) => {
        d.reject(error);
    });
    e.cancel = d.promise();
}
```

If error, scheduler datasource is not updating (correct), but scheduler draws the appointment change as you can see in the image attached.

![imagen](https://user-images.githubusercontent.com/6050403/50648315-310f6f80-0f7b-11e9-828e-664662f42902.png)

If you change the view to next day and then back to previous day, it draws the appointments right.

![imagen](https://user-images.githubusercontent.com/6050403/50648266-0ae9cf80-0f7b-11e9-9b92-ae90a10a685d.png)

This problem does not happen when you change the appointment by onAppointmentFormCreated method, only by resizing or dragging.

Thanks.

**Comment by Yarovaya** [comment]
Hello. I have fixed this behavior in this [pull request](https://github.com/DevExpress/DevExtreme/pull/6546).
