### ISSUE TITLE
setting state doesn't set pageSize on DataGrid when it's in virtual scrolling mode

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#6553]
### Steps to Reproduce:

1. Open this link [https://codesandbox.io/s/o7pkpn9kw5](https://codesandbox.io/s/o7pkpn9kw5)
There are two grid same as each other, the only difference top grid has scrollingMode standard, bottom grid has virtual
2. Change page size to 100, and page number to 3 on both grids
3. Click on `save state` button, to save state of both grids
4. Change page size to 400 and page number to 5 on both grids
5. Click on `load state`

### Results You Received:
on virtual grid, page size resets to 50

### Results You Expected:
on both grid, page size be 100, and page number 3 (whatever is stored in state)

### Environment Details:
Reporducible on both : DevExtreme 18.1.6 and 18.2

![grid-virtual-mode-bug](https://user-images.githubusercontent.com/10086092/50989896-982ea600-14de-11e9-8e60-428088e41b2a.gif)

**Comment by vconst** [comment]
@RezaRahmati 
I've reproduced this issue and created [a public ticket](https://www.devexpress.com/Support/Center/Question/Details/T706575) in the DevExpress Support Center. You can subscribe to it to get a notification once we have any results.
