### ISSUE TITLE
dxDataGrid error "this._contentReadyAction is not a function" from datetime filter

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6561]
### Steps to Reproduce:

Open this codepen and try to group by the Company Name column.
https://codepen.io/anon/pen/yGQJmz

It happens when you have:
1) virtualColumnRendering enabled (and enough columns that some are not rendered)
2) a column with dataType=datetime
3) filterRow visible
4) you try to group by a column that has at least 2 values

The error is "TypeError: this._contentReadyAction is not a function".  It seems to be coming from the dxButton on the datetime filter widget.

### Environment Details:
version 18.2.3

**Comment by vconst** [comment]
@pcurrivan 
I've reproduced this issue and created [a public ticket](https://www.devexpress.com/Support/Center/Question/Details/T706583) in the DevExpress Support Center. You can subscribe to it to get a notification once we have any results.
