### ISSUE TITLE
Pivot Grid Pager

### ISSUE THREAD

**Issue by ZergRushJoe** [DevExpress/DevExtreme#6562]
I need a pivot grid pager because I have over 3000+ rows at minimum most queries.

**Comment by ZergRushJoe** [comment]
An example of how bad its needed I can stall your [demo page](https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/OLAPDataSource/jQuery/Light/) by adding all measure fields, adding Date.date field to columns and adding employee to row. The whole page times out and crashes.

**Comment by vconst** [comment]
Hi @ZergRushJoe,

Remote Paging is on [our roadmap](https://js.devexpress.com/Roadmap/#PivotGrid).
 
Please describe your requirements and expectations:
What data source types are you using?
What UI would you expect with remote paging. Are you fine with virtual scrolling or would like to use a pager for navigation?

**Comment by onebalaban** [comment]
Hello,

We will consider implementing the paging functionality in future releases. Please stay tuned to our news.
