### ISSUE TITLE
resize handler called during scrolling?

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6563]
I'm trying to determine what is making virtual scrolling so slow on my dxDataGrid.  With many columns it is really really slow.   The time seems to be taken up by calls to _correctColumnWidths and _updateRowHeight.  It looks like every scroll event is causing a resize event, which calls synchronizeColumns, which calls _correctColumnWidths.   The thing is, I have only fixed-width columns, and the grid is not being resized.  I haven't looked into why _updateRowHeight is being called, but again I only have fixed height rows.  It just seems like a lot of needless width and height calculations are happening during scrolling.  Is this intended?

**Comment by vconst** [comment]
Hi @pcurrivan,

Currently, the resizing is performed after each content rendering. This is necessary for correct layout calculation in different cases. For example, the _correctColumnWidths method corrects the last column width when the sum of column widths is less than the DataGrid width. The _updateRowHeight method uses rendered row height to calculate which rows should be loaded next during virtualization.
 
In v18.1 we added the [scrolling.rowRenderingMode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#rowRenderingMode) and [scrolling.columnRenderingMode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#columnRenderingMode) options, which improve performance during virtualization. With this options, the DataGrid will render visible cells only and will perform resizing asynchronously after scrolling is finished. Try setting these options to 'virtual' and let us know your results.
 
I have also prepared an example https://codepen.io/anon/pen/wNgdbZ which demonstrates the DataGrid performance when these options are enabled.
 
If the new options do not resolve the issue, please modify my example or create your sample that demonstrates the performance problem. We will analyze it and do our best to help you resolve it.

**Comment by pcurrivan** [comment]
Hi @vconst,

Thanks for your response.  I am fairly sure neither of those reasons for resizing during scrolling apply to my grid, where all columns have fixed width and all rows have equal fixed height.

That example works well - my browser just about keeps up with both vertical and horizontal scrolling without making me wait, but when you start adding additional features it slows down.  For example, showing the filterRow prevents my browser from keeping up with horizontal scrolling, or with vertical scrolling if I disable virtual column rendering (https://codepen.io/anon/pen/WPXRNp).

**Comment by vconst** [comment]
@pcurrivan,

DataGrid has the renderAsync option for such scenarios. It's efficient if columns have heavy templates and columnRenderingMode is virtual. I have added the renderAsync option to your example to demonstrate it in action: https://codepen.io/anon/pen/zbOPaO.
 
Also, we will research if it's possible to remove the updateDimensions method call during virtual scrolling in future versions.
