### ISSUE TITLE
dxDataGrid Filter "Between" dont work with Date

### ISSUE THREAD

**Issue by FabianoCastro** [DevExpress/DevExtreme#6572]
Hi, I have a problem in Row Filter with Dates in dxDataGrid

### Steps to Reproduce:

Config dxDataGrid
        dataSource: {
           store: new DevExpress.data.CustomStore(....)
        },
	remoteOperations: {filtering: true, sorting: true, paging: true,},
        filterRow: {visible: true, applyFilter: "auto", }
															},

1. Select Column Type Date
2. Input two dates

### Results You Received:
At first time work, but after does nothing

### Results You Expected:
Information of filter between In the event "load" of CustomStore, property loadOptions.filter

### Environment Details:
v18.2.4 in Chrome and Windows 10

![image](https://user-images.githubusercontent.com/34251113/51113270-9ae41080-17e8-11e9-8702-3698ff6bdf04.png)

**Comment by komarovalexander** [comment]
Hi,
I've tried to reproduce this issue but to no avail.
I've created a sample [https://codepen.io/anon/pen/Jwzddx/](https://codepen.io/anon/pen/Jwzddx/) please update it to illustrate the problem.
