### ISSUE TITLE
Why devextreme datagrid does not support numeric timestamps in colums of date and datetime type?

### ISSUE THREAD

**Issue by nowaalex** [DevExpress/DevExtreme#6577]
> NOTE
Date-time values stored as strings should have one of the following formats: "yyyy/MM/dd", "yyyy/MM/dd HH:mm:ss", "yyyy-MM-ddTHH:mm:ssx" or "yyyy-MM-ddTHH:mm:ss"

Quote from official docs

**Comment by AntonSermyazhko** [comment]
Hello,

The dxDataGrid support using timestamp for the Date-Time column as a numeric value.
Here is an [example](https://codepen.io/Anton454/pen/GPzVMb?editors=0010).

**Comment by AntonSermyazhko** [comment]
We will add info about timestamp values to our documentation.
