### ISSUE TITLE
calculateSortValue only works for first time sorting on dxDataGrid

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#6578]
### Steps to Reproduce:
Reffering to this documentation https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#calculateSortValue
1. Open this link [https://codesandbox.io/s/ov9onyxnzy](https://codesandbox.io/s/ov9onyxnzy)
2. Click on `Title` column to sort
3. Verify it sorts correctly based on calculateSortValue function (first Mrs. then Dr. and last Mr.)
4. Click on `Title` again to do opposite sorting

### Results You Received:
Nothing happen (although function is called and logged in console)

### Results You Expected:
Sorting values in reverse

### Environment Details:
reproducible on 18.2 and 18.1.6
![grid-custom-sort-issue](https://user-images.githubusercontent.com/10086092/51135788-d989c300-1808-11e9-8510-e0d5d6473c6e.gif)

**Comment by AlisherAmonulloev** [comment]
From what I gather, you wish to sort cells containing the 'Mrs.' and 'Dr.' values in the first place. 
If so, modify the calculateSortValue method in the following manner:
```javascript
customSortingFunction(rowData) {
  let column = this as any;
  if (rowData.Prefix == "Mrs.")
      return column.sortOrder == "asc" ? "aaa" : "zzz";
  else if (rowData.Prefix == "Dr.")
      return column.sortOrder == "asc" ? "bbb" : "yyy";
  else 
      return column.sortOrder == "asc" ? "zzz" : "aaa";
}
```
If this code snippet does not produce a suitable result, please describe how you wish to sort the Title column in greater detail.

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev Thanks, the code you provided is exactly same as I have. The issue is sorting works only for first time, then if you click on the column title again you expect to sort descending, which won't happen, see in my recorded gif I click on Title column multiple times but except first time nothing happens

**Comment by AlisherAmonulloev** [comment]
@RezaRahmati  my apologies for the wrong copy-paste. Following is the correct code snippet:
```javascript
  customSortingFunction(rowData) {
    let column = this as any;
    if (rowData.Prefix == "Mrs.") return "aaa";
    else if (rowData.Prefix == "Dr.") return "bbb";
    else return "zzz";
  }
```

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev this is same repo with your new code [https://codesandbox.io/s/zw1zpxw8zx](https://codesandbox.io/s/zw1zpxw8zx) (p.s your code doesn't include column direction for ascending/descending sorting, it's always ascending)
Still multiple clicking on column to sort doesn't work, I think you still didn't get what is the issue.

1. click on title -> sort works fine
2. click on title again -> sort doesn't work
3. click on title again -> sort doesn't work
4. click on title again -> sort doesn't work
5. click on title again -> sort doesn't work
6. click on title again -> sort doesn't work

(I want data to be sortable `asc` or `desc` like other fields)

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev are you able to reproduce based on my latest comment

**Comment by AlisherAmonulloev** [comment]
I have created a simple project based on my code snippet: https://codesandbox.io/s/jp9z621l3 Please check it.

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev thanks, my mistake when I forked my old sample somehow your new code wasn't applied. I changed it based on your seems working.
