### ISSUE TITLE
Model Binding Camel or Pascal

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#6585]
When using the DevExtreme MVC helper controls, there are times when your model doesn't match the corresponding incoming data.  Is there a way to have it resolve like automapper does, or set a parameter to say Camel or Pascal?

Otherwise I have to create duplicate models to support DevExtreme and base application support since I cant change the defaultResolver as it would break all existing code functionality.  EX CreateDTO, I could add a JsonProperty, but now that could cause issues if we use this DTO in a non DevExtreme method.

Ref: https://www.devexpress.com/Support/Center/Question/Details/T578340/mvc-controls-how-to-allow-camelcase-for-addfor-methods

**Comment by AlekseyMartynov** [comment]
Hello @bbakermmc 

We have already had the idea to support ASP.NET's default `ContractResolver` in our backlog. However, it was not in priority because, in most cases, users were OK with the use of `UpperCamelCase`.

We'll take this ticket into account and raise the priority of the corresponding work item.

Currently, instead of duplicate DTOs, you can specify exact property names in Razor:

```c#
@(Html.DevExtreme().DataGrid<Order>()
    .DataSource(d => d.Mvc().Controller("Orders").LoadAction("Get").Key("orderID"))
    .Columns(columns => {
        columns.AddFor(m => m.OrderID).DataField("orderID");
        columns.AddFor(m => m.OrderDate).DataField("orderDate");
    })
```

Thank you.

cc @San4es @jsdmitry

**Comment by AlekseyMartynov** [comment]
We still don't have a universal solution to the described problem.

Instead of creating duplicate models, I suggest that you use a custom JSON serialization in DevExtreme-related code. For example:

```c#
[HttpGet]
public object Get(DataSourceLoadOptions loadOptions) {
    return CamelCaseJson(DataSourceLoader.Load(SampleData.Orders, loadOptions));
}

static IActionResult CamelCaseJson(object obj) {
    var json = JsonConvert.SerializeObject(obj, new JsonSerializerSettings {
        ContractResolver = new DefaultContractResolver()
    });

    return new ContentResult {
        Content = json,
        ContentType = "application/json"
    };
}
```
