### ISSUE TITLE
TreeView - minimum search length

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#6597]
Unfortunately search in treeView is extremly slow, I think adding minimumSearchLength property for treeView can improve it (or even search by Enter key press). What do you think about it?

**Comment by DokaRus** [comment]
Hi,
Thank you for the suggestion.
TreeView already provides a way to change the search bar options. So, you can change the `valueChangeEvent` option to apply the search value by the Enter key press or on the focus loss. I've prepared a [simple example](https://codepen.io/Doka/pen/ebamRJ?&editable=true)..
As an alternative, you can set the [searchTimeout](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Configuration/#searchTimeout) option.
Did you try these approaches?

**Comment by Bykiev** [comment]
Hi Dmitry,

Thank you for a quick response. Sorry, seems I've missed searchEditorOptions in docs... But in some cases user will enter small keyword (1-4 letters) and the page is unresponsive for a long time on a large dataset. I want to try improve user experience by setting minimum number of characters. Will it improve the search speed? Or maybe there are some ways to improve search speed in virtual mode?
If it's not possbile I've another idea: as I can see the most heavy operation is expanding and displaying the nodes. You can add back and forward button in the search field and expand items when user pressed forward/back button. So, this way you need only expand the parent nodes of target item. I've attached a screenshot to make it more clear.
![sample](https://user-images.githubusercontent.com/13969777/51310954-ddac1f80-1a58-11e9-8b51-9e7ad8729615.png)

**Comment by novsstation** [comment]
Hi Andrey,

You can implement this by subscribing to the valueChanged event for the searchbox editor.
I have created a small [sample](https://codepen.io/SNovikov/pen/eYNLLqQ?editable=true) for you.

As for your question about the TreeView search performance,
could you please describe the problem with treeView configuration options in greater detail, or send us a small sample where we can see this issue?

**Comment by Bykiev** [comment]
Hi Sergey,

Thank you for your sample, it was really helpful!

Here is a demo with the search issue (just start typing 'item' text and you'll see page hangs): 
https://codepen.io/predatorz/pen/xxGaBVq

**Comment by novsstation** [comment]
Hi Andrey,

Thanks for your sample.
We are constantly improving the performance of our widgets, but in this case, the treeview node rendering takes some time. That's why, in your case, I suggest you separate keyboard input and TreeView search. Please try this [sample](https://codepen.io/SNovikov/pen/qBdJrmJ) and let me know your results.

**Comment by Bykiev** [comment]
@novsstation, thank you for your sample!

Indeed, applying search such way will improve user experience, but still search speed is very slow (because expanding treeview items takes a lot of time). The best way to improve search speed I described in https://github.com/DevExpress/DevExtreme/issues/6597#issuecomment-455115978 and now after PR [#12179](https://github.com/DevExpress/DevExtreme/pull/12179) I can disable default treeView search and make separate search textBox with forward/back buttons.

**Comment by novsstation** [comment]
Hi Andrey,

We are happy to hear that you found a suitable approach.
Please feel free to contact us if you have any other questions. We will do our best to help you.
