### ISSUE TITLE
dxDataGrid datatime grouping period control

### ISSUE THREAD

**Issue by nowaalex** [DevExpress/DevExtreme#6607]
If I want to group datetime fields by years, months, days, etc. I use something like this:
```javascript
import { startOfDay } from "date-fns";

const COLS = [
    ...,
    {
        dataField: "Date",
        dataType: "datetime",
        calculateGroupValue: rowData => {
            const v = rowData.Date;
            return typeof v === "number" && v > 0 ? startOfDay( v ) : "-";
        }
    }
];
```

But what if I want to give user an opportunity to choose this period? Should I implement this control manually?

**Comment by Alyar666** [comment]
Hello,

You can use the [onContextMenuPreparing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onContextMenuPreparing) event for this purpose. I have prepared an example to demonstrate this - [https://codesandbox.io/s/2xoypj074y](https://codesandbox.io/s/2xoypj074y).

![dxdatagrid](https://user-images.githubusercontent.com/23191430/51475251-e1121480-1d92-11e9-84a9-9c4c9b95a252.gif)
