### ISSUE TITLE
Setting dxDataGrid columns with groupIndex does not create groups

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6625]
### Steps to Reproduce:

https://codepen.io/anon/pen/dwxbpm
Open this codepen, in which the grid is initialized without any data.  Click the "Set Model" button.  This attaches data to the grid, including a column with groupIndex: 0.  

### Results You Received:

The column (Company Name) with groupIndex: 0 is not grouped.  If you change the initial values of dataSource and columns to getDataSource() and getColumns(), respectively, the grouping does work.

### Results You Expected:

The documentation says

>  there may be cases when grid records must be grouped initially. To do this, assign an integer value to the groupIndex option of those columns that should be used for grouping grid records.

I would expect this to work when setting columns after the widget is initialized.  Please either respect groupIndex when setting the columns option or clearly document that this option only works when the widget is first initialized.

### Environment Details:

version 18.2.3

EDIT:
I just noticed that if I switch the order in which I set the options so that I first set the columns option and then the dataSource option, the grouping works.

**Comment by Alyar666** [comment]
Hello,

Thank you for contacting us. We will process this issue in the context of the following Support Center thread: [dxDataGrid does not apply grouping when options are changed at runtime](https://www.devexpress.com/Support/Center/Question/Details/T708525)
