### ISSUE TITLE
Permission-based control access

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#6648]
Hello,

I'd like to restrict access to controls based on user permissions with AngularJS. For ex.: if user has permission to edit data in DataGrid it should be editable, but user can't add new items and delete old ones, otherwise it should be readonly. Same here for the other controls. For native controls in AngularJS it can be achived by creating a custom directive. Is any elegant way to restrict access to DevExtreme controls except explicitly setting allowAdding/allowUpdating/allowDeleting/disabled props? Thanks.

**Comment by hakimio** [comment]
That's not UI framework responsibility. You have to implement this yourself or use library like [ngx-permissions](https://github.com/AlexKhymenko/ngx-permissions).

**Comment by Bykiev** [comment]
@hakimio, basically, you're right. But with DevExtreme I don't see any easy way to restrict access (ie block adding new items and allow editing) with a custom directive or other way except explicitly setting required properties.

**Comment by hakimio** [comment]
Not sure if it works but you can try something like the following:
```html
<dx-data-grid 
    [dataSource]="dataSource"
>
    <dxo-editing
         ngxPermissionsOnly="ADMIN"
         [allowUpdating]="true"
         [allowDeleting]="true"
         [allowAdding]="true">
    </dxo-editing>
```

**Comment by vconst** [comment]
Hi @Bykiev,
 
Currently, DataGrid does not have any permission mechanism for AngularJS. I recommend you create a helper function that returns the [editing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/) configuration object based on current user permissions.

**Comment by Bykiev** [comment]
@vconst thanks, and what about other controls? Seems the only way is manual configuration.

**Comment by vconst** [comment]
@Bykiev,

Other widgets do not have permission options either. Use a binding to the disabled option for them.
