### ISSUE TITLE
DateBox: cursor should not move when adjusting date with up/down arrows when useMaskBehavior is enabled

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6674]
### Steps to Reproduce:

1.  Enable dateBox "useMaskBehavior"
2. Set displayFormat, ie "dd/MM/yyyy"
3. Use left/right arrow keys to select part of the date
4. Use up/down keys to modify part of the date

### Results You Received:
Part of the date being modified is no longer selected and cursor jumps to start or end of the date depending if you used up or down key

### Results You Expected:
Part of the date being modified should stay selected and cursor should not move

### Environment Details:
DevExtreme: 18.2.5
Browser: Chrome 71
OS: Windows 10

**Comment by DokaRus** [comment]
Hi,
 
Thank you for the report. I've reproduced the same behavior on my side.
I've created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T710547) in our Support Center. You can subscribe to it to get a notification once we have any results.
