### ISSUE TITLE
Doesn't work cascading lookups

### ISSUE THREAD

**Issue by kodermax** [DevExpress/DevExtreme#671]
On the version 17.1.3 doesn't work in a popup edit mode.
https://www.devexpress.com/Support/Center/Example/Details/T334359/dxdatagrid-how-to-implement-cascading-lookup-columns

**Comment by NickMitrokhin** [comment]
Hi @kodermax,

Thank you for bringing this to our attention. I've reproduced the issue. We are going to research it in the context of the [dxDataGrid - Cascading lookup columns do not work when the Popup edit form is enabled](https://www.devexpress.com/Support/Center/Question/Details/T534503) ticket. We will update that ticket when we have any news.
