### ISSUE TITLE
DataSource load method not working with ngrx store

### ISSUE THREAD

**Issue by itprodavets** [DevExpress/DevExtreme#6756]
Hi
How to use DataSource load method with ngrx store?

I have these problems:
   1) When the page loads, the load method is called
   2) infinite loading
   3) 2 requests are send to server instead of 1

```
this.ds = new CustomStore({
      load: (loadOptions: any) => {
        this.myFacade.loadAllRecords(this.filter, loadOptions);
        return this.myFacade.records$
          .toPromise()
          .then(result => {
            return result;
          });
      }
    });
```

![image](https://user-images.githubusercontent.com/5946414/52043305-6abea080-2550-11e9-8dd6-0993b0ef3ea6.png)

```
this.ds = new CustomStore({
      load: (loadOptions: any) => {
        this.myFacade.loadAllRecords(this.filter, loadOptions);
        return new Promise(resolve => this.myFacade.records$
          .pipe(takeUntil(this.unsubscribe$)).subscribe(resolve)).then(result => {
            return result;
          });
      }
    });
```
![image](https://user-images.githubusercontent.com/5946414/52045509-ba539b00-2555-11e9-8e32-85a0888599a5.png)

![image](https://user-images.githubusercontent.com/5946414/52045959-ad837700-2556-11e9-8197-60b028af5d0b.png)

```
public records$: Observable<any>;

  constructor(private store: Store<State>) {
    this.records$ =
      this.store.pipe(select(myQuery.getRecords));
  }
  loadAllRecords(model: myModel, loadOptions?: LoadOptions) {
    this.store.dispatch(new LoadRecords(model, loadOptions));
}
```

# Support Question

Please do not submit support requests and "How to" questions here. Navigate to our Support Center (https://devexpress.com/sc) instead.

**Comment by jailson** [comment]
```

**Comment by jailson** [comment]
@itprodavets Did you find the solution? Have you tried to return the promise instead? For example:
``` 
this.ds = new CustomStore({
      load: (loadOptions: any) => {
        this.myFacade.loadAllRecords(this.filter, loadOptions);
        return this.myFacade.records$.toPromise();
      }
    });
```

**Comment by itprodavets** [comment]
> @itprodavets Did you find the solution? Have you tried to return the promise instead? For example:
> 
> ```
> this.ds = new CustomStore({
>       load: (loadOptions: any) => {
>         this.myFacade.loadAllRecords(this.filter, loadOptions);
>         return this.myFacade.records$.toPromise();
>       }
>     });
> ```

I did not find a solution. I did it differently and more logically. I made a data loading container and I made a component that displays this data.

**Comment by onebalaban** [comment]
This issue has been closed due to inactivity.
