### ISSUE TITLE
dxDataGrid scrolling issue with fixed columns on Firefox

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6768]
### Steps to Reproduce:

1. Open this codepen with Firefox: https://codepen.io/anon/pen/PVpZVp
2. Fix a column.
3. Try scrolling.

### Results You Received:

Scrolling gets "stuck".

### Results You Expected:

Scrolling should not get stuck when columns are fixed.  It does not get stuck on Chrome.

### Environment Details:

DevExtreme version 18.2.5
Seen on Firefox versions 52 through 65.

**Comment by Alyar666** [comment]
Hello,

Thank you for contacting us. We will process this issue in the context of the following Support Center thread: [dxDataGrid - Scrolling works slowly when there are fixed columns in the Firefox browser](https://www.devexpress.com/Support/Center/Question/Details/T712460)
