### ISSUE TITLE
dxDataGrid column.format option restricted to numbers and dates

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#6781]
I just spent several hours very confused because the format I applied to a string column had no effect.  I eventually discovered by looking at the source code that the format option only works for number and date values, and silently fails for other types (https://github.com/DevExpress/DevExtreme/blob/19_1/js/format_helper.js#L12).  The way to format other columns seems to be with calculateCellValue and calculateDisplayValue.

I don't see why format should be restricted to numbers and dates.  If it must be, I think the documentation could be clearer.  There is no mention that it is restricted to numbers and dates [here](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#format), and only if you click through to the Format object structure might you notice that the function parameters are Number | Date.

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the note. However, I'm not sure what built-in formatting can be used for strings in a common case. Would you please describe this part in greater detail?
Have you tried using [customizeText](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#customizeText
) for your task before viewing the format option implementation?

**Comment by pcurrivan** [comment]
Hi @artem-kurchenko,
You would probably not use a built-in format for a string.  You would use a function: string => string.  I did not notice customizeText.

There are three column options with similar purposes: format, calculateDisplayValue, and customizeText.  I would suggest that the documentation for each of these options should explain why you would use it over the others.  Something like this (I'm not clear on why you would use calculateDisplayValue over the others):

**format** 
Formats a value before it is displayed in a column cell.  _Only usable for date and number types._

**calculateDisplayValue** 
Calculates custom display values for column cells. Requires specifying the dataField or calculateCellValue option. Used in lookup optimization.  _Prefer customizeText for string formatting, or format for date and number formatting._

**customizeText** 
Customizes the text displayed in column cells.  _Prefer format for number and date types._

**Comment by artem-kurchenko** [comment]
Hi,
 
Thank you for your feedback. We'll think of improving these parts. 
I'd like to clarify that calculateDisplayValue contains information about formatting at the bottom. It looks like we need to move it to the top to make it more noticeable :)
