### ISSUE TITLE
Popup *dxTemplate slow down the application

### ISSUE THREAD

**Issue by JacopoSciampi** [DevExpress/DevExtreme#6831]
### Steps to Reproduce:

1.  Create a classic popup with a custom html 
2.  The app I use have a map that basically is a div with some handlers. 
3.  After opening the popUp all the portal is slowed.

### Results You Received:
Performances issue.

### Results You Expected:
Nothing releated to a performance issue.

### Environment Details:

Version: 18.2.5

###Note
Here's a GIF that show how the whole application is slowed after the popUp is opened
[https://giphy.com/gifs/8rFgwbeDQFtyidVtXu](url)

**Comment by artem-kurchenko** [comment]
Hi,
 
I didn't notice performance decrease in your .gif image. Anyway, we cannot debug and diagnose performance problems only by screenshots and need to research the same case in action. 
 
Would you please create a test example demonstrating this scenario?
