### ISSUE TITLE
onCustomItemCreating from dxSelectBox not triggering

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/DevExtreme#6855]
I am using AngularJS.
I am on version of DevExtreme 18.2.5 according to my bower.json.

I am using the onCustomItemCreating for the dxSelectBox and I want the user to be able to type in a custom value.

However, this event is only ran in a very specific scenario.
This is the following scenario:
1. Select an item
2. Type in a different value directly after selecting.
3. Click outside the input.
Result => the onCustomItemCreating is ran.

In **any** other scenario, the onCustomItemCreating event is **not** being called.
This behavior is also happening on the demo page of the dxSelectBox: [dxSelectBox Demo Page](https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/AngularJS/Light/)

**Comment by DokaRus** [comment]
Hi,

This issue is related to the existing [T710656: It is difficult to add a custom item to SelectBox](https://www.devexpress.com/Support/Center/Question/Details/T710656) that was fixed in the upcoming v18.2.6.
