### ISSUE TITLE
Toolbar popout windows cut off (CSS?)

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#7002]
The css for the toolbar looks wrong when you hide items and use the button to show them:

V 18.2.6
![image](https://user-images.githubusercontent.com/30090055/53123670-94536200-3527-11e9-85ab-13a9427fe87d.png)

Previous versions:
![image](https://user-images.githubusercontent.com/30090055/53123737-bea51f80-3527-11e9-861c-ec6c66716813.png)

**Comment by hakimio** [comment]
It looks fine in [the demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Toolbar/Overview/Angular/MaterialTealLight/). Are you sure it's not your CSS which is causing the problem? Can you create a demo reproducing the issue?

**Comment by hakimio** [comment]
While the text doesn't seem to be cut-off. Vertical alignment seems to be definitely off -> [demo](https://codesandbox.io/s/6l5orwpx1w).

**Comment by bbakermmc** [comment]
I’ll check with our css.  But I downgraded to previous version and worked fine.

Sent from my iPhone

On Feb 25, 2019, at 5:39 AM, Tomas Rimkus <notifications@github.com<mailto:notifications@github.com>> wrote:


While the text doesn't seem to be cut-off. Vertical alignment seems to be definitely off -> demo<https://codesandbox.io/s/6l5orwpx1w>.
