### ISSUE TITLE
Datagrid's disabled selection checkboxes are clickable

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7014]
### Steps to Reproduce:

1. Create a datagrid and set mode: "multiple", showCheckBoxesMode: 'always'
2. Make all checkboxes disabled

### Results You Received:

Checkboxes are disabled, but still clickable

### Results You Expected:

Disabled checkboxes should be not clickable

### Environment Details:
Devextreme 18.2.6, Online example: https://codepen.io/anon/pen/gqJxGb

**Comment by AlisherAmonulloev** [comment]
We are aware of this limitation and have plans to introduce an API for implementing the functionality to avoid selecting certain rows. In the meantime, we recommend that you manually deselect rows you do not want to be selected in the onSelectionChanged handler. Check the https://www.devexpress.com/Support/Center/Question/Details/T497347 ticket illustrating how to implement this.
