### ISSUE TITLE
Grouping header columns overflow

### ISSUE THREAD

**Issue by tibi2303** [DevExpress/DevExtreme#7042]
### Steps to Reproduce:

1. Add multiple Column Headers to the DxDatagrid
2. Enable Grouping
3. Group by multiple column headers until the headers overflow out of the container

### Results You Received:
The Grouping column Headers are out of the container

### Results You Expected:
The overflow grouping column headers should break into a new line.

### Environment Details:
All browsers

https://i.gyazo.com/0b24c3f6ab842b0ff206e5ed5651d07b.png

**Comment by hakimio** [comment]
Or a simpler solution which wouldn't break any other layouts could be to have a scrollbar.

**Comment by AlisherAmonulloev** [comment]
The idea makes sense. Although this is not a very popular request, we will discuss the possibility of adding this functionality.
