### ISSUE TITLE
Filter will be cleared on DxDataGrid when there is filters with empty values

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#7043]
### Steps to Reproduce:

1. Open this [https://codesandbox.io/s/84731n56z9](https://codesandbox.io/s/84731n56z9) which some filters are applied through app.component.ts
2. Click on filter panel and open filter builder
3. Remove filter for "Invoice Number"
4. Click on OK

### Results You Received:
Filter will be cleared

### Results You Expected:
Filter for other two fields should be retained

### Environment Details:
18.2.6
![devextreme-empty-filter](https://user-images.githubusercontent.com/10086092/53257364-eb784480-3697-11e9-94b0-2f8588fbe6ab.gif)

**Comment by AlisherAmonulloev** [comment]
Hi,
 
The issue occurs since your filter contains incomplete nodes. Would you please describe your scenario in greater detail? In addition, clarify why you need to have nodes that do not have values.

**Comment by RezaRahmati** [comment]
Thanks for getting back, we have customized the grid to show as card-list, hence we had to remove columns and adding our own custom sort! (which is fine) also we enabled the filter-panel so that users are able to filter data. Then there were 2 issues:

1- Our users are complaining that they don't know how to use filter builder and it's hard for them to understand -> to solve this we added a column selector so that users choose the columns and we open filter builder with that columns already selected
2- Based on our UX team reasearch result the being filter builder on bottom of page is not that visible to users, so we had to create our own links on top of the grid -> to solve that we created our own links to create filter and clear filter

Please see the recorded gif
![devextreme-7043](https://user-images.githubusercontent.com/10086092/53507135-5339ef80-3add-11e9-8f1f-545d9e2811e0.gif)

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev ^^ does it make sense?

**Comment by AlisherAmonulloev** [comment]
Thank you for mentioning me. Somehow I missed your post. My apologies. Yes, your scenario makes sense. You need to make sure that an end-user has specified values in all filter nodes. Or, at least specify default values manually while creating the filter.

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev I have to convenience our QA though
