### ISSUE TITLE
how to Assign in object literal the e.dataField of onEditorPrepared (Datagrid)?

### ISSUE THREAD

**Issue by faststare08** [DevExpress/DevExtreme#7044]
it seems automatic generators/looping when making onEditorPrepared method called which I cant simple assignment in a object helper/controller within the popup form.
it seems 3 years ago someone asked this on your community forum (getEditor within dxDataGrid  mode:popup/form)  but you didn't add this feature. I hope that you add this feature within the year because editform within dxDataGrid will have no added value due to cant even control the editor(input) in this form. thanks

[Expected Result](https://media.giphy.com/media/9Vvw71dNrXng5SoUin/giphy.gif)

**Comment by hakimio** [comment]
Like stated in the support forums:

> The dxForm widget that is used when the form editing mode is enabled does not use the formData option. That is why the dxForm.getEditor method does not work.

If you want to customize the editor form you can either define your own form in [editing -> form](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/#form) or use [onEditorPreparing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onEditorPreparing) event to customize default form.
