### ISSUE TITLE
Add support for SelectBox datasource config via function

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7047]
Selectbox should support datasource configuration via function as datagrid's lookup column.

**Comment by hakimio** [comment]
Nowhere in [the documentation](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Configuration/#dataSource) is stated that dataSource config can be assigned to a function.

**Comment by Bykiev** [comment]
@hakimio, thanks, but to be consistent, it should be supported. I'll edit the issue to make it looking like a feature, not a bug

**Comment by San4es** [comment]
Hi @Bykiev @hakimio,

Thank you for your suggestion. At the moment, we see no reason to add the `Function` type to the `dataSource` option. Please share your intended use cases with us.
