### ISSUE TITLE
Grouping overflow when storing is enabled and the page refresh

### ISSUE THREAD

**Issue by tibi2303** [DevExpress/DevExtreme#7071]
### Steps to Reproduce:

1. Have grouping and state-storing enabled
2. Start grouping
3. Refresh the page

### Results You Received:
The grouping overflows the container

### Results You Expected:
The overflow is visible and width it's proper set

### Environment Details:
All browser

![image](https://user-images.githubusercontent.com/36895476/53408002-1cbd8100-39c6-11e9-9a51-ae7de67c1529.png)

**Comment by AlisherAmonulloev** [comment]
I was unable to reproduce the issue by using the https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/jQuery/Light/ demo. Please describe step by step instructions on how to replicate the problem.
