### ISSUE TITLE
Please provide an index.d.ts in your NPM package

### ISSUE THREAD

**Issue by snebjorn** [DevExpress/DevExtreme#7082]
Please provide an index.d.ts file in your root folder of your NPM package for devextreme as this will allow me to do ES6 imports in the "normal" way. You do this perfectly for your devextreme-angular package.

Now:
`import DataSource from "devextreme/data/data_source";`

After:
`import { DataSource } from "devextreme";`

You could also consider registering your name under af scope so something like: 
`npm install @devextreme/core @devextreme/angular`

EDIT

So I just noticed you have https://www.npmjs.com/package/@devexpress/dx-core seems there needs to be some housekeeping :)

**Comment by AlisherAmonulloev** [comment]
Hi @snebjorn,

Please allow me to share my thoughts regarding your suggestions.
The idea of creating an index.d.ts file for our each npm package and especially the devextreme package sounds interesting. At the moment, our modules are compiled with CommonJS and we did not fully migrate to ES6. Although we are going in this direction, we'll face certain challenges when creating the index.d.ts file. Some parts of our modules have the same name. It may be challenging to list them in this file. Thus, it may be also difficult to write import for them. React, for example, has slightly different syntax for the import, and it is not a problem to import different members that share the same name.

As for registering our packages under the devextreme scope, we considered this option and it has its pros. Upon further discussion, we stopped at the current naming. Packages were names a long time ago and I cannot find the exact reason why we used this naming.

As for the devextreme/dx-core package, this is an internal package that we use in our Reactive framework: https://github.com/DevExpress/devextreme-reactive  It is not intended to use separately from the main Reactive package. In any case, I agree that clarifying this on the package's page on npm will be helpful. I already informed the Reactive team about this.
