### ISSUE TITLE
TreeView ItemSelectionChanged event raised twice

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7084]
### Steps to Reproduce:

1. Create a treeView and specify _selectByClick: true_ option
2. Subscripe on ItemSelectionChanged event

### Results You Received:

On the first click on treeView node event raised one time, but other times it fires twice

### Results You Expected:

Event should be raised only one time

### Environment Details:

18.2.6. Online demo: https://codepen.io/anon/pen/WmbVqP

**Comment by artem-kurchenko** [comment]
Hi,
 
It's raised for both 'select' and 'unselect' actions in such cases. You can check event arguments to determine what action is performed.

**Comment by Bykiev** [comment]
@artem-kurchenko thx, it's not clear from the docs, the event object doesn't contain event propery on 'unselect' but does on 'select'. So, do I need just check if event property exists?

**Comment by artem-kurchenko** [comment]
@Bykiev By event arguments, I meant all available parameters. 
In this particular case, you can check the "node" parameter which represents the current node and has the 'selected' field. 
You can check this by clicking a link near this parameter (see the [screenshot](https://monosnap.com/file/PO4iJg7Ew5JW4fCoIbUeh3MRsgzHYn)).
I recommend you inspect all event arguments in our event handlers as they may contain additional information.
