### ISSUE TITLE
setting state caused incorrect pageIndex on DataGrid when it's in virtual scrolling mode

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#7100]
### Steps to Reproduce:

1. Open this link [https://codesandbox.io/s/ym86y77081](https://codesandbox.io/s/ym86y77081)
There are two grid same as each other, the only difference top grid has scrollingMode standard, bottom grid has virtual
2. Change page size to 10, and page number to 3 on both grids
3. Click on `save state` button, to save state of both grids
4. Change page size to 40 and page number to 5 on both grids
5. Click on `load state`

### Results You Received:
on virtual grid, page index goes to 21

### Results You Expected:
on both grid, page size be 10, and page index 2 (whatever is stored in state)

### Environment Details:
Reporducible on both : DevExtreme 18.2.6

Another similar issue was reported as below ticket but seems it's broken this behavior
[https://github.com/DevExpress/DevExtreme/issues/6553](https://github.com/DevExpress/DevExtreme/issues/6553)
[https://www.devexpress.com/Support/Center/Question/Details/T706575/datagrid-page-size-is-not-restored-via-the-state-storing-feature-if-scrolling-mode-is](https://www.devexpress.com/Support/Center/Question/Details/T706575/datagrid-page-size-is-not-restored-via-the-state-storing-feature-if-scrolling-mode-is)
![devextreme-grid-virtual-pageindex](https://user-images.githubusercontent.com/10086092/53523353-99557a00-3b02-11e9-917b-afc66886562a.gif)

**Comment by AlisherAmonulloev** [comment]
Hi,
 
I reproduced the issue and created a report in our Support Center: https://www.devexpress.com/Support/Center/Question/Details/T721065 Please refer to it for further correspondence.
