### ISSUE TITLE
dxTreeView can't set customized sort function like 'sortingMethod' which dxTreeList can.

### ISSUE THREAD

**Issue by yinlianghui** [DevExpress/DevExtreme#7101]
### Steps to Reproduce:
Just set the 'sort' property for the dataSource of dxTreeView,like this:
```
dxOptions = 
	searchEnabled: false
	dataSource: 
		store: 
			type: "odata"
			version: 4
			...
		sort: [{
			selector: 'name'
			desc: false
		} ]
...
...
$(".gridSidebarContainer").dxTreeView(dxOptions).dxTreeView('instance')
```

### Results You Received:
If I'm using English, I can see that the dxTreeView is displayed as a normal sorted tree.
But if I'm using Chinese, I see that the dxTreeView is displayed as a sorted exception tree.

### Results You Expected:
When using Chinese, The dxTreeView is displayed as a normal sorted tree.

I found that the dxTreeList control can customize the collation by using the 'sortingMethod' property, but the dxTreeView control does not support it. I hope it can support it.

The code for dxTreeList is just like this:
```
sortingMethod = (value1, value2) ->
	...
	return value1.toString().localeCompare value2.toString(), locale


showColumns = []
showColumns.push
	dataField: field.name
	caption: field.label
	...

_.every showColumns, (n)->
	n.sortingMethod = sortingMethod

dxOptions =
	...
	dataSource: xxx
	...
	columns: showColumns
	sorting:
		mode: "multiple"

$(".gridContainer").dxTreeList(dxOptions).dxTreeList('instance')
```

### Environment Details:

DevExtreme version: 18.2.4;
Browser: Chrome for Windows 10

**Comment by AlisherAmonulloev** [comment]
TreeView does not support the sortingMethod option. You should sort items at a data source level by using the [sort ](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/Configuration/#sort)option. I see you tried this, but it for some reason does not work for you. Please prepare a simple example so that I can examine it.
