### ISSUE TITLE
alternative solution on this?

### ISSUE THREAD

**Issue by faststare08** [DevExpress/DevExtreme#7105]
https://www.devexpress.com/Support/Center/Question/Details/T373710/dxdatagrid-the-geteditor-method-of-the-edit-form-returns-undefined

this solution doesnt work on node module.
`var editors = {};
$("#gridContainer").dxDataGrid({
    ...,
    onEditorPrepared: function(e) {
        if (e.parentType == 'dataRow') {
            editors[e.dataField] = e.editorElement[e.editorElement.data().dxComponents[0]]('instance');
        }
    },
    onRowUpdated: function(e) {        
        editors = {};
    },
    onRowInserted: function(e) {
         editors = {};
    }
});

...
alert(editors['MyDataField'].option('value'));`
any other alternative solution on this?

**Comment by faststare08** [comment]
SOLVED! but how to check if Adding or Updating Row?

**Comment by faststare08** [comment]
how to check if Adding or Updating Row? - SOLVED also.

**Comment by albertoVieiraNeto** [comment]
it would be awsome if you tell us how you solved the problem.
