### ISSUE TITLE
DataGrid FocusedRowChanged event is triggering twice when ColumnFixing feature added on React

### ISSUE THREAD

**Issue by metehansenol** [DevExpress/DevExtreme#7125]
Column
Paging
Grouping
GroupPanel
Selection
FilterRow
SearchPanel
ColumnChooser
ColumnFixing  --> (Problem !)
StateStoring
Export

I use above features except ColumnFixing on DataGrid. Everything was normal.

But after then I add ColumFixing on DataGrid, suddenly I noticed that FocusedRowChanged event start trigerring twice. I checked it by using console output in FocusedRowChanged event either adding and removing ColumnFixing.

Dependecies in my project's package.json:
 "dependencies": {
    "devextreme": "18.2.3",
    "devextreme-react": "18.2.3",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4"
  }

OS version: Windows 10 Pro x64
Node version: 10.15.1
Npm version: 6.4.1

**Comment by AlisherAmonulloev** [comment]
Hi,

Please accept my apologies for the delayed response. I reproduced the issue by using version 18.2.7 of DevExtreme widgets and created a public bug report in our Support Center: https://www.devexpress.com/Support/Center/Question/Details/T729593 Please add it to your Favorites if you have a DevExpress account to be notified of our progress.
