### ISSUE TITLE
Support for multiple toasts displayed at the same time in screeen?

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#7130]

**Comment by AlisherAmonulloev** [comment]
Currently this functionality is not supported. As a workaround, you can use the notify(options) overload and dynamically define the position option based on the previous dxToast position. Check the https://codepen.io/alishera/pen/eXgvJO example illustrating this.

**Comment by Zedwag** [comment]
Hello,

We added a possibility to stack Toasts via [Notify](https://js.devexpress.com/Documentation/ApiReference/Common/Utils/ui/#notifyoptions_stack) in v22.1. Also, we added [hideToasts](https://js.devexpress.com/Documentation/ApiReference/Common/Utils/ui/Methods/#hideToasts) to make interaction with multiple Toasts easier. See [What's New](https://js.devexpress.com/New/22_1/) and [Toast Stack](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Toast/Stack/Angular/Light/) pages for more details.
