### ISSUE TITLE
DataGrid won't focus new row [angular]

### ISSUE THREAD

**Issue by brunoccsnasajon** [DevExpress/DevExtreme#7186]
On one of your demos for DataGrid:

https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RowEditingAndEditingEvents/Angular/Light/

If you change <dxo-editing  mode to "cell", and then click on the plus button multiple times, the new row won't get focused after the first time. It kinda blinks like it gets focus and then loses it immediately.

**Comment by Alyar666** [comment]
Hello @brunoccsnasajon ,

Thank you for contacting us. We will process this issue in the context of the following Support Center thread: [DataGrid - The first cell is not focused when a new row is inserted in cell editing mode](https://www.devexpress.com/Support/Center/Question/Details/T724908)
