### ISSUE TITLE
dxTreelist filtering cause 'The request URL is too long' error

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7201]
### Steps to Reproduce:

1. Create a treelist with filterRow
2. allow remoteOperations
3. Type smth, apply filter, remove value and apply filter

### Results You Received:

After remove filter value it creates a query with long query string parameters which cause 'The request URL is too long' error (for ex.: [["Task_Parent_ID","=",0],"or",["Task_Parent_ID","=",1],"or",["Task_Parent_ID","=",7],"or",["Task_Parent_ID","=",10],"or",["Task_Parent_ID","=",16]]
_: 1551959872416)

### Results You Expected:

It should not include any query params if filter cleared

### Environment Details:

18.2.6, online demo: https://codepen.io/anon/pen/BbWdaw

**Comment by Alyar666** [comment]
Hello,

Thank you for contacting us. We will process this issue in the context of the following Support Center thread: [TreeList - Invalid query after resetting the filter](https://www.devexpress.com/Support/Center/Question/Details/T724827)
