### ISSUE TITLE
Using Backends rather than  .net

### ISSUE THREAD

**Issue by j209** [DevExpress/DevExtreme#7213]
Hi
Can we use devextreme with other back end technologies like [meteor](https://github.com/meteor/meteor),[Django](https://github.com/django/django),[Flask](https://github.com/pallets/flask),[Ruby on Rails](https://github.com/rails/rails),...?
Considering that Microsoft roadmap is cross platfom!

**Comment by hakimio** [comment]
Yes, you can use it with any backend you want.
