### ISSUE TITLE
DateBox / DateTimeBox with useMaskBehavior: can't disable scroll to change values

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#7223]
### Steps to Reproduce:

1. Configure a datebox with `useMaskBehavior` to `true`
2. Setup a date.
3. Scroll with the wheel

### Results You Received:
Scrolling with the wheel decreased / increased the value.

### Results You Expected:
I just didn't want that, but there is no way to disable such behavior.
As stated in the documentation (https://js.devexpress.com/Documentation/Guide/Widgets/DateBox/Value_Formatting_and_Masked_Input/) of the masked input for the DateBox:

> 
> The following changes apply when masked input is enabled:
> 
> **The mouse wheel or Up/Down Arrow key increases/decreases the selected value portion by 1.**
> The caret is moved to the next date portion when the previous date portion is entered.
> The year is entered right-to-left. For example, if 1 is entered, the year is 2001; if 18 is entered, the year is 2018.
> Numbers and first letters can be used to specify the month and day of week when they are displayed as text. For example, enter A or 4 to specify "April".
> 

However, **there is no way to disable such behavior**, which is most of the times unintended for date inputs; in fact, many users select a date, then scrolls the page to access other data and the date value changes instead. There should be an option to disable that feature.

### Environment Details:
DevExtreme version: 18.1.5
Browsers tested: Chrome, Firefox.
OS: Windows, MacOSx.

WORKAROUND to fix the issue:

In my specific scenario, the goal was just to disable that scroll issue, so what I did is, in Angularjs:

`
onValueChanged: function($event) {
       $event && $event.component && setTimeout(function(){
            $event.component.blur();
        });
}
`
So that this will blur once the value is changed.

**Comment by mrjohn0011** [comment]
Hello. You can disable the mousewheel event in the input using the following code:

`$dateBox.find(".dx-texteditor-input").off("dxmousewheel");`

Please note that you need do this after the widget is repainted.
We will take into account your suggestion about the possibility of disabling this event out of the box. 

Thank you for sharing your ideas with us.

**Comment by briosheje** [comment]
@mrjohn0011 Oh, thanks! I think this should (temporarely) be mentioned into the documentation.

Thanks again. May we close the issue? Of course it could be enhanced, but it can be easily solved with a single line of code.

**Comment by pedrofurtado** [comment]
> Hello. You can disable the mousewheel event in the input using the following code:
> 
> `$dateBox.find(".dx-texteditor-input").off("dxmousewheel");`
> 
> Please note that you need do this after the widget is repainted.
> We will take into account your suggestion about the possibility of disabling this event out of the box.
> 
> Thank you for sharing your ideas with us.

@mrjohn0011 Thanks! :handshake: But is a GREAT idea, provided by @briosheje, to mention this in documentation.

**Comment by pedrofurtado** [comment]
@mrjohn0011 The documentation was updated? If yes, could you share with us a link? Thank you so much! 🤝

**Comment by mrjohn0011** [comment]
@AlexJameson, what do you think about this idea?

**Comment by AlexJameson** [comment]
Hello, thank you for the idea. 
The suggested approach is based on the logic that relies on the internal events structure. We usually document only those features that are a part of the official API.  While a workaround is valid, it may stop working after an upgrade without any warning. 
We'll think of adding a public config (e.g. **maskOptions**) where you can disable certain actions for more advanced customization.
