### ISSUE TITLE
DataGrid: Item count in paging toolbar is not updated correctly when "repaintChangesOnly" is enabled

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#7259]
### Steps to Reproduce:

1.  Set "repaintChangesOnly" to true
2. Enable paging toolbar
3. Filter the data grid

### Results You Received:
Page count is updated correctly but total item count is not
![paging toolbar bug](https://user-images.githubusercontent.com/768105/54265586-f545e700-4575-11e9-96e3-23fb7f09dbb1.PNG)

### Results You Expected:
Both page count and total item count to be updated correctly in the paging toolbar
![paging toolbar correct behavior](https://user-images.githubusercontent.com/768105/54265602-fbd45e80-4575-11e9-9ddf-1a57eb4f8ee2.PNG)

### Environment Details:
DevExtreme 18.2.6

### DEMO app
https://codesandbox.io/s/849m1yqnnl

Check and uncheck "Filter Companies" checkbox to see the actual grid item count change but total item count shown in the paging toolbar remain the same.

**Comment by hakimio** [comment]
@vconst Can you reproduce the issue?

**Comment by vconst** [comment]
Hi @hakimio 

The issue fixed in the https://github.com/DevExpress/DevExtreme/pull/7192 PR. The fix will be available in version 18.2.8.

**Comment by hakimio** [comment]
@vconst Thanks for the fix.

**Comment by hakimio** [comment]
@vconst even with changes from your PR, paging toolbar still has the issue when calling `dataGrid.refresh(true)` directly.

**Comment by vconst** [comment]
@hakimio 
The issue with calling refresh(true) fixed in version 18.2.8 also.
