### ISSUE TITLE
Excel Export Enhancements

### ISSUE THREAD

**Issue by IgnatovDan** [DevExpress/DevExtreme#7294]
# The Problem

The [current DataGrid export implementation](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExportToExcel/) does not allow you to customize Excel files in the following ways:

- add a header and footer 
- add boolean values, images, rich texts, formulas, hyperlinks
- format values 
- border a cell
- add new worksheets
- customize the workbook or worksheet
- export several widgets into one file

# The Proposed Solution

We plan to use the third-party [ExcelJS](https://github.com/exceljs/exceljs) library for Excel file customization and add the 'exportDataGrid' utility for exporting the DataGrid.

**Note**: At the moment, we are testing the proposed solution and want to collect feedback and find out whether this solution covers most scenarios. After we finish the research, we will decide whether to reimplement the DataGrid's export in a similar way. 

## Add header and footer

```js
let dataGridOptions = {
    onExporting: e => {
        var workbook = new ExcelJS.Workbook();    
        var worksheet = workbook.addWorksheet('Main sheet');
      
        exportDataGrid({
            workbook, worksheet, dataGrid: e.component, topLeftCell: { row: 5, column: 1 },
            saveEnabled: false
        }).then(function(dataGridRange) {
            Object.assign(
            worksheet.getRow(2).getCell(2),
            { value: "My Header", font: { bold: true, size: 16, underline: 'double' } }
            );

            Object.assign(
            worksheet.getRow(dataGridRange.to.row + 2).getCell(2),
            { value: "My Footer", font: { bold: true, size: 16, underline: 'double' } }
            );
            return Promise.resolve();
        }).then(function() {
            return workbook.xlsx.writeBuffer();
        }).then(function(buffer) { 
            saveAs(new Blob([buffer], { type: "application/octet-stream" }), "DataGrid.xlsx"); 
        });
        e.cancel = true; 
    } 
};  
```

![header_footer_excel_screen](https://user-images.githubusercontent.com/2094015/54347226-a40e2400-4657-11e9-9898-997c238404bd.png)

## Export two grids into one worksheet

```js
let buttonOptions = {
    text: "Export Grids",
    onClick: function() {
        var dataGrid1 = $("#gridContainer1").dxDataGrid("instance");
        var dataGrid2 = $("#gridContainer2").dxDataGrid("instance");
        var workbook = new ExcelJS.Workbook();    
        var worksheet = workbook.addWorksheet('Main sheet');

        Object.assign(
            worksheet.getRow(2).getCell(2),
            { value: "Costs:", font: { bold: true, size: 16, underline: 'double' } }
        );
        Object.assign(
            worksheet.getRow(2).getCell(7),
            { value: "Ratings:", font: { bold: true, size: 16, underline: 'double' } }
        );

        exportDataGrid({
            worksheet, dataGrid: dataGrid1, topLeftCell: { row: 4, column: 2 },
            saveEnabled: false
        }).then(function(dataGridRange) {
            return exportDataGrid({
            worksheet, dataGrid: dataGrid2, topLeftCell: { row: 4, column: (dataGridRange.to.column + 2) },
            saveEnabled: true, workbook
            });
        });
    }
};
```

![two_grids_one_sheet_excel_screen](https://user-images.githubusercontent.com/2094015/54295634-7d52dd80-45c4-11e9-841e-17ad139a76df.png)

## Export grids into separate worksheets

```js
let buttonOptions = {
    text: "Export Grids",
    onClick: function() {
        var dataGrid1 = $("#gridContainer1").dxDataGrid("instance");
        var dataGrid2 = $("#gridContainer2").dxDataGrid("instance");
        var workbook = new ExcelJS.Workbook();    
        var worksheet1 = workbook.addWorksheet('Costs');
        var worksheet2 = workbook.addWorksheet('Ratings');

        Object.assign(
            worksheet1.getRow(2).getCell(2),
            { value: "Costs:", font: { bold: true, size: 16, underline: 'double' } }
        );
        Object.assign(
            worksheet2.getRow(2).getCell(2),
            { value: "Ratings:", font: { bold: true, size: 16, underline: 'double' } }
        );

        exportDataGrid({
            worksheet: worksheet1, dataGrid: dataGrid1, topLeftCell: { row: 4, column: 2 },
            saveEnabled: false
        }).then(function() {
            return exportDataGrid({
            worksheet: worksheet2, dataGrid: dataGrid2, topLeftCell: { row: 4, column: 2 },
            saveEnabled: true, workbook
            });
        });
    }
};  
```

![two_grids_two_sheets_excel_screen](https://user-images.githubusercontent.com/2094015/54345966-2f39ea80-4655-11e9-8edc-f3385e5a9d47.png)

### ExcelJS library

ExcelJS is a library for reading, manipulating, and writing spreadsheet data and styles to Excel and JSON. See [ExcelJS: Browser](https://github.com/exceljs/exceljs#browser) for more information.

### FileSaver library is used

FileSaver is a library for saving files on a client. See [FileSaver.js](https://github.com/eligrey/FileSaver.js/) for more information.

# Try It

## Live Sandboxes

1. [Add header and footer](https://codepen.io/DanIgnatov/pen/zbELOv)
1. [Export two grids into one worksheet](https://codepen.io/DanIgnatov/pen/RdjbRa)
1. [Export two grids each into a new worksheet](https://codepen.io/DanIgnatov/pen/JzOdpj)
1. [Simple export scenario](https://codepen.io/DanIgnatov/pen/WmEBjy)
1. [Customize file name](https://codepen.io/DanIgnatov/pen/ywoGrE)
1. [Customize workbook, worksheet](https://codepen.io/DanIgnatov/pen/rRzPQa)
1. [Customize cell](https://codepen.io/DanIgnatov/pen/XGawBJ)
1. [Manually generate and save XLSX file](https://codepen.io/DanIgnatov/pen/RdZdEv)
1. [Show dxLoadPanel](https://codepen.io/DanIgnatov/pen/GevLOp)

## Installation

Link [exportDxDataGrid](https://combinatronics.com/IgnatovDan/DevExtreme_DataGridToExcel/b96fe6c9181c3fbbf4883f80d07f75bc7c0e0cef/exportDxDataGrid.js), [ExcelJS](https://github.com/exceljs/exceljs), and [FileSaver](https://github.com/eligrey/FileSaver.js/) libraries.  

# We Need Your Feedback

## Take a Quick Poll

[Do you need these capabilities when exporting DataGrid in your projects?](https://docs.google.com/forms/d/e/1FAIpQLScMByKhqvP0IT5gBCMOG04Cx7viK0Jz5M1cN1X_tVbS5SUHWQ/viewform?usp=sf_link)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by hassankani** [comment]
The initial issue that this one was created from, [5165](https://github.com/DevExpress/DevExtreme/issues/5165), included a reference to being able to customise the exported cell appearance for pivotgrids, but that seems to now not be included in here.  Will the above changes include customisation of cells exported from pivotgrid too?  Or is that being covered elsewhere?  Specifically, we need to able to export pivotrgrids to excel which include color-coding of cell backgrounds.

**Comment by IgnatovDan** [comment]
Thank you for contacting us. I fully understand your idea.
Although I cannot promise you that we will implement it in the near future, we will take your opinion into account.
For DataGrid we considered this scenario and published our current results at [DevExtreme DataGrid – Excel Data Export Customization Enhancements (v18.2)](https://community.devexpress.com/blogs/javascript/archive/2018/11/07/devextreme-datagrid-excel-data-export-customization-enhancements-v18-2.aspx). For PivotGrid, we will manage this scenario in a similar way.

**Comment by CranMalReign** [comment]
Hello.  We currently have a requirement to add headers/footers to the Excel sheet headers/footers, not as rows in the sheet data.  While your examples and suggestions don't meet that, ExcelJS does provide the capability to set these values.  Will legitimate header/footer editing be provided out of the box?  When will these features be available?

We are currently replacing our grid implementation with another product and this feature is a must-have.  Thanks.

**Comment by IgnatovDan** [comment]
Thank you for describing your scenario.
I suggest that you start from our [DevExtreme - Data Grid - New Excel Export API Update (CTP in v19.1)](https://community.devexpress.com/blogs/javascript/archive/2019/10/04/devextreme-data-grid-new-excel-export-api-update-ctp-in-v19-1.aspx) post and the [DataGrid.ExcelJS CTP export](https://www.devexpress.com/Support/Center/Search/List/1?searchString=datagrid%20exceljs%20ctp) tickets.
If this information is not enough to implement your task, don't hesitate to [create a new ticket](https://www.devexpress.com/Support/Center/Question/Create). In this case, please send us a simplified project that demonstrates your requirements. This will greatly help us find a suitable solution for your task.

**Comment by cbogner85** [comment]
Hello, 

I would love to see this implemented in dxPivotGrid. :)

At the moment I'm implementing a custom export logic using other third-party excel libraries on the server-side.

**Comment by EugeniyKiyashko** [comment]
Thank you for contacting us. 
We are planning to do this, but I cannot give you the exact date. We will take your opinion into account.
