### ISSUE TITLE
Scheduler - Adaptability & UX Enhancements

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#7296]
# The Problem

The Scheduler component is not adapted for mobile devices.

# The Proposed Solution

We plan to:

- improve rendering of appointments on small screens. 
- add a floating button that allows a user to create new appointments.
- replace appointment tooltips with a drawer.
- make the appointment detail form fullscreen on mobile devices.

## UI Design

![mobile-scheduler-month](https://user-images.githubusercontent.com/11206389/54283326-d1eb5e00-45ae-11e9-8851-6ecb19d3b51f.png)

![mobile-scheduler-month-details](https://user-images.githubusercontent.com/11206389/54283301-c7c95f80-45ae-11e9-888e-8a4a777ad585.png)

![mobile-scheduler-week](https://user-images.githubusercontent.com/11206389/54283339-d748a880-45ae-11e9-81f4-c25700523e1c.png)

# Installation

Follow the installation guide from the [release page](https://github.com/DevExpress/DevExtreme/releases) and leave us feedback on this topic.

# We Need Your Feedback

## Take a Quick Poll

[Do you find improvements in adaptability useful?](https://docs.google.com/forms/d/e/1FAIpQLSd1PyeB43sAHXB4OJTaqr3SIeoFeDYKDI5d-D0EkeaI1i_UxQ/viewform)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by b1tzer0** [comment]
How does this look when dealing with Grouping and/or other resources?

For example: [Scheduler Overview Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/jQuery/Light/)

Or [Grouping Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation/jQuery/Light/)

**Comment by andrewmakarov** [comment]
Hi @b1tzer0,
We don't have plans to improve UI scheduler in grouping mode on a mobile device.
Primarily we will improve basic UI scheduler, that’s why grouping will not change visually

**Comment by rajiff** [comment]
Two suggestions

- Can we make the height of the schedule dynamic for all breakpoints, to automatically expand its height till the bottom of the browser basis a option, from where it is positioned, without developer having to custom style it

- Custom styling needs to be more easier

**Comment by andrewmakarov** [comment]
@rajiff 
Thank you for your feedback!

**Comment by dxbykov** [comment]
Thank you to everybody who gave us feedback on the adaptivity features. Some of them are available in the [v19.1](https://github.com/DevExpress/DevExtreme/releases/tag/19.1.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/). We will create separate threads for new adaptivity enhancements to discuss.
