### ISSUE TITLE
Menu in Grid Cell doesn't follow scroll

### ISSUE THREAD

**Issue by jperuggia** [DevExpress/DevExtreme#7325]
### Steps to Reproduce:

1.  Click the options button in the title column.
2.  While options menu is open scroll the grid

https://codesandbox.io/s/04lq7n19o0

### Results You Received:
The floating menu does not follow the button which launched it.

### Results You Expected:
The floating menu to follow the button.

### Environment Details:
DevExtreme: 18.2.7
DevExtreme-react : 18.2.7

**Comment by artem-kurchenko** [comment]
Hi,

We fixed the problem in the context of [this thread](https://www.devexpress.com/Support/Center/Question/Details/T707970/menu-a-submenu-is-not-automatically-closed-on-scrolling-the-page-after-the-upgrade-to). Check the hotfix there and let us know your results.
I also updated your example for quick testing and it seems to work as expected - https://codesandbox.io/s/3424777031
