### ISSUE TITLE
Datebox switches to AM when hour editor changed

### ISSUE THREAD

**Issue by cravr** [DevExpress/DevExtreme#7366]
devexteme version:18.2.5
    devextreme-angular version:18.2.5

[x ] bug Report 
This issue is present in the devextreme online demos
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DateBox/Overview/jQuery/Light/
When the Datebox is used at type="datetime", (third editor down in the demo)
Any changes made to the Hours input will switch the AM/PM editor to AM

**Comment by DokaRus** [comment]
Hi,
We already have [T721723 ticket] (https://www.devexpress.com/Support/Center/Question/Details/T721723) in our Support Center. You can subscribe to it to receive a notification once we have any progress.
