### ISSUE TITLE
Request - Tri State Slider

### ISSUE THREAD

**Issue by bbakermmc** [DevExpress/DevExtreme#7406]
Is there away to accomplish something like this with your controls currently?  If not can I request it.

A lot of times in business we have values that are Tri Sated and the tri state checkbox doesnt go over well with users.

EX: When you need an explicit Yes/No you don't want to use a checkbox in most cases since filled in and checked confuse alot of people.

So it would be nice to have a null/unknown center position and then a left/right that evaluates to true/false etc.

![image](https://user-images.githubusercontent.com/30090055/54833897-5ddb4500-4c95-11e9-86b0-13be822eb48c.png)

https://www.jqueryscript.net/form/three-state-switch-theswitch.html

**Comment by NickMitrokhin** [comment]
Hi,

We have the [dxSwitch](https://js.devexpress.com/Documentation/Guide/Widgets/Switch/Overview/) widget. However, it does not support three states. The only option we can suggest is to use [dxCheckBox](https://js.devexpress.com/Documentation/Guide/Widgets/CheckBox/Overview/). Take a look at the [How to implement dxCheckBox with three states](https://www.devexpress.com/Support/Center/Question/Details/T511876/how-to-implement-dxcheckbox-with-three-states) ticket where we discussed how to implement three states.

> can I request it

Of course, you can. However, we hardly implement it in the near future for two reasons:
1. This feature is not in our [Roadmap](https://js.devexpress.com/Roadmap/).
2. You are the only user who wants it.

If other users continue asking about this feature, we may reconsider our plans.
