### ISSUE TITLE
DataGrid focusedRowEnabled={true} and customizeText provided on any column application crashes

### ISSUE THREAD

**Issue by irfnkprc** [DevExpress/DevExtreme#7424]
**This is a Bug Report !**

### Steps to Reproduce:
https://codesandbox.io/s/n9x3xy624p

### Results You Received:

When focusedRowEnabled={true} on DataGrid and 
customizeText is provided to any column application crashes.

**Comment by hakimio** [comment]
Looks more like your event handlers are causing infinite loops, not DevExtreme issue.
DevExtreme seems to be working fine with focusedRow and customizeText:
https://codesandbox.io/s/mj7p3m2y1x

**Comment by irfnkprc** [comment]
@hakimio My example with React DataGrid, And code i provided forked from DexExpress own example.
All I have done is adding customizeText method to demonstrate.

**Comment by hakimio** [comment]
Seems to be an issue with React demo. If you comment out event handler code in the demo, it works.
You can report it DevExtreme React github page -> https://github.com/DevExpress/devextreme-react

**Comment by irfnkprc** [comment]
I have open issue under react project.
https://github.com/DevExpress/devextreme-react/issues/329
