### ISSUE TITLE
DateBox (as TimePicker) : interval 1 performance issues

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#7465]
### Steps to Reproduce:

1. Take the official demo of the DateBox (https://js.devexpress.com/Demos/WidgetsGallery/Demo/DateBox/Overview/jQuery/Light/)
2. Edit the second datebox from:
```
   $("#time").dxDateBox({
        type: "time",
        value: now
    });
```
to:
```
   $("#time").dxDateBox({
        type: "time",
        value: now,
        interval: 1
    });
```

3. Apply and run, click on the clock next to time: https://prnt.sc/n41wxe . This will come up, but it will take a **lot** of time if you don't have a good hardware. It looks like all the items in the dropdown are rendered, taking about 2 to 5 seconds (on an i7 8700) to display the dropdown.

### Results You Received:
The dropdown with the values under the DateBox took a lot of time to appear.

### Results You Expected:
I would've expected the same, with deferred loading or something like that. Perhaps virtual scrolling or similar, since it takes a lot to render the dropdown box.
I know this is just an enhancement, but it's worth mentioning that since there are several DX components that handles deferred loading and virtual scroll, this one should probably use these instead.

### Environment Details:
Devextreme version: 18.2.7
Browser: Chrome

**Comment by artem-kurchenko** [comment]
Hi @briosheje,

We checked this behavior and found that the editor renders more than 1K items in this case. 
We'll research if it's possible to improve the performance in our Support Center:
[DateBox operates slowly if interval is 1](https://www.devexpress.com/Support/Center/Question/Details/T743509)

In the meantime, consider using dxDropDownBox with dxList for this particular scenario. dxList provides paging out of the box.

**Comment by briosheje** [comment]
@artem-kurchenko Thanks, I've worked this around by just using the double dropdown box (with hours and minutes) and, now, I won't have the issue anymore thanks to the possibility to actually add custom buttons to the datebox.

I think this is a very low priority issue, I can't foresee many people needing interval 1, but still, it was worth to point the issue out. Thanks for taking care of that :)
