### ISSUE TITLE
Pivot Grid - Excel Customisation (Header & Footer)

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#7479]
### Steps to Reproduce:

1.   Pivot Grid Data - Export to Excel
2.   Need Custom Header & Footer like  Data Grid
3. 

### Results You Received:

No Custom Header & Footer

### Results You Expected:
Need Custom Header & Footer

**Comment by IgnatovDan** [comment]
Thank you for contacting us. I fully understand your idea.
Although I cannot promise you that we will implement it in the near future, we will take your opinion into account.
For DataGrid we considered this scenario and published our current results at [Excel Export Enhancements](https://github.com/DevExpress/DevExtreme/issues/7294). For PivotGrid, we will manage this scenario in a similar way.

**Comment by badarshahzad** [comment]
Hi, 
Kindly can you please suggest me for the below problem.

Is there any way to add custom column names for the pivot grid data. My pivot grid data columns names also not appearing. I search a lot but didn't find a way. I found many discussion where was mentioned there is no any way to add column name as field name when you export your pivot grid to excel file. 

I have hope you will understand my problem from below attached snap shots easily. 

Thank you.
Badar


![3](https://user-images.githubusercontent.com/19945367/56804752-394c2d00-6840-11e9-85c8-741f4adaa816.PNG)
![1](https://user-images.githubusercontent.com/19945367/56804753-394c2d00-6840-11e9-99e0-42b1338569f6.PNG)
![2](https://user-images.githubusercontent.com/19945367/56804754-394c2d00-6840-11e9-8b83-696b787df144.PNG)

**Comment by IgnatovDan** [comment]
Thank you for contacting us.
We will see how to improve this situation, though I cannot provide you with any time frame. In the meantime, the only option I can suggest is to follow the recommendations at [T570682 - dxPivotGrid - Add Row/Column titles (field panel) in the exported Excel file](https://isc.devexpress.com/Thread/WorkplaceDetails/T570682): use the [Window print()](https://www.w3schools.com/jsref/met_win_print.asp) method or our [ASPxPivotGrid](https://documentation.devexpress.com/#AspNet/clsDevExpressWebASPxPivotGridASPxPivotGridtopic) control from ASP.NET.

**Comment by badarshahzad** [comment]
@IgnatovDan   Can you suggest any answer related to the AngularJs? 
thank you

**Comment by IgnatovDan** [comment]
No, we don't have additional solutions for AngularJS projects to include the [FieldPanel](https://js.devexpress.com/Documentation/19_1/ApiReference/UI_Widgets/dxPivotGrid/Configuration/fieldPanel/) content into the generated XLSX file. Currently, we suggest using the [Window print()](https://www.w3schools.com/jsref/met_win_print.asp) method or our [ASPxPivotGrid](https://documentation.devexpress.com/#AspNet/clsDevExpressWebASPxPivotGridASPxPivotGridtopic) control from ASP.NET.
