### ISSUE TITLE
Feature request: datagrid/treelist filter should reflect UI

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7483]
Right now filter applied to dataGrid/treeList is not reflected by UI, so programmatically applied filters are not displayed in filterPanel. Please, add support for this feature in the future releases. 

Also I want to have ability to save custom user filters, unfortunately, I didn't find any suitable options to grab constructed filter expression and save it.

**Comment by jtoming830** [comment]
Hello Andrey,

You can use [FilterBuilder's value](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFilterBuilder/Configuration/#value) option to programmatically display applied filters and DataGrid's [getCombinedFilter](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#getCombinedFilter) method to get the total filter.

Please try it and let me know your results.
