### ISSUE TITLE
State storing interferes with selectedRowKeys input

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/DevExtreme#7496]
# Bug Report

**Package versions:**

    devextreme version: 18.2.6
    devextreme-angular version: 18.2.6

**Steps to reproduce:**
Initialize a component with a dxDataGrid which has a row selection stored with the stored state and a *different* row selection provided as an input bound to selectedRowKeys.

(Sorry, I don't have a simple repro at the moment.)
  
**Current behavior:**
The stored state selection takes precedence and the grid emits an initial selection event with the stored selection.  In my app, this then overrides the application state's row selection, which overrides the row selection input on the component.  So the new input row selection is effectively ignored.

**Expected behavior:**
<s>The selection I provide as input should take precedence over the stored state selection.</s>  I should be able to control whether each input takes precedence over the stored state for that input.  

**Use case:** 
I am deep linking from another page of the application into the component with the grid with certain rows selected.

**Workaround:** 
I guess I could delete the stored state before initializing the component when I need to override it.

**Comment by pcurrivan** [comment]
As a follow-up...

In some cases you may want the input to take precedence (e.g. you may provide a new sort order that you want to replace any saved sort order), and in other cases you may want the stored state to take precedence (e.g. you may provide a default sort order, but would prefer the saved sort order if it exists).  Sometimes you may want both (e.g. you want to override the stored selection but prefer the stored sort order to the inputted default sort order).

Currently I guess you just need to inspect/modify the gridState object.  It would be nice if it was typed.

**Comment by briosheje** [comment]
Not sure whether it's related or not, but I'm experiencing a problematic bug in devextreme 19.1.3 angularjs and angular.

If you initialize a `DataGrid` configuration and bind keys selection to it, once the widget is loaded, the keys selection is completely ignored.

In my scenario, I have the following happening:

- DxDropDown has a datasource, shared with DxDataGrid.
- Once DxDropDown is expanded, DxDataGrid is populated and loaded.
- The DxDataGrid config has its own binded `selectedRowKeys` property holding the array of selected keys.
- Once the datagrid is loaded, it completely ignores `selectedRowKeys` and overrides it.

I didn't find any solution yet. Even setting the rows manually at runtime doesn't solve the issue, the initial instance of the datagrid just ignores the configuration and resets all the values.

```js
 onInitialized: function(e) {
                                scope.dxDataGridInstance = e.component;
                                scope.LOG('forcing selectedRowKeys on datagrid!');
                                scope.LOG('it should select:', scope.currentlySelectedRowKeys);
                                scope.dxDataGridInstance.selectRowsByIndexes(scope.currentlySelectedRowKeys);
                                scope.LOG('dxDataGrid initialized!');
                                /*
                                if (scope.dxDataGridInitialSearchFilters) {
                                    e.component.filter(scope.dxDataGridInitialSearchFilters);
                                }
                                */
                            }
```

On init, the log is:

![image](https://user-images.githubusercontent.com/1898880/58406207-62432600-8069-11e9-8361-53366cf46129.png)

As you can see the "currentDeslectedRowKeys" is actually the `currentlySelectedRowKeys` scope property, and the configuration of the dxGrid (relevant part) is:

```js
scope.local.dxDataGridConfig = {
                            bindingOptions: {
                                selectedRowKeys: 'currentlySelectedRowKeys'
                            },
```

Surprisingly, it does happen only if you init the datagrid upon a dropDown open, if the datagrid is loaded somewhere else immediately, it does work as intented, it just looks like that if you need to force the selection initially it doesn't really seem to care about it.

**Comment by vconst** [comment]
Hi @pcurrivan,

By default, the DataGrid applies all state settings that can be customized at runtime.
To cancel selection state restore you can clear the [selectedRowKeys](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#selectedRowKeys) field from state on a [stateStoring.customLoad](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/stateStoring/#customLoad) callback:

```
selectedRowKeys: [1],
stateStoring: {
    enabled: true,
    type: "custom",
    customLoad: function() {
        try {
            var state = JSON.parse(localStorage.getItem("storage"));
            state.selectedRowKeys = undefined; // <-- selectedRowKeys is cleared
            return state;
        } catch {}
    },
    customSave: function(state) {
         localStorage.setItem("storage", JSON.stringify(state));
    }
}
```

See the following example: [https://codepen.io/vconst/pen/LYEaYeJ](https://codepen.io/vconst/pen/LYEaYeJ)

If you have other technical questions, please submit a new ticket to our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).

**Comment by vconst** [comment]
Hi @briosheje,

The [onInitialized](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onInitialized) event is designed to save the widget instance. So, it is not recommended to call methods and modify options here. Use the [onContentReady](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onContentReady) to call the selectRowsByIndexes method.

If you have other technical questions, please submit a new ticket to our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
