### ISSUE TITLE
stateStoring cause error when datagrid column had filter before column remove

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7522]
1. Create a datagrid with filer row/filter panel, add state storing
2. Set filter for some column
3. Remove the column with applied filter

### Results You Received:

```
> dx.all.js:17 Uncaught Error: E1047 - The "CustomerInfo.StoreState" field is not found in the fields array. See:
> http://js.devexpress.com/error/18_2/E1047
>     at u (dx.all.js:17)
>     at new Error (dx.all.js:17)
>     at I (dx.all.js:31)
>     at P (dx.all.js:31)
>     at Object.M [as getFilterExpression] (dx.all.js:31)
>     at t._calculateAdditionalFilter (dx.all.js:56)
>     at t._calculateAdditionalFilter (dx.all.js:9)
>     at t.combinedFilter (dx.all.js:49)
>     at t._handleCustomizeStoreLoadOptions (dx.all.js:49)
>     at i._fireCore (dx.all.js:10)
```

### Results You Expected:

Filter should be reset for removed column

### Environment Details:

v18.2.7, online demo: https://codepen.io/anon/pen/pBJJjP

**Comment by artem-kurchenko** [comment]
Hi @Bykiev,

As far as I understand, your colleague contacted us in the [Support Center](https://www.devexpress.com/Support/Center/) regarding this case. We've managed to find a [solution](https://codepen.io/anon/pen/BeQJpJ) for this issue.
 
Let us know if you need further clarification on this.

**Comment by Bykiev** [comment]
Hi @artem-kurchenko,

Yes, we get the answer, but I don't like this workaround. Why does it cannot be implemented inside datagrid?

**Comment by artem-kurchenko** [comment]
We didn't find a straightforward way to fix the problem at the widget level. The fix requires a lot of changes in the internal structure and will introduce changes that will affect more common scenarios. 
 
While we added this task to our extended backlog, there is no estimate for it.
