### ISSUE TITLE
Aggressive Change Detection using DevExtreme

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/DevExtreme#756]
Hi,
I'm starting using DevExtreme and I love it but I found a big performance issue.
I created a basic application with one route-state (main) and I put a dx-button in the main component.
The main component also display a binded variable.
That variable is a `get` property and putting a `console.log()` in it I noticed that it is call every time I move the mouse on the screen.
Removing any DevExtreme module resolve the problem.

Unfortunately I cant reproduce the case on Plunkr so I created a very small application that reproduce the case.
You can find it [here](https://drive.google.com/open?id=0Byg8znpo8wK8dG5GNGkxXzIweUk).

Once downloaded you just need to perform this commands:

- npm install
- npm run

As every angular-cli application the server is binded to localhost:4200 by default.

### Environment Details:
Mac OS 10.10
Node 6.11
angular-cli 1.2.1

**Comment by Aden-git** [comment]
Hello

This issue will be resolved in the context of our DevExtreme-Angular repository. I've created a corresponding issue - please follow our progress here: devexpress/devextreme-angular#516
