### ISSUE TITLE
Dropdown box Support CustomFiltering 

### ISSUE THREAD

**Issue by longnguyenit94** [DevExpress/DevExtreme#7636]
Dear DevExpress,

How to use CustomFiltering for dropdown box!
https://demos.devexpress.com/MVCxDataEditorsDemos/Editors/ComboBoxCustomFiltering

Long

**Comment by artem-kurchenko** [comment]
Hi,

This demo related to DevExpress ASP.NET MVC Components while this forum is devoted to DevExtreme components. 
Please address this question in the [Support Center](https://www.devexpress.com/Support/Center/Search/List/1)
