### ISSUE TITLE
Popup not on front side

### ISSUE THREAD

**Issue by alert83** [DevExpress/DevExtreme#780]
Popup not on front side when using inside TabPanel content template. it was fine before. but broken after npm update couple of days ago

### Steps to Reproduce:

1. Use Popup inside TabPanel content template

### Results You Received:

![image](https://user-images.githubusercontent.com/1808647/28313939-79fb1dd4-6bda-11e7-9c59-da559877289c.png)

### Results You Expected:

![image](https://user-images.githubusercontent.com/1808647/28314098-0b803596-6bdb-11e7-8627-30cf37675bf8.png)

### Environment Details:

17.1.4, angular 4.3.0, chrome, win 10

**Comment by artem-kurchenko** [comment]
Hi,
 
Thanks for contacting us. We are unable to replicate this behavior in a simple example. The issue might be related to the Angular environment specifics (see [Drop-down popup windows and submenus are displayed incorrectly in Angular CLI](https://www.devexpress.com/Support/Center/Question/Details/T535321/drop-down-popup-windows-and-submenus-are-displayed-incorrectly-in-angular-cli) )
 
Please create [a report in our Support Center](https://www.devexpress.com/Support/Center/Question/Create) and post a complete runnable example there for further research. We'll be happy to help.
