### ISSUE TITLE
dxForm: form 'readOnly' property overrides item's readOnly state

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7840]
### Steps to Reproduce:

1. Create a form, bind form's 'readOnly' property to variable, bind some form item's 'readOnly' property to another variable
2. Set form variable to readOnly=true and form item is readOnly = false
3. Update value at runtime: set form variable to readOnly = false and form item readOnly=true

### Results You Received:

Form item is not readonly

### Results You Expected:

Readonly form items should be readonly

### Environment Details:
DevExtreme 18.2.7, 
online demo: https://codepen.io/anon/pen/WWaJga (Press 'readOnly' button to make form not readonly and 'State' field readOnly)

**Comment by AlexanderKovalenko** [comment]
Hi,

Thank you for your sample. I see the problem. It looks like the angular-specific $scope.readOnlyForm = false instruction does not update the form's state immediately. It occurs after the editor.option('readOnly', $scope.readOnly) method call. Thus, it has no effect. I recommend that you introduce a short delay for the second instruction to fix this issue. Here is the modified code example: [https://codepen.io/anon/pen/dLLPEL](https://codepen.io/anon/pen/dLLPEL).

Please take a moment to look at [this](https://codepen.io/anon/pen/MRdYeK?editors=1010) sample that uses pure Angular components and illustrates that the internal input value is not updated immediately. So, it is impossible to change this behavior at the level of third-party components. Please use the approach I illustrated above or set component options directly (see Get and Set Options) without using Angular bindings.

Regards,
Alessandro (DevExpress Support)
