### ISSUE TITLE
Data Grid number Columns filter require Contains option like string filed

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#7848]
### Steps to Reproduce:

1.  Data Grid Number Column Filter need Contains option like string column
2. 
3. 

### Results You Received:
There is no contains option

### Results You Expected:
If filter 6 , should be filtered anywhere 6 placed in that column

**Comment by AlekseyMartynov** [comment]
By default, "Contains" is active for text columns.
For a numeric column, specify [`dataType`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#dataType).
