### ISSUE TITLE
dxForm: change form item visibility via itemOption is very 'heavy' on a weak PCs

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#7849]
### Steps to Reproduce:

1. Crate a form with items
2. Dynamically change form item's visibility using itemOption

### Results You Received:

Changing form items visibility has a great performance impact on a weak devices (it takes up to 5-10 secs to hide 4 items)

### Results You Expected:

Changing form items visibility should be as fast as using editor's option() method (can't use option, beacuse I need to hide labels too)

### Environment Details:

Devextreme 18.2.7 and early,
Online demo: https://codepen.io/anon/pen/WWamGx

**Comment by artem-kurchenko** [comment]
Resolved in the [Support Center](https://www.devexpress.com/Support/Center/Question/Create)
