### ISSUE TITLE
New Floating Action Button UI Component

### ISSUE THREAD

**Issue by groshenkovamarina** [DevExpress/DevExtreme#7878]
# The Problem

The DevExtreme library does not include the Floating Action Button (FAB) &mdash; a button that performs the primary action of a screen. This button should be displayed in front of all screen content. In a special case, the FAB can open a stack of two to five related actions (speed dial).

# The Proposed Solution

Drawing inspiration from Material Design guidelines by Google, we adopted the [Speed dial](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions) concept and implemented the FAB as a configuration container that automatically collects and contains all **SpeedDialAction** components defined on a page.

The **SpeedDialAction** component has the following API:

```js
let speedDialActionOptions = {
    icon: string
    onClick: function
};
```

## Add a Floating Action Button that performs a custom action

```js
$(".action-add").dxSpeedDialAction({
    icon: "add",
    onClick: function(e) {
        // ...
    }
});
```

## Add a Floating Action Button that opens a stack of related actions

```js
$(".action-edit").dxSpeedDialAction({
    icon: "edit",
    onClick: function(e) {
        // ...
    }
});

$(".action-repeat").dxSpeedDialAction({
    icon: "repeat",
    onClick: function(e) {
        // ...
    }
});
```

These **SpeedDialAction**s will be collected in a speed dial menu. It can include up to five actions. The FAB in this case opens the menu. You can change the maximum number of actions, as well as the FAB's position and icons in the opened and closed states, via the **floatingActionButtonConfig** object:

```js
DevExpress.config({
    floatingActionButtonConfig: {
        position: {
            at: "right bottom",
            my: "right bottom",
            offset: "-16 -16"
        },
        icon: "add",
        closeIcon: "close",
        maxSpeedDialActionCount: 5
    },
    // ...
});
```

# Try It

## Live Sandbox

[jQuery](https://codepen.io/anon/pen/oOJNwP)
[Angular](https://codesandbox.io/s/jln8yy5ykw)

## Installation

npm install devextreme@19.1.2-beta

# We Need Your Feedback

[Do you find the Floating Action Button component helpful?](https://docs.google.com/forms/d/1DvuZosG0_hk9izqzuCBEW5nlmKwT_Sa81J-zfZXePxU/edit)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by dxbykov** [comment]
Thank you to everybody who gave us feedback on this feature by different means. It's available in the [v19.1](https://github.com/DevExpress/DevExtreme/releases/tag/19.1.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).
