### ISSUE TITLE
Datebox - Refuse diaeresis when useMaskBehavior is enabled

### ISSUE THREAD

**Issue by fabianoacj** [DevExpress/DevExtreme#7887]
**Package versions:**

    devexteme version: 18.2.7
    devextreme-angular version: 18.2.7

**Steps to reproduce:**

https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/

**Current behavior:**

1) Add dxDateBox to page with useMaskBehavior enabled
2) Type ¨ and it will pass the mask

**Expected behavior:**
Do not permit diaeresis in the mask.

**Comment by artem-kurchenko** [comment]
Hi,

I cannot reproduce the issue in the latest version 18.2.8. I've recorded a [screencast](https://monosnap.com/file/gfnrpxmYUk0CBcBEby7MMLJ11NDAO0) using our [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DateBox/Formatting/jQuery/Light/)

Would you please update and check if the problem persists?

**Comment by fabianoacj** [comment]
Hi,

I've recorded a [screencast](https://monosnap.com/file/PjZ60tUnxkDSRXz8yc8X5iwqZUcSqU) using this [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DateBox/Formatting/jQuery/Light/) reproducing the error.

In Portuguese keyboards there are some different symbols that can be used. The mask refuses all of them, but the ¨ symbol pass the mask, as the screencast shows.

**Comment by artem-kurchenko** [comment]
Thank you for the clarification. Although I don't have the ¨ symbol in my language pack I reproduced the same issue with the '~' symbol. I created a report in our Support Center：
[DateBox allows entering special symbols if mask is enabled](https://www.devexpress.com/Support/Center/Question/Details/T740500/datebox-allows-entering-special-symbols-if-mask-is-enabled)
We'll update it once we have any news.

**Comment by artem-kurchenko** [comment]
Hi @fabianojardim 
We researched this case and found that the '~' symbol is related to "dead" ("system") keys and cannot be prevented in the "keydown" event. We use it to control masked inpput. 
The same behavior is reproducible for the standard input element as well: https://codepen.io/ArtemDevExpress/pen/gJgeeb?editors=1010

Let us know what key code and value the  ¨ symbol has and if it can be entered when "keydown" is canceled in the standard input.

**Comment by fabianoacj** [comment]
Hi @artem-kurchenko.

I used the link https://codepen.io/ArtemDevExpress/pen/gJgeeb?editors=1010 and discovered the following values for the ¨ symbol:

Key = "Dead"
Key code = 54

It can be entered when "keydown" is canceled in the standard input.

**Comment by artem-kurchenko** [comment]
Thank you for the clarification @fabianojardim. In this case, we won't be able to overcome the issue.
