### ISSUE TITLE
ODataStore - Remote Aggregation Support

### ISSUE THREAD

**Issue by Seteh** [DevExpress/DevExtreme#7974]
# The Problem

The [`ODataStore`](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ODataStore/) does not support server-side grouping and summary calculations. Grouping is performed on the client, and summaries are not supported.

The `DataGrid` and `TreeList` widgets allow users to group data and calculate summaries. However, these calculations are performed in the browser and can reduce performance with large data sets in the following cases:

- Data summaries ([issue T477975](https://devexpress.com/issue=T477975)).
- Loading [header filter](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/headerFilter/) items, unless a [custom data source](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/headerFilter/#dataSource) is configured ([issue T460670](https://devexpress.com/issue=T460670)).
- Grouping with the  [`autoExpandAll`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/grouping/#autoExpandAll) option set to `false` ([issue T554493](https://devexpress.com/issue=T554493)).

# A Possible Solution

The [OData Extension for Data Aggregation](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/odata-data-aggregation-ext-v4.0.html) standard introduces a new `$apply`query option. It adds basic grouping and aggregation functionality to the protocol. We would like to use it to enable remote aggregation in the `ODataStore`.

## Draft specification

A new `supportsAggregation` flag will be added to the `ODataStore` configuration, and its default value will depend on the [`remoteOperations`](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/remoteOperations/) value.

If the flag is enabled, the `ODataStore` constructs the `$apply` query parameter based on the load options.

**Example:**

```js
var store = new ODataStore({
  url: "/Products",
  version: 4,
  supportsAggregation: true 
});

store.load({
  group: "Name",
  groupSummary: { selector: "Quantity", summaryType: "sum" },
  totalSummary: { selector: "UnitPrice", summaryType: "sum" },
  requireGroupCount: true
});
```

The following query will be sent to the OData server:

```
/Products?$apply=concat(
  group((Name), aggregate(Quantity with sum as a1)),
  aggregate(UnitPrice with sum as a2)
)
```

The response is then transformed to a format that the `ODataStore` can work with.

# Limitations of OData Server Libraries

[.NET OData stack documentation](https://odata.github.io) suggests using [OData Web API](https://github.com/OData/WebApi/) and [RESTier](https://github.com/odata/RESTier/). The OData Web API has ASP.NET Web API and ASP.NET Core implementations, and the RESTier framework is based on the OData Web API.

We have tested `$apply` implementations in these libraries and found the following **limitations**.

## [Microsoft ASP.NET Web API for OData v4.0](https://www.nuget.org/packages/Microsoft.AspNet.OData/)

This library supports `group` and `aggregate` transformations since [v5.9](https://github.com/OData/WebApi/pull/594). However, the following features are missing:

- Support for `compute` ([issue 794](https://github.com/OData/WebApi/issues/793)). Without it, we cannot build a query for header filter items in `Date` columns or when the [groupInterval](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/headerFilter/#groupInterval) is used.
  
- Support for `concat`. We cannot execute the following query:
   ```
   $apply=concat(
     group((Name), aggregate(Quantity with sum as a1)),
     aggregate(UnitPrice with sum as a2)
   )   
   ```
   Without it, the `ODataStore` has to send multiple requests.

## [Microsoft ASP.NET Core for OData v4.0](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/)

Aggregation is not supported ([issue 893](https://github.com/OData/WebApi/issues/893)). This might be added in [v7.2](https://github.com/OData/WebApi/milestone/24).

# We Need Your Feedback

Before we implement this feature, we would like to hear from you. Please take [a quick poll](https://forms.gle/jSgvHeFSskPmynZj7).

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by AlekseyMartynov** [comment]
Thanks to everybody who gave us feedback on this idea. We've seen that the feature is important for some users. However, the overall amount of feedback is quite low. Considering this as well as the fact that the issues in the existing OData implementations are still open, we decided to remove the feature from our short-term plans.

I'm closing the ticket.

P.S. Thanks @Seteh for your hard work!

**Comment by goncharov-do** [comment]
@AlekseyMartynov do you have any updates regarding plans of supporting OData feature? We are going to utilize it and want to understand if it is excluded from future plans.
