### ISSUE TITLE
DateBox formatting Issue

### ISSUE THREAD

**Issue by sleimanrami** [DevExpress/DevExtreme#8004]
### Steps to Reproduce:

1.To reproduce you can use the devextreme DateBox demo and change as the following
2. Set in the Datebox the display format to 'dd-MMM-yyyy'
3. Set the useMaskBehavior to true
4. fill the day part
5. in the month part press 'm' (Mar is displayed) and then 2
6. The Datebox shows 'NaN-undefined-NaN2'

Any help will be appreciated

**Comment by sleimanrami** [comment]
I fixed it by adding:
  _if (isNaN(value))
        return;_
 to the following function in devextreme\ui\date_box\ui.date_box.mask.js


 _setActivePartValue: function(value, dateValue) {
        dateValue = dateValue || this._maskValue;
        var setter = this._getActivePartProp("setter"),
            limits = this._getActivePartLimits();
        value = (0, _math.inRange)(value, limits.min, limits.max) ? value : value % 10;
        if (isNaN(value))
          return;
        value = this._addLeadingZeroes((0, _math.fitIntoRange)(value, limits.min, limits.max));
        (0, _type.isFunction)(setter) ? setter(dateValue, value): dateValue[setter](value);
        this._renderDisplayText(this._getDisplayedText(dateValue));
        this._renderDateParts()
    }

**Comment by artem-kurchenko** [comment]
Hi @sleimanrami,

Thank you for the report. We're going to address it in the following PRs:
[8063](https://github.com/DevExpress/DevExtreme/pull/8063)
[8064](https://github.com/DevExpress/DevExtreme/pull/8064)
