### ISSUE TITLE
warning messages when loaded dxdatagrid in modal

### ISSUE THREAD

**Issue by douglasevp** [DevExpress/DevExtreme#8005]
### Steps to Reproduce:

1. to reproduce the warning messages, it is necessary to create a quasar framework SPA project
2. to create a dxdatagrid on a page and a button to open a modal to view more registry information
3. create a component that when selected a record in dxdatagrid and clicked on a button to edit the record, a modal is opened with another dxdatagrid

### Results You Received:
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"
RangeError: Maximum call stack size exceeded

### Results You Expected:
no warnings messages when opening the modal with the other dxdatagrid

### Environment Details:
quasar framework 0.17
google Chrome
devextreme 18.2.8
devextreme-vue 18.2.8

**Comment by artem-kurchenko** [comment]
Hi,

We are not aware of any issues with this framework and need a runnable example to research this case. Would you please attach it here? 

You can take DataGrid configuration and data from our [demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/FormEditing/Vue/Light/) to replicate the issue

**Comment by artem-kurchenko** [comment]
Hi @douglasevp ,

We are not aware of any issues with this framework and need a runnable example to research this case. Would you please attach it here? You can take DataGrid configuration and data from our [Vue demos](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/FormEditing/Vue/Light/
)

**Comment by artem-kurchenko** [comment]
@douglasevp  I'm closing the issue due to inactivity.  Feel free to leave a comment here or open a new issue if you have any progress.
