### ISSUE TITLE
Localization does not work for group panel and search panel and noDataText

### ISSUE THREAD

**Issue by MM-RYO** [DevExpress/DevExtreme#8059]
### Steps to Reproduce:

1. [Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Localization/UsingIntl/Angular/Light/)
2. I have updated app.component.html and app.component.ts file
`    <dxo-scrolling mode="virtual" rowRenderingMode="virtual" ></dxo-scrolling>
    <dxo-paging [pageSize]="100"></dxo-paging>
    <dxo-header-filter [visible]="true" [allowSearch]="true"></dxo-header-filter>
    <dxo-column-chooser [enabled]="true"></dxo-column-chooser>
    <dxo-group-panel [visible]="true"></dxo-group-panel>  `

`    changeLocale(data) {
        this.setLocale(data.value);
        //parent.document.location.reload(); 
        locale(data.value);
    }`
3. Click 'Apply' button then scroll up and check the result

### Results You Received:
the default display text did not change properly when i change locale at run-time.

search-panel
group panel  
noDataText

![image](https://user-images.githubusercontent.com/1568013/57840175-b3961e80-77fa-11e9-82c4-4a288e1ad38b.png)

### Results You Expected:

the display text did not affect immediately when i change language option

### Environment Details:
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "devextreme": "^18.2.7",
    "devextreme-angular": "^18.2.7",
    "devextreme-aspnet-data-nojquery": "^2.2.0",

**Comment by AntonSermyazhko** [comment]
Hello, our controls don't support changing the locale at runtime. In the demo this approach works thanks to bindings:
`
[caption]="formatMessage('Company')">
`
