### ISSUE TITLE
[Material] Tagbox input text alignment is off

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#8102]
### Steps to Reproduce:

1.  Add tagbox component
2. Set "searchEnabled" to true
3. Start typing something

### Results You Received:
Text input is not properly aligned with the tag text.
![tagbox bug](https://user-images.githubusercontent.com/768105/58003785-d0c03b00-7ae1-11e9-8349-143c81b256a7.png)

### Results You Expected:
Input text is aligned with tag text.
![tagbox aligned](https://user-images.githubusercontent.com/768105/58003793-d7e74900-7ae1-11e9-914e-0f6f7ea375eb.png)

### Environment Details:
DevExtreme 19.1.3
Chrome 74
Windows 10

**Comment by artem-kurchenko** [comment]
Hi @hakimio,

Thank you for the report. We fixed the issue in the [T739332](https://www.devexpress.com/Support/Center/Question/Details/T739332) thread. The official fix will be available in the next minor. In the meantime, you can request a hotfix for testing.
