### ISSUE TITLE
Suggestion: multi-row cellTemplate for dxDataGrid

### ISSUE THREAD

**Issue by roelvz** [DevExpress/DevExtreme#8104]
We have a requirement where we need to indicate that multiple consecutive rows in a grid are grouped, like this example where item 2 to 5 are grouped:
![requirement](https://i.imgur.com/FdDMoOc.png)

There's no way to do this. I think something like a columnTemplate would be interesting (much like the existing rowTemplate). Note that the demo already mentions a "Column Template" but this actually refers to cellTemplate (for a single cell).

I first posted this in support center: https://www.devexpress.com/Support/Center/Question/Details/T742117/dxdatagrid-icon-that-crosses-several-rows#answer-b4a97d12-9691-41be-bd19-ac6f0c0ac6b1

**Comment by AlisherAmonulloev** [comment]
Thank you for your idea. Although we currently do not have immediate plans to implement this functionality, I will discuss it with the team.
