### ISSUE TITLE
Selectbox with custom field template throws error when using arrow keys to select menu items

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#8132]
### Steps to Reproduce:

1. Create a selectbox with custom field template
2. Click on the input field to expand the selectbox
3. Try to navigate the menu list using up/down arrow keys

### Results You Received:
Error:
![selectbox error](https://user-images.githubusercontent.com/768105/58174294-d95d7080-7c9d-11e9-8d13-f9982160423c.PNG)
Source code line: [ui.drop_down_editor.js#L387](https://github.com/DevExpress/DevExtreme/blob/dca8d0a6b6dca8c8b3eba292be322d2727bdf16e/js/ui/drop_down_editor/ui.drop_down_editor.js#L387)

### Results You Expected:
No error.

### Environment Details:
DevExtreme 19.1.3
devextreme-angular: 19.1.3
Chrome 74
Windows 10

### EDIT: Additional info
Only seems to happen when using Angular wrapper.

### Demo
https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/Overview/Angular/Light/

**Comment by sometimesElen** [comment]
Hello,

Thank you for this bug report. As we process bugs using our Support Center, I created a new ticket - [T743479: Selectbox with a custom field template throws an error when arrow keys are pressed](https://www.devexpress.com/Support/Center/Question/Details/T743479). You can track our progress there.
