### ISSUE TITLE
How to cover a serie with another serie?

### ISSUE THREAD

**Issue by shawn-show** [DevExpress/DevExtreme#8150]
Is there any attribute in serie like zindex in highchart that let one serie be able to cover another serie?

**Comment by pavelgruba** [comment]
The dxChart does not provide such an option. The series is displayed in the order you specified using the [series](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/) option. You can also use the [customizeItems](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/legend/#customizeItems) option to change legend items' order.
