### ISSUE TITLE
The fixed column is shifted when add [scrolling]="{showScrollbar: 'always'}"

### ISSUE THREAD

**Issue by Yura13** [DevExpress/DevExtreme#8207]
### Steps to Reproduce:

The fixed column is shifted when add [scrolling]="{showScrollbar: 'always'}" and scroll to bottom. Sometimes its reproduce with horizontal scrolling.

https://codesandbox.io/s/record-grouping-devextreme-data-grid-kds9y
![image](https://user-images.githubusercontent.com/17030431/58552633-8d6d7700-821b-11e9-950a-dfa98ff21ac5.png)

### Results You Received:
The fixed column is shifted when scrolling to the bottom.

### Results You Expected:
The fixed column is not be shifted when scrolling to the bottom.

### Environment Details:
devextreme: 18.2.8
devextreme-angular: 18.2.8
angular: 6.1.10

**Comment by artem-kurchenko** [comment]
Hi @Yura13,

Thank you for the report. We fixed this issue in the [T737955](https://www.devexpress.com/Support/Center/Question/Details/T737955/datagrid-incorrectly-displays-content-of-a-fixed-column-when-native-scrollbars-are-used) thread.

**Comment by Yura13** [comment]
When version 18.2.9 will be released?

**Comment by artem-kurchenko** [comment]
It will be released in June
