### ISSUE TITLE
DataGrid / TreeList improved column filtering

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#8219]
@dxbykov any planned improvements to the column filtering as discussed in https://github.com/DevExpress/DevExtreme/issues/3565#issuecomment-379485554 ? Though we like your Grid and TreeList controls very much, we recently had several applications in which we had to replace them due to users liking the capability of the filtering in the other grid and not wanting to use the filter panel or liking that it takes extra UI space.

**Comment by dxbykov** [comment]
@genachka, your request for this particular filtering UI is the only one so far. There are a lot of different types of filtering UI in other third-party DataGrids, and we can't implement them all in our DataGrid. So, we implement only highly-demanded ones. At the same time, we provide the capability to implement a custom solution via DataGrid's customization API.

We have prepared a couple of examples on how to customize the DataGrid header cell and the header context menu and put a custom filtering UI into it. You can use them as a starting point for your custom solution.
 
Custom button in the header: https://codepen.io/ArtemDevExpress/pen/zQJevL
Custom filtering UI in the header context menu: https://codepen.io/anon/pen/XwxVxa
 
If you face troubles implementing it, feel free to create a corresponding ticket in our Support Center. Thank you for your collaboration.
