### ISSUE TITLE
Add box-plot in Chart

### ISSUE THREAD

**Issue by shawn-show** [DevExpress/DevExtreme#8278]
Please add a type of [box-plot](https://en.wikipedia.org/wiki/Box_plot) in chart. [Kendo](https://demos.telerik.com/kendo-ui/box-plot-charts/index) has a box-plot chart, but I want to stick with devetreme.

**Comment by alexanderPolosatov** [comment]
Hi,
Thank you for using DevExtreme and this request.
We will take the boxplot widget into account on the nearest planning. At present you can use the [bar](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Series_Types/BarSeries/) series and [errorBars](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/commonSeriesSettings/valueErrorBar/) to 'emulate' this feature.
Also, could you clarify what data will be better for you to pass to boxplot (your dataSource contains calculated values or values to calculate on our side)?

**Comment by shawn-show** [comment]
Hello,for the sake of computational efficiency, I suggest that the key points should be calculated in the background.It then returns the following json to form the boxplot.
```json
   var dataSource = [{
        argument_field: 'station',
        min: 1,
        q1: 2,
        average: 3,
        median: 4,
        q3: 5,
        max: 6
    }]
```

**Comment by alexanderPolosatov** [comment]
Thank you for your feedback . We'll take it into account.

**Comment by Fungusware** [comment]
Definitely need a boxplot control for devExtreme. All our charts are devExtreme except the boxplot where we have to use ChartJs plus a wrapper.
