### ISSUE TITLE
In compact themes, default width of dx-switch is too small to display 'off' text

### ISSUE THREAD

**Issue by roelvz** [DevExpress/DevExtreme#8281]
Use any generic compact theme (e.g. dark compact) and place a dx-switch. By default, it is too small to display the 'off' text. This can be seen on the demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/Switch/Overview/Vue/Dark/Compact/

This can be overcome by changing the width (37 pixels seems to be the minimum). Still, imho the text should be visible for the default width, even in the compact themes.

**Comment by hakimio** [comment]
While it's definitely missing some padding, for me "OFF" label is visible in both Chrome and Firefox. Are you using any custom CSS?

**Comment by roelvz** [comment]
Surprisingly, it seems to be OS related. It's not ok on Mac (in both Chrome, Firefox and Safari), but it is visible on Windows. Here's a screenshot from the demo website on Mac in Chrome:
![MacOS Chrome](https://i.imgur.com/PpaC5iq.png)

On Windows it looks ok:
![Windows Chrome](https://i.imgur.com/7JPSXaK.png)

**Comment by hakimio** [comment]
It seems different fonts are used on Mac. Are those coming from DevExtreme or system?

**Comment by roelvz** [comment]
Tbh I have no idea where the font comes from... since it's the DevExtreme demo website I guess it should be the DevExtreme font for both Windows and MacOS? I don't know.

**Comment by hakimio** [comment]
Just checked. It's using "Segoe UI" system font on Windows and "Helvetica Neue" system font on Mac. That's why they look different. Might be another font on Android & iOS as well.
