### ISSUE TITLE
Floating Action Button doesn't render properly

### ISSUE THREAD

**Issue by tuneis** [DevExpress/DevExtreme#8299]
I'm not sure if this should be posted here or on the base repo but I'm having an issue with the floating action button when using this template. I haven't tried without using the template but I suspect it might be the template causing it because the demos on the dev extreme site work just fine.

This is what is happening:

![Screenshot_14](https://user-images.githubusercontent.com/13182534/58738457-d2d4a480-83d3-11e9-955f-11f6a270b69a.png)

The button is essentially invisible. It renders and the functionality exists but it's massive and this is what it looks like when you click and hold down the left mouse button to render the animation for it.

Any idea what is happening here?

**Comment by groshenkovamarina** [comment]
Hi @tuneis,
I wasn't able to reproduce the issue using a stand-alone DevExtreme Angular Project Template. I have attached my project here for your examination. Please modify it to illustrate your scenario or attach an example demonstrating the issue.

[app-name.zip](https://github.com/DevExpress/DevExtreme/files/3256598/app-name.zip)
