### ISSUE TITLE
Labels not visible while continuously updating the datasource for a PieChart

### ISSUE THREAD

**Issue by joray8** [DevExpress/DevExtreme#8306]
While using a ArrayStore with a DataSource, pushing into it triggers a re-render of the already shown labels and the animation hides it.

**Current Results :**
The pie chart updates itself as intended when there's continuous push to the DataSource, but labels are hidden

**Results Expected:**
The animation of showing the label should be triggered once and only move the label/connector if an update is triggered by a push

Environment Details:
 "devextreme": "^19.1.3",
 "devextreme-react": "^19.1.3",
 "react": "^16.8.6",

**Comment by roman-simionov** [comment]
Hi,
At the moment, we do not have an option to modify label animation types. Right now I can suggest setting a smaller value to the [animation.duration](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxPieChart/Configuration/animation/#duration) option to show labels faster or disable the animation completely. We will take this scenario into account when discussing further pie chart improvements.
