### ISSUE TITLE
dxdatagrid - bottom line of the last item not visible

### ISSUE THREAD

**Issue by Pasto92** [DevExpress/DevExtreme#8381]
I have defined these settings in dx-data-grid:
[showBorders]="true"
[showColumnLines]="true"
[showRowLines]="true"

So I expected to see lines in grid.
Nevertheless row and column lines are not visible (Photo on the left).
But if I sort by clicking on column "Nome", they appear (Photo on the right).
![Photo](https://user-images.githubusercontent.com/50794419/59548938-01b35480-8f56-11e9-92d1-c3a08a0ec215.jpg)

It happens with datagrid inside a dx-popup:
<dx-popup>
            <div *dxTemplate="let data of 'content'">
                            <dx-data-grid #gridCollegamenti [dataSource]="ds_collegamenti [showBorders]="true" [showColumnLines]="true" [showRowLines]="true" height="300px">
                            </dx-data-grid>
           </div>
</dx-popup>

Without being in a popup it works fine.
Devextreme Angular, 19.1.3

**Comment by AlisherAmonulloev** [comment]
I was unable to replicate the problem. Would you please modify the https://codesandbox.io/s/f5qsk example to demonstrate the issue?

**Comment by AlisherAmonulloev** [comment]
I am going to close this thread since there has not been any recent activity. Feel free to reopen it once you modified the example.
