### ISSUE TITLE
TreeList / DataGrid column chooser - don't list some hidden columns

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#8398]
I have some columns that are set as `visible: false` and wanted to take advantage of the **columnChooser** functionality but I notice that when I set the columnChooser mode to **select** it shows those hidden columns for selection in the chooser. I never want those columns to be exposed or user to know about them in the UI of the chooser. There are other hidden columns which I do want to be selectable for the chooser.

How can I prevent the chooser from ever showing specific hidden columns?

**Comment by Alyar666** [comment]
Hello,

You can use the [showInColumnChooser](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#showInColumnChooser) option for this purpose.
