### ISSUE TITLE
Data Grid to Excel Export Using Excel JS

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#8426]
### Steps to Reproduce:

 **Data Grid -> Export to Excel Using Excel JS**
1. Right Alignment required in exported excel sheet
2. How do protected excel sheet while import ?
3. Page Setup,Orientation Setup before export
4. Column width specify each column for excel sheet before exporting

### Results You Received:
1. Amount column stored in text, shows left alignment . But datagrid shows right alignment
2. Excel sheet shows read only ,
3. Page Setup,Orientation Setup unable to find
4. Auto width assigned in excel sheet after exporting

### Results You Expected:
1. Right Alignment for amount column
2. Protected excel sheet required after export
3. Page setup, Orientation Setup required
4. Column width specify each column for excel sheet before exporting

**Comment by IgnatovDan** [comment]
Please accept our apologies for the delay in responding.

The [DevExpress.excelExporter.exportDataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJS) function is based on the [ExcelJS](https://github.com/exceljs/exceljs) library. In the 19.1 release, this function is at the CTP stage and some useful behavior is not implement yet. Although I cannot promise you that we will implement it in the 19.1 release, we will take your opinion into account. Thank you for your feedback. I greatly appreciate your cooperation.

1. With the [DevExpress.excelExporter.exportDataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJS) function in the 19.1 release, you can adjust alignment in this way:
`options.cell.alignment = { horizontal: 'right' };`
See [DataGrid.ExcelJS export - How to modify Excel cell alignment when exporting DataGrid into Excel using ExcelJS library?](https://www.devexpress.com/Support/Center/Question/Details/T756468) for more details.

2. The "excel sheet protection" scenario needs a clarification. Would you please describe it in greater details? For example send to us a reference to a manual like [Protect a worksheet](https://support.office.com/en-us/article/protect-a-worksheet-3179efdb-1285-4d49-a9c3-f4ca36276de6) or [Lock cells to protect them](https://support.office.com/en-us/article/lock-cells-to-protect-them-cb7835f6-9c37-4161-bb53-d1c410acaf21)?

3. ExcelJS provides the [Page Setup](https://github.com/exceljs/exceljs/tree/5efb1c7115f86b483ada46ca82ca9f1d6baaf76e#page-setup) options to adjust printing page settings. With the [DevExpress.excelExporter.exportDataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJS) function you can set the page orientation in this way:
`worksheet.pageSetup = { orientation:'landscape' };`
See [DataGrid.ExcelJS export - How to set Excel page orientation in Excel print dialog when exporting DataGrid into Excel using ExcelJS library](https://www.devexpress.com/Support/Center/Question/Details/T756473) for more details.

4. With the [DevExpress.excelExporter.exportDataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJS) function in the 19.1 release, you can set the column width in this way:
`worksheet.columns = [{ width: 25 }, { width: 15 }, { width: 10 }, { width: 30 }, { width: 30 }, { width: 15 }];`
See [DataGrid.ExcelJS export - How to set column width when exporting DataGrid into Excel using ExcelJS library](https://www.devexpress.com/Support/Center/Question/Details/T756477) for more details.
