### ISSUE TITLE
Selection of TreeList child nodes isn't working with the latest version (T751539)

### ISSUE THREAD

**Issue by Bykiev** [DevExpress/DevExtreme#8440]
### Steps to Reproduce:

1. Select Child item in TreeList (3-d level, for e.x.: Kevin Carter)

### Results You Received:

Child nodes are not slectable

### Results You Expected:

Child nodes should be selectable

### Environment Details:
DevExtreme 19.1.4, online demo: https://codepen.io/anon/pen/xogOqx

**Comment by vconst** [comment]
The issue fixed in 19.1.5
