### ISSUE TITLE
file manager event

### ISSUE THREAD

**Issue by jamokop** [DevExpress/DevExtreme#8489]
i need to manipulate file in file manager , and  i try to bind (create, rename,move,delete,copy) these event, in order to send requests to update my backend. what should i do ?

**Comment by vladkovl** [comment]
Hello,
 
Our file manager is in CTP now and, at the moment, it allows you customize all edit operations only on the server side. You can configure almost any back-end for the file manager's REST API. You can get more details in [this example](https://github.com/DevExpress-Examples/how-to-connect-aspnetcore-file-manager-to-database).
Our file manager doesn't allow customizing editing operations on the client side, but we want to add this functionality in the release version of our widget.
In the meantime, could you please describe what type of events you need and what kind of manipulations you want to perform in the file manager? Do they need to be accomplished on the server side or on the client side? What kind of back-end are you planning to use for the file manager? This information will help us create a solution that best meets your needs.

**Comment by jamokop** [comment]
just normal actions which already provided by file manager(upload file,move file,delete file,copy file,rename file ). Actually , i have created these action interfaces in order to update my backend.  i provider my custom function when i set up file manager(just like "onSelectedFileOpened"). then  pass these function as  options to file_manager.editing. then call these function respectively inside "creareEditAction".

**Comment by jamokop** [comment]
i try to use "_createActionByOption", but not working ,don't know why. However , i can find my custom function inside "_options"

**Comment by jamokop** [comment]
By the way , i want a new option to set currentPath

**Comment by vladkovl** [comment]
Thank you for your detailed information. I'm happy to hear you have found a solution.
As for the `currentPath` option, we have plans for it in our TODO list. For now, you can use it from the private API as shown below:
```
var folder = fileManager._currentFolder.createClone();
folder.parentPath = "Documents";
folder.name = "Projects";
folder.relativeName = "Documents/Projects";

fileManager._filesTreeView.option("initialFolder", folder);
```

Online example: [https://codepen.io/anon/pen/jjYMEb](https://codepen.io/anon/pen/jjYMEb)

**Comment by jamokop** [comment]
I got a new question .  Right now , i have created my own access right for managing file (backend) . 
if the user is unauthorized, i want to raiseOnError. i try to use "this._dialogDeferred.reject()" to show the error message. however , it's not working.
would u offer me a solution?

**Comment by vladkovl** [comment]
In case of an authorization error, you can pass from backend a json with information about the error as shown below:
```
{
    success = false,
    errorId = 100
};
```
 On the client side, you can modify the`fileManager._editing._raiseOnError()` function as shown below:
```
_raiseOnError(errorId, fileItem) {
    const fileItemName = fileItem ? fileItem.name : null;
    const message = errorId === 100
        ? "Access prohibited"
        : FileManagerMessages.get(errorId, fileItemName);
    this._actions.onError({ message });
}
```
As a result, the "Access prohibited" message will be displayed instead of the default message in case of an authorization error.
 
By the way we have "access control" feature in our TODO list for this widget.
