### ISSUE TITLE
[Material theme] Popup title cut off

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#8498]
### Steps to Reproduce:

1.  Open [Popup Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Popup/Overview/jQuery/MaterialTealLight/)
2. Choose Material theme (ie "Teal Light")
3. Click "DETAILS" button

### Results You Received:
Popup title is cut-off.
![cut-off title](https://user-images.githubusercontent.com/768105/60096831-4909c400-9752-11e9-9cbe-e391d30c665f.PNG)

### Results You Expected:
Popup title is not cut-off.

### Environment Details:
DevExtreme 19.1.4
Chrome 75
Windows 10

**Comment by Bykiev** [comment]
@hakimio, it's a [known issue](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=KnownIssues&StartBuildName=19.1.4&EndBuildName=19.1.4&version-mode=single-mode).

**Comment by onebalaban** [comment]
We will fix this issue in the context of this ticket [Popup - Title text is cropped in the Material theme](https://www.devexpress.com/Support/Center/Question/Details/T752400/popup-title-text-is-cropped-in-the-material-theme)
