### ISSUE TITLE
Any chance of having Blazor components?

### ISSUE THREAD

**Issue by thesobercoder** [DevExpress/DevExtreme#8553]
Any chance of having Blazor components? With Microsoft committing to ship it as an official web framework and DevExpress being in the .NET ecosystem for a long time, would be great to see that happen.

**Comment by CodeKarno** [comment]
Hi @thesobercoder 

We have created a set of native Blazor controls. Here is their GitHub repository: [DevExpress/Blazor](https://github.com/DevExpress/Blazor).
Currently, they are available as a Free Preview version. We are actively working on this component suite. Here is the roadmap for the nearest releases: [
Blazor Roadmap – What You Can Expect in the Next Few Months from DevExpress](https://community.devexpress.com/blogs/aspnet/archive/2019/06/24/blazor-roadmap-what-you-can-expect-in-the-next-few-months-from-devexpress.aspx).
Feel free to share your feedback about the existing components or describe features you would like to see in the [DevExpress Blazor](https://github.com/DevExpress/Blazor) repository or in our [Support Center](http://devexpress.com/ask).
