### ISSUE TITLE
The namespaces are inaccessible

### ISSUE THREAD

**Issue by gordon-matt** [DevExpress/DevExtreme#857]
I am using:

**Windows 10**,
**Visual Studio 2017 Enterprise - Version 15.2 (26430.16) Release**

When I install **DevExtreme.Web** from **Nuget** to a new **ASP.NET Core** application, the package reference shows up fine without any errors, but nothing works - the namespaces are inaccessible. I then tried to create another **ASP.NET Core** web app, but this time targeting the **full .NET framework** and I got the same problem. Also, I did restart Visual Studio in both instances to no avail.

Am I missing something here or is there a bug?

**Comment by AlekseyMartynov** [comment]
In ASP.NET Core, client-side libraries are managed via [Bower](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/How_To/Add_Bower_Packages_to_a_VS_ASP.NET_MVC_and_ASP.NET_Core_MVC_App/).
See https://docs.microsoft.com/en-us/aspnet/core/client-side/bower

The NuGet package you mention is for classic ASP.NET.

**Comment by gordon-matt** [comment]
OK thanks.. the [NuGet Package](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/NuGet_Package/) page doesn't actually say it's only for classic ASP.NET.. so naturally I assumed it was applicable for the .NET Core version as well.
