### ISSUE TITLE
NumberBox - Allow custom comma key

### ISSUE THREAD

**Issue by briosheje** [DevExpress/DevExtreme#8656]
### Steps to Reproduce:

1. Setup a number box.
2. Set the following format: `#,##0.00`
3. Run.

### Results You Received:
Using the widget, I can't write numbers using the KeyCode 110 (not 190).

### Results You Expected:
I expected it to work or have a way to define it.

In a nutshell, the big problem is that in some countries, for instance we can take Italy as an example, numbers are expressed in formats like: 1.411,30 (being 1411.30).
Currently, I didn't find any way to allow users to type `.` (keycode 110) to set up a comma: most editors handle that automatically (native inputs do and several other do as well).

It would be a great benefit to have a custom property to set in order to handle a custom keycode as the "comma separator" keycode.

**Comment by onebalaban** [comment]
Hi,

The dxNumberBox widget allows using a decimal delimiter corresponding to the current culture set on your device. For instance, in Italian culture, if a user types the 110 key code, the widget will insert a comma as a decimal separator. Try switching your device to a culture where a comma is used as a decimal delimiter to see the result.

**Comment by briosheje** [comment]
> Hi,
> 
> The dxNumberBox widget allows using a decimal delimiter corresponding to the current culture set on your device. For instance, in Italian culture, if a user types the 100 key code, the widget will insert a comma as a decimal separator. Try switching your device to a culture where a comma is used as a decimal delimiter to see the result.

I did already, and can't make it work.

As stated above, with format `#,##0.00`, typing `.` on an european keyboard (keycode 110) will **not** be considered a comma (though in excel, for instance, it is, as well in any regular input type number). The culture of the device is correct already.

I will try to make a video to properly show the issue, if I will be able to.

**Comment by onebalaban** [comment]
Hello,

If the problem is still relevant, could you please record a screencast demonstrating the steps to reproduce it?

Regards,
Romeo
