### ISSUE TITLE
grid column filter opens in wrong position

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#8744]
### Steps to Reproduce:

1. Open this [https://codesandbox.io/s/filtering-devextreme-data-grid-6zs9y?fontsize=14](https://codesandbox.io/s/filtering-devextreme-data-grid-6zs9y?fontsize=14)
2. click on "Invoice Number" header filter icon

### Results You Received:
filter panels opens in wrong position

![image](https://user-images.githubusercontent.com/10086092/60909899-5f814680-a24d-11e9-97be-e10e4d89e15d.png)

### Results You Expected:
filter panel opens in correct position

Please note if change the dataType of "Invoice Number" to number, filter opens in correct position

### Environment Details:
Devextereme: 19.1

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev Hi Alisher, would you please take a look at this issue and assign it to right person (it's submitted 10 days ago)

**Comment by hakimio** [comment]
Looks like a problem with the way you position your components or "ng-sidebar" does for you.
Why don't you use the "dx-drawer"? It doesn't cause issues like you've shown.

**Comment by RezaRahmati** [comment]
Thanks for replay, at beginning we tried to use dx-drawer but we find out it doesn't support whatever we want,  
Also I noticed that `ng-sidebar` use padding to push the content (including grid) however I believe it's a bug that grid doesn't consider such scenarios, what there would be a padding on page (not even side bar) and user tries to open filter.

**Comment by hakimio** [comment]
What's the scenario which is not supported by dx-drawer?

**Comment by hakimio** [comment]
>  what there would be a padding on page (not even side bar) and user tries to open filter.

Then the filter would go on top of the content with padding. Honestly, from my point of view, the side menu should not go on top of other elements when `mode` is `push`. It's a bug with `ng-sidebar`.

**Comment by RezaRahmati** [comment]
> > what there would be a padding on page (not even side bar) and user tries to open filter.
> 
> Then the filter would go on top of the content with padding. Honestly, from my point of view, the side menu should not go on top of other elements when `mode` is `push`. It's a bug with `ng-sidebar`.

Agree

**Comment by RezaRahmati** [comment]
> What's the scenario which is not supported by dx-drawer?

There were multiple, but most important one was "Dock" mode, so it will show as narrow side bar

**Comment by RezaRahmati** [comment]
@AlisherAmonulloev I fixed the issue by styling ng-sidebar as @hakimio direction

`::ng-deep .ng-sidebar.ng-sidebar--opened.ng-sidebar--push,
::ng-deep .ng-sidebar.ng-sidebar--opened.ng-sidebar--slide {
  z-index: 1;
}
`

[https://codesandbox.io/s/filtering-devextreme-data-grid-7j4ex](https://codesandbox.io/s/filtering-devextreme-data-grid-7j4ex)


Also reporting the issue to [ng-sidebar](https://github.com/arkon/ng-sidebar/issues/186)

**Comment by hakimio** [comment]
> There were multiple, but most important one was "Dock" mode, so it will show as narrow side bar

You can do the narrow sidebar with `dx-drawer`. Take a look at [DevExtreme Angular template app](https://devexpress.github.io/devextreme-angular-template/).
