### ISSUE TITLE
Unable to inject templates into wrapped TabPanel

### ISSUE THREAD

**Issue by RezaRahmati** [DevExpress/DevExtreme#8745]
### Steps to Reproduce:

1. Open this [link](https://codesandbox.io/s/overview-devextreme-tab-panel-3zo9h)
On the top of the page are a dx-selectbox and a dx-tabPanel with custom templates
On the bottom of the page there are a my-selectbox and a my-tabPanel with custom templates that are a wrapper around dx-selectbox and dx-tabpanel
2. Open top select box and confirm the template is applied to items
3. Open bottom select box and confirm the template is applied to items
(This means the way I developed to inject templates is working fine, also same approach like my-tabpanel works fine with datagrid) 

Now same thing on TabPanel, the code is using same approach

### Results You Received:
In the dx-tabPanel templates are working fine, in my-tabpanel only template names are shown

### Results You Expected:
display the temaplates in my-tabpanel

### Environment Details:
devextreme 19.1

**Comment by RezaRahmati** [comment]
Actually I solved the issue by changing ngAfterViewInit to below code

```
	ngAfterViewInit(): void {
		this.templates.forEach((template) => this.tabComponent.templates.push(template));
		this.tabComponent.ngAfterViewInit();
		this.tabComponent.instance.repaint();
	} 
```

Updated sand box with fix [https://codesandbox.io/s/overview-devextreme-tab-panel-627ij](url)

**Comment by sometimesElen** [comment]
Hello,

It is good news that the problem has been resolved. Thank you for letting us know about your progress and sharing your solution. I believe that other customers may find it helpful.

Nevertheless. the best way to get technical assistance is to create a ticket in our Support Center: http://www.devexpress.com/ask. You can get technical support there faster that here on GitHub.

**Comment by RezaRahmati** [comment]
@sometimesElen Thanks, which version is it fixed in?
