### ISSUE TITLE
Feature Request: Calendar Control With Date Range

### ISSUE THREAD

**Issue by b1tzer0** [DevExpress/DevExtreme#8931]
We have several customers who utilize a date range feature.  This is currently available in your MVC Controls.

An example of this can be found here: https://flatpickr.js.org/examples/#range-calendar
Another example can be found here, which falls more in line with what our customers want: https://demos.telerik.com/kendo-ui/daterangepicker/index

I see support center with a few requests for it, including one of my own.  I have implemented the suggested "Linking two date controls", however; I think a more elegant solution can be created.

Thanks

**Comment by sometimesElen** [comment]
Hello,

Thank you for the suggestion. This component is not in our nearest development plans. However, we are tracking all the customer requests to consider implementing it in the future.  It will appear in our [Roadmap](https://js.devexpress.com/Roadmap/) and here on GitHub once we decide to start working on it.
