### ISSUE TITLE
dxSelectBox with acceptCustomValue doesn't work correctly

### ISSUE THREAD

**Issue by AlexZDeveloper** [DevExpress/DevExtreme#9155]
Hello
I'm using DxSelectBox component with next settings:

```
<dx-select-box
        [items]="products" 
        [acceptCustomValue]="true"  
        displayExpr="name"  
        searchExpr="name"  
        [(value)]="selectedProduct"  
></dx-select-box>
```
```
@Component({  
  selector: "demo-app",  
  templateUrl: "./app.component.html",  
  styleUrls: ["./app.component.css"]  
})  
export class AppComponent {  
  selectedProduct: Product;  
  
  products: Product[] = [  
    { id: 1, name: "HD Video Player" },  
    { id: 2, name: "SuperHD Video Player" },  
    { id: 3, name: "SuperPlasma 50" },  
    { id: 4, name: "SuperLED 50" }  
  ];  
  
  constructor() {  
    this.selectedProduct = {  
      id: 7,  
      name: "SuperPlasma 65"  
    };  
  }  
}  
  
export class Product {  
  id: number;  
  name: string;  
}
```
My initial "selectedProduct" is not exists in "products" array. When the page with component loads, I see the text "SuperPasma 65" in select-box.
When I click on drop-down button and then click outside of the select-box component , the text in the select-box changes on "Select...". It's incorrect.
In devextreme 18.1.4 and earlier it's was worked correctly.
Simple example of this behavior: [link](https://codesandbox.io/s/overview-devextreme-select-box-r9rl2)

Devextreme Angular, 19.1.5
Thanks for help.

**Comment by sometimesElen** [comment]
Hello,

Please accept my apologies for this delay. You are right, it is unexpected behavior, so I created a **public** bug report in our Support Center:
[SelectBox removes an initial value when the end-user opens a drop-down part and closes it by an outside click](https://supportcenter.devexpress.com/ticket/details/t870508/selectbox-removes-an-initial-value-when-the-end-user-opens-a-drop-down-part-and-closes)

You can track it to stay informed of our progress.
