### ISSUE TITLE
DataGrid Filter | Cannot read property 'html' of null

### ISSUE THREAD

**Issue by Cammeritz** [DevExpress/DevExtreme#9237]
First of all: I know that this is the plain devextreme js repo. Altough im using it together with the Angular version the error occurs in the devextreme core package.

Basically i am using a DxDataGrid which has a few columns with a lookup table.

After updating to Angular 8 the column filter broke.

Basically it fails at creating the popup for the column filter:

### Steps to Reproduce:

1. Create an DxDataGrid (in devextreme-Angular: <dx-data-grid .../>) 
![image](https://user-images.githubusercontent.com/6163371/62926522-f7c29c00-bdb4-11e9-883b-8b220be6943e.png)

2. Add a colum with a lookup table 
![image](https://user-images.githubusercontent.com/6163371/62926438-d06bcf00-bdb4-11e9-8bc9-53631c579783.png)

3. Enable column filtering 
![image](https://user-images.githubusercontent.com/6163371/62926604-22acf000-bdb5-11e9-90a5-6b23eae975a8.png)

4. Try to filter the column 
![image](https://user-images.githubusercontent.com/6163371/62926665-3b1d0a80-bdb5-11e9-867a-849423caac50.png)

### Results You Received:

1. Nothing happens and this Error occurs:

--> Not compiled

`vendor.js:84047 ERROR TypeError: Cannot read property 'html' of null
    at vendor.js:456563
    at watchMethod (vendor.js:222929)
    at vendor.js:456560
    at Array.map (<anonymous>)
    at Object.map (vendor.js:321498)
    at fieldsWatch (vendor.js:456558)
    at vendor.js:456541
    at watchMethod (vendor.js:222932)
    at globalWatch (vendor.js:456551)
    at start (vendor.js:456535)`

--> Compiled

`main.7457ffe721950c84c2c5.js:1 ERROR TypeError: Cannot read property 'html' of null
    at main.7457ffe721950c84c2c5.js:1
    at main.7457ffe721950c84c2c5.js:1
    at main.7457ffe721950c84c2c5.js:1
    at Array.map (<anonymous>)
    at Object.t.map (main.7457ffe721950c84c2c5.js:1)
    at l (main.7457ffe721950c84c2c5.js:1)
    at main.7457ffe721950c84c2c5.js:1
    at main.7457ffe721950c84c2c5.js:1
    at i (main.7457ffe721950c84c2c5.js:1)
    at Sgvg.d (main.7457ffe721950c84c2c5.js:1)`

2. The popup shows up but keeps loading forever 

--> Not compiled

`core.js:9110 ERROR TypeError: Cannot read property 'getFocusedItemId' of undefined
    at inheritor._renderOpenedState (ui.drop_down_list.js:370)
    at inheritor._renderOpenedState (class.js:17)
    at inheritor._renderOpenedState (select_box.js:208)
    at inheritor._renderOpenedState (class.js:17)
    at inheritor._optionChanged (ui.drop_down_editor.js:558)
    at inheritor._optionChanged (class.js:17)
    at inheritor._optionChanged (ui.drop_down_list.js:667)
    at inheritor._optionChanged (class.js:17)
    at inheritor._optionChanged (select_box.js:647)
    at inheritor._optionChanged (class.js:17)`

--> Compiled

`main.7457ffe721950c84c2c5.js:1 ERROR TypeError: Cannot read property 'getFocusedItemId' of undefined
    at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1)
    at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1)
    at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1)
    at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)
    at n._optionChanged (main.7457ffe721950c84c2c5.js:1)`

### Results You Expected:

I expect it to create the popup and let me select the filteroptions.

### Environment Details:

OS: Windows 10
Browser: Version 75.0.3770.142 (Official Build) (64-Bit)
DevExtreme Version(s): devextreme + devextreme-angular 19.1.5
JS Framework: Angular 8

### Resumé

As you can see this error occurs in devextreme itself, so i assume its a problem with devextreme and not devextreme-angular, it might not be because of the upgrade from Angular 7 -> 8 but who knows. I only know that it used to work in Angular 7.

Thanks for helping out guys!

**Comment by AntonSermyazhko** [comment]
Hello,
I could not reproduce the behavior you described in my [sample](https://codesandbox.io/s/cell-editing-and-editing-api-devextreme-data-grid-y15b5). Perhaps, the custom filtering operations are causing the problem in your project.

Please modify my [sample](https://codesandbox.io/s/cell-editing-and-editing-api-devextreme-data-grid-y15b5) to reproduce the issue.

**Comment by Cammeritz** [comment]
Thank you for your reply. I tried to give my best to break your example. Couldn't do it tho.
I tried around a lot locally and still was not able to find out what it is. I also tried playing around with the lookup etc and removing the filtering operations but i couldn't find a fix yet.
The interesting thing is that the problem only occurs in the lookup columns (because they generate the dropdown list for filtering), but it only breaks in the grid view, in the filterbuilder-panel it works fine. We are now using Angular 8.2.4, Devexpress/(-Angular) 19.1.5 and it still does not work yikes. Ill try out a little bit more and update you if i get it running again :)

**Comment by Cammeritz** [comment]
So i dug a little deeper now and did the sneaky pro-move every developer loves:

Add a try/catch block around the error yikes.

So basically i logged all the parameters the fieldsWatch function gets when its called and throws an error.

You can see the results in the screenshot below:

![image](https://user-images.githubusercontent.com/6163371/64171937-254eb280-ce54-11e9-8fbb-7a34fb1f4061.png)

As you can see it renders fine and also the filter functionallity works but the "(All)" option is missing.
I guess thats why i get a null reference error (data = null).

Any idea how i can fix this?

**Comment by AntonSermyazhko** [comment]
Thanks for the callstack. We have analyzed it and found a similar problem in our support center: [T752172](https://supportcenter.devexpress.com/internal/ticket/details/T752172). The problem relates with a [bug in ZoneJS](https://github.com/angular/angular/issues/31678). As a workaround you can downgrade the ZoneJS version to v0.8.
Hope this would help you solve the issue.
Otherwise, please make a sample project reproducing the issue.

**Comment by Cammeritz** [comment]
Alright, i updated to the newest Version of zone.js (currently ~0.10.2) and now it works again 😃 
Thank you for your help @AntonSermyazhko

**Comment by lcdrN** [comment]
Hello,
I have exactly the same problem.

DevExtreme Version(s): devextreme + devextreme-angular 19.2.6
JS Framework: Angular 8
zone.js : 0.10.2

I tried with zone.js in version 0.8 but I still have the same error :

`main.7457ffe721950c84c2c5.js:1 ERROR TypeError: Cannot read property 'getFocusedItemId' of undefined at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1) at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1) at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1) at n._renderOpenedState (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1) at n._optionChanged (main.7457ffe721950c84c2c5.js:1)`*

Thanks for helping !

**Comment by jsalzarulo** [comment]
Edit: This resolved my issue: https://github.com/angular/angular/issues/31678#issuecomment-635132341
I created a zone-flags.ts file, added the mentioned line, imported into polyfills.ts, added to tsconfig in files list.
Just figured I'd add this in case others are still having this issue. As you can see in the other issue thread, this particular problem is not resolved with the latest version of zone.js and is still being researched.

This has suddenly become a problem again - seems that it may have been fixed, but I suddenly started getting this error in my project. Exactly as @lcdrN describes. Only difference is I'm running Angular 9.

DevExtreme Version(s): devextreme + devextreme-angular 19.2.6
JS Framework: Angular 9
zone.js : 0.10.2
