### ISSUE TITLE
TypeScript dxDataGridRowObject incomplete def

### ISSUE THREAD

**Issue by thenning** [DevExpress/DevExtreme#9244]
dxDataGridRowOjbect is used as the type for e.row in onEditorPreparing for dxDataGrid, however there are properties like e.row.inserted that are not accounted for in the dxDataGridRowObject definition. 

Workaround (e.row as any).inserted

DevExtreme 19.1.5

**Comment by b1tzer0** [comment]
This is previously reported in Support Center.
[T805500](https://www.devexpress.com/Support/Center/Question/Details/T805500/typescript-definition-dxdatagridrowobject-property-missing-inserted)

Support Center Answer:
This option is private and not documented. We have plans to add it in future updates.

**Comment by artem-kurchenko** [comment]
@thenning @b1tzer0

Good news. We added the [isNewRow](https://js.devexpress.com/Documentation/19_2/ApiReference/UI_Widgets/dxDataGrid/Row/) parameter in v19.2. Note that you need to replace 'inserted' with this parameter after an upgrade.
