### ISSUE TITLE
NumberBox - Currency format using zeros instead of comma

### ISSUE THREAD

**Issue by ricardocamara-adinco** [DevExpress/DevExtreme#9266]
### Steps to Reproduce:

1. Setup a devextreme devextreme-angular devextreme-intl
2. Setup config({ defaultCurrency: 'MXN' }); and locale("es-MX");
3. Setup a NumberBox

### Results You Received:
Using the widget, instead of getting comma in thousands, I get a '0' added.
![captura1](https://user-images.githubusercontent.com/37219213/63043206-5cebbf80-be91-11e9-9127-901ea4341109.PNG)

### Results You Expected:
If I dont define a locale (or use 'en'). I get the expected result (but with the money code).
![captura2](https://user-images.githubusercontent.com/37219213/63043259-7b51bb00-be91-11e9-8d6c-19d7b7fb6339.PNG)

### Environment Details:
Using DevExtreme 19.1.5
Chrome v76
Windows 10

**Comment by DokaRus** [comment]
Hi,
 
This issue is already discussed in the [T803422](https://supportcenter.devexpress.com/ticket/details/T803422) ticket in our SC. It is solved and a hotfix for version 19.1 is available for download.
