### ISSUE TITLE
Package's license field is invalid

### ISSUE THREAD

**Issue by bponomarenko** [DevExpress/DevExtreme#9324]
`license` property in `packages.json` file states: "SEE LICENSE IN README.md"
On fact, actual license is in `LICENSE.md` file.

**Comment by BingoRUS** [comment]
Hello @bponomarenko!

`README.md` describes the DevExtreme product and contains an external link to our Licensing FAQ with all information about commercial and non-commercial licenses. The `LICENSE.md` file is related to this repository with source code only which should not be used for commercial purposes.
