### ISSUE TITLE
how devextreme asp.net core DateBox control shows persian datetime picker?

### ISSUE THREAD

**Issue by mammadkoma** [DevExpress/DevExtreme#9327]
[DevExtreme enables](https://js.devexpress.com/Documentation/Guide/Common/Localization/) you to localize date, number and currency values using Intl or Globalize. We recommend using Intl because it is easy to activate.
On [this link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Syntax) Intl supports "Persian" Calendar.
Now how we can show a Html.DevExtreme().DateBox() asp.net core control in persian datetime picker and format?

**Comment by AlisherAmonulloev** [comment]
We have replied to you in the https://www.devexpress.com/Support/Center/Question/Details/T807211 ticket that you posted in our Support Center. Please check it.
