### ISSUE TITLE
FileManager - New Progress and Status UI

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#9336]
# The Problem

The [FileManager](https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/) does not display the following information:

- Whether a file operation(s) is in progress.
- The current operation's progress as a percentage.
- If operations are a success or failure.

# The Solution

We introduced the following UI elements to show the progress and status of operations:

- Popup notification messages
- Enhanced 'Refresh' toolbar item
- Operation progress side panel

![Delete_operation](https://user-images.githubusercontent.com/8307562/63268644-50a2a080-c29d-11e9-9d35-68ce586fb7ae.gif)

![Upload_operation](https://user-images.githubusercontent.com/8307562/63268654-539d9100-c29d-11e9-9731-b0069425d1ef.gif)

## Operation Start

- A notification popup displays general information about the operation. 
- The 'Refresh' toolbar item turns into a status item until the operation is completed.
- Details about the operation are shown in the side panel.

## Operation Progress

- The progress of each operation is reflected in the side panel.

## Operation Failure

- A notification popup displays the error message. 
- The error details appear in the side panel.

## All Operations Completed

- The 'Refresh' toolbar item reverts to its original state with an overall status marker (green for success or red for failure).
- The overall operation summary is available in the side panel.

# Try It
[jQuery demo](https://codepen.io/vladkovl/pen/ExYbmrM)

# We Need Your Feedback

## Take a Quick Poll

[Do you find new FileManager status/progress UI useful?](https://docs.google.com/forms/d/e/1FAIpQLScVbTm3yTyCEJccpbimxZ64vdwSK7wxNh9ixFgbm0XIqhNzdA/viewform?usp=sf_link)

# Get Notified of Updates
Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by maxerokh** [comment]
Thanks to everybody who gave us early feedback on this feature. The feature is now available in the [v19.2](https://github.com/DevExpress/DevExtreme/releases/tag/19.2.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub issues or tickets in our [Support Center](https://supportcenter.devexpress.com/ticket/list).
