### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by sven5** [DevExpress/DevExtreme#9372]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/devextreme) but it fails because the package is over 50 
MB. Are there any files that could be removed to reduce the package size?

I'm currently trying to use jsdelivr for package management out of Visual Studio because of problems with unpkg. 

Thanks
Sven

**Comment by bryanvam** [comment]
I have exactly the same problem

**Comment by BingoRUS** [comment]
@sven5 @bryanvam Could you please describe how you use jsDelivr and provide the list of files you need? In the case of DevExtreme bundles (for example, dx.all.js and dx.light.css), we strongly recommend using our own [CDN services](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/CDN_Services/).

**Comment by bryanvam** [comment]
https://www.jsdelivr.com/package/npm/devextreme

Failed to load the file listing.
Package size exceeded the configured limit of 50 MB.

**Comment by sven5** [comment]
Hi @BingoRUS 

thanks for your update. I'm using Visual Studio's built-in LibraryManager that's configured by libman.json. I wonder whether it works with your DevExpress CDN. Currently it seems only to support cdnjs, unpkg and jsDelivr since the latest update.

However, for me it's not very clear which files the devextreme widgets need to run correctly. So I'm loading the full package through CDN.

**Comment by hakimio** [comment]
@sven5 Normally you only need "dx.all.js", "dx.common.css" and the theme you are using, for example "dx.light.css" or "dx.material.teal.light.css". The total for all of those is around 4MB.
Anyway, any reason you can't just [install the packages using npm](https://docs.microsoft.com/en-us/visualstudio/javascript/npm-package-management)?

**Comment by sven5** [comment]
@hakimio Ok thanks for that clarification. I will change to load only the necessary files.
We're not using npm but instead [LibMan](https://docs.microsoft.com/de-de/aspnet/core/client-side/libman/?view=aspnetcore-3.0). LibMan doesn't support npm sources - only cdnjs, unpkg and jsdelivr since the latest update. Libman is a lightweight library manager. 
We moved to LibMan because we're creating Blazor apps and don't need the bloating npm packages and installers.

**Comment by BingoRUS** [comment]
@sven5,

As @hakimio pointed, we recommend using LibMan in conjunction with npm to add client-side resources to your ASP.NET Core/Blazor applications: https://docs.devexpress.com/AspNetCore/401027/devextreme-based-controls/get-started/configure-a-non-visual-studio-project#add-client-side-resources.
If it isn't an option for you, unpkg is a solution. Some of the requests to unpkg may be not successful, but it works fine the most of the time and we keep using it in our pre-release examples.

We will consider removing some js bundles from the npm package in future releases (for example, dx.web.js and dx.viz-web.js), but this isn't our top priority now and I can't promise you any timeframe when it might be done.
