### ISSUE TITLE
[Material theme] Custom textbox button squished

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#9389]
### Steps to Reproduce:

1.  Create a text box with custom text editor button
2.  Hover over the button

### Results You Received:
Button looks squished vertically.

### Results You Expected:
Button is not squished in any way

### Screenshot:
![texbox bug](https://user-images.githubusercontent.com/768105/63514147-390b2800-c4e8-11e9-9024-c07dca2a7b1f.png)

### Demo:
https://codesandbox.io/embed/overview-devextreme-text-box-6uytk

### Environment Details:
DevExtreme 19.1.5
devextreme-angular 19.1.5
Chrome 76

**Comment by hakimio** [comment]
Also, there seems to be a really big gap between two custom buttons.

**Comment by alexander-kotov-dx** [comment]
Hello,
Thank you for the bug report. I have created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T809959/custom-texteditor-buttons-squished-in-material-theme) in our SC. We'll update it once we have any news.

**Comment by hakimio** [comment]
@alexander-kotov-dx Thanks. Just worth noting that it's not only the icon position that's wrong but also the dimensions of the button: it's 36px in width and 29px in height. It's not exactly round.

**Comment by alexander-kotov-dx** [comment]
Hi again,

Thank you for the clarification. I believe these issues are related and will be fixed together anyway. I have updated the ticket to make it more clear.

If you have additional updates or clarifications regarding this issue, feel free to add a comment to the [bug report](https://www.devexpress.com/Support/Center/Question/Details/T809959/custom-texteditor-buttons-icons-have-incorrect-vertical-alignment-in-the-material-theme). We appreciate your cooperation in advance.
