### ISSUE TITLE
column editing colspan incorrect padding

### ISSUE THREAD

**Issue by HASSANDL** [DevExpress/DevExtreme#9598]
I set colspan for column datagrid but padding incorrect

![photo_2019-09-06_00-18-44](https://user-images.githubusercontent.com/22093903/64375806-f3984000-d03b-11e9-98cf-2bff6df39b6b.jpg)

**Comment by AlisherAmonulloev** [comment]
Would you please share an image demonstrating the expected result? In addition, create a simple compilable example demonstrating how the Form widget is configured.

**Comment by HASSANDL** [comment]
I set colSpan for column config:
```
const columns = [
    {
        dataField: 'name',
    },
    {
        dataField: 'connection',
    },
    {
        dataField: 'query',
        formItem: {
            colSpan: 2,
        },
    },
    {
        dataField: 'scope',
    },
    {
        dataField: 'status',
    },
]
```

**Comment by AlisherAmonulloev** [comment]
Please modify the https://codesandbox.io/s/fu30p example to demonstrate the problem. Thank you in advance.

**Comment by AlisherAmonulloev** [comment]
I am going to close this thread since there has not been any recent activity. Feel free to reopen it once you modified the example.
