### ISSUE TITLE
Data Grid Customisation to Excel Export Using Excel JS 

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#9672]
### Steps to Reproduce:

1.  While exporting data from data grid using excel JS how do [Protect a worksheet](https://support.office.com/en-us/article/protect-a-worksheet-3179efdb-1285-4d49-a9c3-f4ca36276de6) or [Lock cells](https://support.office.com/en-us/article/lock-cells-to-protect-them-cb7835f6-9c37-4161-bb53-d1c410acaf21) 
2.  In Data grid have 10 colums with data. I want to export only 4 columns with data using excel JS. Is possible ?
3.  How do change column data type to number
4. Cell Borders required after export
5. Data Grid Summary Value alignment to right after export

### Results You Received:
1. Excel sheet shows read only ,
2. All columns with data exported
3. Number stored as text
4. No borders
5. Data Grid Summary Value  left alignment only displayed after export

### Results You Expected:
1. Protected excel sheet required after export
2. Mentioned columns with data to be exported
3. Conver to number required 
4. Cell borders required for header & data
5. Data Grid Summary Value alignment to right after export

Example :

V. Date | V. No. | Account | Cost Centre
-- | -- | -- | --
29-05-2019 | zdfr435 | blue berry   enterprises | SPl 1

**Comment by EugeniyKiyashko** [comment]
The DevExpress.excelExporter.exportDataGrid function is based on the ExcelJS library. In the 19.1 release, this function is at the CTP stage and some useful behavior is not implement yet. Although I cannot promise you that we will implement it in the 19.1 release, we will take your opinion into account. Thank you for your feedback. I greatly appreciate your cooperation.

1. The ExcelJS library provides the capability to protect an excel worksheet in this way:
```
// Refer to https://github.com/exceljs/exceljs#sheet-protection
await worksheet.protect('pass');
```
Also you can control locking\unlocking cells when the sheet is protected in the following way: 
```
// Refer to https://github.com/exceljs/exceljs#cell-protection
worksheet.getCell("A1").protection = {
    locked: false
};
```
See the [DataGrid.ExcelJS CTP export - how to protect a worksheet or lock cells into Excel when exporting DataGrid](https://supportcenter.devexpress.com/internal/ticket/details/t815925) for more details.

2.  For DataGrid columns that you don’t want to export to Excel, you need to set the [allowExporting](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#allowExporting) option to false.
See the [CodePen example](https://codepen.io/EugeniyKiyashko/pen/OJLBbbb).

3. With the DevExpress.excelExporter.exportDataGrid function in the 19.1 release, you can set format number values as follows:
`excelCell.numFmt = '"£"#,##0.00;[Red]\-"£"#,##0.00';`
See [DataGrid.ExcelJS CTP export - How to format number values when exporting DataGrid into Excel using the exportDataGrid function](https://www.devexpress.com/Support/Center/Question/Details/T805417/datagrid-exceljs-ctp-export-how-to-format-number-values-when-exporting-datagrid-into) for more details.

4. ExcelJS provides the [Border](https://github.com/exceljs/exceljs#borders) property for assigning border settings. With the DevExpress.excelExporter.exportDataGrid function, you can set the border to the cell as follows:
```
// Refer to https://github.com/exceljs/exceljs#borders
excelCell.border = {
     top: {style:'thin'},
     left: {style:'thin'},
     bottom: {style:'thin'},
     right: {style:'thin'}
};
```
See the [CodePen example](https://codepen.io/EugeniyKiyashko/pen/bGbmwYV), which demonstrates this in action.

5. With the DevExpress.excelExporter.exportDataGrid function in the 19.1 release, you can set cell alignment as follows:
`excelCell.alignment = { horizontal: 'right' };`
See [DataGrid.ExcelJS CTP export - How to modify Excel cell alignment when exporting DataGrid into Excel using the exportDataGrid function](https://www.devexpress.com/Support/Center/Question/Details/T756468/datagrid-exceljs-ctp-export-how-to-modify-excel-cell-alignment-when-exporting-datagrid) for more details.
