### ISSUE TITLE
dx-tag-box don't close by select item

### ISSUE THREAD

**Issue by allahyar** [DevExpress/DevExtreme#9674]
I want the list not to be closed when a tag is selected.
Because the user doesn't do much to select too many tags :) 
I think it should become a feature.

**Comment by DokaRus** [comment]
You can use the [applyValueMode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTagBox/Configuration/#applyValueMode) option. 
Please refer to this [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TagBox/Overview/Angular/Light/). Take a look at the "Batch selection" example.
