### ISSUE TITLE
Fast input in masked textbox do'nt fire event onValueChanged

### ISSUE THREAD

**Issue by egmen** [DevExpress/DevExtreme#9693]
### Steps to Reproduce:

1. Add a masked textbox to page
2. Fastly type some value
3. Defocus the input field

### Results You Received:
Event onValueChanged did not fire

### Results You Expected:
Evget onValueChanged fired

### Environment Details:
DevExtreme v19.1.6
HTML JS
https://codepen.io/egmen/pen/dybKZjw
https://www.dropbox.com/s/g9k7k320hbzht4t/2019_09_13_09_18_01_32.mp4?dl=0

**Comment by egmen** [comment]
Ticket in support center: https://www.devexpress.com/Support/Center/Question/Details/T814692/textbox-the-onvaluechanged-event-doesn-t-fire-under-certain-conditions-if-a-mask-is-set

**Comment by egmen** [comment]
I think because of this commit https://github.com/DevExpress/DevExtreme/commit/69a136f32d66293a3e47a8940da0e51bbe7d2c54

**Comment by San4es** [comment]
We have processed this issue in the context of the [T814692](https://www.devexpress.com/Support/Center/Question/Details/T814692/textbox-the-onvaluechanged-event-doesn-t-fire-under-certain-conditions-if-a-mask-is-set) ticket. Please follow it to get results.
