### ISSUE TITLE
Custom Style Bundles

### ISSUE THREAD

**Issue by babich-a** [DevExpress/DevExtreme#9720]
# The Problem

DevExtreme provides styles for their widgets only in the form of pre-built bundles. Because they contain the styles of all widgets, the bundles have significant size (~500KB for Generic themes; ~600KB for Material Design themes) and should be downloaded to the client in full even if only some of the styles are used.

# The Proposed Solution

## Custom CSS Bundles

You will be able to use the ThemeBuilder CLI to create CSS bundles that include only certain styles.

The `devextreme build-theme` command will have an additional `--widgets` argument that accepts a comma-separated list of widgets whose styles you want to include in the bundle.

```
devextreme build-theme --widgets=button,menu --base-theme=material.blue.light --version=19.2.3
```

The `--widgets` argument can also be specified as a [metadata property](https://js.devexpress.com/Documentation/Guide/Getting_Started/DevExtreme_CLI/#ThemeBuilder/Export_Theme_Metadata).

## LESS Files

The `devextreme` package will include DevExtreme styles as LESS files. You can use them "as is" or import them in your own LESS files to create custom style bundles. We do not recommend that you modify our LESS files. Instead, override the rules declared in them.

We also plan to provide individual LESS files for each widget so that you can optimize the resulting bundle. For example, to add the styles for the **Button** and **Menu** widgets, you need to import only the LESS files that contain styles for these widgets:

```
@import "devextreme/less/imports/button/dx.button.light.less";
@import "devextreme/less/imports/menu/dx.menu.light.less";
```

## Take a Quick Poll

[How does the new Feature meet your needs?](https://docs.google.com/forms/d/e/1FAIpQLSev79Ntq8yKFIhdsL3UF_HqwVjYzaoAzNGQBNuLDfVkks1xhg/viewform)

## # Get Notified of Updates

Subscribe to this thread or to our [Facebook]([https://www.facebook.com/DevExpress.DevExtreme/](https://www.facebook.com/DevExpress.DevExtreme/)) and [Twitter]([https://twitter.com/devextreme](https://twitter.com/devextreme)) accounts for updates on this topic.

**Comment by hakimio** [comment]
Once you have split DevExtreme into modules, it would be nice if the widgets themselves would specify which styles (less) they need and the build tool would automatically generate the right CSS bundle without having to manually edit the theme metadata.

**Comment by babich-a** [comment]
@hakimio we will plan to do it.

**Comment by vandroaurelio** [comment]
Why not Sass (SCSS) instead of Less? Main frameworks and libraries like Bootstrap and Material use Sass. It makes it harder to integrate Less with Sass. You can convert your Less code into Sass easily using specific tools. Please consider converting your Less into Sass (SCSS) to make integrations easier. Thanks.

**Comment by artem-kurchenko** [comment]
@vjwolfa 
Both Sass and LESS are still popular. We started with LESS because our source styles were originally based on LESS. We'll consider conversion to Sass if we get more requests. Thank you for your feedback.

**Comment by vandroaurelio** [comment]
Another suggestion: if you guys can put all the theme variables in one single file it will make it easier for us to create our own theme. Also, do you have an idea of when this new feature will be available?

**Comment by hakimio** [comment]
@vjwolfa you can already do that with DevExtreme theme builder.

**Comment by babich-a** [comment]
@vjwolfa you can use [export-theme-vars command](https://js.devexpress.com/Documentation/Guide/Getting_Started/DevExtreme_CLI/#ThemeBuilder/Export_Theme_Variables). For example
```
devextreme export-theme-vars --version=19.2.4
```

**Comment by byezgi-esq** [comment]
It would be great if you could support SASS export as well. Otherwise we have to compile your LESS and our SASS separately and will not be able to control the order of styles easily.

**Comment by babich-a** [comment]
@byezgi-esq we plan to migrate from less to scss

**Comment by babich-a** [comment]
Thank you to everybody who gave us feedback on this feature by different means. It's available in the [v19.2](https://github.com/DevExpress/DevExtreme/releases/tag/19.2.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).

**Comment by sapelson** [comment]
Please reconsider using SCSS. Of course, LESS works, but SASS (and it's version, scss) has pretty much taken over by now. 

It's impossible to mix LESS andn SASS in the same project projects and automatic conversion tools break with huge amount of files Devexpress has…

**Comment by babich-a** [comment]
@sapelson we are working on migration.

**Comment by babich-a** [comment]
We are working on the migration to SCSS. I'd like to invite you to participate in our R&D process. We are posting related updates on the [feature discussion page](https://github.com/DevExpress/DevExtreme/issues/13654). Feel free to review the current state of development and comment if you have any feedback. There is a poll you can take to help us understand if the suggested solution meets your app requirements. Thanks for your input.
