### ISSUE TITLE
Row cannot be expanded with virtual scrolling

### ISSUE THREAD

**Issue by belgamo** [DevExpress/DevExtreme#9766]
# Bug Report

**Package versions:**
    devexteme version: 19.1-stable
    devextreme-react version: 19.1-stable

**Current behavior:**
When the `columnHidingEnabled `property is true and uses virtual scrolling, it will work well in the first few records. But when you scroll down the grid and new records load, the rows can't be opened by clicking the collapse button.
To see current behavior, just set columnHidingEnabled to true at https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/React/Light/

**Expected behavior:**
I expected that when you click the collapse button the line expanded.

**Comment by belgamo** [comment]
Thank you @AlisherAmonulloev!

**Comment by AlisherAmonulloev** [comment]
We have fixed the issue described in the https://supportcenter.devexpress.com/ticket/details/t815886 ticket. We will include the fix in our next maintenance update. To apply this solution before the official update, request a hotfix  by clicking the corresponding link for product versions you require.
