### ISSUE TITLE
DX Datagrid - Export using Excel JS Multi-Row Headers (Bands)  Issue

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#9826]
### Steps to Reproduce:

1.  Dx data grid  Multi-Row Headers (Bands) export to excel using Excel JS merging bands issue
2.  Dx data grid  export to excel using excel js,  need to specify column-based width while exporting
3.  Dx tree list  data summaries like dx data grid
4.  dx tree list export to excel option

### Results You Received:
1. In excel, Bands are not merged

![image](https://user-images.githubusercontent.com/47413890/65419069-7af6f900-de1b-11e9-826f-2be75250791a.png)
2. Dx data grid - export using excel js, data grid column name based width to specify while export.  Unable to specify excel report a particular data column width.
Because some  data columns are visible manually or hide manually or swapping manually while doing customisation before export

3. Dx tree list - No data summaries option found
4. Dx tree list - No export to excel found

### Results You Expected:
1. Bands should be merged looks like dx data grid view

![image](https://user-images.githubusercontent.com/47413890/65418905-1fc50680-de1b-11e9-9cc0-3e7cf47a8e78.png)

2. dx data grid  export to excel using excel js,  need to specify  data column-based width while exporting. Because some  data columns are visible or hide or swapping while doing customisation before export
3. Need Dx tree list -  data summaries option 
4. Need Dx tree list -  export to excel

**Comment by IgnatovDan** [comment]
Thank you for your feedback.
1. We have not yet implemented the correct merging of band cells for DataGrid's multi-row headers. We will see how to improve our code. However, I cannot provide you with any time frames.
 
2. We implemented column width export in the 19.1.6 version - see the [Advanced Document Customization](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJS) demo. It was not available in previous versions. Please accept our apologies for any possible inconvenience. See also [DataGrid.ExcelJS CTP export - How to set column width when exporting DataGrid into Excel using the exportDataGrid function](https://www.devexpress.com/Support/Center/Question/Details/T756477)
 
3. You are right, the [TreeList](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/) widget doesn't support summaries. We may provide this support in the future. Meanwhile, I suggest that you review summaries in the [DataGrid](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/) widget: see [summary](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/summary/) for more details.
 
4. We have not implemented XLSX export for the [TreeList](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/) widget. Although I cannot promise you that we will implement it in the near future, we will take your suggestion into account.
