### ISSUE TITLE
dxTagBox in dxForm in Vue error E1035

### ISSUE THREAD

**Issue by alepri51** [DevExpress/DevExtreme#9922]
# Bug Report

**Package versions:**

    devexteme version: 19.1.6
    devextreme-vue version: 19.1.6

**Steps to reproduce:**

When trying to modify demo file App.js
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/CustomizeItem/Vue/Light/
with this code:
`...<dx-item  
          :editor-options="{items: positions}"  
          data-field="Position"  
          editor-type="dxTagBox"  
        /> ...`

and in data.js
`var employee = {  
...  
    "Position": ["CEO"],
...`

just replace editor-type to dxTagBox and set some editor options I get an error in console:
**devextreme.vue.systemjs.js:1 E1035 - The editor cannot be created because of an internal error: n(...)[t] is not a function. See: http://js.devexpress.com/error/19_1/E1035**
when applying this code:
` ... {  
            dataField: "Position",  
            editorType: "dxTagBox",  
            editorOptions: {  
                items: positions  
            }  
        }  ...`
on page https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/CustomizeItem/jQuery/Light/
all works fine!

**Screenshots:**

![image](https://user-images.githubusercontent.com/39708925/65753411-a3327080-e117-11e9-853e-919a9803758a.png)

**Comment by AlisherAmonulloev** [comment]
We have received your ticket in Support Center: https://www.devexpress.com/Support/Center/Question/Details/T818532/dxtagbox-in-dxform-in-vue-error-e1035
It has been placed to the processing queue. We will reply to you as soon as possible.

**Comment by alepri51** [comment]
solved as described in: https://www.devexpress.com/Support/Center/Question/Details/T725521/form-the-component-is-not-a-function-error-occurs-if-editortype-is-tagbox
Thanx
