### ISSUE TITLE
DX Data Grid REcord Grouping No Issue While Use Fixed Style

### ISSUE THREAD

**Issue by sunbala** [DevExpress/DevExtreme#9948]
### Steps to Reproduce:

1.  DX Data Grid Record Group  Number Issue while use fixed style
caption: "index 2", 
                 fixed: true,
                 fixedPosition: "left",
                 cellTemplate: function (cellElement, cellInfo) {                
                 cellElement.text(cellElement.parent().index("#gridContainer .dx-datagrid-rowsview tr.dx-data-row") + 1); }

2. 
3. 

### Results You Received:
1. Record Group No started with 9 
https://codepen.io/anon/pen/QmLWKG?editors=0010
In the above example , just add 
fixed: true,fixedPosition: "left",  in  the column of caption: "index 2", 
will get the starting number is 8 

### Results You Expected:
1. Need to get starting number is 1

**Comment by AlisherAmonulloev** [comment]
This behavior is expected - please review the [https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Columns/Column_and_Row_Indexes/](https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Columns/Column_and_Row_Indexes/) help topic describing how DataGrid renders rows and assigns rows' indices.
